### PR TITLE
Remove prorotype patching in flash

### PR DESCRIPTION
**Pull request by ktimothy**
This removes patching of prototypes of String and Date in runtime. Instead, necessary methods are defined as inline in appropriate classes in flash standard library.

### CODE REVIEW

**Comment by ktimothy** [comment]
Hmm can someone fix AppVeyor? It could not install make bacause of Internal Server Error somewhere =)

**Comment by nadako** [comment]
ping @andyli

**Comment by ktimothy** [comment]
ping @ncannasse =)

**Comment by ncannasse** [comment]
What's the rationale behind this ? For instance, inlining each Date.fromString will create a lot of code bloating so it's not an appropriate solution here.

**Comment by delahee** [comment]
inlining String looks cool but inlining Date seems overreaching, would you
consider splitting the PR ?

2015-11-02 11:17 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> What's the rationale behind this ? For instance, inlining each
> Date.fromString will create a lot of code bloating so it's not an
> appropriate solution here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/pull/4615#issuecomment-152977927>.
>



-- 
David Elahee

**Comment by back2dos** [comment]
What if the actual implementation of Date.fromString were moved to
flash.Boot or flash.Lib or DateTools or something, and then the inlined
Date.fromString would simply call that? That would avoid both code bloat
and prototype patching, no?

**Comment by nadako** [comment]
This is what's done in JS (e.g. `HxOverrides`) and I think it should work here as well!

**Comment by ktimothy** [comment]
> What's the rationale behind this 
My goal is to get rid of prototype patching in flash like it was done for js target.

I agree with Date.fromString. It is better idea to use HxOverrides or something like that. I will do it in a couple of days.

**Comment by nadako** [comment]
Does this get rid of the need to do haxe.init() call when one is using haxe-generated swc lib?

**Comment by back2dos** [comment]
Well, something still has to set flash.Lib.current. It could be lazily
initialized in a `@:getter` to some default (possibly by adding a new empty
MovieClip to the stage, if nothing else is found?).

**Comment by ktimothy** [comment]
> Does this get rid of the need to do haxe.init() call when one is using haxe-generated swc lib?

Yes, that's gonna be a nice side effect.

**Comment by Simn** [comment]
I like the notion but this makes me really nervous.

**Comment by ktimothy** [comment]
> Does this get rid of the need to do haxe.init() call when one is using haxe-generated swc lib?

> Yes, that's gonna be a nice side effect.

Well, to be more specific - haxe.initSwc() call will be required if one needs special features like haxe's trace to text field. If thoose features are not needed - so there is no need to call initSwc, because bytecode does not rely on patched prototypes.

**Comment by ncannasse** [comment]
Please note that it will also break all Dynamic accesses to these APIs (including for instance hscript scripts, etc.)

**Comment by delahee** [comment]
wow. not cool at all.

2015-11-04 18:11 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> Please note that it will also break all Dynamic accesses to these APIs
> (including for instance hscript scripts, etc.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/pull/4615#issuecomment-153795247>.
>



-- 
David Elahee

**Comment by nadako** [comment]
Well, we have to get rid of double standards regarding Dynamic access, because for JS we accept that.

**Comment by ktimothy** [comment]
> Please note that it will also break all Dynamic accesses to these APIs (including for instance hscript scripts, etc.)

Yes, I know that. Here I completely agree with @nadako.

JS target now does not have prototype patching. Of course, it breakes some dynamic access to APIs, that do not use runtime patching. But haxe has so great typing system, that I doubt we should make everything to fully support Dynamic features.

Everyone knows, that haxe does not have its own runtime. Everyone should keep in mind, that haxe output will run in some environment, which can cause errors when using Dynamic.

**Comment by delahee** [comment]
Well Haxe still is powering tools in some big houses,  if hscript suddenly
loses ability to call String.something, it is a problem you cannot deny so
easily so wave to be conservative here, especially for the sake of a few
cycles. Js targets does not leverage scripts usually since its already a
script, but other target swf actually will and here comes the big problem.
Marking all this as extern inline is the problem so why not just "inline"
without extern so that the dynamic version exists ? Or am I wrong ?



2015-11-04 20:21 GMT+01:00 Timothy Kovalev <notifications@github.com>:

> Please note that it will also break all Dynamic accesses to these APIs
> (including for instance hscript scripts, etc.)
>
> Yes, I know that. Here I completely agree with @nadako
> <https://github.com/nadako>.
>
> JS target now does not have prototype patching. Of course, it breakes some
> dynamic access to APIs, that do not use runtime patching. But haxe has so
> great typing system, that I doubt we should make everything to fully
> support Dynamic features.
>
> Everyone knows, that haxe does not have its own runtime. Everyone should
> keep in mind, that haxe output will run in some environment, which can
> cause errors when using Dynamic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/pull/4615#issuecomment-153836520>.
>



-- 
David Elahee

**Comment by ncannasse** [comment]
That's the reason I'm asking : what is the rationale for removing prototype extension?
We had actual issues with JS when interacting with third party frameworks that leaded us to decide to add HxOverrides and not to extend prototypes anymore.

Is there such similar problems with Flash?

I'm not against it, but it needs to be a rational decision, or else we're just breaking backward compatibility.

**Comment by Simn** [comment]
I'm with Nicolas on this one. If this doesn't have any clear cut advantage I don't think it's justified to break anything.

**Comment by fzzr-** [comment]
I think it's not necessary. __But__ maybe we need to reconsider for greater consistency with similar method for HxCpp (`hxcpp_set_top_of_stack()` & `hxRunLibrary()` ([here](https://github.com/HaxeFoundation/hxcpp/blob/master/src/ExampleMain.cpp#L52)) ).

**Comment by ncannasse** [comment]
Unless someone has a valid reason to break backward compatibility, I'll close soon.

**Comment by back2dos** [comment]
Sorry, but I have to ask: since when is hscript a Haxe dependency? Whether or not this change is worth adding is one matter, but I find the notion that some quite exotic scripting language would dictate that quite twisted, particularly if we accept the fact that JavaScript itself cannot call many of the core Haxe APIs because they are gone at runtime. More than that: in hscript we can simply deal with it **right here**: https://github.com/HaxeFoundation/hscript/blob/master/hscript/Interp.hx#L329

Back to the original point: I agree that this is a bad time to add it. But I think for Haxe 4 it badly needs to be revisited what exactly works through `Dynamic` and what doesn't. The status quo makes it really easy to write non-portable code, which directly sabotages one of Haxe's value propositions.

**Comment by ncannasse** [comment]
We can't have consistency: on some platforms we implement ourselves Array so of course all the methods will be accessible through Dynamic as well.

On some others we use the native implementation and either adds through prototype injection or HxOverrides-like when it's not possible or cause some issues with other native code (JS).

The default - when possible - should always be to allow Dynamic access since it's the least surprising behavior. As for consistency, everything involving Dynamic is already platform-specific.

@Juraj I understand what you're saying, but that can only be done by introducing another new type that would perform additional (potentialy very slow) runtime checks to ensure consistency. Dynamic is often used to implement std library or for users to bypass the type system so we can't use it directly for that.

**Pull request closed without merging**
