### PR TITLE
Fix infinite recursion in apply_params for recursive anon

### LINKED ISSUE #7997: Crash when compiling recursive local function
```haxe
import haxe.display.JsonModuleTypes;

class Main {
	static function main() {}

	function guessName<T>(type:Null<JsonType<T>>):Null<String> {
		function loop(type) {
			return switch (type.kind) {
				case TInst: type.args.path.typeName;
				case TDynamic: loop(type.args);
				case _: null;
			}
		}
	}
}
```

I'm not getting much useful info such as a stack trace, it just crashes:

>The terminal process terminated with exit code: 3221225725

Not sure if this is a regression or not, since `JsonModuleTypes` hasn't been around for that long.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #7997

Edit: 
Not finished yet. `s_type` and `link` also need recursive anons handling

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Done.
The fixes are a bit ugly, but idk how to make them better without also making them more intrusive.

**Comment by Simn** [comment]
I'm not sure if the focus on anons is correct here. The only thing that's special about them is that they are a compound type, which makes me wonder why we have so many problems with anons specifically as opposed to, say, functions. My concern is that anons are simply the more common case.

**Comment by RealyUniqueName** [comment]
I can't imagine a haxe code, which would create create a recursive functon type.

**Comment by RealyUniqueName** [comment]
During an attempt to generalize the solution I've came to conclusion we (hypothetically) do need a general solution. However we don't need it for compound types, but we need it for "modifiable" types like `TMono of t ref`, `TLazy of tlazy ref` and `TAnon a` (modifiable fields). Because Potentially these cases could happen:
```ocaml
match t with
| TMono r -> r := t
| TLazy lazy -> lazy := LAvailable t
| TAnon a -> a.a_fields <- mk_field "recursive" t null_pos null_pos
```
Any other enum constructor in `Type.t` cannot be recursive.
But I don't see how `TMono` and `TLazy` situations could happen from normal Haxe or macro code unless something like that is actually written in ocaml code.
The only real case is `TAnon`, which is reported in the original issue and fixed in this PR.
If we really want to handle `TMono` and `TLazy` recursions too, then we need to "patch" almost all the compiler, because any code dealing with monomorphs or lazies could become a victim of a recursive type. The most obvious example - `follow t`.

**Pull request closed without merging**
