### PR TITLE
[php] added incomplete Compress / Uncompress implementation

### PR DESCRIPTION
**Pull request by clemos**
This is needed to use `format.swf` in PHP 
(other PR to come on `format` to make `Inflate/Deflate` use `Compress/Uncompress` in PHP)

### CODE REVIEW

**Comment by andyli** [comment]
Would you activate the test at [tests/unit/src/unit/issues/Issue2861.hx](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue2861.hx) for php?

**Comment by nadako** [comment]
ping

**Comment by clemos** [comment]
Sorry, I've been into something else.
I can do that next week.

**Comment by clemos** [comment]
I've enabled the UT, it seems to work :D

**Comment by nadako** [comment]
Thanks!

**Pull request merged**
