### PR TITLE
added Base32 with unit tests, based on Base64 example

### PR DESCRIPTION
**Pull request by lexoyo**

### CODE REVIEW

**Comment by andyli** [comment]
CI tests failed.

**Comment by nadako** [comment]
It's just `TestMisc.hx` is missing `haxe.io.Bytes` import.

**Comment by ncannasse** [comment]
I don't think Base32 is widely used (first time to hear about it) and I suspect that there's a lot of different char sets for it, maybe let's keep it as an haxelib?

**Comment by lexoyo** [comment]
Hello
This is useful to me to encode with acceptable chars in subdomains
If you want to merge it I can take time this week end to fix the build
As you wish

**Comment by lexoyo** [comment]
And sorry about pushing and disappearing like this :shaved_ice:

**Comment by fponticelli** [comment]
I don't understand why this is not a legitimate request when in std we have things like `xml.fast`, `spod` and `proxies` just to mention a few.

**Comment by Simn** [comment]
FWIW, spod is gone and I have plans to remove some other cruft as well. Given that Base32 indeed seems to be very rare, I prefer to not merge this for the time being.

**Pull request closed without merging**
