### PR TITLE
Release 3.2.1

### PR DESCRIPTION
**Pull request by waneck**

### CODE REVIEW

**Comment by Simn** [comment]
The changes look alright, my only concern is that this might cause chaos between our development and master branches when we try to do our next release.

**Comment by waneck** [comment]
Okay, I've done a small test development branch and made the merges from 3.2.1 master. The only conflicts we got were on CHANGES.txt and main.ml (because of version variable) - which are expected. Once we make the 3.2.1 release, I'll merge the changes back to development - so we won't get those conflicts anymore.

Is everyone happy with the changes? I'm thinking about making the release tonight  - after I get sorted out the install bug on Mac "El Capitan"

**Comment by waneck** [comment]
For reference, the merged back version of master/development is at https://github.com/waneck/haxe/tree/dev-test

**Comment by andyli** [comment]
It has been a month... Are there any remaining blocking issue?

**Comment by waneck** [comment]
No. I'm sorry, it was just me who had no time lately. I'll do it this
weekend.

**Comment by andyli** [comment]
Great! Thanks for your effort, @waneck!

**Comment by aduros** [comment]
Can you please cherry pick c6597af into this release to fix the #4490 regression?

**Comment by andyli** [comment]
@aduros I forgot about it, sorry about that! Will do so.

@waneck This PR is made to merge from waneck:master to HF:master. Should it merge from HF:haxe-3.2.1 instead?
Btw, if I try to merge HF:haxe-3.2.1 and HF:development into HF:master, there will be merge conflict in gencpp... I suppose resolving using all of HF:development will work.

Well, git merge...
[git merge](http://giphy.com/gifs/git-merge-xTiTnqEbrWfX7xA9TW)

**Comment by derRaab** [comment]
Just a quick reminder since I came across it:
On Mac OS X El Capitan Haxe itself has to move to /usr/local/lib AND haxelib needs a new default location: /usr/local/lib/haxe/lib (I think)

**Comment by waneck** [comment]
@andyli  you're right; we should merge from the haxe-3.2.1 branch. I'll do it right now

**Comment by waneck** [comment]
I've just made the release. It's available at http://haxe.org/download/version/3.2.1/ . Please let me know if you find any problems - I'll promote it to the current version / announce it later at Monday night

**Comment by jangdan** [comment]
@waneck #4585

**Pull request closed without merging**
