### PR TITLE
[java/cs] Initial implementation of javac-opt / cs-opt. Closes #3768

### LINKED ISSUE #3768: Add -javac-arg / -cs-arg
Add a haxe flag that will pass the arguments to the C#/Java compiler. Not sure about the naming

### PR DESCRIPTION
**Pull request by waneck**
I'm submitting this as a PR to first know if you have better suggestions for the naming/placing of this feature.

### CODE REVIEW

**Comment by ncannasse** [comment]
I think we should have a single crossplatform -ccopt ? that works for Java, C# and C++ (cc @hughsando )

**Comment by waneck** [comment]
Yeah, I thought about that too. If @hughsando is fine with implementing it for hxcpp as well, it seems a better option.
Since we're following ocamlopt's convention, we could have also a `-cclib` to pass options to the linker.

**Comment by andyli** [comment]
I can imagine we have to add different arguments on different OS and doing that with macros would be easier.
So be sure to add a method to `haxe.macro.Compiler` to enable this ;)

For the naming, I thought "opt" is short for "optimization" since we already have `--no-opt`. "arg" seems less confusing.

**Comment by nadako** [comment]
I agree about the `opt` naming thing, I just wanted to comment about that, but andy was faster :-P

**Comment by hughsando** [comment]
hxcpp currently used the buildXml meta to achieve similar results and this allows for delaying some indirection until more is known about the toolchain - eg conditional compiling.  But also adding command-line options would be fine.

**Comment by Justinfront** [comment]
But there have been times with hxcpp where I have had to dig deep into this smart code, especially on mac where systems can work in 32 and 64.  So while it is very powerful it also often the part of the nme/openfl magic which fustrates me as much as amazes me. But macs can be a pain with varying compiler support and rules, windows is normally simpler.  So consider carefully if possible for unknown systems when creating arg tools.

**Comment by waneck** [comment]
Okay, I've added `Compiler.addNativeArg` and renamed it to `-c-arg`. Hugh, if you want I can add a PR with a possible implementation for C++.

**Pull request merged**
