### PR TITLE
Flash externs: add (default,never) to static constants

### PR DESCRIPTION
**Pull request by Gama11**
Code like `TouchEvent.TOUCH_BEGIN = "somthing else"` used to compile (but crash at runtime with `ReferenceError: Error #1074: Illegal write to read-only property TOUCH_BEGIN on class flash.events.TouchEvent.`).

### CODE REVIEW

**Comment by nadako** [comment]
IIRC those externs are auto-generated somehow, cc @ncannasse

**Comment by ncannasse** [comment]
This might have been changed in playersglobals.swc, this should show up the next time I auto generate, try using haxe/extra/extract.hxml

**Comment by ncannasse** [comment]
(PS : you need to delete the "haxe/std/flash subfolders first)

**Comment by Simn** [comment]
Right, I totally forgot about that. Sorry @Gama11!

**Comment by Gama11** [comment]
Where do you get the `library.swf` `etract.hxml` references? Not part of the repo.

**Comment by ncannasse** [comment]
You get it by unzipping the playersglobals.swc

**Comment by Gama11** [comment]
I see. Running `extract.hxml` with `playerglobal19_0.swc` on that doesn't really change the type of the static vars. It does however:
  - duplicate all `@:require` meta for some reason
  - set default values of function arguments to the type's default value instead of their actual value, like in `DropShadowFilter#new()`:
  
```diff
-function new(distance : Float = 4, angle : Float = 45, color : UInt = 0, alpha : Float = 1, blurX : Float = 4, blurY : Float = 4, strength : Float = 1, quality : Int = 1, inner : Bool = false, knockout : Bool = false, hideObject : Bool = false) : Void;
+function new(distance : Float = 0, angle : Float = 0, color : UInt = 0, alpha : Float = 0, blurX : Float = 0, blurY : Float = 0, strength : Float = 0, quality : Int = 0, inner : Bool = false, knockout : Bool = false, hideObject : Bool = false) : Void;
```

**Comment by Gama11** [comment]
I guess `--gen-hx-classes` has to be updated to generate `(default,never)` for constants?

**Comment by Simn** [comment]
Can it even determine that the field in question is considered constant?

**Comment by Simn** [comment]
I'll have to look into this for Haxe 3.3 one way or another, else we risk pattern matching regressions.

**Comment by Simn** [comment]
This is turning into a bit of a problem because I don't think the compiler even knows that these fields are considered "const". I don't know how to address this right now, so I actually consider merging this PR for the 3.3.0-rc1 release. I realize it's only a temporary solution but at least it avoids regressions.

**Comment by Gama11** [comment]
Could always check if the var names are all-uppercase if the Flash API is consistent with their naming conventions.. :D

**Comment by Simn** [comment]
*if*

**Comment by Gama11** [comment]
Well, the find-and-replace regex I used for this pull request was based on that assumption as well..

**Comment by ncannasse** [comment]
@Simn the SWF should report these fields as read-only so you should be able to generate correct (default,never) accesses

**Comment by Simn** [comment]
Does that mean swflib discards this information?

**Comment by ncannasse** [comment]
Uhm, we are already checking for hlv_const indeed...

**Comment by Simn** [comment]
Yes this looks pretty cut and dry:

```ocaml
if v.hlv_const then
	cf.cff_kind <- FProp ("default","never",Some (make_type v.hlv_type),None)
```

So either this goes wrong in the As3 parser or... I don't know.

**Comment by ncannasse** [comment]
Either Adobe has introduced some kind of runtime protection that does not inform the field is const, or the playerglobals.swc used is not up to date with flash runtime restriction. In all cases I would vote for closing this issue without taking action.

**Comment by Simn** [comment]
We have to do something about this because you cannot use these fields in match-patterns anymore.

**Comment by ncannasse** [comment]
The we need to manually mark them as const in bin/extract.patch, or do some heuristic on static uppercase values in classes that extends flash.events.Event in our extractor

**Comment by Gama11** [comment]
This is not limited to `Event` child classes.

**Comment by Simn** [comment]
The library.swf has the information: http://i.imgur.com/aBKYCD9.png

We must be losing it somewhere along the way. I don't understand our -swf-lib handling well enough to figure out what's wrong though.

**Comment by Simn** [comment]
We determined that this is indeed a problem with our parser, in particular this piece of code:

```ocaml
	let kind = (match kind land 0xF with
		| 0x00 | 0x06 ->
			let t = index_opt ctx.as3_names (read_int ch) in
			let value = read_value ctx ch false in
			A3FVar {
				v3_type = t;
				v3_value = value;
				v3_const = kind = 0x06;
			}
```

It compares `kind = 0x06`, but it should compare `(kind land 0xF) = 0x06`.

Unfortunately after fixing that I'm getting an error on extract.hxml: "C:\GitHub\haxe\std/flash/Boot.hx:140: characters 3-50 : String should be flash.text.TextFieldAutoSize".

**Comment by Simn** [comment]
More problems found by @nadako: https://github.com/HaxeFoundation/haxe/blob/development/genxml.ml#L434

```ocaml
	let access is_read a =
		match a, pack with
		| AccNever, "flash" :: _ -> "null"
		| _ -> s_access is_read a
	in
```

@ncannasse: Any idea why that's there?

**Comment by ncannasse** [comment]
@Simn Not sure, maybe that was because we didn't have a proper "never" support in xml docs at this time?

**Comment by Simn** [comment]
I've removed it, let's see what happens.

I'm now getting this:

```haxe
extern class TextEvent extends Event {
	var text : String;
	function new(type : String, bubbles : Bool = false, cancelable : Bool = false, ?text : String) : Void;
	static var LINK(default,never) : String;
	static var TEXT_INPUT(default,never) : String;
}
```

So that looks good!

**Comment by nadako** [comment]
What's the proper workflow to re-generate these externs though? Empirically we found out that to get extern regenerated, one needs to remove current externs from `std/flash`, but it's not clear what exactly to remove and what exactly to copy back from the `hxclasses` folder.

**Comment by ncannasse** [comment]
usually it requires removing by hand haxe/std/flash/DIR where DIR is all directories expect _std. Then runnning the extractor, then copying back the classes generated in extract directory to overwrite the std ones (after restoring them)

**Comment by Simn** [comment]
I think we can consider this issue to be resolved now. Just have to make sure we actually re-generate the externs before the release.

**Comment by nadako** [comment]
I updated the externs, so people like @Gama11 report any issues now, if we break something with it :)

**Pull request closed without merging**
