### PR TITLE
Add full module path to module name errors

### LINKED ISSUE #8750: Context.defineType broken
Due to recent changes, `Context.defineType({ pack : ["hxd","_res"], name : "_Ui_skills" ... })` does not work anymore. Seems like we check the module path on `hxd._res` only instead of `hxd._res._Ui_skills`

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #8750 

Now errrors look like this:
```
Macro2.hx:7: characters 17-18 : "Type+" is not a valid module name. Full module path: "some.Type+"
```

### CODE REVIEW

**Comment by Gama11** [comment]
Might want to include a test case that actually has a package?

**Comment by Simn** [comment]
That reads quite awkward... How about `Module some.Type+ does not have a valid name`?

**Comment by RealyUniqueName** [comment]
Yeah, I thought about that, but I find it also awkward to tell that an error is the whole path, while it's only the name actually.

**Comment by Simn** [comment]
That's why I phrased it with "have" instead of "is". We could even repeat the name: `Module some.Type+ does not have a valid name "Type+"` to leave no one behind.

**Comment by Simn** [comment]
Please update accordingly!

**Pull request merged**
