### PR TITLE
Better error messages for \x and \u

### LINKED ISSUE #8191: `Invalid_argument("String.sub / Bytes.sub")` with `\x`
```haxe
class Main {
	static function main() {
		trace('\x');
	}
}
```

>Invalid_argument("String.sub / Bytes.sub")

This used to give:

>Invalid escape sequence \x

as recently as rc.2. I'm guessing it's because of #8141.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #8191
```
X1.hx:2: character 11 : Invalid escape sequence \x. Must be followed by a hexadecimal sequence.
U5.hx:2: character 11 : Invalid escape sequence \u. Maximum allowed value for unicode escape sequence is \u10FFFF
```

### CODE REVIEW

**Comment by Gama11** [comment]
Hm, very minor complaint, but `Must be followed by a hexadecimal sequence` doesn't seem quite correct for `\u`, since you also need the `{}`..

**Comment by RealyUniqueName** [comment]
Actually `\uFFFF` also works.
Can somebody propose better wording?

**Comment by Gama11** [comment]
Oh, I didn't realize that. What's the point of the `{}` then?

**Comment by RealyUniqueName** [comment]
According to the ml code, the non-curly version is only allowed for two-byte sequences.

**Comment by Gama11** [comment]
I see. But yeah, the message is probably fine then, definitely a big improvement to before. :)

**Comment by RealyUniqueName** [comment]
Changed to 
```
U3.hx:2: character 11 : Invalid escape sequence \u. Must be followed by a hexadecimal sequence enclosed in curly brackets.
```
because of curly brackets always work.

**Pull request merged**
