### PR TITLE
use FindFirstFile to get proper module name casing

### PR DESCRIPTION
**Pull request by nadako**
See #3779 and https://github.com/HaxeFoundation/ocamllibs/pull/12

### CODE REVIEW

**Comment by nadako** [comment]
I'll update the branch for this PR once https://github.com/HaxeFoundation/ocamllibs/pull/12 is merged.

**Comment by nadako** [comment]
Okay, waiting for appveyor greenlight.

**Comment by ncannasse** [comment]
This has entirely disabled Haxe completion on some computers we're working with. Please revert ASAP

**Comment by Simn** [comment]
Can we try to figure out what's the problem instead of hastily reverting? The change was made 9 months ago and has been part of two releases.

**Comment by nadako** [comment]
I agree, besides, reverting this will completely break completion server on all machines we're working on, and many many others since modern Windows 8+ setups often have 8.3 names disabled.

How it breaks for you?

**Comment by ncannasse** [comment]
Uhm, that might be something else then, I didn't check the date, seems a recent pb

**Comment by ncannasse** [comment]
Will investigate further

**Comment by ncannasse** [comment]
Here's the result:
```
[11:57:15] Bernard Stouls: Win32
INPUT=  d:/projects/heaps/hxd/net/SceneInspector.hx
FULL=   d:\projects\heaps\hxd\net\SceneInspector.hx
UNIQUE= d:\projects\heaps\hxd\net\sceneinspector.hx
REAL=   D:\Projects\heaps\hxd\net\sceneinspector.hx

INPUT=  d:/projects/heaps/hxd/net/Property.hx
FULL=   d:\projects\heaps\hxd\net\Property.hx
UNIQUE= d:\projects\heaps\hxd\net\property.hx
REAL=   D:\Projects\heaps\hxd\net\Property.hx
```

Full = Common.get_full_path
Unique = Common.unique_path
Real = Extc.get_real_path

The problem here is that get_real_path fails on long file names (>8 chars), making it impossible to get Haxe completion in these files. I'm pretty sure this is related to this PR, we just didn't hit into it since then.

**Comment by ncannasse** [comment]
Please note that I'm not able to reproduce on my own PC, the PC which display these results runs Win7

**Comment by nadako** [comment]
I'll make a Win7 virtual box and try to reproduce.

**Comment by ncannasse** [comment]
I can't find a difference between the two computers btw, both are NTFS and have NtfsDisable8dot3NameCreation=2

**Comment by nadako** [comment]
IIRC, the value `2` means that the settings is per-voume. Could you compare output of `fsutil 8dot3name query D:`?

**Comment by ncannasse** [comment]
Right, 8.3 are activated on my computer, but disabled on the computer that fails

**Comment by nadako** [comment]
This is really weird, because the fix was done to deal exactly with the problem with disabled 8.3 names (since the old `GetShortPathName`+`GetLongPathName` method doesn't work there). Are you sure that Haxe is compiled with this fix included? Anyway, I can't find any info about `FindFirstFile` lowercasing file name...

**Comment by ncannasse** [comment]
I'm sure about it.
Can you reproduce ?

**Comment by nadako** [comment]
I can't yet, but I'm on windows 8.1 with 8dot3 names disabled.

**Comment by ncannasse** [comment]
And I guess you can confirm it works with >8 chars class names?
This might be specific to Win7.

**Comment by ncannasse** [comment]
This can easily be checked with a normal haxe by using
`--display MyLongFileName.hx@0`
This will error saying that `Display file d:/.../mylongfilename.hx should not start with a lowercase letter`

**Comment by nadako** [comment]
Well, I checked out heaps to exact same path (d:/projects/heaps) and added this:

```ocaml
let input = "d:/projects/heaps/hxd/net/SceneInspector.hx" in
print_endline ("INPUT " ^ input);
print_endline ("FULL " ^ (Common.get_full_path input));
print_endline ("UNIQUE " ^ (Common.unique_full_path input));
print_endline ("REAL " ^ (Extc.get_real_path input));
```

and got:
```
INPUT d:/projects/heaps/hxd/net/SceneInspector.hx
FULL d:\projects\heaps\hxd\net\SceneInspector.hx
UNIQUE d:\projects\heaps\hxd\net\sceneinspector.hx
REAL D:\projects\heaps\hxd\net\SceneInspector.hx
```

**Comment by ncannasse** [comment]
That's what I did to get the output:
```
		("--path", Arg.String (fun path ->
			prerr_endline Sys.os_type;
			prerr_endline ("INPUT=  " ^ path);
			prerr_endline ("FULL=   " ^ Common.get_full_path path);
			prerr_endline ("UNIQUE= " ^ Common.unique_full_path path);
			prerr_endline ("REAL=   " ^ get_real_path (Common.unique_full_path path));
			did_something := true;
		),"");
```
(added to haxe commandline options)

**Comment by nadako** [comment]
> get_real_path (Common.unique_full_path path)

oh, the lowercasing comes from `unique_full_path`, it seems that `Extc.get_real_path` fails, but `Main.get_real_path` swallows the error and returns the lowercase path. could you use `Extc.get_real_path` instead?

**Comment by ncannasse** [comment]
Tried, it's not error'ing, it instead returns the lowercase file name. Giving an unexisting file as input does error

**Comment by nadako** [comment]
Could you add the following code here and recompile: https://github.com/HaxeFoundation/ocamllibs/blob/master/extc/extc_stubs.c#L244

```c
		} else {
			DWORD err = GetLastError();
			char msg[255];
			sprintf(msg,"get_real_path error: %d", err);
			failwith(msg);
		}
```

**Comment by nadako** [comment]
As I said, lowercasing comes from the `unique_full_path` call, but it seems that `FindFirstFile` fails to find the file.

**Comment by ncannasse** [comment]
Ok, tried and rebuilt, it didn't do the error anymore, it seems that for some reason my libs where not recompiled on this computer :'( so while Haxe was up to date, and extc sources were, extc binaries were not sorry about the whole thing.

Sadly we still can't get that completion, but I'll open another issue for that :)

**Pull request merged**
