### PR TITLE
Readme: add HashLink to list of targets

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Simn** [comment]
I feel like that should link somewhere...

**Comment by Gama11** [comment]
Hm.. I considered that too, but none of the others link anywhere either (not even NekoVM)...

"Somewhere" should be http://hashlink.haxe.org/ if a link is added I guess.

**Comment by Simn** [comment]
Yes that's fine.

**Comment by Simn** [comment]
I'll add it, have to change something else in the readme anyway.

**Pull request closed without merging**
