### PR TITLE
`haxe.Utf8`

### LINKED ISSUE #8175: haxe.Utf8
* `encode`, `decode` and `validate` should be either deprecated or replaced with bytes
* we keep the other API, by default they should iterate on charCodeAt but in case the platform is #if tf16, they should correctly decode the surrogate pairs
* `haxe.Ucs2` should be moved to hx3compat
* Lua should not have a static char method as String.fromCharCode already does the same
* compare should be removed

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #8175 

- [x] js
- [x] as3
- [x] flash
- [x] java
- [x] cs
- [x] lua
- [x] python
- [x] php
- [x] cpp
- [x] hl
- [x] neko
- [x] eval

### CODE REVIEW

**Comment by Simn** [comment]
We should add some warnings to the documentation, specifically about both `length` and `charCodeAt` having linear cost over the number of characters (on UTF16 targets). I'd even go one step further and discourage the usage of (multiple) `charCodeAt` operations on the same string because this is a huge performance trap.

**Comment by RealyUniqueName** [comment]
@hughsando I've removed `cpp` specific implementation of `haxe.Utf8`. Cpp target passes tests with the common one. Do you think it's enough?

**Comment by hughsando** [comment]
Yes, AFAIK, cpp should be giving the same results as others (ie, JS) so hopefully should not need any specific code.

**Comment by Simn** [comment]
Is this validate function for eval any different from the one in uTF8.ml?

**Comment by RealyUniqueName** [comment]
Yes. This one checks for surrogate codes. The UTF8.ml fails these tests:
https://github.com/HaxeFoundation/haxe/blob/fc6915914e80706edf9fd9d87f171b8cb85fb35c/tests/unit/src/unitstd/haxe/Utf8.unit.hx#L53-L54

**Comment by Simn** [comment]
IMO we should lose encode and decode. We're changing the signature of this anyway, so this does nothing for backwards compatibility. It's just a different interface into the Bytes API and I don't see the point of that.  It might even be harmful because a "Bytes should be String" error might lead users to just call `toString` on the bytes object, and then things get really weird.

**Comment by RealyUniqueName** [comment]
I agree.

What we lack in our API is a simple way to remove faulty chars from a string to make it a valid UTF8. Because a user is not always in control of his strings. 
E.g. here: 
https://github.com/HaxeFoundation/haxe/blob/f0be760d8673a3bbb621bf6da956c0950c0a7b9a/std/sys/Http.hx#L404-L406
If a web server emits a bytes sequence, which is not compatible with utf8, then `Http.request()` will throw an exception on eval.

**Comment by RealyUniqueName** [comment]
Looks like for neko `encode` and `decode` is the only way to deal with UTF8. Because `haxe.io.Bytes` ignores `encoding` arguments in neko implementation.

**Comment by ncannasse** [comment]
@RealyUniqueName neko strings are "raw bytes" so we can assume they are already UTF8 encoded in memory.

**Comment by ncannasse** [comment]
>  What we lack in our API is a simple way to remove faulty chars from a string to make it a valid UTF8. 

This simply shouldn't be possible at all to have an "invalid string" constructed anymore. We can have invalid bytes, but any result returned by bytes decoding should give some valid string (maybe cut or some character replaced by `<?>` or throw an error)

PS: this excludes neko which is not part of our unicode plans

**Comment by ncannasse** [comment]
PS: I added comments on #8175 related to API. I think we should move haxe.Utf8 to hx3compat and introduce haxe.Unicode instead.

**Comment by RealyUniqueName** [comment]
> This simply shouldn't be possible at all to have an "invalid string" constructed anymore

This is still possible by reading from a file or using target-specific API.

**Comment by ncannasse** [comment]
> This is still possible by reading from a file or using target-specific API.

No that should not be possible. Using "RawNative" for encoding just says you're reading using the native "natural" encoding, it should never return an invalid string which has not be validated.

**Comment by RealyUniqueName** [comment]
Do you mean `Bytes.getString(RawNative)` should validate the result and throw? What's the difference with `Bytes.getString(UTF8)`?

**Pull request closed without merging**
