### PR TITLE
[typer] better error messages when importing nonexistent subtypes / fields

### PR DESCRIPTION
**Pull request by kLabz**
See #10897 

Would also be nice to do the same when using fully qualified paths, but not sure how feasible that would be.

### CODE REVIEW

**Comment by Simn** [comment]
Are these tests supposed to fail? There's only one failure and that's because of a different range.

**Comment by kLabz** [comment]
No, I did implement those. I didn't commit the fully qualified ones yet, need to clean those a bit

**Comment by kLabz** [comment]
> Are these tests supposed to fail? There's only one failure and that's because of a different range.

I added failing tests https://github.com/HaxeFoundation/haxe/pull/10899/commits/659de5cb0d1fe292cbb109e69dfe17a29dfbe071 for the two cases I'm not sure how to handle

```
projects/Issue10897/fullpath-module-field-fail.hxml
-FullpathModuleField.hx:2: characters 2-18 : Module ModuleFields does not define field baz (Suggestion: bar)
+FullpathModuleField.hx:2: characters 2-14 : Module ModuleFields does not define type ModuleFields

projects/Issue10897/fullpath-subtype-fail.hxml
-FullpathSubtype.hx:2: characters 8-17 : Module Types does not define type Baz (Suggestion: Bar)
+FullpathSubtype.hx:2: characters 8-13 : Module Types does not define type Types
+FullpathSubtype.hx:2: characters 8-13 : ... For function argument 'v'
```

**Comment by Simn** [comment]
Yeah the expression-level ones are quite difficult. This portion of code has been working very well since the nadako-rework, but the underlying logic is still complicated. There's a lot of try/resume going on, so communicating meaningful information is not very obvious.

I'll take a look but I don't want to spend too much time on this because it'd be little more than a small QOL improvement anyway.

**Comment by kLabz** [comment]
Yeah I agree; handling only imports for now is fine I guess, it's already an improvement.
Can just disable/remove the expression level tests for now if it's any trouble to implement.

**Comment by Simn** [comment]
We can catch this case in `handle_efield` with this (next to the `Unknown_ident` one):

```ocaml
| Error (Type_not_found((_,mname),tname,Not_defined),_) when tname = first.name && tname = mname
```

However, when we put `ModuleFields` in a package and try `pack.ModuleFields.baz`, we already end up in another code path which results in `Type not found: pack.ModuleFields`.

So yeah I think we shouldn't worry about this at the moment and just merge the changes you've already made. It might be possible to clean up this field chain handling code some more (there are some `TODO` comments there as well), but as I said, this isn't exactly easy.

**Pull request merged**
