### PR TITLE
Move List to haxe.ds.List

### PR DESCRIPTION
**Pull request by kevinresol**
#6586

### CODE REVIEW

**Comment by back2dos** [comment]
Seems to me that the question what to do with `Lambda` is quite strongly related ;)

**Comment by Simn** [comment]
Right, Lambda... How about this:

1. Move current Lambda.hx to hx3compat
2. Create std/haxe/Lambda.hx which only has the List-agnostic stuff, and maybe make it nicer in general (whatever I mean by that).

**Comment by Simn** [comment]
Also: I totally forgot about haxelib... oh man

**Comment by kevinresol** [comment]
Added PR in haxelib

**Comment by Simn** [comment]
Nice, thanks!

... so how do we CI this properly? Or should I just merge both and hope for the best?

**Comment by kevinresol** [comment]
Run on your machine? 😀

**Comment by back2dos** [comment]
There's a bit of a problem in this case, which depends on the class *name* on quite a few platforms: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Serializer.hx#L291

I guess matching against "haxe.ds.List" would work just fine.

**Comment by Simn** [comment]
Merged both PRs, let's see how it goes... and thanks!

**Comment by kevinresol** [comment]
And you will have to update the haxelib ref

**Comment by Simn** [comment]
Right, done!

**Pull request merged**
