### PR TITLE
Add sys.ssl for neko and cpp

### PR DESCRIPTION
**Pull request by pperidont**
New Merged PR (see #4929)

It requires HaxeFoundation/hxcpp#393

Main known limitations :
 - Certificate.loadDefaults() is not implemented on iOS
 - SSL contexts should not be shared across threads. Actually it can be supported on neko, depending on the mbedTLS lib compilation options. More informations on this subject can be found on mbed tls site : https://tls.mbed.org/kb/development/thread-safety-and-multi-threading

### CODE REVIEW

**Comment by Simn** [comment]
There seems to be something wrong with travis.yml, try checking it with http://lint.travis-ci.org/:

```
syntax error: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 126 column 3
```

**Comment by Simn** [comment]
There's some issue with haxelib according to our CI:

```
0.02s$ mkdir ~/haxelib && haxelib setup ~/haxelib
Called from /home/travis/build/HaxeFoundation/haxe/std/neko/_std/sys/ssl/Certificate.hx line 120
Uncaught exception - load.c(237) : Failed to load library : ssl.ndll (ssl.ndll: cannot open shared object file: No such file or directory)
```

**Comment by ncannasse** [comment]
Which version of neko is used ? It should use Git one.

**Comment by Simn** [comment]
It does use git neko, but I don't think git neko actually builds ssl.ndll.

**Comment by ncannasse** [comment]
@pperidont @andyli should it not be done automatically as part of install script?

**Comment by Simn** [comment]
Ok that was not so easy to spot in the travis log, but there's an error when trying to compile ssl.ndll: `Include file mbedtls/error.h not found, skipping mbedTLS library compilation`

**Comment by Simn** [comment]
Ah, but that was a previous build, probably has been fixed by https://github.com/HaxeFoundation/haxe/pull/5014/commits/b78409159bf49f2452fcec447e50376deeec128c already.

**Comment by ncannasse** [comment]
@pperidont I would be interested to see if it's possible to change java/cs specific SslSocket into the standard sys one, if you have some time to look into that, pinging also @waneck

**Comment by pperidont** [comment]
The first error was during mbedtls installation : `sudo: must be setuid root`.
I add `sudo: required` in my last commit, that should fix this error,

neko need mbedtls installed on system to compile ssl.ndll and it will be available as apt-get package only in next Ubuntu (xenial 16.04). I add a `make && make install` in travis.yml, but it requires sudo.

**Comment by Simn** [comment]
Great, now it looks much better and only fails on hxcpp because the PR isn't merged yet. I'll merge both for the RC because this is pretty important.

**Comment by Simn** [comment]
@pperidont: Now this can't be merged again, probably due to the haxe.Http changes from your other PRs. Could you update again?

**Comment by pperidont** [comment]
Merge done, the conflict was in .travis.yml

**Comment by Simn** [comment]
I have merged the hxcpp PR but this still seems to fail:

```
Called from sys.ssl.Certificate::boot /home/travis/build/HaxeFoundation/haxe/std/cpp/_std/sys/ssl/Certificate.hx line 116
Called from cpp.Lib::load /home/travis/build/HaxeFoundation/haxe/std/cpp/Lib.hx line 34
Error : Could not load module ssl@cert_load_defaults__0
Command exited with 255 in 0s: /home/travis/build/HaxeFoundation/haxe/tests/unit/bin/cpp/Test-debug []
```

**Comment by Simn** [comment]
There's another problem: `Uncaught exception - Incompatibilities between sys.ssl.DigestAlgorithm in neko,macro and cpp (could not merge definition)`

Could you add `@:coreApi` to all the platform-specific public types? If DigestAlgorithm is the same on all implementations it should probably be moved to its own file so it can be shared. If it's different then the type should be made private.

**Comment by Simn** [comment]
`/home/travis/build/HaxeFoundation/haxe/std/sys/ssl/Certificate.hx:19: characters 8-38 : No overloaded method named get_notAfter was compatible with the property notAfter with expected type Void -> Date`

Not sure yet where that originates from...

**Comment by Simn** [comment]
Probably fixed by https://github.com/HaxeFoundation/dox/commit/6e1ed4d3991715cc47810e4361a4895cfff84cf6 (not sure yet, travis is not very fast right now).

**Comment by Simn** [comment]
Or not, still failing the same way.

**Comment by pperidont** [comment]
Ok, my last commit bbcc08c71f73e31e427c2eff024e6d6ee0a72fc0 should be better.

As discussed with Nicolas, sys.ssl.Socket now extends sys.net.Socket, this is more consistent with sys.net.UpdSocket and the existing net.SslSocket in java and php.

The tests on Mac should requires https://github.com/HaxeFoundation/hxcpp/pull/410

**Comment by Simn** [comment]
It passed!

Thank you for the patience and the contribution.

**Comment by Simn** [comment]
Hmm, merging this caused the hxcpp tests to start failing:

```
$ mkdir ~/haxelib && haxelib setup ~/haxelib
Called from /home/travis/haxe/std/neko/_std/sys/ssl/Certificate.hx line 120
Uncaught exception - load.c(237) : Failed to load library : ssl.ndll (ssl.ndll: cannot open shared object file: No such file or directory)
```

**Comment by Simn** [comment]
Ah, I overlooked the error again:

```
Compiling ssl...
Include file mbedtls/error.h not found, skipping mbedTLS library compilation
```

**Comment by andyli** [comment]
I'm updating the config to install mbedTLS now ;)

**Comment by andyli** [comment]
Its still failing:
```
Test Socket
  Spawn client..
  connect localhost..
Test Failed:Unexpected error in Socket: Invalid socket handle
############# Errors running tests:
   Unexpected error in Socket: Invalid socket handle
RunTests.hx:94: Error running std32 : failed:cpp32/Test 
Skip test std64
There were errors:
Error running std32 : failed:cpp32/Test 
The command "haxe --run RunTests std32" exited with 255.
```

**Comment by Simn** [comment]
People are coming across this too:

```
<PSvils> Simn: `Called from C:/Projects/haxe/std/neko/_std/sys/ssl/Certificate.hx line 120
<PSvils> Uncaught exception - load.c(237) : Failed to load library : ssl.ndll`
<PSvils> latest haxe from git
<PSvils> can't find the ssl.ndll in the haxe repo anywhere :(
```

**Comment by andyli** [comment]
I think we should look into supporting neko 2.0 by making the loading of ssl.ndll lazy.
I mean unless the user really use https or any of the ssl functions, it shouldn't fail like this.

**Comment by Simn** [comment]
I agree

**Comment by ncannasse** [comment]
That's for sure, @pperidont you need to replace neko.Lib.load by neko.Lib.loadLazy so in case there is no ssl lib you get the error at runtime when calling the function instead of when loading it.

**Comment by mastef** [comment]
Trying to make calls to a https webservice with neko and it's been a pain so far :-/

On a windows build getting a "Failed to load library : ssl.ndll" - which should be solvable with a recompile.

On a Mac build https requests through http fail throwing an error: `ssl@conf_new`, which happens in http when attempting a `sock.connect(new Host(host),port);`, which then calls `buildSSLContext` and fails on `var ctx : CTX = conf_new( server );`

I'm a little bit at the end of debugging, have been trying to narrow it down further in neko, e.g. to see if the library hasn't been loaded fully. SSL works on the cpp target, just haven't been able to get it working on neko.

Any pointers how to get it running? Are there any additional settings to get SSL running on neko, or any settings that can be double-checked? Haxe is on 3.3.0, neko 2.1.0

**Pull request merged**
