### PR TITLE
string to int64: throw if multiplier has flipped

### PR DESCRIPTION
**Pull request by azrafe7**

### CODE REVIEW

**Comment by azrafe7** [comment]
I'll wait for CI, and then I'll try my best to produce some tests (which are a bit problematic)

**Comment by azrafe7** [comment]
Not good yet. Lua seems to have some issues (not sure why?), and I've found some edge cases too (f.e. -7834911985406430862).
Going to investigate them some more tomorrow...

**Comment by azrafe7** [comment]
I think I the tests are now more robust, but lua has a problem with Int64.toStr() I don't know how to fix.

cc @jdonaldson

**Comment by azrafe7** [comment]
Oh... I only tested lua locally with 5.2.4, but CI seems ok with it now.

**Comment by azrafe7** [comment]
Should the lua issue represent, this line is probably involved: https://github.com/HaxeFoundation/haxe/blob/918231c47fbe56fe5f2583011d6f5a801c87fa93/std/haxe/Int64.hx#L149.

**Comment by jdonaldson** [comment]
Thanks for the heads up... including a line number.  Can you check one more time on the latest repo version?  There's a weird case where sometimes Lua will give me "-0".

**Comment by azrafe7** [comment]
Thing is... I knew where lua was failing, but didn't where to look to fix it (or if it was just a lua version problem on my machine). :stuck_out_tongue: 

Anyway, testing your commit with thousands of random (and some custom) digits strings didn't seem to cause any more issues (no `-0` found). That's good!

At the same time I realized that my tests for _this_ issue are still flawed. :disappointed:

**Comment by ncannasse** [comment]
I'm not sure we should do a lot here. We already don't specify much out-of-range for Std.parseInt/parseFloat, so there's no reason we should specify it for Int64

**Comment by azrafe7** [comment]
Here's my reasoning:

The docs of `parseInt()` and `parseFloat()` say that if the input is unrecognized or invalid the output is null/NaN.

Instead with `Int64Helper.parseString()` is currently possible to feed it a _seemingly valid_ value and get an incorrect/unexpected value back - no errors/null/NaN:

```haxe
trace(Int64Helpert.parseString("18484280858095180538")); // 37536784385628922
```

Moreover it's called Int**64**, so I think it would be common for most people to assume it to have well-defined min and max values (like `Int32` has).

**Comment by azrafe7** [comment]
One last thing, want to clarify that I'm not using any explicit out-of-range values in the fix.

Well I use them in the tests as I can't think of a way to write them properly without them, but the actual code in [Int64Helper only checks for multiplier overflows](https://github.com/HaxeFoundation/haxe/pull/6644/files#diff-7119278c9e987febca49a511d074cf9d).

**Comment by ncannasse** [comment]
We don't want to enforce any kind of overflow or parsing checks on "emulated" Int64 as this would it behave differently than "native" Int64 which does not have all these extra checks. 
Closing for now.

**Pull request closed without merging**
