### PR TITLE
Abstract Int64 implementation

### LINKED ISSUE #1851: Issue 1851 - Int32 and Int64 abstracts - haxe
<i>[Google Issue #1851 : https://code.google.com/p/haxe/issues/detail?id=1851]</i>
 <i>by ncanna...@gmail.com, at 24/05/2013, 13:33:11</i>
It was found just before 3.0 final that multiplication between two Int can overflow on JS/PHP/Flash8 because they use doubles, so only have 52 bits precision.

Int64 was fixed accordingly but we might need again an Int32 compatibility class to allow safe multiply on all platforms.

I propose that we add both haxe.Int32 and haxe.Int64 as abstracts in 3.2, that will use either native implementation if available or emulation if not.

### PR DESCRIPTION
**Pull request by Herschel**
An abstract Int64 implementation and unit tests. The default implementation uses ```class __Int64 { high : Int32, low : Int32 }``` as the underlying type.

 * Int64->Int->Int64 arithmetic operations are supported, e.g.`2 * myInt64` instead of `Int64.ofInt(2) * myInt64`. But if Int64 literals `2L` are on the roadmap, then it might be better to disallow mixed-type operations. Thoughts? I didn't bother with Int64->Float->Float or anything like that.

 * I had to make some tweaks to gencs and genjava for their native implementations. I'm not confident in my changes here. I'm sure I did something silly, so I would appreciate if @waneck could review. In particular, I was running into issues with the Int64s getting casted down to int and/or casted up to doubles when they were captured in an anonymous function.

Anyone have a lib that already uses Int64? It'd be good to test these changes with it.

Closes #1851, #2317.

### CODE REVIEW

**Comment by Simn** [comment]
This is going to conflict with #3654 as well, but I really want to make this change for 3.2. :(

**Comment by Herschel** [comment]
Unfortunately I haven't had the time to work on this in the past few months. The last time I tried merging with the latest changes, I think I was having issues with overload resolution on cs and Java.

If I hop on IRC this weekend, maybe @Simn and @waneck could help me get this running again? I can integrate the fromString implementation from @georgkoester as well. Then hopefully we can get this merged within a year's time ;)

**Comment by ncannasse** [comment]
I would like to have this merged too. For the Std.is issue, we could provide a static Int64.is for new, and see for 3.3+ how to deal with the more general case of abstract runtime type checking

**Comment by Simn** [comment]
@waneck @Herschel: Can we get this merged soon? Hugh broke documentation generation by making Int64 an abstract on cpp so we need this more or less urgently.

**Comment by Simn** [comment]
We did it!

**Comment by ncannasse** [comment]
Congrats ;)

**Comment by Herschel** [comment]
Thanks @waneck and @Simn for the help!

**Pull request closed without merging**
