### PR TITLE
Php reflection fixes

### PR DESCRIPTION
**Pull request by mockey**
Same pull request as before but from a seperate branch

### CODE REVIEW

**Comment by andyli** [comment]
Thanks a lot! It fixed the erazor issue I'm working on!

**Comment by mockey** [comment]
Are you using erazor with PHP?

**Comment by andyli** [comment]
No. I just happened to run its unit test since I went to enable TravisCI for it.

**Comment by mockey** [comment]
I see. Just FYI: I had some more tests enabled in Reflect.unit, but they seem to fail with Java (the ones with `null`). Other targets seem to work:
https://github.com/mockey/haxe/blob/5a309accf9b1abb6d59206548e87333ab6e8fe16/tests/unit/src/unitstd/Reflect.unit.hx#L40
https://github.com/mockey/haxe/blob/5a309accf9b1abb6d59206548e87333ab6e8fe16/tests/unit/src/unitstd/Reflect.unit.hx#L41

**Comment by ncannasse** [comment]
@mockey could you open a Java-specific issue for it?

**Comment by mockey** [comment]
@ncannasse: Done: #4934
I can't set any labels, though, I think.

**Pull request merged**
