### PR TITLE
[js] Added try/catch to HaxeError.init for IE8 compatibility

### LINKED ISSUE #6918: IE8 does not support Object.defineProperty on non DOM objects
The HaxeError uses `Object.defineProperty` to define the `message` property, but it cannot work in IE8, 

[js/Boot.hx#L40-L42](https://github.com/HaxeFoundation/haxe/blob/development/std/js/Boot.hx#L40-L42)

### PR DESCRIPTION
**Pull request by R32**
close #6918

### CODE REVIEW

**Comment by R32** [comment]
I noticed that an empty `catch` block will generate unnecessary code:

```haxe
try {
	throw "exp";
} catch(e:Dynamic) {
}
```
output:
```js
try {
	throw new js__$Boot_HaxeError("exp");
} catch( e ) {
	((e) instanceof js__$Boot_HaxeError); // unnecessary
}
```

**Comment by RealyUniqueName** [comment]
So, what would be the value of `HaxeError.message` in `IE8`?

**Comment by R32** [comment]
> So, what would be the value of `HaxeError.message` in `IE8`?

Okay, but i can't find another solution , and IE8 only has a simple debugger,so I think there is no need to access `HaxeError.message` in IE8

**Comment by RealyUniqueName** [comment]
I mean did you check what `HaxeError.message` is used for? Does it make sense to just ignore this exception without any additional changes?

**Comment by R32** [comment]
I not sure but I guess the `HaxeError.message` will only be used for `captureStackTrace`, Maybe @nadako  knows more details.

**Comment by R32** [comment]
since haxe `try/catch` will add unnecessary code in `__init__`, So I'm using "js.syntax.code" here.

It doesn't look smart, maybe someone will have a more elegant way .

(I did rebase here)

**Comment by RealyUniqueName** [comment]
Ok, I'm not sure, but it looks like `message` getter is only needed for retreiving `HaxeError.message` from non-haxe-generated js code. The haxe-generated js always tries to access `HaxeError.val` directly.

**Pull request merged**
