### PR TITLE
Follow through abstract underlying types for null-checks when matching 

### LINKED ISSUE #11715: Switch Abstract<Null<Int>> generation differ from Null<Int>
Related issue on Hashlink: https://github.com/HaxeFoundation/hashlink/issues/696

I observed that for the following code, t1 and t2 are not generated the same way by the compiler:
	
```haxe
class Test {
	static var b1: Null<Int> = null;
	static var b2: Foo = null;
	static function main() {
		var t1 = switch (b1) {
			case 0: "A";
			case 1: "B";
			default: "C";
		};
		var t2 = switch (b2) {
			case A: "A";
			case B: "B";
			default: "C";
		};
		trace(t1, t2);
	}
}
enum abstract Foo(Null<Int>) {
	public var A = 0;
	public var B = 1;
}
```

dump pretty for these switches generated by the compiler (same if we check js source generated):

```haxe
var t1;
var _g = Test.b1;
if ((_g == null)) t1 = "C" else switch ((_g)) {
	case 0: t1 = "A";
	case 1: t1 = "B";
	default: t1 = "C"
};
var t2;
switch ((Test.b2)) {
	case 0: t2 = "A";
	case 1: t2 = "B";
	default: t2 = "C"
};
```
Note: If we added a `case null : "C"` in t2, the code generated becomes the same as t1.

I can manage it at genhl side, but I don't think the dump should differ here. Maybe there is a missing abstract null check somewhere?

### PR DESCRIPTION
**Pull request by yuxiaomao**
Fixes https://github.com/HaxeFoundation/haxe/issues/11715

### CODE REVIEW

**Comment by Simn** [comment]
Note that this penalizes proper `Null<T>` tagging by generating duplicate null-checks. I have philosophical problems with that because I'd like cleaner input code to generate cleaner output code. IMO if someone is diligent by marking a type occurrence as "nullable", that should not be punished by the code generator.

Is the goal here really to make HL work more like JavaScript with regards to `null`-handling? This is news to me, I was always under the impression that differences between static and dynamic targets were acceptable in this regard.

**Comment by yuxiaomao** [comment]
I agree with you, I don't like duplicate null-checks either. Maybe I misunderstood, for me, `Int` is different for static/dynamic targets and that's ok, but `Null<Int>` is something that should behave the same on static/dynamic target?

Note that this null check is only added when all cases are const integer and the subject is typed as `Null<Int>` by the compiler; in any other cases the code is managed by `with Exit` section.

**Comment by Simn** [comment]
It's not `Int` itself that's different, it's assigning `null` to it. And that's exactly what happens here: our switch subjects are `null` and our cases are plain `Int`. In fact, that might actually be the real problem: should the cases really be `Int` in the first place or should they essentially be `Null<Int>` instead? Your latest example in #11715 makes the think the latter, but I'm not sure which ramifications such a change would have. It would ultimately mean that any `Foo.A` should be inlined as `(0 : Null<Int>)` instead of just `0`, and at a glance that doesn't sound very fun...

**Comment by yuxiaomao** [comment]
Inline `Foo.A` to `(0 : Null<Int>)` on switch case will force many useless allocation and dynamic value comparison on HL, so it's better to keep use Int and test null before that :x

**Comment by Simn** [comment]
I'm not sure how much sense that makes because if a type is "int or null" then surely all parts of the run-time have to account for that anyway. If you worry about allocations and dynamic value comparison you shouldn't be defining an abstract over `Null<Int>` in the first place.

**Comment by Simn** [comment]
Could you try if https://github.com/HaxeFoundation/haxe/commit/1c1d967babb499ce6b51d0b85192c7cd7d7cf4dc fixes your problems? If so, feel free to pull that onto the branch here so we can merge it alongside your tests.

**Pull request merged**
