### PR TITLE
"Class not found" error msg should be "Type not found"

### PR DESCRIPTION
**Pull request by Gama11**
This error is produced by invalid imports. A .hx module can contain any type (abstract, typedef, enum), not just classes.

### CODE REVIEW

**Comment by nadako** [comment]
i wanted to fix this as well, but forgot about it, thanks!

**Comment by Gama11** [comment]
Did you mean to close instead of merging?

**Comment by Simn** [comment]
I remember now why I didn't change it: https://github.com/HaxeFoundation/haxe/blob/development/main.ml#L124

**Comment by Gama11** [comment]
Hm... is it safe to simply replace "class" by "type" there as well?

**Comment by Simn** [comment]
If you put it that way... probably!

**Comment by Gama11** [comment]
Done!

**Pull request merged**
