### PR TITLE
[java][jvm] Parse varargs as haxe.extern.Rest

### LINKED ISSUE #9845: [java][jvm] varargs of extern libs not parsed correctly
Varargs parsed as `java.NativeArray<T>`, while it should be `haxe.extern.Rest<T>`
E.g. java signature of `java.nio.file.Paths.get` is `public static Path get(String first, String... more)`
But using it from Haxe as a method with rest arguments fails:
```haxe
class Main {
	static function main() {
		java.nio.file.Paths.get('.');
	}
}
```
error:
```
$ haxe build.hxml 
src/Main.hx:3: characters 3-31 : Could not find a suitable overload, reasons follow
src/Main.hx:3: characters 3-31 : Overload resolution failed for (param1 : java.net.URI) -> java.nio.file.Path
src/Main.hx:3: characters 28-29 : String should be java.net.URI
src/Main.hx:3: characters 28-29 : For function argument 'param1'
src/Main.hx:3: characters 3-31 : Overload resolution failed for (param1 : String, param2 : java.NativeArray<String>) -> java.nio.file.Path
src/Main.hx:3: characters 3-31 : Not enough arguments, expected param2:java.NativeArray<String>
src/Main.hx:3: characters 3-31 : End of overload failure reasons
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #9845

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Blocked by #9274 (see #9845 for explanation)

**Comment by Simn** [comment]
Could we resurrect this?

**Comment by RealyUniqueName** [comment]
This would be a breaking change.
Currently `JavaExtern.method(nativeArray)` works fine, but after this PR it would require a spread operator: `JavaExtern.method(...nativeArray)`.
We can probably allow passing a value of underlying `Rest` type (native arrays or `Array` on some targets) without spread op, but I don't like that because it leads to ambiguity for signatures like `method(args:Rest<Array<Any>>)`

**Comment by Simn** [comment]
This is clearly not working as intended so I'm fine with breaking it.

**Pull request merged**
