### PR TITLE
Inline PHP functions 

### PR DESCRIPTION
**Pull request by markknol**

### CODE REVIEW

**Comment by markknol** [comment]
I don't understand why the tests are failing. @Simn?

**Comment by Simn** [comment]
Because it's PHP?

I don't know what to do with that. Unless someone wants to investigate I doubt it would be worth the time spent.

**Comment by markknol** [comment]
@Simn I removed more inlines, now it only fails on neko (?), but seems like it just timed out?

**Comment by markknol** [comment]
Uhm edit: now it works. Shall I'll make a nice PR for it?

**Comment by Simn** [comment]
Sure

**Pull request closed without merging**
