### PR TITLE
Documented neko.net.ThreadServer

### PR DESCRIPTION
**Pull request by belohlavek**
Documented neko.net.ThreadServer with information taken from: http://old.haxe.org/api/neko/net/threadserver

### CODE REVIEW

**Comment by Simn** [comment]
I know nothing about this class so I'll just trust that what you're documenting is correct. Thanks a lot for this!

**Comment by andyli** [comment]
@belohlavek Would you briefly check if `cpp.net.ThreadServer` is the same and add the same doc there?

**Comment by belohlavek** [comment]
@Simn I'm no expert either, just ported the previous docs and checked that everything made sense. I'm glad it helped!

@andyli Yes I thought about that too, I'll add the docs for the C++ version tomorrow :)

**Comment by andyli** [comment]
Thanks! : )

**Pull request merged**
