### PR TITLE
Added a typer pass between PBuildClass and PTypeField

### LINKED ISSUE #6226: Unexpected behaviour with @:deprecated and inline get/set
Using `@:deprecated` on a variable with `(get, set)` will not work for the get/set function, if it is defined as inline. It only works when the meta is on an inline function.

```haxe
class Main {

	static var a:Int;
	@:deprecated("Not shown")
	static var b(get, never):Int;
	//@:deprecated("Would be shown")
	static inline function get_b():Int { return a;}

	public static function main() {
		a = 1;
		trace(b);
	}
}
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #6226

Currently a function, which copies deprecation meta from a property to getter, is delayed to `PTypeField`. But since inlining happens during `PTypeField` too, that function is executed _after_ inlining. So at the moment of getter inlining the deprecation meta is not yet copied to the getter.
This PR adds a typer pass `PConnectFields`, which allows to deal with property/accessor relation before `PTypeField`.

### CODE REVIEW

**Comment by Simn** [comment]
We can probably argue about the exact name for a couple hours, but yes I've previously come to the conclusion that we need a pass in the middle of these two. I don't really remember what for, but it will probably come up again.

Could you check if this allows us to get rid of `delay_late`?

**Comment by RealyUniqueName** [comment]
> I've previously come to the conclusion that we need a pass in the middle of these two. I don't really remember what for, but it will probably come up again.

Here it is: https://github.com/HaxeFoundation/haxe/issues/6225#issuecomment-327417875

> Could you check if this allows us to get rid of delay_late?

Looks like we still need it because of this: https://github.com/HaxeFoundation/haxe/commit/fbda75f0661589d613d86becdad10c5c928cb9bd#diff-87ac64b477679e8a74ca5d95e4b67018R3024

> We can probably argue about the exact name for a couple hours

I'd like to choose a better name. Maybe something like `PClassBuilt` or `PAfterBuildClass` or `PSealClass`?

**Comment by Simn** [comment]
> Looks like we still need it because of this: fbda75f#diff-87ac64b477679e8a74ca5d95e4b67018R3024

What do you mean? My thinking is that a late PBuildClass should be the same as a normal PConnectField.

**Comment by RealyUniqueName** [comment]
I mean in that commit `delay_late` is used for another attempt to actually build a class. And if we change it from `delay_late PBuildClass` to `delay PConnectFields` then all those `flush_pass PClassBuild` in a couple of places in the compiler will not trigger it anymore.

**Comment by Simn** [comment]
Right, that makes sense.

Good to merge if the Java Mac failure is unrelated, which it should be.

**Pull request merged**
