### PR TITLE
Specify different combinations of negative pos & length in String.substr

### LINKED ISSUE #4365: [js] HxOverrides.substr
It seems that `String.substr` with negative index seems to work for IE > 8 nowadays. So it might make sense to remove the old override with the `js-es5` flag as it is done with `Array.indexOf` and the like.

On a sidenote the override function has support for negative length as well for some reason:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/HxOverrides.hx#L75
Should it?
But then that only works with `pos = 0` due to the first condition:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/HxOverrides.hx#L70

This is some pretty old code from 2006 actually:
https://github.com/HaxeFoundation/haxe/commit/2373abc51e54b29484768089340da210ae215749
https://github.com/HaxeFoundation/haxe/commit/1c90918d126ede685aff8aa2baed901c01b1f201
https://github.com/HaxeFoundation/haxe/commit/a2c9d5eb1f97ae738dd77b7fe72302ef5273d582
Might be worth a revision...;-)

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #4365

### CODE REVIEW

**Comment by Aurel300** [comment]
Please document if some of this is new.

**Comment by Simn** [comment]
@RealyUniqueName What do you want to do with this? CI is failing all over the place.

**Comment by RealyUniqueName** [comment]
I want to specify `substr` behavior with negative `pos` and `length`.
Let's keep it open for now. If I couldn't make it till 4.1, I'll move it to 4.2

**Comment by Simn** [comment]
I don't think this PR does much for us. I'm not opposed to strengthening the specification for `substr`, but that likely has to be approached in a more organized manner.

**Pull request closed without merging**
