### PR TITLE
Add responseHeaders to HttpJs and HttpNodeJs

### PR DESCRIPTION
**Pull request by haath**
see #10794

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by haxiomic** [comment]
Thank you for the PR @haath!

**Comment by Jarrio** [comment]
Bump

**Comment by Simn** [comment]
Any reason to initialize these to `null` instead of an empty map?

**Comment by haath** [comment]
> Any reason to initialize these to `null` instead of an empty map?

My reasoning is that because in the `js` targets the request is asynchronous, the headers of the previous request should be cleared when a new one is started. And then remain `null` until there is a response.

Why reset it to `null` instead of an empty map then? Well I think design-wise it better conveys that there has been no response yet. An empty map could still imply that there was a response with no headers.

In my opinion the same thing should have been done for `sys.Http`, because with multi-threading and such it is still theoretically possible to read old headers while a new request is ongoing. But I didn't want to touch that one as it would involve changing the public API.

Probably the best would have been to just add the headers to one of the callbacks, it's a bit awkward in terms of usage to get the data from the callback, but then also need a reference to the `Http` object to get the headers...

**Pull request merged**
