### PR TITLE
[python] add a hack to work around #7436 for now

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Simn** [comment]
I'm astonished that you of all people would propose a hack like that... :D

... but I agree that this is probably a good idea. Assigning to @frabbit in case he has other plans.

**Comment by Gama11** [comment]
I have to admit, I was inspired by 22494d769d862945d2cae6858bf90fd3eba7a34c. :P

**Comment by Simn** [comment]
Ok this is the worst thing I've ever merged but I don't want  to spend any time thinking about half-assed solutions for this. Will solve this properly once we have typed metas and a proper way to configure warnings.

**Comment by Simn** [comment]
Well played! :D

**Pull request merged**
