### PR TITLE
Array.contains (closes #3323)

### LINKED ISSUE #3323: [proposal] Array.contains - a method to check if element present in the array
It's quite a common need to check if an array contains an element and it's a shame we don't have a function for that. Even tho we now have `indexOf`, checking index against `-1` looks stupid and is not error-proof. Also, performance-wise, a simple `contains` method can be faster, as it doesn't need to handle negative indices and stuff.

So I suggest adding `Array.contains` method to check whether an element present in the array by standard equality. It should be a nice complement to the `Array.remove` method we already have.

I was thinking of naming it `exists`, similar to `Map`, but then it will conflict with existing `using Lambda` code, so I think `contains` is a good alternative.

@Simn @ncannasse what do you think? I could implement that (with unit-tests of course).

### PR DESCRIPTION
**Pull request by nadako**
Resurrected an old branch, let's see what CI has to say about it.

- [x] remove the temporary CI change (a07293ee92ecd3b989fc35535a60bd7380db5d57)

### CODE REVIEW

**Comment by Gama11** [comment]
Before anybody starts discussions about naming: we already have [`StringTools.contains()`](https://github.com/HaxeFoundation/haxe/blob/75523c67a594091019a4e37dfb71fe1d75e3eeee/std/StringTools.hx#L211).

**Comment by nadako** [comment]
> Before anybody starts discussions about naming: we already have [`StringTools.contains()`](https://github.com/HaxeFoundation/haxe/blob/75523c67a594091019a4e37dfb71fe1d75e3eeee/std/StringTools.hx#L211).

Yep, and also this was approved in https://github.com/HaxeFoundation/haxe/issues/3323#issuecomment-368866515.

**Comment by Simn** [comment]
I'm almost too afraid to ask, but does it or does it not work through Dynamic?

**Comment by nadako** [comment]
Not on JS, no, that would be #3330

**Comment by Simn** [comment]
Well, everyone seems to be fine with this not working on JS, so if it's only that I don't mind. But in that case we should add some tests for it on the other targets.

**Comment by nadako** [comment]
Done.

**Comment by nadako** [comment]
CI looks good (the failing linux macro test is unrelated), so waiting for @hughsando to check https://github.com/HaxeFoundation/hxcpp/pull/886

**Pull request merged**
