### PR TITLE
null cast/is/catch

### PR DESCRIPTION
**Pull request by Simn**
For #7115

* [ ] flash
* [x] java
* [x] cs
* [ ] cpp

### CODE REVIEW

**Comment by Simn** [comment]
Fixed neko, as3 and python by updating `default_cast`.

Flash fails in the test for #6871 for some reason that eludes me right now.

**Comment by ncannasse** [comment]
Please add a check `f(Std.is(getNull(),Dynamic))`  , I think many platforms currently check Dynamic before null.

**Comment by Simn** [comment]
`catch (e:Dynamic) { trace(Std.is(e, Dynamic)); /* false, lol */ }`

**Comment by Simn** [comment]
And yes you're right, this fails on every single target.

**Comment by ncannasse** [comment]
is(null,null); should be removed from TestReflect:116

**Comment by Simn** [comment]
This PR already removes that.

**Comment by ncannasse** [comment]
@Simn seems like no because it was failing unit tests ;)

**Comment by Simn** [comment]
You committed to development, not the PR branch.

**Comment by ncannasse** [comment]
Uhm yes, but Travis checks the PR against Development right ? I got the TestReflect issue after fixing the Std.is(null,Dynamic) on development.

**Comment by ncannasse** [comment]
Updated failing targets

**Comment by ncannasse** [comment]
JS is now passing once we have merged #7658

**Comment by Simn** [comment]
We have to deal with #7658 before we can finalize this one.

**Comment by ncannasse** [comment]
#7658 is (almost) done, let's finish this one too :)

**Comment by Simn** [comment]
Uhm, after updating from development all targets fail this test again:

```haxe
f(Std.is(getNull(), Dynamic));
```

**Comment by ncannasse** [comment]
I fixed that in fc895aaf18ada34132fd4cec2f351bbbeaff6357 and ad443a5fc8c7eb1512afe89e3f538d12a41878ff

**Comment by ncannasse** [comment]
And you reverted it there: https://github.com/HaxeFoundation/haxe/commit/a200541e35d86af1446d8a8241312c3d835be965#diff-a067785a9bcc7e8d173749ef6261b2c8

**Comment by Simn** [comment]
Updated the list of failing targets.

**Comment by Simn** [comment]
The flash failure is weird:

```
src/unit/TestMain.hx:52: START
src/unit/Test.hx:276: ABORTED : Class cast error in unit.issues.Issue7115.testCast
src/unit/Test.hx:279: STACK :
Called from unit.issues.Issue7115.testCatch (/home/travis/build/HaxeFoundation/haxe/tests/unit/src/unit/issues/Issue7115.hx line 86)
Called from Function.http://adobe.com/AS3/2006/builtin::apply
Called from Function.<anonymous>
Called from unit.TestMain.main (/home/travis/build/HaxeFoundation/haxe/tests/unit/src/unit/TestMain.hx line 141)
```

It refers to this code:

```haxe
		var i = try {
			throw (getNull() : Interface);
		} catch(s:Interface) {
			1;
		} catch(e:Dynamic) {
			2;
		}
		eq(2, i);
```

However, if I isolate that into a standalone example it works as expected:

```haxe
private interface Interface { }

class Main {
	static function eq<T>(e1:T, e2:T) {
		trace(e1, e2);
	}

	static public function main() {
		var i = try {
			throw (getNull() : Interface);
		} catch(s:Interface) {
			1;
		} catch(e:Dynamic) {
			2;
		}
		eq(2, i);
	}

	static function getNull<T>():T {
		return null;
	}
}
```

I can't find any compilation parameters that could influence this.

@ncannasse: Any quick idea what could cause this?

**Comment by Simn** [comment]
Java and C# work now.

C++ still has some issues...

**Comment by Simn** [comment]
C++ only has three remaining failures:

```
src/unit/issues/Issue7115.hx:19: 0 should be null
src/unit/issues/Issue7115.hx:20: 0 should be null
src/unit/issues/Issue7115.hx:21: false should be null
```

The tests this refers to are:

```haxe
		eq(#if static 0 #else null #end, cast(getNull(), Int));
		eq(#if static 0. #else null #end, cast(getNull(), Float));
		eq(#if static false #else null #end, cast(getNull(), Bool));
```

So the problem is that `cast(nullValue, Int)` ends up as `null` instead of `0`. @hughsando: Where do we fix this?

**Comment by hughsando** [comment]
I think you need this one: https://github.com/HaxeFoundation/haxe/commit/eb412e2d9d2968f7dc70abf1b57cb480660d2385 and the latest hxcpp.

**Comment by Simn** [comment]
Nice, C++ passes now!

So only the weird flash thing left.

**Comment by Simn** [comment]
The flash issue is crazy. If I comment out the failing test it fails on a test _earlier_. If I comment that out as well it fails even earlier. If I comment out all the tests it fails in a different file. I don't know wtf is going on right now but we can't merge this PR like that...

**Comment by Simn** [comment]
Turns out the problem was in a different place. I have no idea why the reported error pointed me elsewhere...

I have commented out the failing tests for now so we can merge this. There's #7721 to keep track of it.

**Pull request merged**
