### PR TITLE
Add unit tests for several cpp regressions

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Gama11** [comment]
Looks like a few of those issues will have to be reopened because they are failing on lua / hl / php: https://travis-ci.org/Gama11/haxe/builds/120507180

**Comment by Simn** [comment]
Interestingly the PHP test fails only on Linux.

**Comment by Simn** [comment]
Could you sync this PR again? I'm curious where we're at now.

**Comment by nadako** [comment]
ping, rebase plox

**Comment by Gama11** [comment]
Hm, cpp tests failing with a segfault. https://travis-ci.org/HaxeFoundation/haxe/jobs/146056568#L2661

**Comment by Gama11** [comment]
Now cpp passes on Windows, but not Linux / Mac.. wth.

**Comment by Gama11** [comment]
Ok, this finally passes Travis and is good to merge.

**Comment by RealyUniqueName** [comment]
What's the point of this test? https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue4988.hx
That catch swallows any error.

**Comment by RealyUniqueName** [comment]
Also, analyzer became too smart )
It completely optimizes away whole test body.
@simn @Gama11

**Comment by RealyUniqueName** [comment]
I'm going to correct that test in a PR like this: https://github.com/RealyUniqueName/haxe/commit/e69849d82051bdf748e6ebb917bca8018c25aab6

**Pull request merged**
