### PR TITLE
4.3.4

### LINKED ISSUE #11394: Pull requests for 4.3 Hotfix (part 4)
## 4.3.4

* [x] https://github.com/HaxeFoundation/haxe/commit/dd28b83951356dff776c451e8201fb64577679ac
* [x] 3a9445219a023253ff4c78cdbb84262e8f6a5276
* [x] 7653f686cdff23fa650c80eb4e87030a1b154687 / #11402
* [x] 13666860eceb09a98269d07d97ebbcc6abb6405f
* [x] https://github.com/HaxeFoundation/haxe/commit/ed838d789588487e817a326b60d31c4397ce9012
* [x] https://github.com/HaxeFoundation/haxe/commit/822dd87c1e7e56caac29aa3d42eb7879edeebade
* [x] https://github.com/HaxeFoundation/haxe/commit/dbc9952adf5a7ab30c430ddca0428313dbb1e376
* [x] 4463066539cc707ee74f1e90a770d8c39458c202 / #11560
* [x] #11526

See also: 
* [Bugfix candidates](https://github.com/HaxeFoundation/haxe/issues?q=+milestone%3A%224.3+Hotfix+candidates%22+)

### PR DESCRIPTION
**Pull request by kLabz**
> [!warning]
> This is to be merged to `4.3_bugfix` (do not squash!)

* [x] CI fixes
* [x] Deprecation warnings
* [x] Warn for `--java ... -D jvm` to be replaced with `--jvm ...`
* [x] Backport bugfixes - #11394
* [x] Update changelog

## Backported bugfixes from [4.3 Hotfix Candidates](https://github.com/HaxeFoundation/haxe/issues?q=+milestone%3A%224.3+Hotfix+candidates%22+)

* [x] #11553
* [x] #11427 
* [x] #11399 
* [x] #11526 
* [x] ~#11379~ (not worth it)
* [x] #11285
* [x] #11205 
* [x] ~#11461~ (no semantic difference, not worth it)
* [x] #11581 
* [x] ~#11577~ (old regression)

## Update `-D haxe-next` behavior

* [x] ~Not sure what to do about #11168~ (let's not even try)

Start applying some haxe 5 behavior:
* [x] #11582
* [x] #11318 
* [x] #11533

### CODE REVIEW

**Comment by kLabz** [comment]
Regarding the `bind` change:

```haxe
function f(notOpt:Int, ?opt:String) {}
function g(notOpt:Int, alsoNotOpt:Bool, ?opt:String) {}

function main() {
	var fBind = f.bind(1);
	var gBind = g.bind(1);
	$type(fBind);
	$type(gBind);

	var fBind = f.bind(1, _);
	$type(fBind);

	var f1 = f.bind(1, null);
	$type(f1);

	var g1 = g.bind(1, _, null);
	$type(g1);
}
```

Gives:
```
# 5.0.0 nightlies
src/Main.hx:7: characters 8-13 : Warning : (?opt : Null<String>) -> Void
src/Main.hx:8: characters 8-13 : Warning : (alsoNotOpt : Bool, ?opt : Null<String>) -> Void
src/Main.hx:11: characters 8-13 : Warning : (?opt : Null<String>) -> Void
src/Main.hx:14: characters 8-10 : Warning : () -> Void
src/Main.hx:17: characters 8-10 : Warning : (alsoNotOpt : Bool) -> Void

# 4.3.3
src/Main.hx:7: characters 8-13 : Warning : () -> Void
src/Main.hx:8: characters 8-13 : Warning : (alsoNotOpt : Bool) -> Void
src/Main.hx:11: characters 8-13 : Warning : (?opt : Null<String>) -> Void
src/Main.hx:14: characters 8-10 : Warning : () -> Void
src/Main.hx:17: characters 8-10 : Warning : (alsoNotOpt : Bool) -> Void

# 4.3.4 nightlies
src/Main.hx:7: characters 8-13 : Warning : () -> Void
src/Main.hx:8: characters 8-13 : Warning : (alsoNotOpt : Bool) -> Void
src/Main.hx:11: characters 8-13 : Warning : (?opt : Null<String>) -> Void
src/Main.hx:14: characters 8-10 : Warning : () -> Void
src/Main.hx:17: characters 8-10 : Warning : (alsoNotOpt : Bool) -> Void

# 4.3.4 nightlies with -D haxe-next
src/Main.hx:7: characters 8-13 : Warning : (?opt : Null<String>) -> Void
src/Main.hx:8: characters 8-13 : Warning : (alsoNotOpt : Bool, ?opt : Null<String>) -> Void
src/Main.hx:11: characters 8-13 : Warning : (?opt : Null<String>) -> Void
src/Main.hx:14: characters 8-10 : Warning : () -> Void
src/Main.hx:17: characters 8-10 : Warning : (alsoNotOpt : Bool) -> Void
```

**Comment by kLabz** [comment]
(disregard the branch name, this branch is pretty much about all changes between 4.3.3 and 4.3.4 now)

I've added some changes that I thought we might want to add in addition to the ones tracked in #11394:

* #11553
* #11427 
* #11399 
* #11526 

I can obviously remove some/all from here if that's an issue.

There are also a few more changes that I didn't add (yet), for which there are conflicts / I have some doubts / there is still some work to do:

* ~~#11439~~ - conflicts as I rewrote message reporting on nightlies
* #11379 - conflicts; do we want this?
* #11205 - conflicts; do we want this?
* #11461 - I think we'd want this?
* #11581 - Not merged yet, guess we'd want this too?
* #11577 - I suppose it'd be nice too, but is it done?

As for `-D haxe-next`, I'm not sure what can be done about Rework module resolution #11168 ; any idea?

**Comment by RblSb** [comment]
Would like to have https://github.com/HaxeFoundation/haxe/commit/03aa20efb678e02768c4a25afbf4d69ac4ee11d9, change seems pretty small?

**Comment by kLabz** [comment]
Already cited above

**Pull request merged**
