### PR TITLE
Reset static inits in macros when the context is reused

### LINKED ISSUE #5746: Macro statics initilization
Following conversation in #5676

In macro context (with compilation server), static variables:
a) can be kept in the state they were in the previous compilation (reusing macro context)
b) can be reset the their default value during compilation (discarding + creating a new macro context)

Now in order to improve it, we could fix (a) by generating all statics initialization code in a separate function that would get called when reusing the macro context, so you would get a freshly initialized module. That should render useless the `onMacroContextReused`

For (b) the only solution would be to detect before reusing the macro context (so on the first called macro) if one of the modules of the macro context has been modified.

This would ensure the same statics behavior has you would get without macro context reuse, without the extra time required to initialize the context.

### PR DESCRIPTION
**Pull request by Simn**
This PR changes the macro interpreter so it resets static variables to their initialization value if the macro context is reused. It supports `@:persistent` in case the value should be persisted across multiple compilations.

With this change, we now always reuse the macro interpreter for a given server context. Statics are reset when a new compilation (or completion) is made.

We also deprecate the two haxe.macro.Context functions `registerModuleReuseCall` and `onMacroContextReused`, where "deprecated" means that they now throw an exception. I prefer this over giving a warning because these situations should be addressed.

Closes #5746.

### CODE REVIEW

**Comment by ncannasse** [comment]
If the idea is to have an error, it's a lot better to have a compilation error than a runtime one, so simply remove them from Context.

Also, I think it will be a necessary addition to add `haxe.macro.Context.getStorage(key:String) : Any` (and the corresponding set) that would persist across context changes.

**Comment by Simn** [comment]
> If the idea is to have an error, it's a lot better to have a compilation error than a runtime one, so simply remove them from Context.

Well, macro run-time is still compilation-time, so you get a compilation error either way. I'm fine with removing them too, but in that case we don't get a nice exception that tells the user what's going on.

> Also, I think it will be a necessary addition to add haxe.macro.Context.getStorage(key:String) : Any (and the corresponding set) that would persist across context changes.

I still don't understand why this would be useful. If you want to store stuff like this, you can always declare some `@:persistent static var myStorage` map.

**Comment by back2dos** [comment]
Off the top of my head I'm pretty sure I'll have to tag almost every static var as `@:persistent`, which just seems weird. So could somebody please explain the motivation here? I just don't get it.

**Comment by ncannasse** [comment]
`@:persistent static var myStorage` persist until the macro context changes. Storage would persist across context changes.

**Comment by ncannasse** [comment]
@back2dos macro context reset can happen any time during compilation after some macros have already been executed. So while statics can be used as some cached state that can be rebuild at any time if not set, they should not be used to store some kind of persistent data that is necessary for the macro to work correctly.

**Comment by Simn** [comment]
> @:persistent static var myStorage persist until the macro context changes. Storage would persist across context changes.

Do you mean when the macro hosting the `myStorage` variable changes?

**Comment by ncannasse** [comment]
@Simn or any other file it depends on yes

**Comment by ncannasse** [comment]
But more importantly, it allows you to explicitely tells when you want to load/save your cache.

**Comment by Simn** [comment]
I'm concerned that you might end up with multiple versions of the same prototype. You could `Context.store` or whatever `YourClass`, change `YourClass.hx` and then get the previous version through `Context.getStorage`. I have no idea what exactly happens in such a case.

**Comment by ncannasse** [comment]
That's versioning and it should be handled by adding a version to the key string, unless you want to have to restart your server ;)

**Comment by Simn** [comment]
I have no idea what you mean. What would a version on the key string do?

**Comment by ncannasse** [comment]
@Simn version would mean that if you modify your storage format, you'll have to increment the version and since it's part of the requested key, you will never get back previous results, so no conflict.

**Pull request merged**
