### PR TITLE
Add test cases for issues #10544 & #10545

### PR DESCRIPTION
**Pull request by zagortenej**
Added unit test cases as per @Simn's comment on #10545

### CODE REVIEW

**Comment by Simn** [comment]
I have fixed the eval case, and pushed a fix to hxcpp for the negative hexes: https://github.com/HaxeFoundation/hxcpp/commit/cb38fcc2f89d59c44baa13c10af3ebe15fe1e353

Somehow I ignored the fact that this has to be fixed in the libraries directly. We'll not fix this for neko then because I don't think we plan to have another neko release anyway. I've changed the failing tests to not run on neko accordingly.

Something also fails on HL, will have to look into that as well.

**Comment by Simn** [comment]
The Lua failure is something else we have to check.

And for some reason, HL does not fail on Windows. No idea what's the deal with that.

**Comment by RealyUniqueName** [comment]
HL doesn't fail on my Linux too.
We could blindly add handling of `+` to HL's parseInt, but that doesn't sound like a perfect solution.

**Comment by Simn** [comment]
@Aurel300 Do you happen to have an idea why `Std.parseInt("+123")` would fail on some systems but not on others?

**Comment by Aurel300** [comment]
> @Aurel300 Do you happen to have an idea why `Std.parseInt("+123")` would fail on some systems but not on others?

It failed locally too so I tracked down the issue. On Windows, Hashlink uses `wcstol` directly: [this define](https://github.com/HaxeFoundation/hashlink/blob/c72c5d37162704d8876c564fa15bddfb5eefa02f/src/hl.h#L224) shadows `_utoi` on Windows. On Linux and Mac, that define does not exist, so a custom `_utoi` is provided [here](https://github.com/HaxeFoundation/hashlink/blob/c72c5d37162704d8876c564fa15bddfb5eefa02f/src/std/ucs2.c#L104). It copies decimal chars and `-` into a (non-wide) string buffer and passes that to `strtol`. The oversight here is that `+` is not considered a valid character. Also note that hexadecimal parsing is implemented manually higher up the callstack—unsure why @ncannasse, since both `wcstol` and `strtol` should be able to handle that ([docs](https://www.cplusplus.com/reference/cstdlib/strtol/)).

The fix should be this:

```diff
diff --git a/src/std/ucs2.c b/src/std/ucs2.c
@@ -109,7 +109,7 @@ int utoi( const uchar *str, uchar **end ) {
        while( is_space_char(*str) ) str++;
        while( i < 16 ) {
                int c = *str++;
-               if( (c < '0' || c > '9') && c != '-' )
+               if( (c < '0' || c > '9') && c != '-' && c != '+' )
                        break;
                buf[i++] = (char)c;
        }
```

**Comment by Simn** [comment]
Thanks for checking, that did the trick!

**Pull request merged**
