### PR TITLE
Bug #3648 - Fix exception when calling peer().

### PR DESCRIPTION
**Pull request by ckentgeorge**
Per your request here: https://github.com/HaxeFoundation/haxe/issues/3647

Bug #3648 - Fix exception when calling peer().
Bug #3647 - Return a valid Socket from accept()
Bug #3646 - host().port now returns local port as documented.

### CODE REVIEW

**Comment by ckentgeorge** [comment]
Is there anything I need to do to help this move forward?  I seem to be able to create only one pull request, and I have other changes I would like to share.

**Comment by Simn** [comment]
You can create additional pull requests by creating branches and push your changes to these.

**Comment by ckentgeorge** [comment]
Not meaning to ask questions that are answered elsewhere, but if I have already pushed those changes, is there a way to move them to a new branch?

**Comment by Simn** [comment]
Try git-cherry-pick

**Comment by waneck** [comment]
All changes were merged. Thank you, and sorry for taking so long to review it

**Pull request closed without merging**
