### PR TITLE
Small modifications to PHP exception/error handling

### PR DESCRIPTION
**Pull request by mockey**
make HExceptions with an error code != null catchable, i.e. HExceptions from _hx_error_handler
remove duplicated error message, filename and line in HException from  _hx_error_handler

### CODE REVIEW

**Comment by mockey** [comment]
Some explainations (only if you're interested ;-):
There is this class [`HException`](http://api.haxe.org/php/HException.html), which extends the normal PHP Exception. It is needed as a wrapper so you can `throw "anything"` because PHP5 can only throw Exceptions. But the HException can never be caught as an Exception because of this hard coded line in genphp:
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp.ml#L1565
While this makes sense for things thrown from Haxe, it is not so good for HExceptions, that are thrown from `_hx_error_handler`, that covers error handling from PHP. So I added a check if the error code is set, which should only be set from the error handler.
Also I removed some duplicate text (message, file, line) from the HException that is thrown from `_hx_error_handler`.
This whole `HException` class should maybe be made private or something. It makes no sense to use it in Haxe code.

**Comment by Simn** [comment]
My first question is always if there's any way we can test this.

**Comment by mockey** [comment]
Exceptions can be tested in the test runner, I suppose? So when I catch an exception I can check its type and then proceed, right?

**Comment by Simn** [comment]
Yes, there should be an `exc` function which can be used to check exceptions. I don't know if that allows checking exception types though, so maybe just something custom would work best.

**Comment by mockey** [comment]
I'll try to make something up.

**Comment by Simn** [comment]
You'll have to change the test, it currently causes `src/unit/TestIssues.hx:16: characters 30-39 : Module unit.issues.Issue4973 does not define type Issue4973` on all targets but PHP. Try #ifing out the test function instead.

**Pull request merged**
