### PR TITLE
add remap for full directory or one file

### PR DESCRIPTION
**Pull request by pleclech**
Trying to tackle this issue https://github.com/HaxeFoundation/haxe/issues/4732
as i have myself needed it a couple of time ;)

- you can remap a full package a.b.c to another e.d.... or remap only
one file but the name has to be the same (ex.; a.b.Foo to e.Foo)

### CODE REVIEW

**Comment by Simn** [comment]
This is way too complicated. We don't want to turn --remap into a fancy feature to obscure package paths, it should really only allow simple package remapping.

**Comment by pleclech** [comment]
@Simn Let's developer decide what they want to do with their code, you already trust them when you can give/override  private access to some part of the code ?

**Comment by skial** [comment]
I was really surprised to see this pop into my inbox, thanks @pleclech!

Which feature is the problem, remapping `a.b.c` to `e.d` or remapping a file `a.b.Foo` to `e.Foo`, or is it entire pull request?

**Comment by Simn** [comment]
I'm not a big fan of --remap in general because it might make your code depend on compiler parameters in a weird way. I originally thought remapping a.b to c would be fine, but maybe even that is too much.

What are people using --remap for anyway?

**Comment by skial** [comment]
My current issue is remapping the `js` package to a private package like `a.b.c`, which recreates parts of the js api for some sys targets, a work in progress. This is what lead me to created the issue in the first place. For small or new projects, refactoring the packages to be the same length as the one you want to remap isn't a problem.

An example that I know people in the past have run into is remapping just a single path like `openfl.display` so they can point a single file or path to another implementation, while continuing to use the rest of the framework.

**Comment by pleclech** [comment]
Yes that was also my problem when rewriting some api for flash.

**Comment by hughsando** [comment]
You can handle one or two files easy enough by putting your version in a priority class path, with a typedef pointing to your override implementation (or just override with the same name).

**Comment by skial** [comment]
That's a great idea, thanks @hughsando.

**Pull request closed without merging**
