### PR TITLE
add tests for accessing core type fields hidden behind anons

### PR DESCRIPTION
**Pull request by frabbit**
i added these for the python target, but i'm not sure if these should be part of the specification.

### CODE REVIEW

**Comment by frabbit** [comment]
@simn @ncannasse any complains or can we merge this?

**Comment by Simn** [comment]
If only travis would run...

**Comment by frabbit** [comment]
sorry, i thought travis was green, but i looked at the wrong build

**Comment by nadako** [comment]
apparently c++ is not happy with string reflection https://travis-ci.org/HaxeFoundation/haxe/jobs/53665354

**Comment by frabbit** [comment]
@hughsando this looks like a bug in hxcpp when this is supposed to work.

**Comment by frabbit** [comment]
@nadako i already wondered if this reveals some problems ;)

**Comment by hughsando** [comment]
This is quite tricky.  I think there are similar issues if you do this: 
```
static function createMap<T:{}>(a) {
     var m = new Map<T,Bool>();
    m[a] = true;
    return m;
}
```
You can pass a string in and you will get an object map instead of a string map.  String is not actually an "object with fields" - it is much closer to an abstract in cpp.
But this may just be manifestation of the cast issue already reported, since I think boxing should solve the issue.

**Comment by frabbit** [comment]
@Simn @ncannasse i can also add tests for all the other methods of String and Array too (python would need some adjustments i guess), but the question is if it's part of the specification?

**Comment by Simn** [comment]
Array definitely. String I'm not sure about, there have been issues with String being assigned to {} for a while now.

**Comment by frabbit** [comment]
the problem that i see is that all of them will compile fine, but will possibly fail at runtime which is bad.

**Comment by frabbit** [comment]
but currently we have tests for some String methods which should work and all other methods are not required to work which seems quite arbitrary.

**Comment by Simn** [comment]
I agree, the problem is that String should not be a real class to begin with. We can't really change that at this point in time though.

**Comment by frabbit** [comment]
ok, that means i will remove the string tests from this pull request. And Strings should become abstracts in haxe4, right?

**Comment by frabbit** [comment]
i also added commented out tests for all other array methods, should we decide to make them available too.

**Comment by hughsando** [comment]
The string issue was the same as the cast issue I had with cpp earlier, and should be working on cpp now.

**Pull request merged**
