### PR TITLE
[js] Remove TypedArray polyfill

### PR DESCRIPTION
**Pull request by haxiomic**
See #7091 for discussion

- Removes `js.html.compat` directory
- Removes references to `js.html.compat` files
- Removes `EMULATED` field from `ArrayBufferView` and updates tests that use it

### CODE REVIEW

**Comment by nadako** [comment]
I'll assign this to @ncannasse because he worked so much on those polyfills :)

**Comment by haxiomic** [comment]
See #7407 for test failures

**Comment by ncannasse** [comment]
I only work on Chrome now so feel free to merge anytime when ready :)

**Comment by nadako** [comment]
@haxiomic Should I merge this?

**Comment by haxiomic** [comment]
@nadako, not just yet - final change is to add some flags to disable the failing tests (#7407). l’ll make time to do it today

\* just waiting on AppVeyor now

**Pull request merged**
