### PR TITLE
[ci] Update luv to 0.5.12

### LINKED ISSUE #11116: luv 0.5.12 broke compiler build
I tried to package haxe 4.3.0 for fedora, got the build error as follows:
```
File "src/macro/eval/evalLuv.ml", line 2392, characters 15-20:
2392 | 				"uid",vint p.uid;
       				           ^^^^^
Error: This expression has type Unsigned.ulong = Unsigned.ULong.t
       but an expression was expected of type int
```

full build log: https://kojipkgs.fedoraproject.org//work/tasks/258/99770258/build.log

I believe it's because of Luv 0.5.12, which was released just 3 days ago and it's not yet on OPAM: https://github.com/ocaml/opam-repository/pull/23652

### PR DESCRIPTION
**Pull request by kLabz**
Also:
 * use [setup-ocaml](https://github.com/ocaml/setup-ocaml/) on windows to be able to access recent packages (see #11116)
 * use [a fork](https://github.com/kLabz/setup-ocaml/tree/win32) of setup-ocaml to make our 32bit windows build work
 * bump ocaml to `4.08.1` (the one in ubuntu 20.04; needed for setup-ocaml) -- checked with Andy, it's ok

Closes #11116

Note to windows users: for updating to luv 0.5.12, please install linux.
Alternatively, you can do that:
```
opam repository remove default --all-switches
opam repository remove opam-repository-mingw --all-switches
opam repository add default https://github.com/ocaml/opam-repository.git --all-switches --set-default
opam repository add opam-repository-mingw https://github.com/ocaml-opam/opam-repository-mingw.git#sunset --all-switches --set-default
opam update
opam upgrade
```

### CODE REVIEW

**Comment by RblSb** [comment]
Isn't you downgraded current latest-ocaml ci to 4.08 on Windows (instead of using 4.14)? Can this affect performance in builds?
Also 4.08 can in theory affect macOS 10.13 support:
https://github.com/HaxeFoundation/haxe/commit/56bb846c725d383629460db9161d7e471ce85c28
https://github.com/HaxeFoundation/haxe/issues/10723

**Comment by kLabz** [comment]
I'm _upgrading_ from 4.07 to 4.08.
As for macos 10.13, it's been EOL for a long while :thinking:

**Comment by MisterDA** [comment]
Out of curiosity, why are you using OCaml 4.08 rather than 4.14? A lot of improvements have been made since, especially on Windows.

**Comment by kLabz** [comment]
We're syncing with the version available on the oldest supported ubuntu LTS (which will be 20.04 in a short while)

**Pull request merged**
