### PR TITLE
Flatten blocks in inline constructors. Fixes #6229

### LINKED ISSUE #6229: minor var fusion regression after the inline ctor rework
The following used to fuse before #6178 merge (see below):

```haxe
class Vec2 {
    public var x:Float;
    public var y:Float;

    public inline function new(x) {
        this.x = x;
        this.y = x;
    }
}

class Main {
    static inline function mkVec(x)
        return new Vec2(x);

    static function f()
        return 1.0;

    inline function getVec() {
        return mkVec(f());
    }

    static var inst:Main;

    static function main() {
        var v = inst.getVec();
        trace(v.x + v.y);
    }
}
```

was 
```js
Main.main = function() {
	var x = Main.f();
	console.log(x + x);
};
```

now
```js
Main.main = function() {
	var v_y;
	var v_x;
	var x = Main.f();
	v_x = x;
	v_y = x;
	console.log(v_x + v_y);
};
```

note that if we remove the block from the `getVec` function (so it's body is just the return expression), it fuses again

cc @basro as he might have a quick idea what and how to fix that :)

### PR DESCRIPTION
**Pull request by basro**
The reworked constructor inliner was already unwrapping blocks inserted by constructor inlining, this change will make it also unwrap any nested block inside of an unwrapped block.

This should fix #6229

### CODE REVIEW

**Comment by Simn** [comment]
Could you add a test case for what this fixes so we can be sure it doesn't regress again later?

**Comment by basro** [comment]
Made a test.
Here it is failing in a branch before this fix: https://travis-ci.org/basro/haxe/builds/227975300

**Comment by nadako** [comment]
Nice, the fusion was fixed in my codebase. If you guys are interested I think there's something to improve further here (left is pre-new-inline, right is latest):



There are a couple of redundant vars not fused here (e.g. `_x`, `_y` which were ctor arguments). Also what would be nice is that instead of `this`, var names would be prefixed with the original var name (if it's possible to get from context, of course (so in this example it would be `deployDelta_x` instead of `_this_x`)).

I can reduce that.

**Comment by basro** [comment]
Regarding the name of the inlined variables: In the old inliner it was simple because there was only one aliasing variable. In the reworked version there can be many aliasing variables so at the very end of the filter there's a pass that will rename inlined field variables using one of the aliasing variable names. It currently selects the aliasing variable that was added last.. which should be the outermost variable.

For example in this code:
``` haxe
var c = {
	var g = new Vec(1);
	trace(g.x);
	g;
}
trace(c.x);
```
Both c and g are considered aliases of the same object, c.x and g.x are the same variable and can only have one name, my algorithm currently selects c_x because it is c is added last as an alias.

The result is:
``` js
var c_x = 1;
var c_y = 1;
console.log(c_x);
console.log(c_x);
```

I'm not sure how _this ends up being added last in your code or why the variables didn't fuse.
If you give me some code I can compile I'll investigate it further. Maybe I can come up with a better name selection scheme..

**Comment by nadako** [comment]
Here's a small example having both redundant `x` argument tempvaring, and `_this` naming:
```haxe
class Obj {
    public var x:Int;

    public inline function new(x) {
        this.x = x;
    }

    public inline function f() {
        x *= 2;
        return this;
    }
}

class Main {
    static var x:Int;

    static function main() {
        var somename = new Obj(x);
        somename.f().f();
        trace(somename.x);
    }
}
```

```js
Main.main = function() {
	var x = Main.x;
	var _this_x = x;
	_this_x = x * 2;
	_this_x *= 2;
	console.log(_this_x);
};
```

if we remove the second `f()` call, here, it'll preserve the var name.

**Comment by nadako** [comment]
Oh, actually, `x` is not redundant here i guess, since it's used twice.

**Comment by basro** [comment]
In that example the constructor inliner is receiving this code:
``` haxe
var somename = new Obj(Test2.x);
{
	var _this = {
		somename.x *= 2;
		somename;
	};
	_this.x *= 2;
	_this;
};
```
So yeah, in this case _this is the last assigned alias..

**Comment by basro** [comment]
I can give priority to variables that have the UserVariable metadata. So selection would first try to get the last assigned variable that is a user variable. Might still not be perfect but it fixes cases like these.

**Pull request merged**
