### PR TITLE
Document in Input interface that Eof is thrown.

### PR DESCRIPTION
**Pull request by binki**

### CODE REVIEW

**Comment by Simn** [comment]
We should probably check/test that before we document it...

**Comment by back2dos** [comment]
I can confirm that. Also, the [implementation of `readAll`](https://github.com/binki/haxe/blob/851dd4ef2f30b6b385fe90c505634f9b72a483c6/std/haxe/io/Input.hx#L108) is explicitly based on that assumption.

**Comment by Simn** [comment]
Right, that's good enough for me.

**Comment by binki** [comment]
> We should probably check/test that before we document it…

I think you just demonstrated the need this documentation ;-).

Thanks for merging!

**Pull request merged**
