### PR TITLE
[js] use Object.create(null) instead of {} and remove reserved key handling in StringMap when -D js-es5 (closes #4372)

### LINKED ISSUE #4372: [js] use Object.create(null) for StringMap when -D js-es5
apparently on ES5 objects created with `Object.create(null)` instead of simple `{}` has no properties at all, so we don't need to check for reserved words and can simplify/speedup StringMap on modern js.

See https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/create

### PR DESCRIPTION
**Pull request by nadako**
See #4372.

### CODE REVIEW

**Comment by nadako** [comment]
It seems that V8 version in node 0.10 doesn't fully support ES5 `Object.create(null)` functionality - it can't delete `__proto__` and other reserved fields from that object. However it works on node 0.12 here. I'll disable node testing for this branch for now to make saucelabs work, let's check what browsers think about that.

**Comment by nadako** [comment]
It seems that Firefox and Safari 5 (is version 5 supposed to support ES5?), as well as Android browsers are not happy about that at all. :( Investigating.

**Comment by nadako** [comment]
Okay, it seems all those ES5 compilant browsers are not okay with changing `__proto__` in an object created by `Object.create(null)` which seems to be a game breaker for StringMap which should allow any string value. I then don't see any value in doing anything further towards `Object.create(null)` solution and tend to cancel this PR and try to add ES6 `Map` support.

Unless there is some solution by the JavaScript experts around here? :-) cc @explorigin

**Comment by explorigin** [comment]
No. I suspected that some browsers would have trouble with prototype.  Surely, even thought the Mozilla docs hint at this usage, I would gather that it is a corner-case with unlikely usage for some browsers.

> Okay, it seems all those ES5 compilant browsers are not okay with...

There is a larger question here.  "What this es5 flag supposed to do?" If it produces es5-compliant code then you include this PR without regard for which browsers support it (so long as it would still fit haxe-compliant behavior).  If the flag is supposed to produce optimized code for all browsers that _claim_ es5 compliance then you have a different story.  Does Haxe have a list of browsers that it aims to support at different levels?  If not, perhaps it's time to formalize this.

**Comment by Simn** [comment]
There's little point in generating "es5-compliant code" if nobody can use it.

**Comment by back2dos** [comment]
I think it would be sensible to write an implementation against ES6 Maps and then polyfill those, not unlike it works with typed arrays. The vast majority of browsers are really new, and the vast majority of the rest is really old. Intermediate versions are rare enough to run a version that runs correctly, even if it means forfeiting a chance to optimize for a language version that is neither truly ubiquitous, nor truly modern.

**Comment by explorigin** [comment]
> There's little point in generating "es5-compliant code" if nobody can use it.

(Echoing @back2dos) But that is not this case. The vast majority of browsers used today can use it.  And for those other browsers, developers don't need to include the es5 flag.

**Comment by nadako** [comment]
I'll close this for now as there's no concencus.

**Comment by explorigin** [comment]
In lieu of closing the story due to lack of consensus, perhaps it's better to appeal to the project leader to make the best choice for the project.

**Comment by nadako** [comment]
This is a PR and I just made a comment in the original issue #4372. The project leader reads all these anyway (well, I hope so), so further discussion may be continued.

**Comment by explorigin** [comment]
:+1:

**Comment by ncannasse** [comment]
I do read all of them :) and yes as long as there's no actual proper map (free of any reserved fields) that's not a correct solution

**Pull request closed without merging**
