### PR TITLE
Some internal analyzer improvements

### PR DESCRIPTION
**Pull request by Simn**
* calculate immediate dominators automatically
* give warnings on unknown `@:analyzer` flags (and remove some of them)
* avoid some more unreachable blocks
* remove `unreachable_code` option because it doesn't work properly anymore
* run some basic CFG integrity checks in debug mode

I'm not squashing the commits in order to be able to bisect more accurately in case something goes wrong.

### CODE REVIEW

**Comment by Simn** [comment]
@nadako: Please do your thing!

**Comment by nadako** [comment]
I won't be able till Monday!

**Comment by Simn** [comment]
@hughsando: Any idea why the cpp AppVeyor tests for this PR are failing like this?

```
cl.exe -DPCRE_STATIC -DSUPPORT_UTF8 -I../../../../project/thirdparty/pcre-7.8 -nologo -Od /WX- /fp:precise -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -Zi -Fdobj/msvc19-debugxp/vc.pdb -FS -Oy- -c -EHs -GS- -arch:SSE -IC:/projects/haxelib/hxcpp/git/include -DHXCPP_DEBUG -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT C:/projects/haxelib/hxcpp/git/src/hx/libs/regexp/../../../../project/thirdparty/pcre-7.8/pcre_get.c -FoC:/projects/haxe/tests/unit/bin/cpp/obj/msvc19-debugxp/2ac97e23_pcre_get.obj
RegExp.cpp
C:/projects/haxelib/hxcpp/git/src/hx/libs/regexp/RegExp.cpp: fatal error C1041: cannot open program database 'C:\projects\haxelib\hxcpp\git\src\hx\libs\regexp\obj\msvc19-debugxp\vc.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
 
Error: Build failed
Command exited
```

**Comment by hughsando** [comment]
Looks like it is putting the pdb file in the wrong directory, which suggests it is probably the hxcpp Build.hx file doing something a bit strange.  The command line you have pasted is for a different thread, not RegExp.cpp, but I should see the same behaviour locally.
But I'm not sure why this is only happening with this commit.
I will double check

**Comment by Simn** [comment]
AppVeyor worked now. Travis is failing on cpp, but that's not my fault so I'll go ahead and merge this!

**Pull request merged**
