### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by kLabz**
Default `dune build` doesn't like warnings, and too many warnings makes us miss new potentially real issues.

I did ignore some warnings instead of fixing because it seemed like something we use willingly (unused methods, "useless" `with` because we pass all (current) fields, not adding `; _` in record patterns, etc.):
```
; 3 - Remove deprecation warnings
; 6 - Label omitted in function application
; 9 - Missing record field in a record pattern
; 23 - Useless record `with` clause (all fields already listed)
; 27 - Unused var (strict)
; 32 - Unused value declaration
; 36 - Unused `as super`
; 50 - Unexpected docstring
```

I hesitated to add `35 unused-for-index` but "fixed" those instead (`for _ = 0 to ...`); can revert and add that warning to ignore list instead.

[diff without whitespace noise](https://github.com/HaxeFoundation/haxe/pull/11170/files?w=1)

### CODE REVIEW

**Comment by Simn** [comment]
Ah nice, I was seeing some of these `Missing record field in a record pattern` in particular and was wondering what was going on.

**Comment by kLabz** [comment]
Yeah we're potentially being a bit lazy with record patterns but I suppose that's fine :)

**Comment by Simn** [comment]
I wouldn't call that lazy, IMO this is just a huge anti-feature. But I'm sure real OCaml devs will disagree.

**Comment by Simn** [comment]
I just pulled this, but I still get some warnings:

```
 *  Executing task: make ADD_REVISION=1 -f Makefile.win -s -j haxe 

File "libs/ilib/peReader.ml", line 28, characters 6-27:
28 |    ch : Pervasives.in_channel;
           ^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ilib/peReader.ml", line 45, characters 1-18:
45 |    Pervasives.pos_in r.ch
      ^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/neko/ncompile.ml", line 676, characters 11-18:
676 |                   let _ = jmp ctx in
                 ^^^^^^^
Warning 5: this function application is partial,
maybe some arguments are missing.
File "libs/extlib-leftovers/uTF8.ml", line 180, characters 20-38:
180 | let compare s1 s2 = Pervasives.compare s1 s2
                          ^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ilib/peReader.ml", line 28, characters 6-27:
28 |    ch : Pervasives.in_channel;
           ^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ilib/peReader.ml", line 45, characters 1-18:
45 |    Pervasives.pos_in r.ch
      ^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ilib/ilMetaReader.ml", line 2349, characters 8-24:
2349 |          match String.lowercase s.str_name with
               ^^^^^^^^^^^^^^^^
Alert deprecated: ExtString.String.lowercase
Use String.lowercase_ascii instead.
File "libs/neko/ncompile.ml", line 676, characters 11-18:
676 |                   let _ = jmp ctx in
                 ^^^^^^^
Warning 5: this function application is partial,
maybe some arguments are missing.
File "libs/swflib/swfPic.ml", line 62, characters 7-23:
62 |    match String.uppercase ext with
            ^^^^^^^^^^^^^^^^
Alert deprecated: Stdlib.String.uppercase
Use String.uppercase_ascii instead.
File "libs/ilib/ilMetaReader.ml", line 2349, characters 8-24:
2349 |          match String.lowercase s.str_name with
               ^^^^^^^^^^^^^^^^
Alert deprecated: ExtString.String.lowercase
Use String.lowercase_ascii instead.
File "libs/swflib/swfPic.ml", line 62, characters 7-23:
62 |    match String.uppercase ext with
            ^^^^^^^^^^^^^^^^
Alert deprecated: Stdlib.String.uppercase
Use String.uppercase_ascii instead.
File "libs/ziplib/zip.ml", line 65, characters 16-37:
65 |     if_channel: Pervasives.in_channel;
                     ^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 75, characters 16-38:
75 |     of_channel: Pervasives.out_channel;
                     ^^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 220, characters 11-33:
220 |   let ic = Pervasives.open_in_bin filename in
                 ^^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 235, characters 2-21:
235 |   Pervasives.close_in ifile.if_channel
        ^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 372, characters 17-40:
372 |     of_channel = Pervasives.open_out_bin filename;
                       ^^^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 419, characters 2-22:
419 |   Pervasives.close_out oc
        ^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 555, characters 4-23:
555 |     Pervasives.close_in ic
          ^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ziplib/zip.ml", line 557, characters 4-23:
557 |     Pervasives.close_in ic; raise x
          ^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/swflib/swfParser.ml", line 447, characters 14-31:
447 |   seek_in ch ((Pervasives.pos_in ch) + n)
                    ^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ttflib/tTFParser.ml", line 27, characters 8-29:
27 |    file : Pervasives.in_channel;
             ^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/swflib/swfParser.ml", line 447, characters 14-31:
447 |   seek_in ch ((Pervasives.pos_in ch) + n)
                    ^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
File "libs/ttflib/tTFParser.ml", line 27, characters 8-29:
27 |    file : Pervasives.in_channel;
             ^^^^^^^^^^^^^^^^^^^^^
Alert deprecated: module Stdlib.Pervasives
Use Stdlib instead.
```

**Comment by kLabz** [comment]
Right, I didn't do a full recompilation of libs in the end. Fixed that in https://github.com/HaxeFoundation/haxe/commit/f6a263f8367060a51353cadfb8967bac507314db.

**Pull request merged**
