### PR TITLE
Fix Sys.executablePath to return valid path

### PR DESCRIPTION
**Pull request by vroad**

### CODE REVIEW

**Comment by andyli** [comment]
As suggested by the deprecation warning, use `Sys.programPath()` instead. It is implemented exactly like your change to `executablePath`. I don't think we should change `executablePath` since it will break existing code that depends on its current behavior.

**Comment by vroad** [comment]
@andyli I think that nobody is using this function now as this returns wrong path (path in URI format, not in standard win/linux path format). Making this inconsistent with other platforms may confuse users as well.

**Comment by andyli** [comment]
Let me explain :)

Firstly, the [implementations across different targets](https://github.com/HaxeFoundation/haxe/issues/3401#issuecomment-169676191) were inconsistent to a point that it is hard to tell what is the intended behavior. So it may not be considered as a "fix".

Secondly, if we "fix" it now, the new version will be available in Haxe 3.3, which you should use `programPath()` anyway. Fixing a deprecated function make it even more confusing.

**Comment by vroad** [comment]
Now I think that you are right. If this function is not used by anybody because it's unreliable, then it doesn't affect anybody even if we don't fix this... This fix is just too late.

**Pull request closed without merging**
