### PR TITLE
[lua] fix missing close() call in Boot.systemName()

### PR DESCRIPTION
**Pull request by Gama11**
Thanks to the new diagnostic (#6917). :)

### CODE REVIEW

**Comment by jdonaldson** [comment]
gracias

**Comment by Gama11** [comment]
Btw, any reason you don't choose the squash-merge option? Should have the same result I think? :)

**Comment by jdonaldson** [comment]
Merges sometimes will add an additional commit, which I like to avoid for simple one liner fixes like this.  No other reason aside from that.

**Comment by Gama11** [comment]
Yes, that's why I mentioned the squash-merge option, which doesn't do that. :)

**Comment by jdonaldson** [comment]
Sure, I've used that before.  I guess it autocloses the issue and prompts you to delete your branch as well?

**Comment by Gama11** [comment]
Yep. Doesn't make a big difference either way, I was just curious.

**Comment by jdonaldson** [comment]
I'll do it next time then, thanks!

**Pull request closed without merging**
