### PR TITLE
Do not store warnings as cache bound objects during display requests

### PR DESCRIPTION
**Pull request by kLabz**
See #11675 (not closing because I'd like to add a test first)

### CODE REVIEW

**Comment by Simn** [comment]
The obvious question here is if this is really the fix we want or if the warning shouldn't occur in the first place.

**Comment by kLabz** [comment]
We're not reading expressions for many modules during display requests; this kind of warnings are bound to happen.

The correct way to handle it would indeed be to do more advanced checks where we emit those warnings (and it's not only about `WInlinedOptimizedField`), but it's a lot more work and likely a lot of trial and error.

I don't think this PR is wrong either way: display requests are not doing work that is persisted so they should not write cache bound objects.

**Comment by Simn** [comment]
> I don't think this PR is wrong either way: display requests are not doing work that is persisted so they should not write cache bound objects.

That seems quite agreeable, but here we're only fixing it for warnings in particular. I can't really think of any problems that would come from resources or include files, but we could run into this again in the future if we add more CBOs.

Then again the nature of warnings makes this rather particular indeed, and perhaps it's really the only potential issue that could arise from display requests. I'm fine with merging this but let's keep this in mind.

**Comment by kLabz** [comment]
Yeah I plan to look into other cache bound objects while adding tests, but not sure I'll find problems with those.

**Comment by kLabz** [comment]
Merging this for now, but keeping #11675 open until my next PR that will handle tests (and potential issues with other cache bound objects).

**Pull request merged**
