### PR TITLE
Run -cmd with linked stdin/stderr/stdout

### LINKED ISSUE #1604: Issue 1604 - haxe -x hangs when haxe script contains user input using readLine() function - haxe
<i>[Google Issue #1604 : https://code.google.com/p/haxe/issues/detail?id=1604]</i>
 <i>by ashishw...@gmail.com, at 07/03/2013, 11:06:33</i>
% cat Test21.hx

<pre>   class Test21 {
    static function main() {
        Sys.print(&quot;haha1\n&quot;);
        Sys.println(&quot;haha2&quot;);
        }
    }
</pre>

</b>

% haxe -x Test21.hx
# it will generate Test21.hx.n and execute it
#  hence it is fine to use &quot;haxe -x&quot;

% cat Test31.hx

<pre>   class Test31 {
    static function main() {
        // print a message on the screen
        Sys.println(&quot;What's your name?&quot;);
        // read user input
        var input = Sys.stdin().readLine();
        // print the result
        Sys.println(&quot;Hello &quot; + input);
        }
    }
</pre>

</b>

% haxe -main Test31.hx -neko  Test31.n
# it will generate Test31.n and work properly(does not hang)

% haxe -x Test31.hx
# it will generate Test31.hx.n and HANG WHILE executing it. It does not even print &quot;Whats your name&quot;

hence, whether &quot;haxe -x&quot; hangs fails when user input via &quot;readline()&quot; is involved?, even though the same script compiled via neko commandline option will not hang

### PR DESCRIPTION
**Pull request by ibilon**
It fixes #1604 for me (linux)

Though I feel like it's way too simple for a fix and there must be a catch somewhere :D

### CODE REVIEW

**Comment by ibilon** [comment]
Travis failed on `brew install mono`.

**Comment by Simn** [comment]
@ncannasse: What's the story here?

**Comment by ncannasse** [comment]
Compilation server needs to send the -cmd output back to the client

**Comment by ncannasse** [comment]
So I don't see how we could support readLine() , maybe detect if it's compilation server or not...

**Comment by Simn** [comment]
From what I understand, this is not a valid solution.

**Pull request closed without merging**
