### PR TITLE
[hl] Rework Null<Int/Float/Bool> comparison for spec/alloc

### PR DESCRIPTION
**Pull request by yuxiaomao**
- When OpGt | OpGte | OpLt | OpLte `Null<Int/Float>`, first test with null (if null return false), then safecast and compare the value. For https://github.com/HaxeFoundation/haxe/pull/8426
- When OpEq | OpNotEq `Null<Int/Float/Bool>` with `Int/Float/bool`, first test with null (if null return false), then safecast and compare, reduce the use of todyn (memory allocation). For https://github.com/HaxeFoundation/haxe/issues/11416
- Remove recursion of `common_type` with the use of `common_type_number`, so that the recursion is more clear
- Use the same comparison logic during jump and normal comparison: let `eval_expr` use `jump_expr` in case of comparison

### CODE REVIEW

**Comment by yuxiaomao** [comment]
Oh Flash ! I'll remove the test file after CI run. Just to ensure that it works on HL.

**Comment by Simn** [comment]
Maybe merge this with #8426 so we have the changes and tests in one place?

**Comment by yuxiaomao** [comment]
I would like to, but as you can see in the CI of previous commit, the flash test fail. Should I make an exception for flash target?

**Comment by Simn** [comment]
Yes we're not going to fix it for Flash.

**Pull request merged**
