### PR TITLE
Pass access mode through handle_display to type_expr

### LINKED ISSUE #8383: [display] write-only properties are not liked by IDE services
```haxe
class Main{
	/** doc **/
	static var v(never,default):Int;

	static function main() {
		v = 3;
	}
}
```

no hover over `v`, no goto-definition, display requests are failing with `Message: Field v cannot be accessed for reading`

the behaviour is the same for `(never,set)`

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #8383

Actual changes are:
* https://github.com/HaxeFoundation/haxe/pull/8446/files#diff-a5d39c7b15f0eb43335c0e74725dc438L2387 and the next one
* from here to the bottom: https://github.com/HaxeFoundation/haxe/pull/8446/files#diff-a0106aa896464f7939bef347a261d90fR435

### CODE REVIEW

**Comment by Simn** [comment]
That's quite brutal... My first idea would have been to handle this in `type_access` with a `EDisplay _ when mode = MSet` case. This way you can pass the mode to `handle_edisplay` without messing with `type_expr`.

**Comment by RealyUniqueName** [comment]
I thought about that, but it looks like a workaround instead of an actual fix.

**Comment by Simn** [comment]
Why? Isn't `EDisplay(e1) = e2` exactly what the issue is about?

**Comment by RealyUniqueName** [comment]
Because that will require to duplicate this:
https://github.com/HaxeFoundation/haxe/blob/09b9a891bf52a84e40c61391657bb140d97addf8/src/typing/typer.ml#L2380-L2391
here:
https://github.com/HaxeFoundation/haxe/blob/09b9a891bf52a84e40c61391657bb140d97addf8/src/typing/typerDisplay.ml#L474-L475

**Comment by RealyUniqueName** [comment]
A quote from slack to not forget:

Because we need to pass the correct access_mode here https://github.com/HaxeFoundation/haxe/blob/907eb71/src/typing/typer.ml#L2387 and here https://github.com/HaxeFoundation/haxe/blob/907eb71/src/typing/typer.ml#L2391 for `EField` and `EConst (CIdent _)`. And we still need to handle all those special cases of `EField` and `EConst`, so we either _not_ bypass `type_expr` or copy that handling.

**Comment by RealyUniqueName** [comment]
@simn So what do you think after all?

**Comment by Simn** [comment]
I think this is the equivalent of squashing a mosquito with a sledgehammer.

I'll look into the original issue and try to propose a different solution. Then I'll tell you that it doesn't work for some reason and merge this PR after all.

**Comment by Simn** [comment]
As promised, I've made an alternative suggestion to fix this, see linked commit. The idea here is to group expressions with a function that types them, defaulting to `type_expr`. This is quite flexible because we could keep arbitrary contextual information.

However, as predicted, I don't really like this either. It feels quite hacky, just in a different way.

I propose that we 4.1 this because your solution still strikes me as too wide. Maybe we can clean up typerDisplay.ml as a whole in some smarter way which allows to interface with individual typing functions better. I really don't want to add a the mode to its arguments if the only reason we need it is because we lose contextual information somewhere between typer.ml and typerDisplay.ml.

**Comment by nadako** [comment]
is there any temporary solution for #8383 meanwhile? I expect it to be annoying in our post-as3 code base...

**Comment by RealyUniqueName** [comment]
The issue looks stupid to exist and the reason looks simple :)
I'll do another take on this as I feel there should be a simple solution.

**Pull request closed without merging**
