### PR TITLE
[lua] fix typo in systemName() check

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Why does `systemName()` return plain string in the world where ADT exist? :)

**Comment by Gama11** [comment]
I actually want to make another PR after this that adds a `SystemName` abstract enum. :)

**Comment by ncannasse** [comment]
For the record, we have more exotic system names in some other not open source APIs (XBox, Switch, PS4 etc.)

**Comment by RealyUniqueName** [comment]
We can define something like 
```haxe
enum {
  Windows;
  Osx;
  Linux;
  Other(name:String);
}
```
Maybe even add version and arch to these constructors.

**Comment by Gama11** [comment]
I was thinking something more like this to preserve backwards compatibility.

```haxe
@:enum abstract SystemName(String) from String to String
```

I don't really want to have to surround each `systemName()` check with `#if (haxe_ver >= "4.0.0")`.

**Comment by jdonaldson** [comment]
What a silly mistake, can you please also add a test?

**Comment by Gama11** [comment]
Hm... not sure how much good that would that, as it looks like Lua tests are not being executed at all on AppVeyor / Windows?

https://github.com/HaxeFoundation/haxe/blob/development/appveyor.yml#L17

There is already some `Process` tests which might catch this (can't easily verify that, as I don't have Lua setup on Windows):

https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/src/io/TestProcess.hx

**Comment by jdonaldson** [comment]
I see, I'll make a separate issue for that then.

**Comment by jdonaldson** [comment]
closed via cherry pick.

**Pull request closed without merging**
