### PR TITLE
[CI] General cleanup for tests

### PR DESCRIPTION
**Pull request by tobil4sk**
Did some general cleanup, especially to make local runs more convenient, e.g. all downloads are made in a single `haxe-ci` folder in the home directory.

### CODE REVIEW

**Comment by tobil4sk** [comment]
Windows and MacOS flash tests are failing while trying to access: https://www.apache.org/dyn/closer.lua?as_json=1, due to a certification error:
`Uncaught exception X509 - Certificate verification failed, e.g. CRL, CA or signature check failed`

**Comment by Simn** [comment]
Let's factor out the flash part so we can merge the general cleanup part first.

**Comment by tobil4sk** [comment]
I've moved out all the flash related stuff. (to #10599)

**Comment by Simn** [comment]
Thank you for your work!

**Comment by tobil4sk** [comment]
No problem!

**Pull request merged**
