### PR TITLE
Use Compiler.Platform enum for user defined meta/defines

### PR DESCRIPTION
**Pull request by SomeRanDev**
Some leftover code from #11128. Figured might as well add here instead of getting rid of completely.

### CODE REVIEW

**Comment by Simn** [comment]
CI failures look (somehow) related.

**Comment by kLabz** [comment]
Yeah, this changes the signature of custom define/metadata functions (`@:optional final platforms:Array<Platform>`) so it breaks current code using this API

**Comment by kLabz** [comment]
I don't think that will work, actually. We need to be able to add defines/metadata through a Json file, and enums won't work there.

**Comment by SomeRanDev** [comment]
Could maybe allow for strings to be loaded from json exclusively? But then I guess you gotta have two struct declarations. Hmmm... well no problem if this doesn't seem necessary, feel free to close. 👌

**Comment by Simn** [comment]
Since this is outdated and causes problems, I'll go ahead and close. Feel free to open an issue about whatever this is actually addressing!

**Pull request closed without merging**
