### PR TITLE
Added MeshOptimizer interface in hl.Format

### PR DESCRIPTION
**Pull request by TothBenoit**
Added MeshOptimizer interface un hl.Format that which can performs various optimization on index and vertex buffers.

### CODE REVIEW

**Comment by Simn** [comment]
Huh, I've never noticed hl.Format before... this doesn't look like something that should be in the Haxe standard library. :/

**Comment by yuxiaomao** [comment]
We can technically move it into hashlink (except `hl.Format.digest` used by crypto I think?), just as what was done for DirectX / SDL. But it would needs to fix heaps a little bit.

**Comment by kLabz** [comment]
> except hl.Format.digest used by crypto I think?

We also want to move the crypto package to https://github.com/HaxeFoundation/crypto, but I'm not sure what the best place for `hl.Format.digest` would be :thinking:

**Comment by ncannasse** [comment]
I agree this is outside the scope of the standard library.
Format started as support for inflate/md5/sha1 and has evolved into jpg/png/dxt and now a bit more.
I will discuss internally but we need to take backward compatibility into account.

**Pull request closed without merging**
