### PR TITLE
Hl tostring

### PR DESCRIPTION
**Pull request by ncannasse**

### CODE REVIEW

**Comment by ncannasse** [comment]
Can be merged if unit tests successful. No squash please :)

**Comment by RealyUniqueName** [comment]
CI is ok, but I can't select any other kind of merge except squashing in github UI. Those are just not active o.O

**Comment by Aurel300** [comment]
Why no squash anyway? Rebase and merge are not allowed for this repo.

**Comment by kLabz** [comment]
Possibly to be able to revert the optimization easily

**Comment by Gama11** [comment]
@RealyUniqueName The other options have probably been disabled in the repo settings then (probably to avoid accidentally using merge commits).

**Comment by kLabz** [comment]
Yeah iirc those have been disabled shortly after we got rid of the submodules, and it was said that when it was really needed to rebase a PR it would be enabled temporarily

**Comment by Simn** [comment]
I have enabled rebase & merge because I think that's fine to do. Should still squash by default to avoid some noise.

**Pull request merged**
