### PR TITLE
add TEnumIndex and make matcher generate that instead of Type.enumIndex call

### PR DESCRIPTION
**Pull request by nadako**
This adds `TEnumIndex of texpr` node and makes pattern-matcher generate it instead of `Type.enumIndex` call, as well as adds handling of that node to target generators. Adding this introduced some optimizations that eliminated a couple switches on some targets, also surfacing #6352 on C# (disabled the test for now).

I didn't remove older enum index hacks and Type.enumIndex for now, and there's no way to generate `TEnumIndex` from haxe code right now, so `Type.enumIndex` implementations are duplicated. I tried to add matching on `EnumValueTools.getIndex()` and using that for `Type.enumIndex` but that loses the enum expression type making it `EnumValue` instead, so this is something we have to think about.

Also, I have to check out the diffs again, but creating this PR nevertheless so Travis can show if everything is okay.

### CODE REVIEW

**Comment by Simn** [comment]
It's missing here: https://github.com/HaxeFoundation/haxe/blob/c3dc791bd10d3b14436dde6c3e638dfa051c41c3/src/optimization/analyzer.ml#L447

But I'm fine with merging this as soon as the CI is green so we can take it from there.

**Comment by nadako** [comment]
No it's not :) https://github.com/HaxeFoundation/haxe/blob/c3dc791bd10d3b14436dde6c3e638dfa051c41c3/src/optimization/analyzer.ml#L423

**Comment by nadako** [comment]
Huh, Lua is failing with some weird error `Type not found : Issue6276`

**Comment by Simn** [comment]
Ah I see. Looking forward to cleaning up that mess.

I wonder why it checks the type for TEnum in the current implementation.

**Pull request merged**
