### PR TITLE
Split up RunCi.hx

### PR DESCRIPTION
**Pull request by Simn**
It's becoming a bit of a mess, so I decided split it up into multiple files before it turns a second haxelib:

```
RunCi.hx: Entry point with the target loop
runci
  targets
    As3.hx etc.: Target-specific dependency/run.
  Config.hx: Most of the static vars for directories and such.
  Deployment.hx: Everything related to deploying binaries/docs/installers.
  Linux.hx: Linux-specific commands (apt-get).
  System.hx: General sys/command related stuff
```

There's probably more clean-up potential, but this should be a good start.

### CODE REVIEW

**Comment by andyli** [comment]
That's so nice :D

Btw, sometimes I wish we can define static methods in interfaces... Those `runci.targets.*` classes could be a good use case.

**Comment by Simn** [comment]
Funny you say that because I had the exact same thought. I almost turned these functions into non-static ones to be able to define an interface for them. But OOP always scares me...

**Comment by RealyUniqueName** [comment]
Same thoughts come to my mind sometimes.
Maybe Haxe should have some sort of compile-time "static interface"?

**Comment by nadako** [comment]
Or "object" thingy like kotlin to easily define singleton implementation

**Pull request merged**
