### PR TITLE
Keep original function block position on optimizing single-expr functions

### LINKED ISSUE #6742: invalid position generated for single-expr blocks
Single-expression blocks have the position of their only expression instead of their original expression:

```haxe
class Main {
    static function main() {
        some();
    }

    static function some() throw "impure";

    #if macro
    static function f() {
        haxe.macro.Context.onGenerate(function(types) {
            for (t in types) {
                switch t {
                    case TInst(_.get() => cl, _) if (cl.name == "Main"):
                        function loop(e:haxe.macro.Type.TypedExpr) {
                            trace(e.expr.getName(), e.pos);
                            haxe.macro.TypedExprTools.iter(e, loop);
                        }
                        loop(cl.statics.get()[0].expr());
                    case _:
                }
            }
        });
    }
    #end
}
```

```
haxe --macro "Main.f()" Main
```

```
Main.hx:15: TFunction,#pos(Main.hx:2: lines 2-4)
Main.hx:15: TBlock,#pos(Main.hx:3: characters 3-9)
Main.hx:15: TCall,#pos(Main.hx:3: characters 3-9)
Main.hx:15: TField,#pos(Main.hx:3: characters 3-7)
Main.hx:15: TTypeExpr,#pos(Main.hx:3: characters 3-7)
```

As you can see, TBlock's position is the same as TCall's, not its original one. This only happens when it's a single-expression block.

It's a bit of an issue for source mapping so would be nice to get fixed.

It happens somewhere in filters, because in a `onAfterTyping` callback it shows the correct position. My guess is that it happens when CFG building, the block is lost and then re-introduced, or something like that.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #6742

### CODE REVIEW

**Comment by Simn** [comment]
Doing this as a filter seems wrong to me. Why not fix the position at the place it's created?

**Comment by RealyUniqueName** [comment]
I'm not sure, which place do you mean.
If you mean the place, where function block is inserted for "non-blocked" functions (which is `sanitize_expr`), then it's impossible because at that point the original position info is lost and it's not even known whether the block existed or not.

**Comment by RealyUniqueName** [comment]
> Doing this as a filter seems wrong to me

The original block is removed in filter. This PR restores the block right away after that removal.

**Comment by Simn** [comment]
Where is it removed?

**Comment by RealyUniqueName** [comment]
In `reduce_expr` here (line 210):
https://github.com/HaxeFoundation/haxe/blob/2985c9d8282003a35ade2971cbe0190300417e42/src/optimization/optimizer.ml#L197-L211

**Comment by Simn** [comment]
Moving this to 4.1 as a filter just for this seems a bit unacceptable.

**Comment by RealyUniqueName** [comment]
But it's not a new filter. It's a small modification of an existing filter.

**Comment by Simn** [comment]
That code is extremely confusing... I'm not even sure if it maintains the bottom-up properties of the algorithm because the `map_expr` recursion is now inside a local closure.

**Comment by nadako** [comment]
What's the status here?

**Comment by RealyUniqueName** [comment]
Idk. I revisited the issue and this fix still seems legit to me.

Another option is to not drop `TBlock` here:
https://github.com/HaxeFoundation/haxe/blob/83c23933eca4fa621658ca77fea9358fe5e355c4/src/optimization/optimizer.ml#L206-L219
but then all one-line `while` loops become "blocked". I mean `while(true) console.log('')` becomes generated as `while(true) { console.log(''); }`

**Comment by Simn** [comment]
Closing because approach seems wrong to me. #6742 remains open.

**Pull request closed without merging**
