### PR TITLE
[js][jQuery] fixed JQuery.on() arguments, [sys][sql][Postgres] Fixes 'LIMIT #,# syntax is not supported' on PostrgreSQL

### PR DESCRIPTION
**Pull request by theRemix**
2 updates to std .hx files
### [js][jQuery] fixed JQuery.on() arguments

.on() should allow .on( events [, selector ] [, data ], handler(eventObject) )
according to http://api.jquery.com/on/#on-events-selector-data-handlereventObject

This update fixes a Build failure http://try.haxe.org/#e4ea8

```
Test.hx:9: characters 27-32 : String should be Dynamic<js.JqEvent -> Void>
Test.hx:9: characters 27-32 : For function argument 'events
```

Here's a test: https://gist.github.com/theRemix/3b9bcff991e99de2a70d
This test will compile and run successfully after this update.
### [sys][sql][Postgres] Fixes 'LIMIT #,# syntax is not supported' on PostrgreSQL

Generates "SELECT \* FROM table WHERE TRUE LIMIT # OFFSET #" query
which is compatible with PostgreSQL
While still remaining compatibility with MySQL

MySQL 5.5.32 (shows works with both)
http://sqlfiddle.com/#!2/130f7/4

PostgreSQL 9.3.1 (shows only works with this patch)
http://sqlfiddle.com/#!15/6a28b/1

Link to PostgreHX : https://github.com/jdonaldson/postgrehx

Test project that will build and generate proper postgresql successfully with this update
https://gist.github.com/theRemix/e404fec94e10a8d103a6

### CODE REVIEW

**Comment by andyli** [comment]
@waneck Is the PostrgreSQL stuff useful?

The jQuery changes can be discarded since we have a new extern.

**Comment by theRemix** [comment]
i can create a new PR with just the postgres stuff,
then i'll close this one

**Comment by nadako** [comment]
I cherry-picked https://github.com/theRemix/haxe/commit/f1381f4cc4517c850fb6dcc59a889878d9556e02 and https://github.com/theRemix/haxe/commit/8f130db72be1db946efe5a3e99c3c2c8cacb8de4, however the third one looks weird to me. I guess this was there before and I'm not too familiar with SPOD, but I'd like to ask, why `opt.limit.pos` is used for `LIMIT` and `opt.limit.len` is used for `OFFSET`, shouldn't it be vice-versa (e.g. OFFSET is a `pos`, and LIMIT is a `len`)? Am I misunderstanding something here?

**Comment by Simn** [comment]
There has been no follow-up here, closing this PR.

**Pull request closed without merging**
