### PR TITLE
New stringmap

### PR DESCRIPTION
**Pull request by ncannasse**
An update of #3462. I choose to go with a lot simpler implementation when using reserved identifiers. These cases are so rare that I guess we can afford the extra string allocation here. Feel free to comment / test / benchmark before merge.

### CODE REVIEW

**Comment by Simn** [comment]
My new XML implementation greatly benefits from this on Flash. However, on JS parsing slightly (but consistently) slower:

target | old parse | new parse | old access | new access
--- | --- | --- | --- | ---
flash | 0.87 | 0.73 | 3.1 | 1.71
js | 0.34 | 0.42 | 0.22 | 0.22

This basically means that reading is equal, but writing is a bit slower (the parser sets a lot of XML's attribute StringMap).

**Comment by SmerkyG** [comment]
Looks great at first glance. Glad you were able to get rid of a lot of the nasty code I introduced!

I'm a little bit worried about the check of `__in__` against the empty `__reserved__` object, since that is a similar strategy to the very first thing I tried and rejected (although not with `__in__`). It was several months ago now, so I unfortunately don't remember exactly why I couldn't do it that way, but there were some properties in as3 that I had issues with. Something like that they were normally null, but that it was bad to set them. It's possible that I was using a Dictionary or something like that was causing the issue for me. I will try to see if I can find any problems there.

I had copied my version of `reserved` to a non static member because flash supposedly is slow at static access. I will benchmark and see how things change.

**Comment by Simn** [comment]
Any objections to merging this?

**Comment by ncannasse** [comment]
Still waiting for @SmerkyG benchmarks

**Comment by SmerkyG** [comment]
I checked the `__in__` issue mentioned above and it seems fine, so imho the code looks great.

New benchmarks (this time tested better with release flashplayer):

attempts|hashentry count|old unsafe|new safe
-|-|-|-
10|100000|630|780
100|10000|510|680
1000|1000|550|690
10000|100|510|680

I checked and my version didn't fare any better in terms of speed. Maybe this means we shouldn't deprecate UnsafeStringMap? Not sure.

**Comment by Simn** [comment]
Could you post your benchmark code? I would like to check something.

**Comment by SmerkyG** [comment]
Sure, sorry in advance that it's crappy. I actually just edit it each time and run it because I'm afraid of garbage collector stuff getting the way of a proper result otherwise...

You'll need a copy of the old UnsafeStringMap (the current branch has it deprecated and mapped to StringMap)

```
package ;

import haxe.ds.*;

import haxe.Timer;
class Main 
{
	static function main() 
	{
		var attemptCount:Int = 10000;
		var hashEntryCount:Int = 100;		
		var keys:Array<String> = new Array<String>();
		for (hashEntryIndex in 0...hashEntryCount) {
			keys.push(Std.string(hashEntryIndex));
		}
		var t:Float;
		t = Timer.stamp();
		for (attemptIndex in 0...attemptCount) {		
			var d:StringMap<Int> = new StringMap<Int>();
			for (key in keys) {
				d.set(key, 1);
				d.set(key, d.exists(key) ? (d.get(key) + 1) : 0);
			}
			for (key in keys) {
				d.remove(key);
			}
		}
		t = Timer.stamp() - t;
		trace(t*1000);
}
}
```

**Comment by Simn** [comment]
Thanks!

I think this is as good as it gets and still 3x faster than the old StringMap. We can keep UnsafeStringMap around for people who need that extra bit of speed.

I have also confirmed that the Js version is superior overall.

Thanks again for your work on this, I'll go ahead and merge this now.

**Comment by ncannasse** [comment]
Also, we could have UnsafeStringMap defined for all platforms (defaulting on StringMap if there is no reserved identifiers). The only think preventing me to do that is that we will have sometimes `typedef UnsafeStringMap<T> = StringMap<T>` and sometimes a custom class implementation and I don't think documentation generation we like it. Any idea @Simn ? (maybe ignore UnsafeStringMap in docgen ?)

**Comment by Simn** [comment]
Couldn't that also cause trouble with serialization between two targets where one has the class defined and the other one doesn't?

**Comment by ncannasse** [comment]
That's for sure, we should document that as part of UnsafeStringMap header.

**Comment by SmerkyG** [comment]
@ncannasse do you have any ideas how we could change haxe in such a way that map iteration on JS target does not require allocation, even for UnsafeStringMap? (See #3762 )

**Comment by nadako** [comment]
I guess there's no way to optimize that without adding specific map iteration handling code into Haxe compiler itself, but we really don't want to do it that way.

**Comment by SmerkyG** [comment]
Only other way afaik is to do something non-threadsafe like put the results into a pre-allocated static array.

**Comment by ncannasse** [comment]
@SmerkyG we could use an Array for keys per Map, but each iterator will have to keep its own position counter (modifying the Map/Array during iteration is unspecified)

**Comment by SmerkyG** [comment]
Yeah, that is sort of what I was hinting at with my prior implementation that cached the array of keys for a given map. The usual two-loops method of optimizing allocations would be helpful here too. Do one loop to see how many keys we need, then increase the arraysize if necessary. Second loop fills them in. Maybe decrease arraysize if a map gets dramatically smaller between key generations.

**Pull request merged**
