### PR TITLE
[cpp] add methods to get NULL pointer and address of a value in Raw(Const)Pointer

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by nadako** [comment]
There were some problems with GitHub, hence CI failures, I restarted the jobs.

**Comment by nadako** [comment]
@hughsando pls review

**Comment by nadako** [comment]
any feedback on this? or i'll just merge it myself :wink:

**Comment by hughsando** [comment]
I'm still thinking about it.  I think "NULL" should just be '0', since NULL is a # define which may not be defined on some systems.  It is also a different style to the cpp.Pointer.addressOf, which is extern and relies on the cpp code (include/cpp/Poiner.h) to provide the implementation, and has an entry in gencpp.ml (is_addressOf_call) to try to pick up non-lvalues at haxe compile time instead of cpp compile time.
So while it may appear simple, there are a few other things to think about.

**Comment by deltaluca** [comment]
It's c++, why not ```nullptr``` ?

**Comment by nadako** [comment]
@deltaluca
Isn't `nullptr` C++11 only?

@hughsando
I was also reluctant to use `NULL` instead of `0` but I did search hxcpp c++ sources and found that `NULL` is used there so I thought it's okay.

As for the implementation, I'm not sure. I like the lvalue check done by compiler, but I think it's really nice to simply generate `&whatever`, but since `Type*` is generated for `RawPointer` by gencpp itself, we could move the `&whatever` generation there as well.

In the end, I'm fine with anything, I just want to have a standard way to get a pointer and a null pointer in Haxe to simplify writing 1:1 externs.

**Comment by nadako** [comment]
Just tell me how you think it should be done, I think I can even mess with gencpp a bit :)

**Comment by deltaluca** [comment]
@nadako, so it is. I've not touched anything 'but' c++11/14 in years ^^

**Comment by nadako** [comment]
Yeah, but I have no idea to what extent c++11 is supported in the whole variety of hxcpp targets.

**Comment by mcheshkov** [comment]
One can always fake nullptr, like [here](https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/support/config.h) in grpc

**Comment by nadako** [comment]
@hughsando bump. is this irrelevant now?

**Comment by hughsando** [comment]
Yes, things have moved on.  The current (3.4.2) best practice is to use ```cpp.Star< type >``` and ```null``` in haxe source, and hxcpp should sort everything else out.

**Pull request closed without merging**
