### PR TITLE
tf_args expr

### PR DESCRIPTION
**Pull request by Simn**
From #4287.

* [x] hl
* [x] as3
* [x] cpp

### CODE REVIEW

**Comment by Simn** [comment]
As3 done!

**Comment by hughsando** [comment]
@Simn, I have no idea how to use git to get the changes to you - please try the attaches diff.
[hugh.zip](https://github.com/HaxeFoundation/haxe/files/2433229/hugh.zip)

**Comment by Simn** [comment]
Travis says that there's a problem with native compilation:

```
 - src/unit/issues/_Issue5340/Vector.cpp 
Error: In file included from ./src/unit/issues/Issue5340.cpp:17:0:
include/unit/issues/_Issue5340/Vector.h: In static member function ‘static hx::ObjectPtr<unit::issues::_Issue5340::Vector_obj> unit::issues::_Issue5340::Vector_obj::__alloc(hx::Ctx*, Dynamic)’:
include/unit/issues/_Issue5340/Vector.h:43:71: error: operands to ?: have different types ‘Dynamic’ and ‘double’
                ::Dynamic x = hx::IsNotNull(__o_x) ? __o_x : ((Float)0.);
```

I cannot seem to reproduce that locally though.

**Comment by hughsando** [comment]
Looks like a gcc v msvc thing.  I usually compile with  android on windows to reproduce these.

**Comment by hughsando** [comment]
This seems to work on linux.
[gencpp.zip](https://github.com/HaxeFoundation/haxe/files/2463367/gencpp.zip)

**Comment by Simn** [comment]
Thanks, applied!

**Comment by Simn** [comment]
Cpp confirmed passing! Only HL left.

**Comment by ncannasse** [comment]
I fetched your branch but can't commit to it.
Simply replace the `assert false` by `op ctx (OMov (r, eval_to ctx c vt));`  (tested , it passes the unit tests)

**Comment by Simn** [comment]
Done, thanks. I wonder why GitHub doesn't let you guys push to this branch. That usually works fine when opening a PR...

**Comment by Simn** [comment]
The tests pass. I'll go ahead and merge now, but we still have to discuss if we want to allow `Some(1)` as default value. I'll reopen #4287 for that.

**Pull request merged**
