### PR TITLE
[std][hl] Fix array pos check, force UInt

### LINKED ISSUE #723: [NIGHTLY?] Array getDyn broken
Unsure if this also happens in base hashlink since theres no mac build for the stable release.

but

```hx
var hello = [];
trace(hello[hello.length - 1]); // crash
```

```
hl.types.ArrayDyn.getDyn(/Users/neo/.haxeget/std/hl/types/ArrayDyn.hx:62)
$Main.main(Main.hx:13)
.init(?:1)
```

haxe version: 4.3.4
hashlink version: 1.14.0

### PR DESCRIPTION
**Pull request by yuxiaomao**
Closes https://github.com/HaxeFoundation/hashlink/issues/723

Seems to be some missing cast from https://github.com/HaxeFoundation/haxe/pull/8408

### CODE REVIEW

**Comment by Simn** [comment]
This entire UInt business here looks pretty wonky, can't we just do a `pos < 0 || pos >= length` check like normal humans?

**Comment by yuxiaomao** [comment]
I searched UInt in std and got for example

https://github.com/HaxeFoundation/haxe/blob/fe0d3e34abb5de658d160eba0b8cc126fab77edc/std/hl/_std/String.hx#L50-L55

So I thought it's the "normal" usage. Can change to `pos < 0 || pos >= length` too if you prefer.

UInt seems to save a comparison (using OJULt)

**Comment by Simn** [comment]
Doesn't this just work incidentally because something like `-1` becomes a large number that then exceeds `length`? I don't see how this is sound because with a sufficiently small number you could end up with something that's `< length` after casting.

**Comment by yuxiaomao** [comment]
Negative Int has the most significant bit at 1, with INT_MIN it's 0x80000000 and is always bigger (unsigned operation) than a normal length ranged from 0 to INT_MAX (0x7FFFFFFF)

**Comment by Simn** [comment]
Ah right, because the length is Int, not UInt... Well, if this is how you want to handle this then I'm fine with it.

**Pull request merged**
