### PR TITLE
add `using override` syntax

### PR DESCRIPTION
**Pull request by Simn**
This picks up my idea from https://github.com/HaxeFoundation/haxe/issues/5271#issuecomment-331695232: Add a `using override Path` syntax which works exactly like a normal static extension, but is checked before the type's fields are checked. The implementation is accordingly straightforward.

Usage is like so:

```haxe
using override Main;

class Main {
	static public function main() {
		trace("foo".charAt(0));
	}

	static function charAt(s:String, i:Int) {
		return 'myCharAt: $s.($i)';
	}
}
```

Generated JavaScript:

```javascript
// Generated by Haxe 4.0.0
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("Main.hx:5:",Main.charAt("foo",0));
};
Main.charAt = function(s,i) {
	return "myCharAt: " + s + ".(" + i + ")";
};
Main.main();
})();
```

Output:

```
Main.hx:5: myCharAt: foo.(0)
```

## Remarks

This allows local drop-in replacements, which can be made global through import.hx. I see quite a few use-cases for this, such as having a set of null-handling overrides for standard library functions or even provide Unicode String drop-ins once we have them.

The only peculiarity is that you might want to ignore such usings, especially in a using-function itself. For this I'm checking for `@:noUsing` metadata at expression-level and simply skip the static extension lookup if it's active. Here's an example from the test I added:

```haxe
class MyDefaultUsingClass {
	static public function charAt(s:String, i:Int) {
		return @:noUsing s.toUpperCase().charAt(i); // Use String's real charAt function
	}
}
```

I don't care much for the actual syntax here, but I think `using default` makes some sense.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Maybe a better syntax can be found? It doesn't look obvious `using default` means overriding own methods with static extensions.

**Comment by Simn** [comment]
I'm open to suggestions, as I said I don't care much about the syntax.

**Comment by RealyUniqueName** [comment]
`using override Main`?

**Comment by Simn** [comment]
Sounds good to me. :)

**Comment by mastef** [comment]
How about allowing a specific method in the `using` syntax?

In this case you'd have `using Main.charAt;` and that would have precedence. Might be a bit more obvious usage, and would also allow the nice side-effect of only adding specific static extensions, instead of the whole class. Something that's already possible with the `import` syntax.

**Comment by Simn** [comment]
Changed to `using override`.

**Comment by ncannasse** [comment]
IMHO this goes a bit too far in language re-design. While we allow things to be easily extended, I would not especially research ways to replace the core language features/API, as it might creates Haxe "dialects" that would not longer be Haxe.

Plus, I don't like the suggested syntax :)

**Comment by Gama11** [comment]
That should already be possible via shadowing std lib files and/or manipulating them with macros. ;)

**Comment by ncannasse** [comment]
@Gama11 so let's leave it for people doing these things, we don't want to encourage it by giving them new syntax to see how ugly this can go ;)

**Comment by Simn** [comment]
You wanted something like this yourself for unicode drop-in replacement. But if you have another solution for that, I don't mind. Can't say I understand the "dialects" argument, surely macros are _much_ worse in this regard.

**Comment by back2dos** [comment]
This has nothing to do with language redesign. It's about giving people the possibility to provide alternative implementations, that are better suited for *their* use case and *their* requirements. It's a thing and always will be, because there's no way the stdlib will ever be able to provide implementations that are optimal for *all* cases. Therefore, a decent solution should be offered to create the possibility of tweaking implementation to best fit the problem at hand and shadowing is not sustainable: congratulations, not only have you improved that one method, but you will also get to bathe in the exquisite joy of maintaining the whole rest of the class you copy pasted from stdlib \o/

At the risk of this being closed because "reasons", here's a ready to use solution based on macros (with the usual limitations that macros entail): https://github.com/back2dos/no-spoon

**Comment by ncannasse** [comment]
Since there's already a macro for it I don't see the point of adding specific syntax.

**Comment by mastef** [comment]
What about `using Main.charAt;` syntax ( directly importing methods, not the whole class ) - where could this be suggested? Or is it possible to make with a macro?

**Pull request closed without merging**
