### PR TITLE
Lua support

### PR DESCRIPTION
**Pull request by Simn**
This pull request adds the `-lua <file>` command, allowing compilation of Haxe programs to lua.

The changes are mostly what's to be expected: A set of new files under std/lua, some conditional compilation elsewhere and the straightforward adjustments in the OCaml sources. The only part that is a bit more involved is the CI testing because that's not so easy to set up at the moment.

This target passes the unit tests. Some sys-parts are not yet implemented, we'll get to that later.

@jdonaldson is going to be the main maintainer of this target and I'll help out as usual.

### CODE REVIEW

**Comment by ncannasse** [comment]
Congrats @jdonaldson , and welcome to the team ;)

**Comment by ncannasse** [comment]
PS: there seems to be a not lua-specific change in haxe.Unserializer, could you check @Simn ?

**Comment by Simn** [comment]
Yes I commented on that commit already, it should be safe to remove.

**Comment by delahee** [comment]
Congratulations!

2016-04-03 13:13 GMT+02:00 Simon Krajewski <notifications@github.com>:

> Yes I commented on that commit already, it should be safe to remove.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/pull/5020#issuecomment-204942265>
>



-- 
David Elahee

**Comment by jdonaldson** [comment]
Thanks everyone!

**Comment by nadako** [comment]
Cool, congrats!

**Comment by waneck** [comment]
WOOHOO!!

**Comment by fullofcaffeine** [comment]
Very nice!

**Pull request merged**
