### PR TITLE
Fix issue #4608

### PR DESCRIPTION
**Pull request by mandel59**
This pull request fixes an error in the function that calculate hash code of string. (See #4608)

### CODE REVIEW

**Comment by andyli** [comment]
Would you add a test case in https://github.com/HaxeFoundation/haxe/tree/development/tests/unit/src/unit/issues?

**Comment by fponticelli** [comment]
Note that the test will fail in Python because of this: https://www.python.org/dev/peps/pep-0263/
But it is actually not exposing the issue described in #4608 since there are not enough cases to generate the offending code.

**Comment by fponticelli** [comment]
I am referring just to the test case, the code to fix Java looks ok to me.

**Comment by fponticelli** [comment]
@mandel59 thank you a lot for fixing both issues, the PR looks good to me.

**Comment by Simn** [comment]
@waneck: Can you check the Java part? If that's fine we can merge  this.

**Comment by waneck** [comment]
Thank you for the fix!!

**Comment by mandel59** [comment]
close #4608

**Pull request merged**
