### PR TITLE
Compilation server: do not load module if already loaded

### LINKED ISSUE #8368: [server] Type name X redefined from module X
There's been a lot of talk about this type of error. I'm not sure if it's one issue or multiple, but I managed to make a minimal example for my current one. Interestingly it's very similar to https://github.com/HaxeFoundation/haxe/issues/8043#issuecomment-491915152 from my previous issue.
hxml
```hxml
-lib hxnodejs #this isn't really used, but without it, it works
-cp src
-main Main
-js build.js
```
Main.hx
```hx
class Main {
    public static function main():Void {
        MyMacro.foo();
    }
}
```
MyMacro.hx
```hx
class MyMacro {
    #if macro
    static var issue = haxe.macro.ComplexTypeTools.toType(macro :js.lib.Uint8Array);
    // ^ this causes the issue
    #end
    public static macro function foo() return macro { };
}
```
Compiling this normally works. First compile via `haxe --connect 6000 build.hxml` works, second one will result in `C:\HaxeToolkit\std/js/lib/Uint8Array.hx:28: characters 36-51 : Type name js.lib.Uint8Array is redefined from module js.lib.Uint8Array`.

It's the combination of the `ComplexTypeTools.toType` and the hxnodejs library (tested with haxelib latest, 6.9.1).
Haxe version https://github.com/HaxeFoundation/haxe/commit/877addced238fbf2cfdd3010e19f3b906d777aa8.

Possibly related to https://github.com/HaxeFoundation/haxe/issues/6993, https://github.com/HaxeFoundation/haxe/issues/4234, https://github.com/HaxeFoundation/haxe/issues/5725. Maybe also related to https://github.com/HaxeFoundation/haxe/issues/7279, I'm not sure as that seems to complain more about the error reporting than the error being false.

### PR DESCRIPTION
**Pull request by kLabz**
Fixes #8368

### CODE REVIEW

**Comment by kLabz** [comment]
Starting with a fresh compilation server, with some added logs (including a "Warning : Avoided X is redefined" instead of `()` in this PR's modified code):

```sh
$ haxe --connect 6000 compile.hxml
(unknown) : Warning : call_init_macro
(unknown) : Warning : before create_macro_interp
(unknown) : Warning : after create_macro_interp
Warning : type_types_into_module Type1

$ haxe --connect 6000 compile.hxml
(unknown) : Warning : call_init_macro
(unknown) : Warning : before create_macro_interp
Warning : type_types_into_module Type1 # << (triggered by `Interp.do_reuse`)
(unknown) : Warning : after create_macro_interp
Type1.hx:4: characters 9-14 : Warning : Avoided X is redefined

$ haxe --connect 6000 compile.hxml
(unknown) : Warning : call_init_macro
(unknown) : Warning : before create_macro_interp
Warning : add_module Type1
Warning : add_module Type1
(unknown) : Warning : after create_macro_interp
```

Note that everything is fine starting from third compilation, whatever changes are made or not to the project files.


This PR also fixes the project [here](https://github.com/HaxeFoundation/haxe/issues/6993#issuecomment-482029929), but the issue is not happening in `Interp.do_reuse` there and subsequent compilations still have the "Warning : Avoided X is redefined".

**Comment by Simn** [comment]
As I said on slack, I don't think this is the right fix. We should instead investigate why this problem occurs.

**Comment by Antriel** [comment]
> As I said on slack, I don't think this is the right fix. We should instead investigate why this problem occurs.

Well, the minimal example is there. If there's something more I can do, let me know.

**Comment by kLabz** [comment]
I agree that there's most probably something going on that triggers that, but would it really hurt to stop the compilation server from crashing until we find what's going on?

**Comment by Antriel** [comment]
Alright, not sure what's happening, but if I use this PR (from CI build), compiling normally works, completion server works, but compiling via completion server produces `js.lib.Uint8Array` references instead of `Uint8Array`. And not at all places.

Can't be sure if it's caused by this PR or something else, as I can't compile this project via completion server with nightly haxe. But considering that it fails on `js.lib.Uint8Array is redefined` I guess it is connected.

**Comment by Simn** [comment]
I'll go ahead and close this because I'm quite certain that this isn't the right fix. We have #8368 to keep track of the status.

**Pull request closed without merging**
