### PR TITLE
[ci] Support Lua 5.4

### PR DESCRIPTION
**Pull request by RblSb**
And lua on macOS runner.
Older unicode lib does not work with 5.4, and new one has unfortunate restriction for bad data, so library fork probably will be required to uncomment lua5_4 tests.

### CODE REVIEW

**Comment by Simn** [comment]
What's the deal with all the `"--trace-sigint"` stuff in the JS tests?

**Comment by RblSb** [comment]
There is a deadlock in ci sys js tests sometimes:
https://github.com/HaxeFoundation/haxe/actions/runs/4578946851/jobs/8086371024
https://github.com/HaxeFoundation/haxe/actions/runs/4413447979/jobs/7734280085
https://github.com/HaxeFoundation/haxe/actions/runs/4281657319/jobs/7455203037
If you view raw log, then you will see that job is canceled after 6 hours without any info.
With `--trace-sigint` we should see line of js file next time, where code is stucked.

**Comment by RblSb** [comment]
Potential fix for https://github.com/HaxeFoundation/haxe/actions/runs/4583112933/jobs/8093855766
At least `@:timeout(5)` here gives same stacktrace

**Comment by Simn** [comment]
Branch needs an update.

**Pull request merged**
