### PR TITLE
Add File.update for writing to file without truncating

### PR DESCRIPTION
**Pull request by bendmorris**
Fixes https://github.com/HaxeFoundation/haxe/issues/3467

Requires https://github.com/HaxeFoundation/hashlink/pull/114

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Can you, please, add a `seek` usage to the test of `update` so we can be sure it doesn't just always write at the beginning of a file?

**Comment by RealyUniqueName** [comment]
Reminder: hxnodejs will need to have an implementation too, if this PR will be merged.

**Comment by bendmorris** [comment]
Didn't realize there was a js sys implementation, although it makes sense. Was going off of: https://haxe.org/documentation/introduction/compiler-targets.html but I think some target-specific developer docs would be very helpful. Currently requires a lot of guesswork.

**Comment by bendmorris** [comment]
Actually I'm a bit confused what to do with hxnodejs, as their `sys.io.File` isn't fully compliant (no `write` or `append` for example).

**Comment by RealyUniqueName** [comment]
I think there is nothing to do with hxnodejs until this PR is merged.
Also maybe @nadako knows what to do regarding nodejs.

**Comment by bendmorris** [comment]
Good idea on the additional test. Turns out FileOutput.seek didn't work at all on C#, so I've added a fix here.

**Comment by bendmorris** [comment]
LMK if we're waiting on anything here. The AppVeyor failure looks unrelated.

**Comment by thescottsmith** [comment]
What Haxe release will/is this fix in? (Been waiting for it...)

**Comment by Gama11** [comment]
It's in [Haxe 4 preview 4](https://haxe.org/download/version/4.0.0-preview.4/).

**Pull request merged**
