### PR TITLE
modified StringMap implementation for PHP

### PR DESCRIPTION
**Pull request by mockey**
As promised in #3898
Uses a `stdClass` as underlying data structure. This should keep the keys as strings.

### CODE REVIEW

**Comment by Simn** [comment]
Thanks!

This currently fails with "PHP Fatal error:  Cannot access empty property in /home/travis/build/HaxeFoundation/haxe/tests/unit/bin/php/lib/haxe/ds/StringMap.class.php on line 15" when running tests/unit/compile-php.hxml. Could you check?

**Comment by mockey** [comment]
No more information where that fails exactly? Is there a test you can run without travis?
compile-php.hxml gives me an index.php that wants to connect to a MySQL-server with user `travis` and then fails of course. Also IMO the call stack information on PHP is much better without `-debug`. I never compile PHP with `-debug`.

**Comment by Simn** [comment]
@waneck: I keep hearing about this MySQL problem in the tests. What's going on with that?

**Comment by mockey** [comment]
see: https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/Test.hx#L302
Maybe add that `&& travis` to the other targets as well like for `cs`?
I commented the SPOD tests and can run the test now. Also tried without `-debug` but only get same stupid `Fatal error`. No idea where that fails. Problem with ArrayAccess maybe? Have to check...

**Comment by mockey** [comment]
Uhm, array access doesn't work at all that way. It doesn't even compile. What is necessary to make array access work on a map?

**Comment by Simn** [comment]
Ah yes, that conditional compilation doesn't look right.

I don't know how array access works/is supposed to work on PHP , sorry... what error are you getting?

**Comment by mockey** [comment]
`Array access is not allowed on haxe.ds.StringMap<Int>`
I have that `private var h : ArrayAccess<T>`, where h is not an `array` now but a `stdClass`...

**Comment by mockey** [comment]
Oh wait, array access only works for `Map<String,Int>` not for `haxe.ds.StringMap<Int>`. I forgot. So that's not the problem apparently. So I still don't know where that test fails...
But back to the original problem: the problem was that keys() didn't show the key as a string. Maybe it's enough to force strings there?

**Comment by mockey** [comment]
Uhm, what's the problem with AppVeyor now?

**Comment by Simn** [comment]
That was my bad, should be fixed now.

**Comment by mockey** [comment]
Can the test be restarted then?

**Comment by Simn** [comment]
Not sure if that helps without syncing the PR, but I'll try.

**Comment by Simn** [comment]
AppVeyor seems to be stuck, but travis tells me it's working so I'll go ahead and merge. Thanks!

**Comment by mockey** [comment]
@back2dos
Yes, `foreach` seems much slower indeed, not so much for `array_keys`, though. But `stdClass` was a bad idea anyway. `array_map('strval', array_keys($arr))` also seems quite expensive, so a custom iterator like yours could be a good idea.

**Pull request merged**
