### PR TITLE
[cs] Consider String as basic type

### LINKED ISSUE #8361: [cs] Native compilation failed - 'ClassC<T>' does not implement interface member
The following code does not compile with Haxe 4rc2 on C#, but works fine for all other platforms:

```haxe
class SortedStringMapImpl<V> extends haxe.ds.BalancedTree<String, V> implements haxe.Constraints.IMap<String,V> {

    var cmp:String -> String -> Int;

    public function new(?comparator:String -> String -> Int) {
        super();
        this.cmp = comparator == null ? haxe.Utf8.compare : comparator;
    }

    override
    function compare(s1:String, s2:String):Int {
        return cmp(s1, s2);
    }
}

class TestRunner {
    static function main() {
        var m = new SortedStringMapImpl<String>();
        m.set("foo", "bar");
        trace(m);
    }
}
```

The result is:
```
haxelib run hxcs hxcs_build.txt --haxe-version 4000 --feature-level 1
src\test.TestRunner.cs(5,15): error CS0535: 'test.SortedStringMapImpl<V>' does not implement interface member 'test.SortedStringMapImpl.compare(string, string)'
src\test.TestRunner.cs(159,7): (Location of symbol related to previous error)
Compilation error
Native compilation failed
Error: Build failed
```

I reported a similar error before https://github.com/HaxeFoundation/haxe/issues/6533

### PR DESCRIPTION
**Pull request by kLabz**
Fixes #8361

### CODE REVIEW

**Comment by kLabz** [comment]
This will probably break tests... It's breaking my project with `datetime.DateTime`, `haxe.CallStack`, `haxe.ds.Either` and `haxe.ds.Option`) because of `HxEnum.getParams()`.

**Comment by kLabz** [comment]
Also fixes #5434

**Comment by Simn** [comment]
I'm a bit nervous about this because it might affect various things. But it makes sense in theory, so I'll go ahead and merge this.

**Comment by kLabz** [comment]
Yeah, I'm a bit nervous about it too but so far I've only seen things it _fixed_ instead of things it broke.. Happy to work on whatever it does end up breaking, though.

**Pull request merged**
