### PR TITLE
use native .bind for $bind when js-es >= 5

### PR DESCRIPTION
**Pull request by R32**
I'm not sure, maybe it's better than before..

### CODE REVIEW

**Comment by nadako** [comment]
I don't think native `.bind` does closure caching, which might be something we don't want to lose. I'm not sure though.

**Comment by back2dos** [comment]
Nope: https://jsfiddle.net/06ff2hud/1/

**Comment by R32** [comment]
Actually, I haven't changed parts of the cache. 

**Before:**

```js
function $bind(o,m) {
	if( m == null ) return null;
	if( m.__id__ == null )
		m.__id__ = $fid++;
	var f;
	if( o.hx__closures__ == null )
		o.hx__closures__ = {};
	else
		f = o.hx__closures__[m.__id__];
	if( f == null ) {
		f = function(){
			return f.method.apply(f.scope, arguments);
		};
		f.scope = o;
		f.method = m;
		o.hx__closures__[m.__id__] = f;
	}
	o = null;
	m = null;
	return f;
}
```

**After:**

```js
function $bind(o,m) {
	if( m == null ) return null;
	if( m.__id__ == null )
		m.__id__ = $fid++;
	var f;
	if( o.hx__closures__ == null )
		o.hx__closures__ = {};
	else
		f = o.hx__closures__[m.__id__];
	if( f == null ) {
		f = m.bind(o);  // DIFF
		o.hx__closures__[m.__id__] = f;
	}
	return f;
}
```

**Comment by nadako** [comment]
It would be interesting to see performance comparison for this...

**Comment by back2dos** [comment]
Nah, looks right ;)

**Comment by ncannasse** [comment]
Ok for merge on my side

**Comment by elsassph** [comment]
I'd think that things would be less confusing if only the part that differs would be behind the es version test, and the cache part would be common const string.

**Pull request merged**
