### PR TITLE
Adding Unserializer.TypeInstantiator, squashed + unit tests

### PR DESCRIPTION
**Pull request by jcward**
Squashed, added testcases for TypeInstantiator and TypeResolver

For original feature description / motivation / etc, see: https://github.com/HaxeFoundation/haxe/pull/6497

### CODE REVIEW

**Comment by jcward** [comment]
(Huh, [3 out of 4 travis jobs passed](https://travis-ci.org/HaxeFoundation/haxe/builds/264439843?utm_source=github_status&utm_medium=notification), only [this unrelated AS3 test](https://travis-ci.org/HaxeFoundation/haxe/jobs/264439844#L3142) failed.)

**Comment by ncannasse** [comment]
I don't like the fact that you have to rely on knowing the serialization format for writing your own TypeInstanciator (in KVIterator)

**Comment by jcward** [comment]
@ncannasse - I'm confused what you mean by "knowing the serialization format".

If you need to write a custom `TypeInstantiator`, you must use the provided `KVIterator`, which is merely a convenience for iterating over key-value pairs. You don't need to know about (what I consider to be) the serialization format [details](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Serializer.hx#L120-L151) or reading name/values from the serialization stream.

I previously (see [this comment](https://github.com/HaxeFoundation/haxe/pull/6497#issuecomment-320816384)) had the API providing a `nextKey` and `nextValue` functions, but they're cumbersome, and if you call them repeatedly or at the unexpected time, you could mess up the serialization pointers. So KVIterator is a safer way of receiving the member data.

As you can see in the example where I have a [custom `MyTypeInstantiator`](https://github.com/HaxeFoundation/haxe/pull/6514/files#diff-8ff9c7fd14fc41ae741d20b64e31ecafR93), the function that handles the KVIterator has a very [simple while loop](https://github.com/HaxeFoundation/haxe/pull/6514/files#diff-8ff9c7fd14fc41ae741d20b64e31ecafR136) to handle incoming K/V pairs. At this point the end user knew what his serialized data members used to be, and knows how they changed over time. If this is the "serialization format" you're referring to, then yes, I need to express how to handle members of my class that I've changed since the serializtion was made. e.g. Previously my codebase had a foo:String that changed to a bar:Enum, and only I know how that needs to be translated.

I could make this a separate library, except that it's tied closely to `Unserializer.hx`. And again, it seemed like a natural extension to `TypeResolver`.

But if you dislike it, feel free to close. It's easy enough to drop this version into a project's class path. (You might want to take the [`TypeResolver` testcase](https://github.com/HaxeFoundation/haxe/pull/6514/files#diff-be8959067be7922a2e5528d4bf5217ddR3) in any case.)

**Comment by ncannasse** [comment]
If you want developers to be able to reuse KVIterator then it needs to be
public, not private
Is it not possible to have such implementation in a library which "extends
Unserializer" ? maybe by just doing some lightweight refactoring of it we
could make it possible

**Comment by jcward** [comment]
> If you want developers to be able to reuse KVIterator then it needs to be public, not private
Meh, it gets inferred. :laughing:

Alright, I'll look into a refactor for extension later.

**Pull request closed without merging**
