### PR TITLE
Eval

### PR DESCRIPTION
**Pull request by Simn**
This replaces the current macro interpreter with a new one named `eval`. I have a blog post prepared to introduce it in detail.

### CODE REVIEW

**Comment by ncannasse** [comment]
EvalStack should be by default if it's like 10% extra cost
Why EvalTimes and not reusing MacroTimes ?

**Comment by Simn** [comment]
eval-times is very slow because it really times every function call. macro-times just times the entry points of your macros.

I can check the stack handling again but I think it slows everything down quite a bit. I find that annoying for something you don't really need 99% of the time if you're just a macro user.

**Comment by Simn** [comment]
My raw call benchmark goes from 41M ops/sec to 21M ops/sec. Granted, such benchmarks are not very realistic, but I do see a difference in e.g. haxe-checkstyle as well (from 5.0/2.4 to 5.4/2.8).

**Comment by nadako** [comment]
As a maintainer of a very macro-heavy project I agree that having macro run at max speed is more important, since that as well affects completion. If something goes wrong, there's no issue of re-running the compilation with `-D eval-stack`.

**Comment by Simn** [comment]
Alright boys, let's do it!

**Pull request merged**
