### PR TITLE
remove haxe.unit

### PR DESCRIPTION
**Pull request by Simn**
This changes our sys tests to use -lib utest and removes haxe.unit. I'll push the haxe.unit implementation to hx3compat once we merge this.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Is HF going to maintain utest?

**Comment by Simn** [comment]
If we have to. But I don't subscribe to the idea that everything has to be officially maintained by us.

**Comment by markknol** [comment]
Are we also going to remove https://haxe.org/manual/std-unit-testing.html ?

**Comment by RealyUniqueName** [comment]
Maybe update it instead of removing?

**Comment by Simn** [comment]
To be blunt, we don't have the time. Solutions like munit and utest are superior, so if anything our efforts should be focused on that instead of keeping this insufficient solution around.

**Comment by markknol** [comment]
We also need to remove it from try.haxe (example22) https://try.haxe.org/#4B260

**Comment by RealyUniqueName** [comment]
Simn, i meant updating https://haxe.org/manual/std-unit-testing.html . Not `haxe.unit`.

**Comment by Simn** [comment]
Oh, haha... Yeah we shouldn't just remove it I guess, just add that the implementation has been removed and can be found in hx3compat.

**Pull request merged**
