### PR TITLE
Rework module resolution

### LINKED ISSUE #9197: enumerators obscure classes
Haxe helpfully will attempt to resolve naked enumerators where possible. This is a good behavior, but has the side-effect of obscuring classes that may share the name

The resolution order here should probably put enumerators at the bottom, since you can *always* qualify an enumerator, but some types can't be. As an example:

```haxe
enum Foo {
	Bar;
}

class Bar
{
	public static var someVar : String = "Yay";
}

class Main
{
	static function main()
	{
		Bar.someVar = "test";
	}
}
```

will produce the error `src/Main.hx:14: characters 8-15 : Foo has no field someVar`

In this case, we lose access to the `Bar` class entirely, as there's no more specific way to identify it. However, had the reverse been true we could have still accessed the enum via `Foo.Bar`

At a minimum this should at least produce a better error, since enums are often buried in imports (which still produce this behavior)

### PR DESCRIPTION
**Pull request by Simn**
This changes resolution behavior to consistently consider lexical appearance instead of always preferring enum constructors. Previously, the typer would keep 3 separate lists:

1. A list of module imports
2. A list of "global" imports
3. A list of wildcard imports

This PR merges those into a single list, in which they are distinguished by a variant type. Identifier resolution then walks through that list and compares all imports in-order. This means that this changes the specified [resolution behavior](https://haxe.org/manual/type-system-resolution-order.html) and is a breaking change.

Additionally, resolution now treats its own types and statics as if they were imported, and caches this information in `ctx.m.own_resolution`. This fixes #9197.

## Aliasing

The implementation of `import X as y` was changed by giving all imports an implicit alias name, which is what resolution compares against. For types, it's the type name and for fields it's the field name. As a consequence, we no longer introduce special typedefs to make this work, which caused one display test to fail. I will track this in #8660.

## Field imports

One problem with field imports is that by the time we're processing imports initially, we don't know a module's structure yet. To deal with that, the current implementation passed a `context_init` object around which manages the delays for such fields. I have removed that completely and instead introduced the resolution kind `RLazy`.

You can think of `RLazy` as a placeholder in the resolution list, which then expands itself when it's time to resolve a field. So a resolution list like `[Type1, Type2, RLazy, Type3]` then becomes `[Type1, Type2, Field1, Field2, Type3]`. This ensures that the lexical order is maintained.

This functionality is also used to deal with enum and enum abstract constructors: When we add a type import, we also add an `RLazy` _in front of it_ which might resolve to a list of constructors. This gives us the same behavior as before.

## Breaking...

I'm not sure how much this will break in practice, but it's definitely a specification change. Once we merge this, I'll consider the path to Haxe 5 open. Before that, I'd appreciate if people could test their codebases on this branch and report problems.

I'll also make sure to run this on https://benchs.haxe.org/ before merging. There's a chance that this linear kind of lookup performs worse than the previous implementation, although that one also wasn't exactly optimized. If this turns out to be a problem, we can look into adding a proper lookup cache, which might be a good idea anyway.

Also closes third-oldest open issue #2729.

### CODE REVIEW

**Comment by Simn** [comment]
This should be ready, or at least as ready as it will be for the time being. I have updated the initial post to explain what's happening. Now waiting for CI to behave so that I can benchmark.

@kLabz Could you try this branch with Shiro codebases, and whatever else you find that might be interesting?

**Comment by kLabz** [comment]
I will try to find some time this week-end (worst case I'll do it on Monday)

**Comment by Simn** [comment]
There's a strange case in [heap's Quat.hx module](https://github.com/HeapsIO/heaps/blob/master/h3d/Quat.hx): At the top of the file it has `using hxd.Math;` which means there's an implied import. Throughout the file, it accesses some fields that clearly come from that class, such as `Math.invSqrt` and `Math.EPSILON`.

However, inside the `pow` function it calls `Math.log` and `Math.exp` which do _not_ exist on `hxd.Math`. This must mean that they are resolved on std/Math, but I don't understand how that's possible because the `using hxd.Math` should completely shadow that.

I'm currently in a state of confusion.

**Comment by Simn** [comment]
We're working towards merging this. Some libraries are going to need updates because they rely on unintended importing behavior. However, all fixes required can be made in a way that is compatible with both Haxe 4 and 5.

**Comment by Simn** [comment]
Unfortunately, the benchmarks for this don't look good:

brave_fqWO2tfhJJ

While it's not massively slower, the graph suggests that this doesn't scale well in larger projects. It's quite difficult to determine the cause of this accurately, but we'll have to look into that.

Edit: Actually, these results are not recent. But I doubt the more recent results will look much different.

**Comment by Simn** [comment]
Good news: After running the benchmarks again with the current version, the results look much better:

brave_mAf7f439P6

**Comment by Simn** [comment]
@kLabz Could you check Shiro codebases with https://github.com/HaxeFoundation/haxe/tree/module_resolution_no_weirdness? I still want to make that change too (for #9150), but if it causes too much friction right now we can wait a bit.

**Pull request merged**
