### PR TITLE
[dce] only keep fields if unified with an anon, which is kept

### LINKED ISSUE #9185: [dce] unification with an anon struct makes dce to keep unused class fields.
```haxe
class Main {
	static var tmp:Int;
	static public function main() {
		tmp = Cls.field;
	}
}

abstract Abstr(Cls) to Iterable<Int> {}

class Cls {
	static public var field:Int;

	//this field is never used
	public function iterator():Iterator<Int> {
		return null;
	}
}
```
Generated js:
```js
var Main = function() { };
Main.main = function() {
	Main.tmp = Cls.field;
};
var Cls = function() { };
Cls.prototype = {
	//this field is kept, but never used
	iterator: function() {
		return null;
	}
};
```
Removing `to Iterable<Int>` makes `Cls.iterator` disappear from the output.

The issues is caused by these lines:
https://github.com/HaxeFoundation/haxe/blob/282df7714cd8fe82da70831ecdade098d3a3379e/src/core/tUnification.ml#L553-L555

I think `@:maybeUsed` should anly be added upon actual use of `to Iterable<Int>` in expressions. Currently it is triggered upon checking the compatibility of the underlying type with `to` types.

This issue is the reason why `haxe.iterator.ArrayIterator` is always kept even in a simple "hello world" sample:
https://github.com/HaxeFoundation/haxe/blob/282df7714cd8fe82da70831ecdade098d3a3379e/std/haxe/ds/ReadOnlyArray.hx#L34

### LINKED ISSUE #9310: [dce][js] Unnecessary code in "hello world" sample
After #9167 every compiled js now contains following lines (even if these functions are never used):
```js
function $iterator(o) { if( o instanceof Array ) return function() { return new haxe_iterators_ArrayIterator(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
```
Together with [`ArrayIterator`included in every compiled js](https://github.com/HaxeFoundation/haxe/issues/9185) it gets quite ugly for minimal samples.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #9185 
Closes #9310

### CODE REVIEW

**Comment by Simn** [comment]
Urgh, let's please not do something that changes `tanon` like that... We would have to sort out anon identity on a larger scale before we try to do something like this.

That, plus I don't really consider #9185 a big issue.

**Comment by RealyUniqueName** [comment]
But now all our "hello world" examples include ArrayIterator :)

**Comment by Simn** [comment]
That seems like a different problem. Unification with anons should only ever add  `@:maybeUsed`, and that should only come in effect if the type itself ends up being used.

**Comment by RealyUniqueName** [comment]
> Unification with anons should only ever add @:maybeUsed, and that should only come in effect if the type itself ends up being used.

That happens, because of this:
https://github.com/HaxeFoundation/haxe/blob/fcce3faed36ed2ccec172c6fb6b72260fbf418d3/std/js/_std/HxOverrides.hx#L144-L151
or this (I don't remember, which one exactly):
https://github.com/HaxeFoundation/haxe/blob/fcce3fa/std/js/_std/Std.hx#L77-L111

This is kept because it's `__init__` and `__feature__` is decided in genjs, well past DCE.

**Comment by Simn** [comment]
I'll close this because I don't think it's the right thing to do. Anon identity is a problem that has to be solved differently and we shouldn't add any more hacks around it.

**Pull request closed without merging**
