### PR TITLE
added unit test for #5271

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by Simn** [comment]
Could you update the branch so we can see where we're at test-wise?

**Comment by sebthom** [comment]
Done.

**Comment by Simn** [comment]
Something must be wrong because the tests are timing out. Can you update again and see what's going on?

**Comment by sebthom** [comment]
I updated the branch again.

**Comment by Simn** [comment]
I'll look into this after we've merged the unicode branch.

**Comment by Simn** [comment]
I've fixed it for eval, but this is not Haxe 4 critical.

**Comment by ncannasse** [comment]
Given the change might result in changing current behaviour for some basic functions I think it qualifies for Haxe 4 no?

**Comment by Simn** [comment]
Not if you consider adhering to the spec a bugfix.

**Comment by ncannasse** [comment]
Well i would agree in general but given it affects String that's quite a general bug that can have massive impact. Usually we would not merge a platform that does not pass String tests.

**Comment by Simn** [comment]
But this is such a minor special case that fails on every target except JavaScript (and now eval).

I'm guessing we won't fix this on Flash, AS3 and neko?

Anyway, I'll close this so I can manage updates on my own branch. We have #5271 open to track progress.

**Pull request closed without merging**
