### PR TITLE
New `List` implementation proposal

### PR DESCRIPTION
**Pull request by RealyUniqueName**
What about changing our list to something like this?

* Can preallocate required amount of nodes;
* Reuses nodes of previously removed items;
* No garbage left after an item removal;
* `reverse()`;
* Doubly linked
  * O(1) `popLast()`;
  * `removeLast()`;
  * could be extended with backward iterators;
* API is backward compatible.

### CODE REVIEW

**Comment by Simn** [comment]
This calls for some benchmarks!

**Comment by RealyUniqueName** [comment]
Iteration behavior is different. 
With the current `List` implementation if the next item is removed, iteration stops after the _next_ step.
In the new implementation If the next item is removed, iteration stops after the _current_ step.

**Comment by Simn** [comment]
Maybe we should add this as a separate class so we don't break current List behavior. It looks more like a DoubleEndedQueue anyway.

I'm also still very interested in benchmarks for this.

**Comment by RealyUniqueName** [comment]
I'll do some benchmarking later. It's not in my top-priority list.

**Comment by nadako** [comment]
Honestly I'm not sure how useful is this anyway, because usually if you need an efficient linked list of things, you don't really want to have a wrapper container instance for every element.

Maybe something like `class List<T:{previous:T, next:T}>` would be better? (optionally tossing in `@:generic` for static targets). OTOH this would surely be an incompatible and separate implementation, so meh...

**Comment by Simn** [comment]
> Maybe something like class `List<T:{previous:T, next:T}>` would be better?

It might be faster, but I wouldn't consider it better because it violates the separation of concerns if your objects have to know about their neighbors. This might work in a trait-based environment, but it doesn't look right for Haxe.

**Comment by nadako** [comment]
You're right, I guess I work on optimizing stuff too much lately:)

That said, if the performance is not a concern, one can just use Array:)

**Comment by ncannasse** [comment]
I don't think the double linked list adds much compared to what it requires in terms of management/memory, and I'm not sure about pooling either, given each GC might have very different behavior wrt pooling, it should only be used when we are sure it improves things, which cannot be guaranteed for any List.

**Comment by Simn** [comment]
There wasn't a whole lot of enthusiasm for this implementation, so at this point I'll go ahead and close this PR.

**Pull request closed without merging**
