### PR TITLE
remove jquery and swfobject from std

### LINKED ISSUE #2893: [debian] Please document compatibility of jquery javascript library
Can I replace haxe/std/js/jquery  by lastest debian version aka 1.7.2 ?

It will be nice to document the compatibilty, thus we could update if needed.

The same with swfobject-1.5.js.

Bastien

### PR DESCRIPTION
**Pull request by Simn**
I really don't see the point of having outdated JS files in our standard library.

Closes #2893

### CODE REVIEW

**Comment by ncannasse** [comment]
Refused. We might remove swfobject, but Jquery is the single mostly used JS library, it is IMHO more useful than the whole DOM API and we should make sure it's properly maintained and complete instead of removing it.

**Comment by Simn** [comment]
Well I'm glad you plan to actually maintain it then!

**Comment by delahee** [comment]
+1 This is not the good timing to do this.
if you want to give this a go, let's wait after the 3.2


thx :)

2015-03-24 20:59 GMT+01:00 Nicolas Cannasse <notifications@github.com>:

> Refused. We might remove swfobject, but Jquery is the single mostly used
> JS library, it is IMHO more useful than the whole DOM API and we should
> make sure it's properly maintained and complete instead of removing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/pull/4074#issuecomment-85669300>.
>



-- 
David Elahee

**Comment by Simn** [comment]
I wanted to wait until after 3.2 anyway, I just opened it now because I always forget about it. But I don't care either way as long as someone maintains this and it doesn't cause any issues.

Seeing how we're still on 1.6.4 and call the file "jquery-latest.min.js" of course suggests that nobody actually cares about maintaining it, which is kind of strange considering it's allegedly more important than the DOM API.

**Comment by ncannasse** [comment]
I think @andyli agreed to maintain it ?

**Comment by Simn** [comment]
I thought that was about the externs only. But it works for me, as it happens we're in the process of making a release so it might not be the worst time to update it. Of course it would have been nicer to have in the RC if it's so super-important, but oh well.

**Comment by ncannasse** [comment]
Oh, your issue was wrongly named, you meant removing the *embed* part of JQuery/SWFObject, sorry about it. This can actually be discussed but I can't reopen (branch deleted)

**Comment by Simn** [comment]
I thought the "outdated JS files" made it clear but I'll be more careful next time. Let's wait till after 3.2 though to not scare anyone...

**Comment by Simn** [comment]
@andyli: What's your opinion on this?

**Comment by andyli** [comment]
As I am going to take care of all the jQuery stuff, I can make sure the embedded file is up-to-date in the repo. So for backward compatibility I would suggest to keep them (and I'll update them soon).

**Comment by andyli** [comment]
And l think I can take care of swfobject too.

**Comment by Simn** [comment]
If you think that's worth it I don't mind. My concern is that this kind of inclusion should be discouraged anyway. Also I don't think many people are using it so it might still be better to get rid of this if it means additional maintenance effort for us.

**Comment by clemos** [comment]
IMHO we should remove these and put them in official haxelibs.
If such externs / inclusions were to be kept in the standard lib, I think we should at least have a plan to encourage the use of `npm` (+ `browserify`) to fetch and `require` third parties.
Ideally, I think `js.Cookie` and `js.Selection` should also be removed similarly (if needed, moved to some haxelib + relying on some npm lib such as https://www.npmjs.com/package/cookie, https://www.npmjs.com/package/selection-range)

**Comment by andyli** [comment]
It would be merely a matter of replacing the files every time we update the externs to a new release. I mean, it is easy comparing to updating the externs itself.

However, I'm fine with removing them other than backward compatibility issue. So maybe we can add a warning when `-D embed_js`, and then remove the support in later release.

**Comment by Simn** [comment]
I'll let you deal with that, either way is fine for me.

**Comment by Simn** [comment]
We'll have to make a decision here.

**Comment by ncannasse** [comment]
I'll let @andyli decide what's best.

**Comment by andyli** [comment]
I have finally decided to remove those JS files anyway. It decouples the JS library version with users' projects, so there will be less opportunity of breakage when users upgrade their haxe version. Also it reduces my effort on the Debian packaging, which reviewers complained inclusion of third-party source code.

**Pull request closed without merging**
