### PR TITLE
Added a deep copy/clone functionality to haxe serializer

### PR DESCRIPTION
**Pull request by ncannasse**
Note : this might require some extra platform support so we can support circular references such as `obj = E(obj)`

### CODE REVIEW

**Comment by back2dos** [comment]
Can we please put this somewhere else? Deep copy is no doubt useful, but it has no business being in the serializer. If anything, it makes it unnecessarily hard to find.

It should be `Reflect.deepCopy` or something and frankly on most platforms it could have *much* better implementations, especially for enums. On some targets it could have an implementation in the runtime itself,, i.e. eval and probably hl too.

**Comment by Simn** [comment]
Yes this was merged prematurely. I agree it shouldn't live in haxe.Serializer, and we need tests for this. I'll revert this and open an issue to look into it further.

**Comment by ncannasse** [comment]
This was reverted but I don't see the corresponding issue neither were the code was moved ?

**Comment by Simn** [comment]
#11863

**Pull request merged**
