### PR TITLE
[js] Add js.lib.Number

### PR DESCRIPTION
**Pull request by terurou**

### CODE REVIEW

**Comment by Gama11** [comment]
Hm.. I wonder if there should be an abstract wrapper around this for implicit casts and such, with the actual extern being a `private class NumberImpl` or similar?

**Comment by terurou** [comment]
@Gama11 Thanks for your review.
I changed to use abstract.

**Comment by Simn** [comment]
Please update this PR to see what the CI is doing.

**Comment by RealyUniqueName** [comment]
`js.lib.Number` should probably be a `@:coreType abstract` instead of using `extern private class` as an underlying type.

**Comment by Simn** [comment]
There hasn't been any update here, so at this point I'll close this PR.

**Pull request closed without merging**
