### PR TITLE
Retyper

### PR DESCRIPTION
**Pull request by Simn**
This PR adds a retyping mechanism which aims to improve the reuse of cached typed. It's not quite finished yet, but I would like to discuss the approach in general.

For the time being, this feature is enabled for modules by using this:

```
--macro haxe.macro.CompilationServer.setModuleCheckPolicy(['Module'], [Retype], false)
```

This tells the compiler that **the module's signature does not change implicitly**. What this allows the compiler to do is to try loading the signature of a class field without triggering any typing. If this is successful, the class field can be reused by retyping its expression.

The signature being checked consists of the explicit signature (i.e. type-hints) where any blanks are filled in from the cached information we have. This means that an explicit type change will trigger a normal cache invalidation, which is the same behavior as before.

Ultimately, my goal is still the the cache works better without any additional user interaction. However, this is a very hard problem to solve in an environment with heavy type-inference. The approach here should at the very least be a good basis for future improvements.

### CODE REVIEW

**Comment by Simn** [comment]
I'll go ahead and merge this now because I don't really know how to proceed otherwise. It's nicely isolated and won't affect anything else, so this shouldn't be a problem.

**Comment by trethaller** [comment]
I tried this on a large project and got what appears to be duplicate module in the cache: 
```
(unknown) : Type name shaders.Stealth is redefined from module shaders.Stealth
```
I don't have a reproducible sample yet

**Comment by trethaller** [comment]
I was made aware that you @Simn have access to the Northgard codebase - error appears there on first try

**Comment by Simn** [comment]
That didn't happen when I tested it before merging... I'll take another look at it.

**Comment by Simn** [comment]
Can you share the relevant part of the CLI arguments?

**Comment by trethaller** [comment]
I tried with ```--macro haxe.macro.CompilationServer.setModuleCheckPolicy(['Game'], [Retype], false)```

**Comment by Simn** [comment]
Alright, thanks. This depends on which file is being edited after the initial caching. I managed to reproduce a "redefined" error after changing Player.hx. The retyping of `Game` fails in that case, probably because of some intricate dependency chain. This is not supposed to cause any kind of "redefined" error though, so there must still be something wrong in the general logic...

**Comment by Jarrio** [comment]
I'm not entirely sure if I used this correctly. But I get an assertion error on haxe dev release 779b005 
Error: `File "src/core/globals.ml", line 120, characters 1-7: Assertion failed`
Command: `--macro haxe.macro.CompilationServer.setModuleCheckPolicy(['Main'], [Retype], false)`
Repo is public: <https://github.com/Jarrio/Haxebot/> 
`git clone --recurse-submodules https://github.com/Jarrio/Haxebot.git`  Will get you a completion valid project

--
Command: `--macro haxe.macro.CompilationServer.setModuleCheckPolicy([''], [Retype], false)`
causes a `Type name ecs.core.EntityManager is redefined from module ecs.core.EntityManager` error

**Pull request merged**
