### PR TITLE
Fix inconsistencies with define flags

### LINKED ISSUE #7795: Context.defined / Context.definedValue keys should translate dashes to underscores
**Description**
In current setup, If I use `-D haxe-is-great` then
-  `Context.defined("haxe-is-great")`  is false
-  `Context.defined("haxe_is_great")`  is true

Same goes for `Context.definedValue`.
This is because `#if haxe-is-great` doesn't work, which makes sense. 

The `Context.defined` docs now say  
> Compiler directives are set using the `-D` command line parameter

This is confusing because the -D parameter does contains a dash, but its translated somewhere in the process. I would expect both to work.

**Question:**
Can we allow `Context.defined("haxe-is-great")` and `Context.defined("haxe_is_great")` to both return `true` if `-D haxe-is-great` is set?

### LINKED ISSUE #10184: Compiler define flags switching dash to underscore can result in flag defined with two values
It is possible to overwrite a define flag like this

```hxml
-D a-a=1
-D a_a=0
```
`a-a` is 1, and it auto-generates `a_a` with the same value. However, only `a_a` is overwritten by the next line. So during compilation `a-a=1` and `a_a=0`.

## Implications
As conditional compilation can only use the `a_a`, which is always updated correctly, this issue should not have any impact on code generation. However, it could end up being a problem for macros.

The changes described in #7795 seem to have been made.

When compiling with `-D a-a=1`:

```haxe
haxe.macro.Context.defined("a-a"); // true
haxe.macro.Context.defined("a_a"); // true
```

In comparison to compiling with `-D a_a=1`:

```haxe
haxe.macro.Context.defined("a-a"); // false
haxe.macro.Context.defined("a_a"); // true
```

### Hashlink C compilation
From here, the rest of this section is just about how an example of this happening can be seen when compiling to hashlink c. As far as I can tell it does not result with any functional difference in the code generated, so it isn't as big a problem here as with macros.
```hxml
-D hl-ver=1.12.0
-D hl_ver=1.10.0
```
If you compile to the hashlink c target like above, in the `"defines"` of the `hlc.json` file you get: 
```json
"hl_ver" : "1.10.0",
"hl-ver" : "1.12.0",
```

Even if you just use only `-D hl-ver=1.12.0`, you still get:
```json
"hl_ver" : "1.12.0",
"hl-ver" : "1.12.0",
```
(same thing happens in this file with `-D analyzer-optimize`, the hlc.json file contains both `analyzer-optimize`, `analyzer_optimize` ). Again, here it does not seem to make a difference but it seems wrong for it to add both of them to the json.

## Solutions

I would suggest that the changes in #7795 should not have been put in place, but I guess it's been done.

As `--help-defines` lists the flags with dashes, so it seems like it is intended that the dash versions of flags are meant to be put inside. Maybe this could be changed to suggest the underscore versions as the defaults?

The page on the haxe manual lists them mixed together with dashes for some but underscores for others: https://haxe.org/manual/compiler-usage-flags.html

### LINKED ISSUE #10376: Hashlink C target ignores the `source-header` define
When compiling Haxe to c code using the Hashlink target, the C code generated ignores the `source-header` flag, and simply always begins with:

`// Generated by HLC 4.3.0-rc.1 (HL v4)`

Other targets work fine.

### PR DESCRIPTION
**Pull request by tobil4sk**
Fixes #10184, fixes #10376, and fixes #7795

- Fixes the inconsistent use of dashes and underscores in the `src-json/define.json`, so that the documentation generated will be consistent.
- Trying to compile with `-D haxe-ver` now properly gives an error, as `-D haxe_ver` does.
- Fix the hlc target ignoring the `source-header` flag
- The flags `flag-a` and `flag_a` are now considered completely the same internally, so there are no weird differences between doing `-D flag-a` and `-D flag_a` 
- Define lists are now all in alphabetical order (some were in reverse before)
- Added tests for fixes that were done prior to this pull request (mostly a990a0d), which were:
  - Fix for `-D no_deprecation_warnings` not working
  - Remove raw define flags from `hlc.json` in the hlc target and from `Options.txt` in the hxcpp target.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
If your tests require a separate haxe project, you can put them into `tests/misc/projects/Issue10184`

**Comment by tobil4sk** [comment]
Done, hope those are all laid out fine.

**Comment by tobil4sk** [comment]
I realise now that a990a0d fixed the `hlc.json` issue, but now I undid it... Should I keep it how it is now or filter out the `hlc.json`?

**Comment by RealyUniqueName** [comment]
> I realise now that a990a0d fixed the hlc.json issue, but now I undid it... Should I keep it how it is now or filter out the hlc.json?

Well, if it was fixed I'd like to keep it fixed :)

**Comment by tobil4sk** [comment]
It's now been done as described in #10184

**Comment by tobil4sk** [comment]
I dont think there's any reason for the windows-64 js tests to have broken since 3c87faf. Seems like a one-off fail.

**Comment by RealyUniqueName** [comment]
Thanks!

**Pull request merged**
