### PR TITLE
Adds onBytes function to enable bytes requests

### PR DESCRIPTION
**Pull request by mundusnine**
This will enable the ability to get bytes data for images, zip files, etc. Tested on Hashlink but should work on neko also. Initial pull request was [here](https://github.com/HaxeFoundation/haxe/pull/7891). Proposed changes by @haxiomic are made in this repo.

### CODE REVIEW

**Comment by haxiomic** [comment]
Copying comment from previous PR:
I agree adding support for binary data in http requests is an important change to make, but I think we've also got to be very careful about getting it right. Changing HttpBase.hx will affect _a lot_ of projects, so if we have to make a breaking change we ideally want to make it future proof.

As the response is usually a `String`, maybe it makes sense to always return an object that unifies with `String` but lets you access the binary data easily? This way existing projects will still work as normal but you can access binary responses when you need them. (In JavaScript you [override the responseType to do this](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data#Receiving_binary_data_using_JavaScript_typed_arrays)).

I'd say this is a good starting point but we need to do a design pass + a set of tests so we can be confident we've got it right.

**Comment by ncannasse** [comment]
Please don't call twice output.getBytes() as it might construct twice the bytes result

**Comment by mundusnine** [comment]
@ncannasse  change was made.

**Comment by RealyUniqueName** [comment]
Implemented in #8570

**Pull request closed without merging**
