### PR TITLE
[diagnostics] show help message if StringTools not imported

### PR DESCRIPTION
**Pull request by Frixuu**
This PR displays a hint message (technically a suberror) if it looks like the user wanted to use StringTools, but did not import them:

Screenshot of a Haxe compiler error message. It reads: "String has no field endsWith. Help: perhaps you missed 'using StringTools'?"

Questions:
- Is ```display_error ?depth:1``` a good way to suggest fixes, or is there a better suited mechanism for this?
- What phrasing should be used to be helpful and not condescending?
- Should the compiler make such hardcoded assumptions about the standard library at all?

### CODE REVIEW

**Comment by Simn** [comment]
> Should the compiler make such hardcoded assumptions about the standard library at all?

I really don't think so...

**Comment by Aurel300** [comment]
Yeah, this is a nice usability feature, but implementing it this way is not good. FWIW there are such usability hints in Rust, e.g. when trying to use `Iterator` methods on non-`Iterator` types. But the way it is implemented is with attributes (like our metadata) and a tiny almost-DSL for matching errors, see [here](https://github.com/rust-lang/rust/blob/8a778ca1e35e4a8df95c00d800100d95e63e7722/library/core/src/iter/traits/iterator.rs#L27-L69).

**Comment by Simn** [comment]
Would that mean that String has to know about StringTools? Because that wouldn't seem quite right either...

**Comment by kLabz** [comment]
> Would that mean that String has to know about StringTools? Because that wouldn't seem quite right either...

Maybe some meta could be added to a type to hint at what extension tools can be used on it?
... and then libs could add more with ~~addMetadata~~ addGlobalMetadata

**Comment by Simn** [comment]
I think I suggested long ago that functions (or entire classes) which are intended to be used as static extensions should be marked in some way. Then the compiler could collect these and consider them when erroring.

One problem with such solutions is that it only works if the tools  classes are actually seen by the compiler.

**Comment by kLabz** [comment]
> Is display_error ?depth:1 a good way to suggest fixes, or is there a better suited mechanism for this?

It works fine this way yes. Other way to achieve this now is something like:
```ocaml
display_error_ext ctx.com (make_error
  (* contextual informations *)
  ~sub:[make_error (Custom "help: perhaps you missed `using StringTools;`?") pfield]
  (* main error here *)
  (Custom (StringError.string_error i (string_source tthis) (s_type (print_context()) tthis ^ " has no field " ^ i)))
  pfield
)
```

I do want to add some "hints" to pretty errors at some point, possibly via a new `Hint` (like `Custom` above) or something similar to make it easy to ignore in other modes. This example and/or implementation just isn't a very good one.

**Pull request closed without merging**
