### PR TITLE
[cpp] Non-blocking process exit code reading

### PR DESCRIPTION
**Pull request by Aidan63**
No longer throw when using non blocking process exit code reading

Depends on https://github.com/HaxeFoundation/hxcpp/pull/962

### CODE REVIEW

**Comment by Simn** [comment]
Sorry for the delay! I've merged the hxcpp PR, could you update this one so CI runs?

**Comment by Aidan63** [comment]
No problem, I've just merged development into the branch.

**Comment by Aidan63** [comment]
Seems like I forgot to change the HXCPP api level define in haxe.ml in this PR so its still trying to use the non blocking function. I'll look into changing that this afternoon.

**Comment by Simn** [comment]
Thanks!

**Pull request merged**
