### PR TITLE
Group warnings in compiler output with -w flag

### PR DESCRIPTION
**Pull request by RealyUniqueName**
This PR allows to remove warnings from compiler output with `-w` flag
With `-w`:
```
Warning : Run without -w to see 96 warnings.
src/main/haxe/sm/machines/slots/games/game327/slot/MoonlightMonstersDraculaAnimationComponent.hx:92: characters 51-60 : Type not found : EventArgs
```
Without `-w`. Can you notice an error message in this mess? :)
<details>
  <summary>Click to see full compiler output</summary><p>

```
/home/alexanderkuz/work/smh/pltk/src/main/haxe/apicommunication/api/infra/ApiRequestManager.hx:131: characters 73-100 : Warning : not used at all
/home/alexanderkuz/work/smh/pltk/src/main/haxe/apicommunication/network/RpcAddress.hx:33: characters 2-23 : Warning : not used at all
/home/alexanderkuz/work/smh/pltk/src/main/haxe/apicommunication/network/RpcAddress.hx:44: characters 2-25 : Warning : not used at all
/home/alexanderkuz/work/smh/pltk/src/main/haxe/apicommunication/network/RpcAddress.hx:77: characters 58-74 : Warning : not used at all
/home/alexanderkuz/work/smh/pltk/src/main/haxe/core/http/UriQueryBuilder.hx:82: characters 3-11 : Warning : Use try-catch with finally function instead.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/Payment.hx:34: characters 2-32 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/Payment.hx:44: characters 38-49 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:163: characters 52-71 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:177: characters 54-73 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:192: characters 50-64 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:219: characters 67-86 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:225: characters 75-94 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:234: characters 56-75 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:237: characters 48-67 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentService.hx:253: characters 58-77 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentStorageExtensions.hx:17: characters 86-105 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentStorageExtensions.hx:23: characters 7-26 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentStorageExtensions.hx:36: characters 5-24 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentStorageExtensions.hx:43: characters 7-26 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentStorageExtensions.hx:56: characters 5-24 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/pltk/src/main/haxe/inapppurchases/PaymentStorageExtensions.hx:63: characters 7-26 : Warning : Mobile product name is not relevant for web platform.
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:36: characters 31-226 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:37: characters 34-232 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:49: characters 22-104 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:52: characters 20-113 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:53: characters 23-119 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:54: characters 20-126 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:61: characters 24-107 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mge/src/main/haxe/minigameengine/core/configuration/XmlMiniGameConfigurationReader.hx:62: characters 27-113 : Warning : Please use CsLambdaCsList.singleOrDefault. 7/25/2017 12:43 PM
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/content/AbstractContentManager.hx:192: characters 2-10 : Warning : Use try-catch with finally function instead.
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/content/SoundReader.hx:25: characters 8-16 : Warning : Use try-catch with finally function instead.
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/builders/v3/SceneBuilder.hx:146: characters 5-26 : Warning : remove right after migrating to SceneData2
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/builders/v3/SceneBuilder.hx:147: characters 10-23 : Warning : remove right after migrating to SceneData2
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn.ext/src/main/haxe/mnsn/ext/ActionHelpers.hx:86: characters 25-42 : Warning : Please use CsLambdaInt.maxElement. 16/8/2017
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn-html5/src/main/haxe/mnsn/platform/html5/webgl/programs/AbstractGlShader.hx:165: characters 2-10 : Warning : Use try-catch with finally function instead.
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn-html5/src/main/haxe/mnsn/platform/html5/webgl/programs/AbstractGlShader.hx:169: characters 3-11 : Warning : Use try-catch with finally function instead.
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/resource/packages/BinaryPackage.hx:375: characters 3-17 : Warning : remove right after migrating to SceneData2
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/resource/packages/BinaryPackage.hx:1690: characters 3-13 : Warning : remove right after migrating to SceneData2
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/widgets/impl/TtfTextEditNode.hx:92: characters 2-14 : Warning : Please use method `PropertyMap.register2`. 02.02.2017
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/widgets/impl/TtfTextEditNode.hx:97: characters 2-14 : Warning : Please use method `PropertyMap.register2`. 02.02.2017
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/widgets/impl/TtfTextEditNode.hx:102: characters 2-14 : Warning : Please use method `PropertyMap.register2`. 02.02.2017
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/widgets/impl/TtfTextEditNode.hx:107: characters 2-14 : Warning : Please use method `PropertyMap.register2`. 02.02.2017
/home/alexanderkuz/work/smh/mnsn_haxe/mnsn/src/main/haxe/mnsn/scene/v3/widgets/impl/TtfTextEditNode.hx:36: characters 15-34 : Warning : Please use method `IContentManager.load1_1_String`. 2/3/2017 3:45 PM
/home/alexanderkuz/work/smh/reels_engine/src/main/haxe/reelsengine/IEntityCache.hx:49: characters 9-41 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
/home/alexanderkuz/work/smh/reels_engine/src/main/haxe/reelsengine/IEntityCache.hx:65: characters 18-50 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
/home/alexanderkuz/work/smh/reels_engine/src/main/haxe/reelsengine/ReelEngineBase.hx:158: characters 3-19 : Warning : Please use method update(). 11/8/2017
/home/alexanderkuz/work/smh/reels_engine/src/main/haxe/reelsengine/SymbolEnumerator.hx:216: characters 25-46 : Warning : Please use CsLambdaInt.minElement. 16/8/2017
/home/alexanderkuz/work/smh/reels_engine/src/main/haxe/reelsengine/SymbolEnumerator.hx:217: characters 24-45 : Warning : Please use CsLambdaInt.maxElement. 16/8/2017
src/main/haxe/sm/arena/arena/megabonus/MegaBonusController.hx:196: characters 36-87 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/arena/arena/megabonus/MegaBonusController.hx:325: characters 15-51 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/components/dev/DropFreespinsCheatComponent.hx:111: characters 3-37 : Warning : Usage of this field is deprecated
src/main/haxe/sm/machines/slots/components/dev/customcheat/CustomCheatProgressSender.hx:245: characters 3-49 : Warning : Usage of this field is deprecated
src/main/haxe/sm/machines/slots/components/dev/customcheat/CustomCheatSpinsSender.hx:145: characters 4-50 : Warning : Usage of this field is deprecated
src/main/haxe/sm/machines/slots/games/common/commands/KillWinLinesOnReelCommand.hx:25: characters 69-98 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/machines/slots/games/game012/minigame/MiniGameConverters.hx:37: lines 37-39 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game015/minigame/rounds/TombsRound.hx:76: characters 18-50 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game020/MiniGame20.hx:80: characters 19-57 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/machines/slots/games/game020/MiniGame20.hx:264: characters 17-48 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/machines/slots/games/game029/minigame/rounds/EditorRound.hx:87: characters 18-44 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game032/minigame/rounds/SubRound0.hx:46: characters 17-33 : Warning : Please use CsLambdaInt.minElement. 16/8/2017
src/main/haxe/sm/machines/slots/games/game047/MiniGame47.hx:251: lines 251-253 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game262/minigame/MiniGame262.hx:43: lines 43-47 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game262/minigame/rounds/Fireworks.hx:158: characters 15-171 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/machines/slots/games/game262/minigame/rounds/Fireworks.hx:159: characters 15-164 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/machines/slots/games/game263/slot/HippieHippoAutospinComponent.hx:20: characters 79-98 : Warning : use IsScatter
src/main/haxe/sm/machines/slots/games/game299/minigame/MiniGameConverters.hx:55: characters 20-58 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game299/minigame/MiniGameConverters.hx:58: lines 58-60 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game299/minigame/MiniGameConverters.hx:59: characters 27-59 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game300/MiniGame300.hx:47: characters 41-70 : Warning : Please, use CsLambdaIterator.select(), 8/15/2017 1:33 PM
src/main/haxe/sm/machines/slots/games/game300/MiniGame300.hx:51: characters 43-74 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game300/MiniGame300.hx:52: characters 38-67 : Warning : Please, use CsLambdaIterator.select(), 8/15/2017 1:33 PM
src/main/haxe/sm/machines/slots/games/game327/slot/MoonlightMonstersDraculaAnimationComponent.hx:92: characters 51-60 : Type not found : EventArgs
src/main/haxe/sm/machines/slots/games/game327/slot/MoonlightMonstersDraculaAnimationComponent.hx:106: characters 9-73 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/machines/slots/games/game332/slot/PeterPanSymbolIconEnumeratorComponent.hx:225: characters 25-46 : Warning : Please use CsLambdaInt.minElement. 16/8/2017
src/main/haxe/sm/machines/slots/games/game332/slot/PeterPanSymbolIconEnumeratorComponent.hx:226: characters 24-45 : Warning : Please use CsLambdaInt.maxElement. 16/8/2017
src/main/haxe/sm/machines/slots/games/game338/slot/AliceReturnIconEnumeratorComponent.hx:58: lines 58-60 : Warning : Please use CsLambdaInt.minElement. 16/8/2017
src/main/haxe/sm/machines/slots/games/game338/slot/AliceReturnIconRenderObjectComponent.hx:24: characters 22-75 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game344/minigame/MiniGameConverters.hx:78: characters 48-69 : Warning : Please use CsLambdaInt.maxElement. 16/8/2017
src/main/haxe/sm/machines/slots/games/game344/minigame/rounds/BottlesRound.hx:83: characters 19-43 : Warning : Please use CsLambdaInt.minElement. 16/8/2017
src/main/haxe/sm/machines/slots/games/game349/minigame/rounds/ButterflyRound.hx:120: characters 24-63 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game349/minigame/rounds/ButterflyRound.hx:121: characters 24-63 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game356/minigame/rounds/TopUiManager.hx:151: characters 22-36 : Warning : Please use CsLambdaInt.sum. 16/8/2017
src/main/haxe/sm/machines/slots/games/game366/slot/TemplePrincessIconModel.hx:45: characters 49-76 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game366/slot/TemplePrincessIconModel.hx:46: characters 49-74 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game395/slot/fakereels/ProbabilitiesConfigurator.hx:36: characters 9-46 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/SlotComponents396.hx:107: characters 145-187 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/InitializePotsComponent.hx:28: characters 24-66 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/InitializePotsComponent.hx:29: characters 14-58 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/InitializePotsComponent.hx:34: characters 40-82 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/maps/MapsResource.hx:43: characters 40-82 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/pots/PotsActionSource.hx:42: characters 24-41 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/pots/PotsActionSource.hx:43: characters 14-33 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/slots/games/game396/slot/pots/PotsFeatureSet.hx:35: characters 29-47 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/machines/tournamania/controllers/ContestModelBuilder.hx:101: characters 20-103 : Warning : Please use CsLambdaArray.skip. 7/25/2017 6:03 PM
src/main/haxe/sm/shared/api/LobbyApi.hx:478: characters 23-45 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/shared/api/LobbyApi.hx:1225: characters 22-49 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
src/main/haxe/sm/shared/collectibles/service/CollectiblesAlbumService.hx:129: characters 9-31 : Warning : Please, use CsLambdaIterator.toArray() 2017-08-11
```
</p></details>

If there is only one warning in compilation result then it will be printed as-is even with `-w` flag.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Any opinions?

**Comment by RealyUniqueName** [comment]
Since it's not a breaking change and CI is ok, I'm going to merge this.
Any objections?

**Comment by ncannasse** [comment]
That is a pretty unusual way to handle things. Maybe what you want is to (in all cases) print the errors before the warnings.

**Comment by RealyUniqueName** [comment]
I really want to hide warnings. Most people in our team don't care about warnings, so they don't need to see them.
AFAIK scala compiler does similar thing with warnings by default.

**Comment by ncannasse** [comment]
I would then prefer something more explicit such as --no-warnings that simply disable warnings, and do no print anything else (no warning count)

**Comment by RealyUniqueName** [comment]
I don't like hiding probrlems completely. I prefer to show me warnings as-is instead of silently ignore them.

**Comment by RealyUniqueName** [comment]
Feel free to close this PR if proposed behavior is not an option.

**Comment by ncannasse** [comment]
@RealyUniqueName that's the way all compilers are working ;)

**Pull request closed without merging**
