### PR TITLE
The Reflect.callMethod situation

### PR DESCRIPTION
**Pull request by Simn**
From #7106 

* [x] **php**

### CODE REVIEW

**Comment by Simn** [comment]
@RealyUniqueName: Can you comment on the PHP situation here? The idea is to ignore the context argument, but it depends on the closure behavior of the target.

**Comment by RealyUniqueName** [comment]
PHP correctly swaps the context in all cases.
I can align it with any new spec.

**Comment by Simn** [comment]
Then please make the tests pass!

**Comment by RealyUniqueName** [comment]
Done!

**Comment by Simn** [comment]
Alright, I think with that we're done. Someone should check the drivel I put on Reflect.callMethod for accuracy at some point, but I'm gonna merge this already.

What's funny is that I don't think we actually ended up fixing anything...

**Pull request merged**
