### PR TITLE
[typer] more helpful error for invalid usage of @:const type params

### PR DESCRIPTION
**Pull request by Gama11**
I initially forgot the `@:generic` when playing around with const type params and had to scratch my head a bit wondering what I was missing. I think mentioning the need for a @:generic class directly in the error is helpful. :)

### CODE REVIEW

**Comment by Gama11** [comment]
Oh, `@:generic` on class fields is a thing? Does that work with const type params though? There's still no syntax for specifying type params explicitly for function calls after all, i.e. this wouldn't work:

```haxe
Test.genericMethod<"foobar">()
```

The if here has `TClassDecl`, nothing about functions, but my OCaml is bad, so... :)

**Comment by Gama11** [comment]
Actually, there is one problematic scenario here: when you're missing `@:const` instead of `@:generic`. I'll adjust the error to mention that.

**Comment by Simn** [comment]
I find this "Unless" phrasing strange... I think we can lose the actual type parameter name because it is identified by the position anyway. So we could have a more general message like "Only @:const type parameters on @:generic classes can be used as value".

**Comment by Gama11** [comment]
Agreed, that's both shorter and sounds better.

**Pull request merged**
