### PR TITLE
fixed Array#slice when end is null

### PR DESCRIPTION
**Pull request by andyli**
A possible fix for https://github.com/HaxeFoundation/haxe/issues/4460#issuecomment-128156336
Not sure if this is the right approach.
Also, should this be applied to haxe-3.2.1 branch too?

### CODE REVIEW

**Comment by Simn** [comment]
Shouldn't that `null` become `0` on static targets?

**Comment by andyli** [comment]
But optional argument declared like `?end` should be nullable, right?

**Comment by Simn** [comment]
I guess so, though `?end : Int` is kind of contradictory.

**Comment by ncannasse** [comment]
I'm a bit reluctant to fix this here. Potentially a lot of native classes/methods have the same issue, so I don't think we should make an exception for slice

**Comment by andyli** [comment]
What about adding a sentence like "the behavior of passing `null` as `end` is unspecified" to the doc?
[The doc](http://api.haxe.org/Array.html#slice) currently only mentions:
> If end is omitted or exceeds this.length, it defaults to the end of this Array.

**Comment by andyli** [comment]
Second option:
We can change the signature of `slice` to:
```haxe
function slice( pos : Int, end : Int = 2147483647 ) : Array<T>
```
which `end` is not nullable on static platform anymore. `2147483647` is the max value of 32bit signed int, which effectively the same as specifying `end` as the length of the Array according to the doc.

It is the way the AS3 [`Array#slice`](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Array.html#slice()) is defined. However they used `16777215` as the default value... not sure why. The [AS3 doc on Array](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Array.html) says
 > The maximum size of an indexed array is 232 - 1 or 4,294,967,295.

And it reminds us we should specific a supported Array size too. e.g. "An Array is guaranteed to able to hold 2147483647 elements".

**Comment by ousado** [comment]
That the length of an array is an Int should be sufficient documentation of the theoretical limit, how many items an Array can actually hold depends on many factors and can certainly not be guaranteed.

**Comment by Simn** [comment]
This is related to #3826.

**Comment by Simn** [comment]
This PR no longer merges. Sorry for not looking into it earlier, but at this point the best we can do is close it.

**Pull request closed without merging**
