### PR TITLE
RemoveAt

### LINKED ISSUE #4238: Array.removeAt
Hi,

Deepnight and I think haxe Array misses : 
```
function removeAt( pos : Int) : Void;
```
when there is only :
```
function splice( pos : Int, len : Int ) : Array<T>;
```
Splice is very problematique since int creates another array and totally trashes memory. On most platforms this function already exists so here is a big astraction leak that haxe should fill.

for example on cpp, ths function would not ungrow the memory zone but use a memmove to retrieve the overlappig pointer zone, thus providing a very fast imlementation.

So we propose we introduce this function in cross platform.

we can start with a naive implementation which is 

```
function removeAt( pos : Int) : Void {
arr.remove( arr[idx] );
}
```

For informations, array is very often the (very) worst offender in memory usage yet the best ergonomic alternative, so we think improving it would be great.

### PR DESCRIPTION
**Pull request by delahee**
adds Array.removeAt for js cpp neko and swf
optimizes Array.insert for flash19
I don't quite get why nadako's commit are interlaced into my modifications...
tests where executed in a side project since they were not running on my local machine
fixes #4238

### CODE REVIEW

**Comment by MSGhero** [comment]
I don't like how it's `insert` and `removeAt` versus having them look the same. But I guess `insert` is no different than `push` or `unshift` while `remove` is its own thing.

**Comment by delahee** [comment]
@MSGhero I don't get your point :D

**Comment by MSGhero** [comment]
`insertAt` and `removeAt` just sounds better.

**Comment by delahee** [comment]
@MSGhero ah well you are right but.... insert was already there and deprecation or regression are complicated negociations these days, so let's pass this on dev branch and discuss tactical deprecation on next release :)

**Comment by MSGhero** [comment]
`removeAt` is 5x faster than `splice` for Arrays in flash :)

**Comment by delahee** [comment]
Yep I ll finalize it after Ludum Dare ;)

**Comment by delahee** [comment]
@simn Hi! I made a new tentative with removeAt() : Bool.
Everything seems fine on local tests, but let's be honets, I completely sucks at git...I have updated the branch etc... but I fear some pull messed something.

Could you check if everything is in order, thanks ?

**Comment by Simn** [comment]
```
/home/travis/build/HaxeFoundation/haxe/std/neko/_std/Array.hx:148: lines 148-163 : Public field removeAt is not part of core type
```

That's all I'm seeing on our CI right now.

**Comment by delahee** [comment]
Thanks!

I have referenced removeAt for neko in Array.hx:231, is there some other place I should declare for coretypes ? 

I had the feeling it should not be necessary to merge with cur dev but if there are core type changes...
Maybe I should git fetch+rebase with the current development branch ?

As a side note I cannot run the ful test suit on local, do you think the problem may be related to macro tests ? 

Sorry for the really dummy questions, I still struggle a lot when it comes to what is really needed for git pull requests. Thks!

**Comment by Simn** [comment]
You can't add public fields to a `@:coreApi` type unless you also add it to the base definition (std/Array.hx). This in turn requires to also add it to all implementations. At the very least you'll have to add a dummy implementation on the other targets.

As I said multiple times extending Array is not much fun. I'd still prefer ArrayTools as a default static extension, but nobody listens to me!

**Comment by delahee** [comment]
Well ahem, I have humbly looked at the ticket : https://github.com/HaxeFoundation/haxe/issues/4238 and its dependencies...I maybe dumb but you have never mentionned I should go the ArrayTools way..And I wasn't even aware that it was your thought....If I was aware I would have changed my plans accordingly...

So I humbly think you missed a pedagogy opportunity here...

That being said, even if it's an error on my side, I don't mind taking the time it take for removeAt to be in coretypes, 

=> _BUT_ if you create ArrayTools ( I won't take this responsibility ), I'll gladely put removeAt there, trash the PR and be done with it as fast as possible.

Gros bisous and refrain feeling, anyone disrespect your opinion, yes there are very hard rebukals but it's life :)

:love:

**Comment by Simn** [comment]
ArrayTools was rejected so we'll have to make do with this approach. This still requires adding the implementation to all targets, there's no way around that.

**Comment by delahee** [comment]
Okidoki :)
I can be stupidly persistent at this kind of boring work if I know it leads to closure so no problem to me.
I'll add other targets tomorrow.

**Comment by delahee** [comment]
@Simn ok this was kind of a long roller coaster adventure...

1- every non flash target is implemented correctly and tested here : https://github.com/delahee/haxe_utest

2- flash target did not allow me to override default removeAt crappy definition and use it inside the function itself...I tried with hxOverrides but didn't get very far...So I just defaulted to separating the definitions and make non flash target standardized yet efficient and let flash target efficient but with funky return values...

for example, on flash :
```
var b = [5]; b.removeAt( -2 ); //prints 5...gives me sweat that prod code relies on this thing
```

3- I separated the test because I could not run haxe regular test suit so it was easy for me to just mimic your test suit and hope you'll just copy paste the thing where it should go.

Conclusion : In my opinion, you can merge the thing or at least bits you are interested in... I am sorry that it's not an out of the box merge but I don't see how to make something cooler with the current flash generation...Do you have insights ?

xoxo

**Comment by ncannasse** [comment]
We won't allow a different signature in the removeAt function depending on the platform.

**Comment by delahee** [comment]
@ncannasse @Simn yep seems totally sound... is there any workaround so I can intercept "removeAt" calls and call the previous definitions in boot.hx like in aproto["filter"] = ... ?  

I tried to capture the old definitions but failed maybe I should push further tests in this way...

**Comment by Simn** [comment]
I have to ask again... why are we doing all this instead of optimizing an unassigned (i.e. block-level) `a.splice(x, 1)` to something native like [Hugh's removeAt hxcpp implementation](https://github.com/HaxeFoundation/hxcpp/commit/5aec71fd1e7ca54e9b2440f02d290dc13d7c22c0)?

This is not only much easier to implement but also optimizes existing code without the need to manually change it to use `removeAt`.

Also I really dislike these custom Array API changes in general.

**Comment by delahee** [comment]
@Simn I simply don't know how to do this, if you do, please do, this is an open discussion :)

This way, i'll just have to refactor the flash remove() to internally use flash removeat and we'll be done with it once and for all !

In a more general way, I know ocaml but am not teached how to modify the compiler / optimisers in depth so I usually try to hack the std lib so don't hesitate to bring your lore :)

**Comment by Simn** [comment]
I'll close this so we don't fragment the discussion, see #4238.

**Pull request closed without merging**
