### PR TITLE
Add attributes. uncomment constructor, fix native

### PR DESCRIPTION
**Pull request by TheoSabattie**

### CODE REVIEW

**Comment by Simn** [comment]
Does anyone know what this is/does?

**Comment by TheoSabattie** [comment]
@Simn  
I don"t understand your note.
Don't you know pdo attributes?
They allow to create directly object from request result,clean datas on fetch, transform string to int if numeric. Do nothing, show warn or disptach Exception on request error. etc..

**Comment by TheoSabattie** [comment]
@Simn Do you know who setup appveyor test?
There is problem with mysql : 

> 'mysql' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1

**Comment by andyli** [comment]
I'm the Haxe CI guy.
The mysql error was fixed in https://github.com/HaxeFoundation/haxe/commit/376c419bc5bc4e8bb3d77b8660ec61aa071514c7, you may either merge master to your patch-1 branch or rebase patch-1 on top of master.

**Comment by andyli** [comment]
For the PR, may be @mockey can comment?

**Comment by mockey** [comment]
> For the PR, may be @mockey can comment?

Well, the PDO class contains a huge amount of named constants (which are actually integers) for setting options:
http://php.net/manual/en/pdo.constants.php
This adds some of them to the Haxe API. Not really nice, but shouldn't do any harm either.

About uncommenting the constructor and adding `@:native`: I don't know why it was originally done this way, maybe there was a reason?

I think PDO.hx was mainly meant to make PHP PDO connections work in the Haxe sys.db context and hide the gory details, not as a proper extern.

>  Don't you know pdo attributes?

@TheoSabattie A bit of description for your PR would be nice. Why should anybody know about some PHP API details around here?

**Comment by TheoSabattie** [comment]
Ok', Thanks @andyli , @mockey , @Simn 
You can close this PR,
I cleaned up my computer so I remade changes.
I open an other with description.

https://github.com/HaxeFoundation/haxe/pull/5210

**Pull request closed without merging**
