### PR TITLE
[dce] Optimize search for descendants. ~60% faster compilation.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
This PR moves collecting list of descendant classes from dce filter to "main" compilation phase (idk how to call it).
It brings faster compilation, but requires compiler contributors to use special functions to add interfaces or super to classes instead if directy assigning them to `tclass.cl_implements` and `tclass.cl_super`.
Here are stats for our project with `-dce full`:
```
Before optimization
name     | time(s) |   % |      # | info
-----------------------------------
analyzer |   5.630 |   8 | 776168 | 
filters  |  30.020 |  43 |      1 | 
generate |   4.040 |   6 |      1 | 
  js     |   4.040 |   6 |      1 | 
haxelib  |   0.000 |   0 |      2 | 
macro    |  14.480 |  21 |  18625 | 
other    |   4.320 |   6 |      1 | 
parsing  |   1.970 |   3 |   8870 | 
typing   |   9.880 |  14 |  11575 | 
-----------------------------------
total    |  70.340 | 100 |      0 |

After optimization
name     | time(s) |   % |      # | info
-----------------------------------
analyzer |   5.340 |  13 | 776168 | 
filters  |   4.980 |  12 |      1 | 
generate |   3.780 |   9 |      1 | 
  js     |   3.780 |   9 |      1 | 
haxelib  |   0.000 |   0 |      2 | 
macro    |  13.260 |  31 |  18625 | 
other    |   4.030 |   9 |      1 | 
parsing  |   1.790 |   4 |   8870 | 
typing   |   9.440 |  22 |  11575 | 
-----------------------------------
total    |  42.620 | 100 |      0 | 
```
Check `filters` line.
Since this repo has troubles with CI, you can track tests here: https://travis-ci.org/RealyUniqueName/haxe/builds/222829588
Though it looks like i missed something, because our js build increased from 46092992 bytes to 46093704 bytes (0.0015% more bytes :) ). However our app works like nothing is broken. So maybe i just kept some unnecessary code.
Please, review.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Looking at a diff of our builds i can see some properties of interfaces are kept, while without this PR they were not.

**Comment by RealyUniqueName** [comment]
Perhaps this PR also fixes yet unknown bug. I see usages of those properties in both builds. But properties were generated only in optimized version.

**Comment by Simn** [comment]
I have made a similar change before but then started thinking about the compilation server and discarded everything. The problem I see is that these reverse relationships could cause old classes to be referenced in the following situation:

1. Compile CParent
2. Compile CChild, add it to CParent's `cl_descendants` list.
3. Compile CChild again. Its `cl_path` is already in CParent's `cl_descendants` list, so it is not updated and the previous version of the class is still referenced.

Even if you fix this (by removing the `Hashtbl.mem` check I suppose), things get out-of-sync when a class relationship is removed. That's a rare case, but should still be considered.

I also don't particularly like that we have to call `add_interface` because that's quite easy to forget and then error-prone. I think a better solution would be to populate `cl_descendants` during post-processing.

**Comment by RealyUniqueName** [comment]
> things get out-of-sync when a class relationship is removed. That's a rare case, but should still be considered.

What is this case? Or rather can you write a test for such case?

**Comment by Simn** [comment]
You have `class C extends D` and compile that, so C gets added to D's descendant list, and then you remove the `extends D` from C. D would not be recompiled and keep the reference to C.

**Comment by RealyUniqueName** [comment]
@Simn I updated PR. 
Moved population of `tclass.cl_descendants` to post-processing.
Classes from `tclass.cl_descendants` are being verified with `is_direct_descendant` on dce.

**Comment by Simn** [comment]
That looks better!

However, there's still the problem with compilation server state. Keeping outdated references around is really not good and actually could leak memory. Since you're updating all types anyway, I think the correct approach is to clear the descendants hash table when the class is re-used by the server. This can easily be done here: https://github.com/HaxeFoundation/haxe/blob/development/src/optimization/filters.ml#L396

`cl_restore` is called by the compilation server when it re-uses a class, so clearing the table at that point should ensure that we have a clean state during the next post-processing. Note that this is only true because you always check all types again (`com.types` instead of the `new_types` result of the filter). If we want to change that at some point we'll have to be a bit smarter and make sure everything stays in-sync.

**Comment by RealyUniqueName** [comment]
Done

**Comment by Simn** [comment]
Do we still need `is_direct_descendant` now?

**Comment by RealyUniqueName** [comment]
Oh, right. I guess not.

**Comment by RealyUniqueName** [comment]
Done

**Comment by Simn** [comment]
Ok, since we are trying to optimize here: Do we actually need a Hashtbl or could we just use a plain old list now? You're not doing any lookups and I don't think there's the risk of duplicates, so a list would be faster.

**Comment by RealyUniqueName** [comment]
Wouldn't it be error-prone since clearing the list and populateing it are in different places not tied to each other?

**Comment by RealyUniqueName** [comment]
I checked and List doesn't give any noticable improvements in `--times` report even on our really big project.

**Comment by Simn** [comment]
I'm fine with merging this, but I would like to see the CI results first. Apparently it has been fixed, can you push something so it triggers?

**Comment by RealyUniqueName** [comment]
Can we merge this to 3.4_bugfix?
It reduces compilation time by up to 40 seconds for us.
I'm using it for debug builds of our project since May without any issues. 
Current 3.4.4 produces the same js output with and without this patch.

**Comment by Simn** [comment]
I'm a bit reluctant because it's neither trivial nor a bugfix, technically. Normally I'd say no, but I'll let you guys play your foundation partner card on this one. So if you're sure about it, feel free to merge it to the bugfix branch.

**Comment by RealyUniqueName** [comment]
If you're reluctant then I prefer to stay in safe zone :)
I'll just continue to distribute patched version among devs, but our CI will build releases using "safe" compiler version.

**Comment by Simn** [comment]
My only real concern is the compilation server not maintaining the state properly. But since only Nicolas uses the compilation server, it should be fine. So let's add it.

**Comment by Neverbirth** [comment]
I would use it too if it would be 100% reliable in our main project... :P. But it's not the case already with 3.x versions, so I don't care for this one being there or not.

**Comment by RealyUniqueName** [comment]
Simn, pushed.

@Neverbirth What exactly is not reliable for your project in 3.4 branch?

**Comment by Neverbirth** [comment]
Quite difficult to tell. After some long time the compiler service may report back non existing errors, or maybe the project compiles but when using some display modes it starts returning wrong information (like missing fields on completion mode).

Not something simple to report as it may happen after a few minutes of developing, hours or days.

**Pull request merged**
