### PR TITLE
[js] Fix `TypedArray.entries()` mistake

### PR DESCRIPTION
**Pull request by terurou**

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Should the same fix also be applied to other typed arrays?

**Comment by terurou** [comment]
No. There are all same fixes of TypedArray in this PR :)

**Comment by RealyUniqueName** [comment]
Huh, somehow Github showed me only `FloatXXArray.hx` files

**Comment by haxiomic** [comment]
Thanks for the PR :),

Maybe it's worth using the [MapEntry abstract](https://github.com/HaxeFoundation/haxe/blob/bd87d4447d85094fdcfc60a3876c7dc548fed200/std/js/lib/Map.hx#L109) like is done for `js.lib.Set` rather than a new abstract for each type

**Comment by terurou** [comment]
> Huh, somehow Github showed me only FloatXXArray.hx files

Umm...

**Comment by terurou** [comment]
@haxiomic 

> Maybe it's worth using the MapEntry abstract like is done for js.lib.Set rather than a new abstract for each type

I think better that `MapEntry` should be separated from `js.lib.Map.hx` and made an another module (e.g, `js.lib.MapEntry.hx` or `haxe.ds.KeyValue.hx` ).

**Comment by haxiomic** [comment]
That's a good idea, I vote `js.lib.MapEntry.hx` because I don't think it's general enough for `haxe.ds`

**Comment by terurou** [comment]
> I don't think it's general enough for haxe.ds

Indeed.

**Comment by terurou** [comment]
I pushed commit that use `js.lib.Map.MapEntry` instead of TypedArrayEntry .

`js.lib.MapEntry.hx` is out of this PR scope, so I'll create another PR.

**Comment by terurou** [comment]
This PR is rebased from 3fe878cf9b25d17e9d2e83a0bd6e6f15553a9751 (includes #8757).

**Comment by haxiomic** [comment]
I think this one is good to go now

**Comment by terurou** [comment]
Will this PR be included in Haxe 4.0.0 final?
4.0.0-rc.5 doesn't include this.

**Comment by Gama11** [comment]
Yes, rc.5 was released from a separate bugfix branch instead of development to fix a few specific issues with rc.4.

**Comment by RealyUniqueName** [comment]
I think it's ok to merge this into 4.0. Current typing of these fields makes them unusable anyway.

**Comment by Gama11** [comment]
Merge it into 4.0? So Haxe 4 is not going to be released from the development branch?

**Comment by RealyUniqueName** [comment]
It will be released from 4.0_bugfix

**Comment by RealyUniqueName** [comment]
Hm... This PR is based on be528d916cdfbb8e724168126cb326fd6d5ae079 which renames and moves types around. 
It looks safe, but violates the  idea of final rc :)
I'm not sure it's ok to merge it into 4.0. @Simn ?

**Comment by Simn** [comment]
This one doesn't really look like a critical bugfix... or is this a regression from another change?

**Comment by haxiomic** [comment]
On balance I'd say it's worth merging this to final since without it you can't use `keys()` `entries()` or `values()` on js TypedArrays. ***Edit:** Just saw the [iterator change](517f0a4ff0322d790486f40d1acb6bb42cde1b09) isn't in 4.0_bugfix, so I guess yeah as @RealyUniqueName says, they can't be used in practise yet*

But I think we should add a deprecated typedef for the old MapEntry type so it's not a breaking change – I'll make a PR now

**Pull request merged**
