### PR TITLE
Happy new year!

### PR DESCRIPTION
**Pull request by markknol**
🎉 Its 2018! 🎉

### CODE REVIEW

**Comment by andyli** [comment]
What's changed in the submodules (haxelib and ocamllibs)? It's quite likely the cause of CI failure, but GitHub doesn't show the changes properly to me...

**Comment by andyli** [comment]
Looked more closely, the submodules are reverted to older commits (which shouldn't). Please fix that ;)

**Comment by markknol** [comment]
OOPS!
Can you help me, I have no idea how to fix this (no git expert).

**Comment by andyli** [comment]
Roughly:
 1. check out your 2018 branch
 2. `git reset --soft HEAD~` (reset the 2018 branch "pointer" to the previous commit but keeping all the current changes in the stage area)
 3. `git reset extra/haxelib_src` and `git reset libs` to unstage the submodule changes
 4. `git commit -m "Happy new year!"`
 5. `git push --force` to overwrite the remote 2018 branch

**Comment by markknol** [comment]
That works!

**Pull request merged**
