### PR TITLE
Reduce excessive casts

### LINKED ISSUE #8715: Excessive casts with abstracts over Int
AST dumps of classes using abstracts over Int show a lot of redundant casts, here an example from Lime's `ImageDataUtil`. It's enough that it might even have a noticable impact on cache size:

And a screenshot of a non-pretty dump from @nadako:

@Simn said there should be a filter to clean these up.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #8715
```haxe
class Main {
	static function main() {
		var c = (2:FInt) * 3;
	}
}

abstract FInt(Int) from Int {
	@:op(A * B)
	static inline function add(a:FInt, b:FInt):FInt {
		return a.toInt() * b.toInt();
	}

	inline public function toInt():Int {
		return this;
	}
}
```
`haxe -main Main -js test.js -D dump=pretty` Before this patch:
```haxe
static function main() {
	var c = cast cast cast 2 * cast 3;
	var a = 2;
	var d = cast cast a * cast 3;
}
```
after this patch:
```haxe
static function main() {
	var c = cast 6;
	var a = 2;
	var d = cast cast a * 3;
}
```

### CODE REVIEW

**Comment by Gama11** [comment]
Looks like this removes roughly 0.7 MB of casts in the cache of a Flixel project. :D The AST dump looks much saner too.

There's still a few places with more than two casts in a row:



I guess sometimes there's a bit back-and-forth:

**Comment by RealyUniqueName** [comment]
> I guess sometimes there's a bit back-and-forth:

This patch should deal with such places. Could you provide a sample?

**Comment by RealyUniqueName** [comment]
@Simn ready for review )

**Comment by Simn** [comment]
Uh, that `TODO` affecting most of our static targets tells me that something isn't quite right with this PR. If this is safe to do then it should be safe to do on static targets, too.

**Comment by RealyUniqueName** [comment]
That's about how our generators deal with binops, when there is no cast.
E.g. on C# with `-D erase-generics` a binop with type `UInt` is casted like `(object)` when passed to `object` argument instead of `(uint)`.
So this test fails:
https://github.com/HaxeFoundation/haxe/blob/456434674efae188514903163f703d1de33145c2/tests/unit/src/unit/issues/Issue3852.hx#L27
because `i - u` suddenly becomes an integer instead of `uint` in the generated code, while ast looks like `[Binop:UInt]`.
I can try and fix each of those targets now but this PR already eliminates a lot of unnecessary casts even on those targets.
E.g. `[Cast:Int] [Cast:UInt] [Cast:Int] [some expr:Int]` becomes `[Cast:Int] [some expr:Int]`. And on "good" targets it becomes just `[some expr:Int]`

**Comment by Simn** [comment]
Also, this is not a good place to handle cast reduction because it's too early. There could be subsequent transformations which cause redundant casts to appear in the AST, e.g. through the analyzer fusion.

Can you try adding this to optimizer.ml `reduce_control_flow`? The name doesn't really fit, but that's another issue. Note that this is a bottom-up algorithm, which works nicely for this scenario because we get to apply TCast rewrites transitively.

**Comment by RealyUniqueName** [comment]
To illustrate what I'm talking about here is a sample:
```haxe
class Main {
	static function main() {
		var u:UInt = 4;
		var i:Int = 3;
		eq(i - u, (-1 : UInt));
	}

	static function eq<T>(a:T, b:T) {
		if(a != b) {
			throw '$a != $b';
		}
	}
}
```
With current development the `i - u` expression in ast:
```
[Cast:UInt]
	[Binop:UInt]
		[Local i(3565):Int:Int]
		-
		[Local u(3564):UInt:UInt]
```
It has a reduntant cast because binop is already typed as `UInt`
With this PR without `TODO` that cast is removed and gencs generates this:
```cs
global::Main.eq<uint>(((uint) (( i - u )) ), ((uint) (-1) ));
```
but with `-D erase-generics` gencs generates this (while AST is not changed):
```cs
global::Main.eq(((object) (( i - u )) ), ((uint) (-1) ));
```
It's clearly an issue of gencs, not an issue of `reduce_unsafe_casts` of this PR.

**Comment by Simn** [comment]
This change has a small positive impact on memory consumption.

Before:

Code_2019-09-01_17-24-58

After:

**Review by Simn — APPROVED** [review]

**Pull request merged**
