### PR TITLE
Update JQuery to match our private version signature.

### PR DESCRIPTION
**Pull request by delahee**
http://api.jquery.com/off/

### CODE REVIEW

**Comment by Simn** [comment]
We have to check if that's available in our packaged JQuery. Also, we should get rid of that packaged JQuery.

**Comment by Simn** [comment]
If I'm understanding the JQuery API correctly it should not be allowed to call this with a handler but without a selector. The signature you're using here would allow skipping the middle argument.

I would prefer to leave JQuery.hx alone and focus on @andyli's externs instead.

**Comment by Simn** [comment]
@andyli: Could you handle this? If you have broader plans feel free to close this PR.

**Comment by andyli** [comment]
Please use the new extern instead: #4377

**Pull request closed without merging**
