### PR TITLE
Disallow null condition in ternary

### LINKED ISSUE #8634: add compiler error for ternary operator with null condition
I can't imagine following code being written intentionally:
```haxe
class Test {
  static function main() {
    var b: String = null;
    trace(b = null ? "null" : "not null"); // note the =/== typo, traces "not null"
    trace(b); // traces "not null"
  }
}
```
I propose add compiler error, when ternary operator condition is `null` identifier to help users avoid such typos.

### PR DESCRIPTION
**Pull request by RblSb**
Should be enough for typo check.
Closes https://github.com/HaxeFoundation/haxe/issues/8634

### CODE REVIEW

**Comment by Simn** [comment]
We should at least type the `null` identifier and see what happens. Not sure if that could ever resolve to anything other than `TConst TNull`, but I don't like these syntax-based checks.

**Comment by RblSb** [comment]
Maybe port `make_if_then_else` from null coal pr and add `is_ternary` argument to that function?

**Comment by Simn** [comment]
I don't think that helps because that function takes all arguments already typed, so if you call it you can just do the check beforehand.

**Comment by Simn** [comment]
Thanks!

**Comment by Simn** [comment]
By the way, while looking at the related code I noticed that we don't type the conditions against `Bool`: `let e = type_expr ctx e WithType.value in`. Not sure if that matters, but doesn't look right...

**Pull request merged**
