### PR TITLE
DynamicAccess key/value iterator

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by nadako** [comment]
I'm a bit concerned about this. The reason I didn't even add `iterator` is because it's super heavy and I wanted to have explicit `keys`  that returns an `Array<String>`. But on the other hand, of course a map-like API begs a key-value iterator, so we probably should have one.

One improvement I'd like to see though is `DynamicAccessKeyValueIterator` not to use `Iterator` as it won't be inlined. Can we use `index < length` + `keys[index++]` instead? That should be as good as the old `for (key in d.keys()) {var v = d[key];}` performance-wise.

**Comment by Gama11** [comment]
Hm... I figured this thing already has `Dynamic` in its name, so performance is probably not the biggest concern. ;)

**Comment by RealyUniqueName** [comment]
> I didn't even add `iterator`

Maybe it's time to add `iterator` too?

**Comment by nadako** [comment]
> Maybe it's time to add `iterator` too?

Maybe, so we're more consistent with Map. Although I don't find value-only iterator useful in most cases.

**Comment by Gama11** [comment]
I think it would make sense to have it. Not sure if that belongs in a separate PR or not though.

**Pull request merged**
