### PR TITLE
haxe.Log.traceOutput

### PR DESCRIPTION
**Pull request by ncannasse**
ensure the same formatting of Haxe trace on all platforms, eliminate redundant implementations
add haxe.Log.traceOutput dynamic function to only redirect the output

Missing platforms support:

- CPP
- PHP / PHP7
- Flash
- Eval (?)
- Check if Lua can use Sys.println (if not, we need to inverse the #if checks, if yes the #elseif lua part can be removed)

### CODE REVIEW

**Comment by ncannasse** [comment]
@hugh you can either remove your haxe.Log if it's the same as doing Sys.println or you can add traceOutput support to your existing class.

**Comment by back2dos** [comment]
I think it would be preferable to flip it around and expose the formatting functionality directly (so it can be used from other places also) and then just build on that:

```haxe
package haxe;

class Log {

	public static function formatOutput( v : Dynamic, infos : PosInfos ) : String { 
		var str:String = null;
		if (infos != null) {
			str = infos.fileName + ":" + infos.lineNumber + ": " + v;
			if (infos.customParams != null)
			{
				str += "," + infos.customParams.join(",");
			}
		} else {
			str = Std.string(v);
		}
		return str;
	}

	public static dynamic function trace( v : Dynamic, ?infos : PosInfos ) : Void {
                var v = formatOutput(v, infos);
		#if sys
		Sys.println(v);
		#elseif js
		if( js.Lib.typeof(untyped console) != "undefined" && (untyped console).log != null )
			(untyped console).log(v);
		#elseif lua
		untyped __define_feature__("use._hx_print",_hx_print(v));
		#else
		throw "Not implemented";
		#end
	}
}
```

**Comment by ncannasse** [comment]
I don't agree. In the case I'm proposing, it also allows to print
unformatted traces to the "debug output" (whatever it is)

**Comment by back2dos** [comment]
For starters, here are a few examples, where the proposed `Log.formatOutput` would come in handy:

- [`haxe.unit.TestRunner`](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/unit/TestRunner.hx#L105)
- [buddy](https://github.com/ciscoheat/buddy/blob/a35d7aaf4a6e6ecdda202646460a309ab2511a86/src/buddy/SuitesRunner.hx#L375)
- [munit](https://github.com/massiveinteractive/MassiveUnit/blob/835124965b55ef729450506c0baa2a7da1cf0278/src/massive/munit/client/AbstractTestResultClient.hx#L298)
- [hunit](https://github.com/RealyUniqueName/HUnit/blob/becd5753436d7329fd10859539d3acbd1e96f1f2/src/hunit/Utils.hx#L147)

Note the slight deviations caused by the lack of a standard, and how none of the deal with `customParams` (probably because it was added later).

As for the use case you're proposing, I do wonder if it's a thing, but sure, if you feel like it, it's trivial to have both:

```haxe
package haxe;

class Log {
	public static dynamic function traceOutput( v : String ) : Void {
		//what you said
	}
	public static function formatOutput( v : Dynamic, infos : PosInfos ) : String { 
		//what I said
	}
	public static dynamic function trace( v : Dynamic, ?infos : PosInfos ) : Void {
		traceOutput(formatOutput(v, infos));
	}
}
```

**In any case `#if js` should precede `#if sys`**, otherwise electron/nw.js will run into the sys branch and log to stdout rather than the dev tools console, making it effectively *lost* to anyone who doesn't launch the app from the command line.

**Comment by Simn** [comment]
Separating the formatting function makes sense to me.

**Comment by Pauan** [comment]
Does this fix the fact that `trace("hi!")` does not print file/line information on the JavaScript target?

**Comment by Gama11** [comment]
@Pauan See https://github.com/HaxeFoundation/haxe/issues/4497 (also applies to JS, not just Python).

**Comment by Pauan** [comment]
@Gama11 Thanks for pointing that out.

**Pull request closed without merging**
