### PR TITLE
[eval] Check statics reset on field access

### LINKED ISSUE #8631: [display] safe navigation operator breaks diagnostics
@RealyUniqueName's safety lib implements a [`!.` operator](https://github.com/RealyUniqueName/Safety#safe-navigation-operator) via macros. In 4.0.0-rc.3 this worked fine with diagnostics, but with latest Haxe dev there are errors that sound like the macro is not being executed:

```hxml
-lib safety
--macro Safety.safeNavigation('test')

-cp source
-main test.Test
```

```haxe
package test;

class Test {
	static function main() {
		var s:Null<String> = null;
		trace(s!.length); // null
		s = 'wow';
		trace(s!.length); // 3
	}
}
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #8631
I don't like this, but I failed to find  a better solution.
Another option is to revert ["X is redefined from X" fix](https://github.com/HaxeFoundation/haxe/pull/8571)

This PR adds a check if static fields need to be reset on each static field read/write. It's a simple boolean check so I don't think it would affect performance.
Probably only affects diagnostics, because on compilation through compilation server statics get reset as usual.
Also, I don't know how to write a test for this.

### CODE REVIEW

**Comment by Simn** [comment]
Urgh...

**Comment by Gama11** [comment]
>Also, I don't know how to write a test for this.

There's some diagnostics tests, for instance: https://github.com/HaxeFoundation/haxe/blob/23ca866a7ae3b25006535ac1787fa7b7a0e6da7c/tests/display/src/cases/Issue7943.hx

**Comment by RealyUniqueName** [comment]
> Urgh...

We should've done #7871  for 4.0...

**Comment by Simn** [comment]
Could you add a test for this? I'd like to see if I can fix this differently.

**Comment by RealyUniqueName** [comment]
> Could you add a test for this? I'd like to see if I can fix this differently.

done

**Comment by Simn** [comment]
See linked commit. My idea would be to delay the static inits until we actually start running something, i.e. the two places that count as `EKEntrypoint`.

This passes your test and I'm also not seeing the vshaxe problems from #8631. Unfortunately, #8571 didn't add a test, so that has to be checked again.

Something that's most likely still wrong with my change is the usage of `IntMap`. I'm pretty sure this introduces ordering concerns, but I'm not quite sure what order to use here.

**Comment by RealyUniqueName** [comment]
Unfortunately it indeed brings back "X redefined from X". I've pushed a test to your branch.

**Pull request closed without merging**
