### PR TITLE
Remove jquery and swfobject externs from std/js

### LINKED ISSUE #7478: [js] Move jquery and swfobject to haxelib
I'm not sure these belong in std, they assume you're targeting the web not node.js and they assume you have the right version of jquery or swfobject loaded – I think they're probably better moved to haxelib for haxe 4

I'm happy PR these to hx3compat if we're in favour of removing from std

### PR DESCRIPTION
**Pull request by haxiomic**
Closes #7478

- Delete directories `std/js/jquery` and `std/js/swfobject`
(These files are added to hx3compat in https://github.com/HaxeFoundation/hx3compat/pull/4)
- Removes `-D jquery_ver`
- Removes jquery dependence in tests

SWFObject and jQuery externs are available independently on haxelib
- https://lib.haxe.org/p/swfobject/
- https://lib.haxe.org/p/jQueryExtern/

### CODE REVIEW

**Comment by Simn** [comment]
`src/unit/TestJQuery.hx:4: characters 8-24 : Type not found : js.jquery.Helper`

I'm shocked we actually have tests for this...

**Comment by haxiomic** [comment]
Thanks for catching @Simn, turns out there's a lot more jQuery references that I thought! – will remove those too

**Comment by haxiomic** [comment]
Should be sorted now – CI is failing but it seems to be back to failing in the same way it was _before_ this PR

I've removed `-D jquery_ver` and removed jquery dependence in tests (f2dd99f)

**Comment by Simn** [comment]
Thanks a lot! I really like these cleanup PRs.

**Comment by eliasku** [comment]
@haxiomic @Simn Hey, what I should use instead of `js.jquery.*`? Seems like @andyli extern library (jQueryExtern) is not haxe-4-latest compatible yet (no CI,  compile error because of `overload` identifier). `hx3compat` have only legacy `js.JQuery`. Could we just publish previous `js.jquery.JQuery` externs as-is?

**Comment by haxiomic** [comment]
Hey @eliasku, the std lib jquery externs are moving to [hx3compat](
https://github.com/HaxeFoundation/hx3compat) once the PR merges. I’ll have a look at the haxelib ones and fix the haxe 4 compat issues (overload was reserved very recently). Once fixed I think the haxelib externs are the preferred choice. I'd be cautious to upload the std externs to haxelib because they're unlikely to be kept up-to-date whereas the jQueryExterns are

**Comment by haxiomic** [comment]
Created PR to rename overload in jQueryExtern lib: https://github.com/andyli/jQueryExternForHaxe/pull/24

**Comment by haxiomic** [comment]
@eliasku While waiting on that PR to merge you can use
`-lib jQueryExtern:git:https://github.com/haxiomic/jQueryExternForHaxe.git`

To get the latest version

**Comment by eliasku** [comment]
@haxiomic cool, thank you, will try soon

**Pull request merged**
