### PR TITLE
Make host name public for the c# target

### PR DESCRIPTION
**Pull request by lublak**
Its also available on lua, python, neko, macro, cpp, hl, php, java
[Host Api](https://api.haxe.org/v/development/sys/net/Host.html)

### CODE REVIEW

**Comment by Simn** [comment]
wtf is going on with travis on this branch...

**Comment by lublak** [comment]
@Simn I don't know. :flushed:

**Comment by Simn** [comment]
Just noticed that this was opened against the master branch. Please open it against development instead.

**Comment by Gama11** [comment]
You can actually change the target branch of existing PRs these days via "Edit".

**Comment by Simn** [comment]
Nice... however, it looks like it was _sent_ from master too. So no luck.

**Pull request closed without merging**
