### PR TITLE
Only compare mono refs in dup and s_type

### PR DESCRIPTION
**Pull request by frabbit**
Don't compare TMono, because it can be different (after a macro roundtrip for example).

### CODE REVIEW

**Comment by frabbit** [comment]
I discussed this issue roughly with simn, but i'm not sure if these changes are enough or can cause other probelms, but in general the underlying problem that we compare the type itself can blow something up, because you can map a mono or create a mono via genericBuild and use it in more than one places in a composed type like TEnum(x, [mono, mono]) where mono comes from a generic build macro. Also a type roundtrip from ocaml -> haxe -> ocaml causes encoding and decoding which change the physical identity of the mono type.

**Comment by frabbit** [comment]
ping @ncannasse

**Comment by frabbit** [comment]
ping @ncannasse again ;)

**Comment by ncannasse** [comment]
Seems fine to me, but I wonder if we are always correctly handling the mono
using its reference and not its type when dealing with unification. If we
don't, having a print different than the actual type handling will surely
cause some headaches later when debugging

**Comment by Simn** [comment]
My concern is that we're doing some `t == t` checks in various places...

**Comment by ncannasse** [comment]
Yes that's what I meant. Maybe we need some kind of TMono cache to make
sure they are physically equal when doing the macro round tripping (or
store the "t" instead of the "r")

**Comment by ncannasse** [comment]
I think this should be handled another way, and we should ensure physical equality of types as much as possible.

**Pull request closed without merging**
