### PR TITLE
Fix #8187

### LINKED ISSUE #8187: Enum case without arguments cannot be used in inline final
Functions can accept enums without arguments as default values, but this does not work for `inline final`s:

```haxe
enum A {
  NoArgs;
}

class Test {
  //static inline final a:A = NoArgs; // <- does not work
  
  static function foo(a:A = NoArgs):Void {}
}
```

### PR DESCRIPTION
**Pull request by Aurel300**
Closes #8187.

Allows enum constructors without arguments in `static inline var`s.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Test please

**Review by nadako — COMMENTED** [review]
why everyone is doing all in `misc` tests nowadays, just have a normal `Issue8187.hx` and also I think we should do a basic `eq(enumValue, Leaf)` test just to be sure it's actually working at run-time.

**Comment by Aurel300** [comment]
@nadako My bad :)

**Comment by Simn** [comment]
An optimization test for this wouldn't hurt to ensure that the inline actually happens. But then again, why wouldn't it...

**Pull request merged**
