### PR TITLE
[js] Uses the native String.trim if es5

### PR DESCRIPTION
**Pull request by R32**

### CODE REVIEW

**Comment by RblSb** [comment]
js trim removes more chars than `StringTools.isSpace` detect, see whitespace/lineterminator definitions
https://tc39.es/ecma262/multipage/text-processing.html#sec-trimstring
Not sure how strict to haxe spec we should be here.

**Comment by kLabz** [comment]
I'd rather have consistent (but have we for java/cs atm?) behavior across targets, and have native js behavior exposed via some js util

**Comment by R32** [comment]
I think the differences are trivial, and in js platform the behavior of native String.trim is probably more expected.

**Comment by Simn** [comment]
I'm also in favor of consistency here, unless someone provides an argument for why we should be doing this.

**Pull request closed without merging**
