### PR TITLE
[flash] Fix wrapping of exceptions

### PR DESCRIPTION
**Pull request by tobil4sk**
Oversight in #10519

### CODE REVIEW

**Comment by Simn** [comment]
I mean, I certainly believe you that this fixes something, but maybe we should still add a test for whatever it fixes?

**Comment by tobil4sk** [comment]
The flash CI tests would have covered this bug, however, those were disabled when the original PR was merged. I will create another PR to restore them.

**Comment by Simn** [comment]
Oh, I hadn't realized that we're no longer testing Flash, hmm... Now I'm scared of what enabling the tests again might uncover.

**Comment by tobil4sk** [comment]
Hopefully not too much else, but this was one of the things it uncovered.

If all goes well, then #10598 CI should fail because of this issue, and then once this is merged it should work (fingers crossed).

**Comment by tobil4sk** [comment]
In the meanwhile, this is the failing test:
https://github.com/HaxeFoundation/haxe/blob/d3306f4738ee09bd84a43e5b88ab1f858529496e/tests/unit/src/unit/TestExceptions.hx#L86-L99

When `e` is rethrown (line 93), it becomes a `haxe.Exception` so no longer gets caught by the `CustomNativeException` catch. This causes the test to fail because the exception is never caught and crashes the test:
(from the [linux test](https://github.com/HaxeFoundation/haxe/runs/5266185440?check_suite_focus=true#step:10:6811))
```
+test-flash *failed* | Running .swf file: /tests/unit/bin/unit9.swf
+test-flash *failed* | Waiting 2 seconds for flash log file...
+test-flash *failed* | src/unit/TestMain.hx:42: Generated at: 2022-02-20 19:14:14
+test-flash *failed* | src/unit/TestMain.hx:44: START
+test-flash *failed* | utest/ui/text/PrintReport.hx:52: 
+test-flash *failed* | assertations: 10597
+test-flash *failed* | successes: 10596
+test-flash *failed* | errors: 1
+test-flash *failed* | failures: 0
+test-flash *failed* | warnings: 0
+test-flash *failed* | execution time: 7.827

+test-flash *failed* | results: SOME TESTS FAILURES (success: false)
+test-flash *failed* | unit.TestExceptions
+test-flash *failed* |   testWildCardCatch_rethrow: ERROR ..E
+test-flash *failed* |     
```

**Comment by Simn** [comment]
Makes sense to me!

**Pull request merged**
