### PR TITLE
remove extra null check in formatOutput. It is not needed.

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by Simn** [comment]
Why would that not be needed? The `customParams` field is optional.

**Comment by Gama11** [comment]
I think the means because fields are already accessed the line before, so it can't be null anymore at this point.

**Comment by lublak** [comment]
Yes if you look into the line:
https://github.com/HaxeFoundation/haxe/blob/df4b2ee9a9e369963341e08032489b7823e5998b/std/haxe/Log.hx#L35

So we don't need check `infos` twice @Simn 
You are right @Gama11

**Comment by Simn** [comment]
But this doesn't check `infos`, it checks `infos.customParams`.

**Comment by Simn** [comment]
Oh I see, I can't read diffs.

**Comment by lublak** [comment]
@Simn yes the diff looks a little bit disordered with the "remove `!= null && infos`"

**Pull request merged**
