### PR TITLE
Treat Any as a wildcard type. Just like Dynamic

### LINKED ISSUE #6649: Improper constraint check failure with new "Any" type and Std.instance
Easily reproducible constraint check problem with trying to get a Std.instance of something that's Any. It works fine if you use Dynamic instead of Any in Haxe 3.4.0:
```haxe
class Test {
    var any:Any;
    function foo() {
        var test = Std.instance(any, Test);
	}
}
```
```
Test.hx:4: characters 19-31 : Constraint check failure for instance.S
Test.hx:4: characters 19-31 : Test should be Any
Test.hx:4: characters 19-31 : Constraint check failure for instance.T
Test.hx:4: characters 19-31 : Any should be { }

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #6649

### CODE REVIEW

**Comment by nadako** [comment]
Didn't we want to forbid/limit Dynamic variance, not add even more?

**Comment by RealyUniqueName** [comment]
@Simn marked that issue as a bug. So I guess no.

**Comment by Simn** [comment]
I have mixed feelings about dynamic variance. I would indeed prefer to have less of it, but at the same time I always run into these problems when trying to use `Any`.

`Any`way, branch needs an update.

**Comment by RealyUniqueName** [comment]
This is wrong.

**Pull request closed without merging**
