### PR TITLE
Save types of local vars too in `save_class_state`

### LINKED ISSUE #4073: [cs] abstracts lost in compilation server
Consider the following example:

Main.hx

``` haxe
abstract A(Int) {}

class Main {
    function f(a:A) {}
}
```

MyMacro.hx

``` haxe
import haxe.macro.Context;

class MyMacro {
    static function run() {
        var cl = switch(Context.getType("Main")) {
            case TInst(cl,_): cl;
            default: throw false;
        }

        for (f in cl.get().fields.get()) {
            if (f.name == "f") {
                switch (f.expr().expr) {
                    case TFunction(fun):
                        trace(fun.args[0].v.t);
                    default: throw false;
                }
            }
        }
    }
}
```

Run:

```
haxe --wait 6000
```

and then 

```
haxe --connect 6000 --macro MyMacro.run() -cs cs
haxe --connect 6000 --macro MyMacro.run() -cs cs
```

The first output will be: `TAbstract(A,[])` as expected, however the second one yields underlying type: `TAbstract(Int,[])` which is going to break macros.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #4073 

gencs/genjava actively mess with types, so I ended up just saving/restoring that data.

### CODE REVIEW

**Comment by Simn** [comment]
But we already do that in `save_class_state`. Is there something specific that isn't saved there?

**Comment by RealyUniqueName** [comment]
Types of local vars and function arguments. 
Also, gencs/genjava mess with cl_restore too and that breaks subsequent compilation somehow.

**Comment by RealyUniqueName** [comment]
I mean, using `save_class_state` upon entering genjs/genjava and `cl.cl_restore` upon leaving them. I tried that and subsequent compilations started throwing `Not_found` ocaml exception.

**Comment by Simn** [comment]
Yes you're not supposed to run it at that point.

What we should do is handle the `tvar`s there so it's all in one place. Maybe only on targets where it's necessary, but it might be a good idea to always do this.

**Comment by RealyUniqueName** [comment]
Yeah, that works. I've updated this PR

**Pull request merged**
