### PR TITLE
Add arrow functions

### PR DESCRIPTION
**Pull request by ousado**

### CODE REVIEW

**Comment by nadako** [comment]
Still can't believe this is happening :)

**Comment by frabbit** [comment]
It's still open ;)

**Comment by RealyUniqueName** [comment]
I don't know... Maybe Haxe world is not ready yet...

**Comment by Simn** [comment]
Yeah, let's come back to this in a year or so. Closing for now.

**Comment by Simn** [comment]
Shit, wrong button...

**Comment by fponticelli** [comment]
WOW!!!!!

**Comment by mrcdk** [comment]
Nice! good job people!

**Comment by nadako** [comment]
I've added a link to the original proposal for people that are not following the whole story.

**Comment by sledorze** [comment]
Great!

**Comment by fullofcaffeine** [comment]
This is so awesome! Can't wait to start using it!

On Thu, Apr 27, 2017 at 4:02 PM, Stéphane Le Dorze <notifications@github.com

**Comment by Justinfront** [comment]
Nightlies seem to be stuck on 23rd ?  Interested to try, thought I 
should mention they seem stuck. Many Thanks ;j

**Comment by jdonaldson** [comment]
:soon:

**Comment by FrancisBourre** [comment]
So, it's done. Congrats guys!

**Comment by cooljith91112** [comment]
yeeeeeeey!!!!

**Comment by Lazarus404** [comment]
It's a good feature.  I've enjoyed using it in ES2016 and will enjoy using it in Haxe, also.

**Comment by ciscoheat** [comment]
[This calls for a celebration](https://www.youtube.com/watch?v=roRQ2mNwMMQ "This calls for a celebration")

**Comment by fullofcaffeine** [comment]
@Lazarus404 Long time no see, good to see you around :) and yes, arrow functions FTW!

**Comment by jeebus3000** [comment]
Seems that no one paid attention to what @Justinfront is written. _Make nightly builds great again!_

**Comment by Justinfront** [comment]
I can wait ;)   - don't fancy trying homebrew at mo. But @jeebus3000 homebrew maybe an option if your on mac, if your on pc then there is suggestion on haxelang, if your on linux then you can probably do it from terminal .. ! :)

**Comment by dstrekelj** [comment]
Can't believe this passed me by. Great work! I look forward to using and abusing arrow functions :D

**Comment by ciscoheat** [comment]
Is there any way of detecting if the function AST expression is an arrow function?

**Pull request merged**
