### PR TITLE
Refactor Macro

### PR DESCRIPTION
**Pull request by ncannasse**
This is the second (big) part of macro refactoring before trying HL interp.
I *think* (hope) I have kept all previous behaviors identical but before merging I guess it would need some tests with macro extensive code (my projects are passing). Ping @nadako @Simn :)

### CODE REVIEW

**Comment by Simn** [comment]
I don't really have a lot of macros other than in hxparse, so if it works for nadako it's gonna be fine for my stuff too.

**Comment by Simn** [comment]
Though something on the CI is failing:

```
Command: make [-s,package_doc]
--macro:1: character 0 : Type not found : haxe.macro.Context.hl
make: *** [package_doc] Error 1
Command exited with 2 in 2s: make [-s,package_doc]
Called from ? line 1
Called from RunCi.hx line 1105
Called from RunCi.hx line 693
Called from RunCi.hx line 102
Called from RunCi.hx line 67
Uncaught exception - Fail
```

**Comment by frabbit** [comment]
Maybe you should ask @back2dos if you want to be sure ;)

**Comment by nadako** [comment]
As I said on Slack, my codebase compiles without any noticeable differences.

**Comment by ncannasse** [comment]
@andyli any idea about the CI ? Seems like some script which chokes on `haxe/macro/Compiler.hl.hx`

**Comment by ncannasse** [comment]
It seems it comes from `haxelib run dox` which wrongly recognize it as a module, who can help with this?

**Pull request merged**
