### PR TITLE
Disallow defining types into existing modules

### LINKED ISSUE #10374: Context.defineModule on exists module with TDField not works
I can use `Context.defineModule` to create a extra class in a module to inject some stuff.
This works fine.
If i use TDField the compiler throws an error: `File "src/typing/typeloadModule.ml", line 402, characters 4-10: Assertion failed`

```haxe
Context.defineModule('sub.test.Test', [{
  pos: Context.currentPos(),
  pack: ['sub', 'test'],
  name: 'SomeFancyVarName',
  params: [],
  meta: [],
  kind: TDField(FVar(null, macro null), [AInline, AFinal]),
  fields: []
}]);
```

### PR DESCRIPTION
**Pull request by Simn**
Salvaged from https://github.com/kLabz/haxe/tree/definemodule_disallow_redefine. I'm deleting the test for #4160 because it depends on a type being defined in the local module in order to access one of its private types. The test for #6006 was adjusted.

### CODE REVIEW

**Comment by Simn** [comment]
@yuxiaomao Could you check if this breaks something for you? I wouldn't be surprised if it did...

**Comment by yuxiaomao** [comment]
I'm having this type of error, `cdb` is catsle DB and the line is the official setup
```
[ERROR] src/Data.hx:1: characters 24-79
 1 | private typedef Init = haxe.macro.MacroType < [cdb.Module.build("data.cdb")] > ;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | Cannot redefine module Data
    ->  (project)\src\Data.hx
      |   Previously defined here
```

**Comment by Simn** [comment]
Yeaaaah that sounds like I might as well close this PR...

**Comment by kLabz** [comment]
Maybe it's just the restriction being applied "too early"? Build macros for types inside the module could be allowed to add types for that module but once everything is built, the  module is "locked".

**Comment by Simn** [comment]
There isn't really a "once everything is built" point though with how lazy everything is typed. The module would have to be locked upon first access, and I don't know if that improves anything.

**Comment by kLabz** [comment]
Can it only be allowed for `ctx.m.curmod`?

**Comment by Simn** [comment]
I was considering that as well when I looked at the tests I had to change because both of them use `Context.getLocalModule()`. I'm not sure if that would even fix CastleDB though...

**Comment by yuxiaomao** [comment]
Seems good now for our projects

**Comment by Simn** [comment]
Thanks for checking!

Unfortunately this means that we still have to leave #10374 open, but this should at least help somewhat.

**Comment by kLabz** [comment]
Any idea why this would report with an absolute path?

```
> ls -1
compile-fail.hxml
compile-fail.hxml.stderr
Main.hx
Test.hx

> haxe compile-fail.hxml -D message.reporting=classic
Main.hx:4: characters 3-9 : Cannot redefine module Test
/git/haxe/tests/misc/projects/Issue10374/Test.hx:1: character 1 : Previously defined here
```

**Pull request merged**
