### PR TITLE
Fix EReg use as type parameter

### PR DESCRIPTION
**Pull request by bendmorris**
Fixes the other part of #6952

### CODE REVIEW

**Comment by Simn** [comment]
Does this distinguish `1` and `"1"`?

**Comment by Simn** [comment]
Never mind, I saw `Std.string` and got confused. Should be fine!

**Comment by bendmorris** [comment]
It does; strings are wrapped in quotes (which become 34s...)

```haxe
        new Test<"1">().foo();
        new Test<1>().foo();
```

```python
class Test_1:

class Test__34_1_34_:
```

**Comment by bendmorris** [comment]
There's an issue with `return T` on C#/Java which is breaking the test: https://github.com/HaxeFoundation/haxe/issues/6979

**Comment by bendmorris** [comment]
Seemingly unrelated PHP test failure on AppVeyor

`ErrorException: unlink(C:/projects/haxe/tests/sys/temp/(two words).exe): Permission denied in C:\projects\haxe\tests\sys\bin\php\Main\lib\TestCommandBase.php:203
`

**Pull request merged**
