### PR TITLE
[js] Add extern for the `structuredClone()` function

### PR DESCRIPTION
**Pull request by cedx**
See: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

### CODE REVIEW

**Comment by cedx** [comment]
@haxiomic I wonder if this method should be strongly typed/made generic:
`function structuredClone<T>(value: T, ?options: {transfer: Array<Any>}): T`

After all, a clone is supposed to have the same type as the source object. OTOH, automated externs would probably result in what I've currently provided.

**Comment by haxiomic** [comment]
Agreed, I think the generic version is best

Lib.hx is all handwritten so no need to worry about html extern updates in the future :)

**Comment by haxiomic** [comment]
LGTM :), thanks cedx!

**Comment by Simn** [comment]
Does this just work everywhere all the time or do we have to worry about different JS run-time environments or something like that?

**Comment by haxiomic** [comment]
Very good point @Simn, thanks for spotting, this is a DOM API rather than a js language one; it should be in `js.html/`

In the spec it's defined in [`WindowOrWorkerScope`](https://github.com/microsoft/TypeScript/blob/16b6f0f53388b01fd383ca75474d2503e7f455dd/src/lib/webworker.generated.d.ts#L5270)

In haxe we have [WorkerGlobalScope.hx](https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/WorkerGlobalScope.hx) and [Window.hx](https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/Window.hx)

It should probably be defined in both (and one day we could seek to unify these two properly)

**Comment by cedx** [comment]
OK to add it to `Window` and `WorkerGlobalScope`... but these are autogenerated externs, and I'm afraid that @Simn is against editing them (see #10620 and #10603).
@Simn we already have some handmade JS externs in the code base, you should consider revising your position.

**Comment by Simn** [comment]
All these files have a comment stating `// This file is generated from mozilla\Window.webidl. Do not edit!`. Is that no accurate anymore? If not, why not? The whole purpose of having a generator for these externs was so that we _don't_ have to painfully keep them updated by hand.

**Comment by haxiomic** [comment]
It's still accurate for js.html, but churn in the WebIDLs means an update is a big project – too big for me to find budget for, at least at the moment. The extern generator is hacks upon hacks, I think we ought to build a new one TypeScripts generator which I expect will make future updates much easier

I think not editing these files only matters if we plan to run the generator again, I don't know if anyone plans to take on that project but I am not likely to in the near term (sorry to say)

I'd be tempted at a major haxe version to switch to a `js.dom` that uses a new generator and move `js.html` to compatibility

**Comment by cedx** [comment]
See @haxiomic's answer in #10166: it seems that the current way of generating these externs is not maintenable.
And that's why:
- they haven't been generated for several years now
- several PR were merged to address the missing APIs or the incorrectness of some generated externs

**Comment by Simn** [comment]
I thought this whole TypeScript-based generator thing had been done years ago... But I guess I must be confusing this with something else. In that case I agree that we can just modify things by hand. I'm not happy with that state of affairs but I suppose it is what it is.

**Comment by cedx** [comment]
I've updated the externs. That should be good.

**Comment by haxiomic** [comment]
I've forked typescripts dom lib generator and setup a haxe entry point that receives the processed WebIdl structure:
https://github.com/haxiomic/Haxe-TypeScript-DOM-lib-generator/blob/main/src-haxe/Main.hx

Just generates enums for now, I'll try to return to this and make progress bit by bit

I don't think we should strive for a perfect match for js.html because there's some historical issues we should try to fix, like the [Element / HTMLElement](https://github.com/HaxeFoundation/haxe/issues/9085#issuecomment-574702015) mixup

I think at first we can release a new js.dom to haxelib with --remap to js.html and maybe we can replace js.html in std in a major release

**Pull request merged**
