### PR TITLE
Faster Bytes

### PR DESCRIPTION
**Pull request by ncannasse**
This improves and cleanup bytes/float conversion. Waiting for unit tests results on all platforms to merge.
Also requires improved flash support using helper ByteArray and macro neko 2.1 builtins for faster IO

### CODE REVIEW

**Comment by ncannasse** [comment]
Feel free to comment @hughsando @waneck

**Comment by hughsando** [comment]
So the helpers are about reinterpreting bit patterns?  The cpp.Pointer class should help here.  I'll see about optimizing this at some stage.
The tmp result thing does not look very thread safe - maybe pass in an optional buffer to doubleToI64, and only use the tmp if the buffer is null.

**Comment by ncannasse** [comment]
@hughsando we should use a TLS for thread safety here. using an optional buffer will only move the problem upwards

**Comment by ncannasse** [comment]
PS: I'm planning to add DataView and typed array views (UInt8/Float/Double/UInt16/Int32), using a Bytes reference as a default implementation. They will be abstracts in order to allow array access. Platforms might want to implement their own optimized version afterwards.

@Simn do we check @:coreApi on abstracts ? (including from/to/etc.)

**Comment by Simn** [comment]
We check the implementation classes, but I don't think we check the relations.

**Comment by ncannasse** [comment]
@Simn maybe we should. I was thinking also we should make Int64 an abstract, since we're starting to use it in the standard library.

**Comment by Simn** [comment]
See https://github.com/HaxeFoundation/haxe/pull/2617

**Comment by waneck** [comment]
I'll improve what I can on Java and C#. I know how to do it on C# without needing the temp buffer; and on both there will be an optimized version if `-D unsafe` is defined

**Comment by waneck** [comment]
@ncannasse an abstract of Int64 would be awesome. Specially if they are bundled with Int64 literals :)

**Comment by ncannasse** [comment]
@waneck let's first merge #2617 and we'll see ;)

**Comment by waneck** [comment]
That's very exciting!!

**Comment by ncannasse** [comment]
Anybody have any idea why I get an error in macro Travis compilation in a #if flash section ?

Also @waneck could you look quickly at the CS issue, not sure where it went wrong :)

**Comment by Simn** [comment]
The flash error came from Dox generating the documentation XML files.

**Comment by waneck** [comment]
@ncannasse done. I've taken off all static buffer helpers, and the only allocation happening on C# is actually stack-allocated, since it's a struct.
I agree that we should implement a Tls for the targets that support threads and still use helpers.

**Comment by ncannasse** [comment]
Thanks ! My next step is to work of bytes "views" (similar to JS typedarrays), which should be easier to implement now

**Comment by andyli** [comment]
I noticed there is usage of a static bytes object `helper`. Would it cause issue when using threads?

**Comment by ncannasse** [comment]
@andyli yes, potentially. We need to use a TLS for that on platforms that have this issue. ATM this is hxcpp (because i64tmp and helper, but the later should be optimized), and neko (because of i64tmp)

**Comment by Simn** [comment]
I only just noticed that it should be `UInt8Array` because we have `UInt`.

**Comment by ncannasse** [comment]
@Simn we maybe want to keep JS namings here (only package change)

**Comment by Simn** [comment]
Why? I prefer consistency here.

**Comment by Simn** [comment]
API-question: I've replaced my own bytes implementation in hxparse with an abstract over Uint8Array (to retain the exact API). However I had to keep both `ofString` and `readString` which I originally copied from haxe.io.Bytes. Is there (going to be) a way to go from String to Uint8Array directly or do I have to detour over Bytes?

**Comment by ncannasse** [comment]
We could add a quick helper UInt8Array.ofString, but that might not be a good idea because of Unicode (this limit you to ASCII here), so I would prefer we don't do anything until we have proper encoding parameters supported

**Comment by Simn** [comment]
Well the methods in haxe.io.Bytes deal with UTF8 encoding at least, but I suppose it makes sense to allow options here.

**Comment by waneck** [comment]
I feel that `fromString`/`toString` Bytes methods being implicitly UTF8 is bad; It makes transparent for the user something that shouldn't be - which is what encoding you want to read the bytes with.
If we think that our internal String representation should always be in the same (internal) enconding, I think it makes sense to always require the encoding to be passed when using these methods.

**Comment by ncannasse** [comment]
@waneck string encoding is something we will look at the next version, allowing explicit encoding in all bytes from/to string operations

**Pull request merged**
