### PR TITLE
Fixed EReg to throw exception on missing group on php, for #5352

### PR DESCRIPTION
**Pull request by dracony**
For issue #5352

### CODE REVIEW

**Comment by Simn** [comment]
I'm not sure about this, the comment there suggests that there was some reason for doing this.

**Comment by dracony** [comment]
The comment also made me think, but I honestly can't think of a failing use case. It's not like regexs work somehow different on PHP or anything. What even constitutes an "invalid group" ? Surely if the group is invalid the regex would not run at all

**Comment by Simn** [comment]
Yes it's quite strange. Still, I would prefer to not make this change right now because we're between RC and release, and this has been broken for years now anyway.

**Comment by dracony** [comment]
Anything other I could work on then ?
On Jun 14, 2016 12:39, "Simon Krajewski" <notifications@github.com> wrote:

Yes it's quite strange. Still, I would prefer to not make this change right
now because we're between RC and release, and this has been broken for
years now anyway.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HaxeFoundation/haxe/pull/5373#issuecomment-225844045>,
or mute the thread
<https://github.com/notifications/unsubscribe/AC-3KGQAsPRYpL9lRrZneNhaTf8SzRJ4ks5qLoTMgaJpZM4I1FhV>
.

**Comment by sebthom** [comment]
Would this fix break the expected behavior in case of un-matched optional groups?

```haxe
class Test {
    static function main() {
        var pattern = ~/(dog)(cat)?/g;  // defines 1 mandatory and 1 optional group
        pattern.match("dog");
        trace(pattern.matched(1));  // returns "dog" as group 1
        trace(pattern.matched(2));  // should return an empty string because of optional group 2
        trace(pattern.matched(3));  // should throw an exception because of non-existing group 3 BUT currently returns null
    }
}
```

**Comment by Simn** [comment]
@RealyUniqueName: Could you check this?

**Comment by RealyUniqueName** [comment]
I've rechecked and the comment is correct. This PR cannot be merged.

**Pull request closed without merging**
