### PR TITLE
Error Format change

### PR DESCRIPTION
**Pull request by ncannasse**
Use one-based error format, add -D old-error-format to keep zero-based behavior

### CODE REVIEW

**Comment by back2dos** [comment]
Stupid question, but doesn't this mess up error positions in about every IDE out there?

**Comment by RealyUniqueName** [comment]
Isn't it better to leave old behavior by default and enable new one via define?

**Comment by Neverbirth** [comment]
Agreed with @RealyUniqueName

**Comment by nadako** [comment]
It's gonna fix some positions and probably break some other, but it's haxe 4 which already breaks column numbers because of utf8-lexer, so i think it's fine for a major release.

**Comment by back2dos** [comment]
@nadako To be perfectly honest, I must admit that I am biased against the change, because it was introduced without prior warning, subsequent notification or any attempts to fix [the tests it broke](https://travis-ci.org/HaxeFoundation/haxe/jobs/246231162#L1433). With that in mind, I still don't accept your argument:

1. It will most certainly not *fix* anything, because it merely shifts columns by 1
2. The utf8-lexer only changes position if you have non-ascii chars in your source files

But I suspect I'm once again talking against a wall here. If someone could just please clean up Nicolas' mess and fix the tests, I would very much appreciate that. Thank you.

**Comment by Simn** [comment]
> It will most certainly not fix anything, because it merely shifts columns by 1

It does fix https://github.com/vshaxe/vshaxe/issues/134.

> The utf8-lexer only changes position if you have non-ascii chars in your source files

Which still means IDEs have to adapt. We actually do have quite a few Russian and CJK users.

> If someone could just please clean up Nicolas' mess and fix the tests, I would very much appreciate that.

Done!

**Pull request merged**
