### PR TITLE
Add `TypeTools.resolveTypeParameters`

### PR DESCRIPTION
**Pull request by SomeRanDev**
Function to help prevent user created `haxe.macro.Type`s from crashing the compiler as described in #10959

### CODE REVIEW

**Comment by Aurel300** [comment]
I'm not sure I understand the value of filling in type parameters. What is the use case? Wouldn't such a `Type` be invalid anywhere except within the class/type that declared the original type parameters anyway?

**Comment by Simn** [comment]
I was having the same thought, and this also isn't exactly what I'd expect a "validate" function to do.

**Comment by SomeRanDev** [comment]
Ahh, that's fair. Was so focused on blocking the original error didn't think about the other implications this could cause. In retrospect, this would make more sense as a function that returns a Bool (returns true if type params make sense) rather than a modified Type. Lemme try that instead.

**Comment by SomeRanDev** [comment]
How's this? Renamed to `resolveTypeParams` and now takes a callback that is called for each missing type parameter. The return value fills the missing type parameter, similar to how the map func works.

**Comment by Simn** [comment]
These are fantastic tests, I wish every PR was like that!

As for the function itself, I'm slightly worried that this is turning into something quite specific, so I'd like to hear some other opinions. It's a useful function for sure, I'm just not entirely sure if it should live in the standard library. But that's sometimes not easy to judge!

Alternatively, you could bribe me into merging anything you want if you write a full C# target as a demo for reflaxe. :D

**Comment by kLabz** [comment]
I'm not sure if I would have a use for it either, but I write less macros nowadays. Maybe @back2dos would have an opinion on this?

**Comment by back2dos** [comment]
Personally, I don't have much use for this. Then again it's unopinionated, small and doesn't look like it'll require any maintenance moving forward, so we might as well merge it, no? ^^

**Comment by SomeRanDev** [comment]
Haha, glad you found the tests helpful! No hard feelings if it doesn't make the cut, things have strayed pretty far from the original problem and there's probably only a tiny bit of people who work with `Type`s as much as I do in macros. 😅

@Simn 👀👀I'll hold you to that. Not this pr, but if we could get the next one to happen (one last lil tweak to make custom targets nicer), I'll 100% have a decent C# target prototype you can point the mob to on Haxe 5 release day. 😏

**Comment by Simn** [comment]
Well, I'm sold!

**Pull request merged**
