### PR TITLE
[display] add dependents to server/module

### PR DESCRIPTION
**Pull request by kLabz**
Not sure about passing `cc` like that, should I do it some other way?

### CODE REVIEW

**Comment by Simn** [comment]
Why do we need `cc#get_modules` here? The `module_def` is already in `m_deps`.

**Comment by kLabz** [comment]
In `m_deps` we get modules that the current module depends on, while here we want modules that depend on current module. I don't think such a relation is stored atm so I had to browse other modules of current context and look for modules that have current module in their `m_deps`.

**Comment by Simn** [comment]
Ah right, it's that direction. This is a module * module operation so this could get somewhat expensive in large codebases. It might be a good idea to only generate this if we actually want it, i.e. for the server inspection. This should be pretty easy to configure because we pass that `ctx` around.

**Comment by kLabz** [comment]
Isn't `server/module` only used for server inspection?

**Comment by Simn** [comment]
I thought `generate_module` would be used for other JSON-based generation, but yeah it's only called from there at the moment... which makes sense because we now need that `cc`. Which actually makes me wonder if this is a good design, I think we should still be able to call that function without having access to a cache.

On the other hand, we can worry about that if the need arises. So I'm fine with going ahead like this for now!

**Pull request merged**
