### PR TITLE
Building a macro inside of a macro

### LINKED ISSUE #6156: autoBuild static macro function
Create static macro function not works in autoBuild:

```haxe
#if !macro @:remove @:autoBuild(ObjectImpl.build()) #end
extern interface Object {}
 
class ObjectImpl {
#if macro
   
    public static function build() {
        var fields = Context.getBuildFields();
       
        fields.push({
            name: 'test',
            access: [Access.APublic, Access.AStatic, Access.AMacro],
            kind: FFun({
                args: [],
                expr: macro {
//                        return macro {
//			        trace('hello world');
//		        };
                },
                params: [],
                ret: null
              }),
            pos: Context.currentPos()
        });
       
        return fields;
    }
#end
}

class Test implements Object {
	public static macro function hi() {
		return macro {
			trace('hello world');
		};
	}
}
 
// Error Message: Method test not found on class Test
class Main  {
    public static function main() {
        Test.hi();
        Test.test();
    }
}
```

Also this:
```haxe
//                        return macro {
//			        trace('hello world'); // <- Unknown identifier : __mk_pos__
//		        };
```

Not works: Unknown identifier : __mk_pos__

I think is it not a bug, i think haxe don't support something like this.
I'm right?

### LINKED ISSUE #9080: eval code leaked into source code via macros
I'm running into an issue where eval-related identifiers seem to be inserted into the target output.
This isn't a critical issue, since the haxe code itself is invalid.  However, the compiler doesn't complain and generates invalid target code instead, which can cause a bit of confusion to sort out.

E.g., given:

```haxe
import haxe.macro.Expr;
class Foo {
    macro public static function macroFunc(enm : Expr) : Expr {
        return macro function() {
            return macro null;
        };
    }
}
```

and the following use case:

```haxe
class Main {
    static function main(){
        var foo = Foo.macroFunc(Page);
  }
}
```

(with Lua target)

I get the following error:

```
lua: out.lua|399 info| unexpected symbol near '$'
```

The culprit is an identifier called `$__mk_pos__` that gets inserted into the output.  That isn't generated in genlua, but I found a few places in `evalJit.ml` and `reification.ml` where it is referenced.

Here's the generated code showing the mk_pos call:

```lua
...
Main.main = function() 
  local foo = function() 
    do return _hx_o({__fields__={expr=true,pos=true},expr=__haxe_macro_ExprDef.EConst(__haxe_macro_Constant.CIdent("null")),pos=$__mk_pos__("Foo.hx", 159, 163)}) end;
  end;
  local param_parser = nil;
end
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #6156
Fixes #9080 

@simn Is it a correct approach: https://github.com/HaxeFoundation/haxe/issues/6156#issuecomment-504168907 ?

### CODE REVIEW

**Comment by Simn** [comment]
Please update the branch.

Also please don't use `serror`. I think what we should do here is parse it and _then_ error, by using `syntax_error`. This way the parser doesn't completely die, which yields better diagnostics results.

**Comment by nadako** [comment]
Please update the branch :)

**Comment by RealyUniqueName** [comment]
Apparently we can't just ban nested macro reification, because we already use it in tests: 
https://github.com/HaxeFoundation/haxe/blob/c79046aee5ba2f18ee9ff868fd225e106fa02f32/tests/unit/src/unit/issues/misc/Issue3183Macro.hx#L73-L76

**Comment by Simn** [comment]
Closing due to conflicts, #9080 remains open.

**Pull request closed without merging**
