### PR TITLE
Flesh out + test sys.net.Socket on all sys targets

### PR DESCRIPTION
**Pull request by bendmorris**
Edit: expanding scope to fix issues on multiple targets, work in progress

- [x] Neko
- [x] PHP: passing but needs SSLSocket replacement
- [x] C++: ~`read()` returns `"[97, 98, 99]"` instead of `"abc"`~
- [ ] Java: `waitForRead`, `setBlocking`, `select` not implemented
- [x] C#: ~`select` not implemented~
- [x] Python
- [x] Lua: `bin/unit.lua:28717: attempt to index global 'sys' (a nil value) in unit.TestSpecification.testSocket_unit_hx`
- [x] HL
- [x] Eval

### CODE REVIEW

**Comment by bendmorris** [comment]
C# should be pretty straightforward, and I have this mostly working with Java nio, but what a pain... If anyone wants to look at eval/lua feel free 😅

**Comment by jdonaldson** [comment]
I'll pick up lua, thanks!

**Comment by Simn** [comment]
I'll take a look at eval.

**Comment by Simn** [comment]
Eval fixed

**Comment by jdonaldson** [comment]
I added the lua implementation here.  Although it looks like opam is refusing to update itself on travis.

**Comment by jdonaldson** [comment]
Tests are passing for all targets except Java now.  Paging Dr. @waneck.

**Comment by jdonaldson** [comment]
Also, consider splitting off the php ssl impl to a separate issue.

**Comment by bendmorris** [comment]
Temporarily disabling most of the Socket test for Java until it's fully implemented for that target.

I added a `php.net.Socket` which is a copy of the old `sys.net.Socket`. PHP's `SslSocket` now extends and returns these instead of the new fleshed out `sys.net.Socket`, because supporting SSL in the new Socket would be nontrivial.

**Comment by Simn** [comment]
I don't think anyone around here cares much about commits and authors. 

Anyway, I'm fine with merging this as soon as the CI is green. So probably next week...

**Comment by bendmorris** [comment]
Looks like we are cleared for landing :airplane:

**Pull request merged**
