### PR TITLE
[js] Use "let" for ES6 mode

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Variables declared with "let":
* don't pollute debugger with local variables from other branches (#9035)
* have separate scope for each loop iteration, which allows to avoid closure wrapping

### CODE REVIEW

**Comment by nadako** [comment]
I'm curious to see some benchmarks with this change. I remember back in the days there were some concerns against using `let` because of excessive scope object... allocations? (also with loops) But it might be obsolete.

UPDATE: Looks like it was some V8 issue years ago and we can safely ignore it: https://stackoverflow.com/questions/40449494/why-is-using-let-inside-a-for-loop-so-slow-on-chrome (we don't generate JS `for` anyway for now).

**Comment by nadako** [comment]
> * don't pollute debugger with local variables from other branches

Can we also teach local var renamer to consider js scoping rules and not add counters in this case?

**Comment by RealyUniqueName** [comment]
> Can we also teach local var renamer to consider js scoping rules and not add counters in this case?

I'm working on a more generic version so that it won't rename even if `let` is not available. However I'm still not sure it will work out. In case of failure I'll resort to avoid renaming with `let` only.

**Comment by RealyUniqueName** [comment]
> I'm curious to see some benchmarks with this change.

I've tried these primitive tests with NodeJS:
* no var capturing in closures
```haxe
var cb = [for(i in 0...cnt) null];
Timer.measure(() -> {
	for(i in 0...cnt) {
		cb[i] = i;
	}
});
```
* with var capturing
```haxe
var cb = [for(i in 0...cnt) null];
Timer.measure(() -> {
	for(i in 0...cnt) {
		cb[i] = () -> i;
	}
});
```
The former showed same numbers for `let` and `var`, while the latter  was ~1.5 times faster with `let` (obviously because of no wrapping with auto-generated closures)

**Comment by RealyUniqueName** [comment]
I think this is ready for review.

**Pull request merged**
