### PR TITLE
faster join implementation

### PR DESCRIPTION
**Pull request by malublu**
not check everytime if its the first (last) element.

### CODE REVIEW

**Comment by Simn** [comment]
That looks like it would not work correctly for empty arrays.

**Comment by malublu** [comment]
ah okay yes. thanks for the information.

**Comment by ncannasse** [comment]
Did you benchmark it ?
An additional equality test will not result in any speedup compared to the time it takes to build the buffer and convert the value to String.

**Comment by malublu** [comment]
First of all, it is logical, that is it faster.
But here the jsperf test that i created for you:
https://jsperf.com/arrayjoin-fastes-impl

**Comment by ncannasse** [comment]
There seems to be a problem in your JSPerf, you need to store this.length in a tmp var for all cases, that's what Haxe does when you do `for( i in 0...length )` (it does not evaluate length each loop)

**Comment by malublu** [comment]
first of all it does not depends for the performance test, because i only check how to use the loop.
Also for all cases they are the same conditions.

but i already cached the length, if you are looking in the setup function.

 Benchmark.prototype.setup = function() {
    var words = [], i, **length = 100000**

the last implementation in jsperf ("calculate to and add behind").
I that what i implemented and it is the fastest,
because the **if** is not used in the loop and not check every time if it the first or last value on each iteration.

**Comment by jdonaldson** [comment]
you're performing raw string concatenation here, which different targets optimize for differently.   You probably need to just worry about adding to a stringbuf container here.  Also, I know that certain jits (java, node, c#) can have priming effects (i.e. later tests run faster). 

Once all that is sorted, we'd need a good test across all the platforms.

**Comment by malublu** [comment]
yes you are right. but for that, i need help or more time.
so lets open the pull request and reorder the informations.
Hl:
```

```
Java:
```

```
Cs:
```

```
Neko:
```

```

**Comment by jdonaldson** [comment]
I appreciate your interest here, but I wasn't seeing any strong evidence that there was much room for improvement.  Until I see better evidence, I don't feel particularly motivated to put in all the effort required to vet this out.  I think others feel the same.

**Comment by back2dos** [comment]
Generally speaking I think if you want maximum performance, you should not be using join, because it relies on runtime string conversion of the individual elements. There's probably far more to be gained from dealing with #5440 and thus creating a portable basis for efficient string concatenation.

**Comment by malublu** [comment]
@back2dos thank you for the information about the stringbuffer.
@jdonaldson also thank you

**Pull request closed without merging**
