### PR TITLE
Move warning list to prebuild

### PR DESCRIPTION
**Pull request by Simn**
This uses a nice JSON file for warnings and generates the required OCaml types and functions from it. Also, we now support identifiers for enabling and disabling warnings, so you can do `haxe -w -WDeprecated` and `@:haxe.warning("-WDeprecated")`. I figured that this is nicer to work with than random numbers.

In that context, I've also changed the warning output to include that identifier, so now we get something like `Warning : (WDeprecated) Usage of this typedef is deprecated`. This makes it easy to figure out how to disable a warning. If anyone has a particular preference for how to format this message, let me know.

### CODE REVIEW

**Comment by kLabz** [comment]
Can `@:haxe.warning` be used on any "level"? (type / field / expression)

As for the new warning output, I like that change but maybe some would like it not to be included? (with a define enabling or disabling it, depending on what the default behavior would be)

**Comment by Simn** [comment]
> Can @:haxe.warning be used on any "level"? (type / field / expression)

It works at type and field level. Expression-level is too messy to get right and IMO not worth it.

> As for the new warning output, I like that change but maybe some would like it not to be included? (with a define enabling or disabling it, depending on what the default behavior would be)

Meh, you usually want to either fix the warning or hide it. Wanting to see a warning in a specific style seems like a really niche fetish.

**Comment by Aurel300** [comment]
I see the warnings still have a code defined in the JSON: is it possible to still use range syntax to disable a bunch of (probably related) warnings at once? If so, then the compiler should output both the identifier and the code for the warning.

**Comment by kLabz** [comment]
> Meh, you usually want to either fix the warning or hide it. Wanting to see a warning in a specific style seems like a really niche fetish.

The use case I was thinking about was more like:

* disable it pretty much all the time because then I don't care about the codes
* enable it only when I want to see some warning codes so I can easily configure those warnings

(but I agree this is not really important)

**Comment by Simn** [comment]
We do support `-w -123...456`, but I'm not sure how useful this actually is because it would require keeping related warnings close together, which seems difficult to do in a future-proof way. I really don't want to worry about what exact number I'm using for each new warning...

But while typing this I just had the idea to give each warning an optional parent warning. That way we get a nice tree and you can disable an entire group at once.

**Comment by Simn** [comment]
Ok, I've realized that this isn't the 80s and removed the notion of numeric codes completely. We now work with warning identifiers exclusively, and they are defined as a tree. This also automatically gave us `WAll` as the root of the tree and thus the way to disable all warnings.

I think this is much cleaner and easier to discover.

**Pull request merged**
