### PR TITLE
Strictness levels for null safety

### LINKED ISSUE #7723: [nullsafety] false-positive error for field access
```haxe
@:safety
class Main {
	static function main() {
		var s:{?f:Int} = {};

		if (s.f != null) {
			f(s.f); // error!
		}
	}

	static function f(v:Int) {}
}
```

This gives:
```
src/Main.hx:7: characters 6-9 : Safety: Cannot pass nullable value to not-nullable argument "v" of function "f".
```

It's currently a [known limitation](https://github.com/RealyUniqueName/Safety#limitations), but I think we can make it work for physical field access as long as there's no _impure_ operations between the null check and the access. Note that there can be a case when we read the field twice - first time right after null check, and the second one after some impure call - we should allow first and complain about the second one.

### LINKED ISSUE #7745: Null safety strictness levels
Something like 
```
--macro nullSafety("pack", Weak)
```
For TypeScript-like null safety.

And
```
--macro nullSafety("pack", Strict)
```
For Kotlin level of strictness.

Rough example to showcase the difference:
```haxe
function example(o:{field:Null<String>}) {
  if(o.field != null) {
    mutate(o);
    var notNullable:String = o.f;
  }
}

function mutate(o:{field:Null<String>}) {
  o.field = null;
}
```
The `Weak` null safety would not complain about such code, while the `Strict` one will emit an error on `var notNullable:String = o.f;` because `o.f` could be changed to `null` in `mutate(o)` call.

If different modes are used in the same build, a warning should be emitted and the least strict mode used.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Replaces `@:nullSafety` and `@:nullSafety(false)` with `@:nullSafety(Strict)`, `@:nullSafety(Loose)` and `@:nullSafety(Off)`. If no argument is provided then `Loose` is implied.
```haxe
enum abstract NullSafetyMode(String) to String {
	/**
		Disable null safety.
	**/
	var Off;
	/**
		Full scale null safety.
	**/
	var Strict;
	/**
		Loose safety.
		If an expression is checked ` != null`, then it's considered safe even if it could be modified after the check.
		E.g.
		```
		function example(o:{field:Null<String>}) {
			if(o.field != null) {
				mutate(o);
				var notNullable:String = o.field; //no error
			}
		}

		function mutate(o:{field:Null<String>}) {
			o.field = null;
		}
		```
	**/
	var Loose;
}
```

closes #7745 
closes #7723 in "Loose" mode.

### CODE REVIEW

**Comment by nadako** [comment]
Looks good, great job! 😍 I have just one question. That C# article was mentioning the case when the mutation is "obvious", like below. Do we also handle that?
```haxe
if (o.field != null) {
  o = getNewO();
  trace(o.field);
}
```

**Comment by RealyUniqueName** [comment]
Yes, we do:
https://github.com/HaxeFoundation/haxe/blob/277afef9bc7cb7bae12efa5e420e5346a5fe1b7b/tests/nullsafety/src/cases/TestWeak.hx#L34-L39

**Comment by Simn** [comment]
`Weak` sounds quite judgmental here. Can we just call it `Default`?

**Comment by RealyUniqueName** [comment]
I don't like `Default` here, because unlike `Off` and `Strict` it doesn't reflect semantics.

**Comment by RealyUniqueName** [comment]
Maybe `Loose`?

**Comment by RealyUniqueName** [comment]
Also calling it `Default` won't let us switch the default to `Strict` if we ever want it :)

**Comment by Simn** [comment]
It's hard to reflect semantics with just one word anyway, and when put in context between `Off` and `Strict`, the semantics are pretty much implied.

> Also calling it `Default` won't let us switch the default to `Strict` if we ever want it :)

That's a better point. Not sure then, hmm...

**Comment by RealyUniqueName** [comment]
`Normal`?

**Comment by back2dos** [comment]
It should either be `Strict | Loose` or `Strong | Weak` or `Paranoid | Gullible`, but not a mix of different spectra. And I think the first is best, because it's pretty much to the point, without being judgmental.

**Comment by nadako** [comment]
I also think `Strict` and `Loose` are accurate and nicely worded

**Comment by RealyUniqueName** [comment]
Changed to `Strict`/`Loose`/`Off`

**Pull request merged**
