### PR TITLE
adds warning when comparing methods (not to null)

### PR DESCRIPTION
**Pull request by ncannasse**
Requesting for comment before merging.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Please don't. Or make it an opt-in or make it only for targets where direct compariosn does not work. 
Most targets can compare methods directly. Others (like php :) ) should aim to implement direct methods comparison.
I can imagine developer will not want to use `Reflect.compareMethods()` (extra code, performance hit) because of targets one does not use.
It will be super annoying. Also it does not cover all cases. E.g. `Array.indexOf`.

**Comment by Simn** [comment]
How about `pf_supports_method_equality`?

**Comment by ncannasse** [comment]
It that a thing already or a suggestion?

**Comment by Simn** [comment]
A suggestion

**Comment by ncannasse** [comment]
I'm fine with @Simn suggestion

**Comment by Simn** [comment]
Not 4.0-critical

**Comment by ncannasse** [comment]
Putting it back, as it might generate several warnings when transition from Haxe 3.x to Haxe 4. Also, it's very small patch and there's already `pf_supports_function_equality` flag in platform config, although it remains to set which platforms supports it or not + some unit test if they do.

**Comment by Simn** [comment]
Results of my tests:

* **hl**, **cs** and **java** fail the `staticFunction == staticFunction` check
* **js**, **php**, **flash**, **as3**, **python**, **lua**, **cpp** say `memberFunction == memberFunction`, other targets disagree

We should fix the `staticFunction` situation. And I guess we set the flag to true for the targets that think `memberFunction != memberFunction`?

**Comment by Simn** [comment]
Closing in favor of #7441.

**Pull request closed without merging**
