### PR TITLE
fix conversion of STimeStamp to Date, fix conversion String like types (...

### PR DESCRIPTION
**Pull request by frabbit**
...e.g.STinyText) to String instead of Bytes

### CODE REVIEW

**Comment by frabbit** [comment]
in one project, this fixed conversion problems for me. It would be nice if some php users can review this fix @fponticelli @mockey

**Comment by frabbit** [comment]
@RealyUniqueName what is your opinion on this patch.

**Comment by frabbit** [comment]
ping @tml

**Comment by tml** [comment]
:+1:

**Comment by frabbit** [comment]
thx!

**Comment by RealyUniqueName** [comment]
Me? Why me? )
 
Anyway i had no issues converting `Date` to `STimestamp`. AFAIR i still had no need in backwards convertion.

**Comment by frabbit** [comment]
@RealyUniqueName sorry that was actually a mistake, i thought you use haxe/php a lot ;)

**Comment by frabbit** [comment]
@mockey would be nice if you could test this with your code base, i will leave this open until you tested it.

**Comment by mockey** [comment]
I dont' have any haxe-php code that uses PDO actually, so can't really test, but your changes look reasonable to me. Is there a unit test for this?

**Comment by frabbit** [comment]
yes we have:
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/MySpodClass.hx
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/TestSpod.hx

would be nice if someone could add some more, i don't have the time atm.

**Comment by frabbit** [comment]
i added another PDO fix for STinyInt (stored as tinyint(4)) which becomes Bool after PDO conversion, any complains @mockey @tml ?

**Comment by frabbit** [comment]
@fponticelli are you fine?

**Comment by fponticelli** [comment]
No complains here.

Il giorno gio 12 mar 2015 alle ore 01:58 frabbit <notifications@github.com>
ha scritto:

**Pull request merged**
