### PR TITLE
Add interface tests

### PR DESCRIPTION
**Pull request by Simn**
We totally forgot about this... opening a PR to see where we're at.

### CODE REVIEW

**Comment by ncannasse** [comment]
Seems like hxcpp is missing Std.is(interface,Interface) (ping @hughsando), and there's some compilation error in Java (ping @waneck)

**Comment by Simn** [comment]
Lua fails as well:

```
Command exited with 0 in 3s: haxe [compile-lua.hxml,-D,travis]
Command: lua [bin/unit.lua]
Test.hx:294: Generated at: 2016-04-09 09:40:27
Test.hx:296: START
TestInterface.hx:53: false should be true
TestInterface.hx:54: false should be true
Test.hx:272: ABORTED : Cannot cast { y : 5, x : 1.3 } to { __name__ : { 1 : unit, 2 : _TestInterface, 3 : IX }, new : {} } in unit.TestInterface.test
Test.hx:275: STACK :
Test.hx:221: DONE [6712 tests]
Test.hx:222: SUCCESS: false
```

@jdonaldson

**Comment by Simn** [comment]
On the bright side hxcpp passes now.

**Comment by jdonaldson** [comment]
Lua's Std.is for inheritance checks had some problems.  The necessary metadata for an instance was not getting preserved in some cases.  I fixed that in the development branch, and also added the logic for inheritance as well.
https://github.com/HaxeFoundation/haxe/commit/5c7189a78f96ec12e4398c67cb1b87d4c070585a

**Comment by Simn** [comment]
Thanks!

Just Java remaining then @waneck.

**Comment by nadako** [comment]
I just rebased this one on latest development.

**Comment by nadako** [comment]
Rebased it on development again. Could we do something with this already? @waneck

**Comment by ncannasse** [comment]
I agree that it would be nice to merge, please @waneck , just a (hopefully small) java fix :-)

**Comment by frabbit** [comment]
@waneck is this relevant for 3.3 or should we postpone this issue?

**Comment by vizanto** [comment]
The Java test doesn't fail on actual interface checking, but name collision with another Point class?

```
src/unit/_TestInterface/Point.java:7: error: Point is not abstract and does not override abstract method getY() in IY
public class Point extends haxe.lang.HxObject implements unit._TestInterface.IY, unit._TestInterface.IX
       ^
src/unit/_TestInterface/Point.java:55: error: getY() in Point cannot implement getY() in IY
	public int getY()
	           ^
  return type int is not compatible with double
Note: Some input files use or override a deprecated API.
```

**Comment by Simn** [comment]
I would like to see this PR fixed/merged.

**Comment by ncannasse** [comment]
I've resolved the conflicts, are all Test* files added by macro now ? if not TestInterface needs to be added where it should

**Comment by Simn** [comment]
Turns out that if we actually add the tests and don't just ignore them, they still fail.

Java:

```
src/unit/_TestInterface/Point.java:7: error: Point is not abstract and does not override abstract method getY() in IY
public class Point extends haxe.lang.HxObject implements unit._TestInterface.IY, unit._TestInterface.IX
       ^
src/unit/_TestInterface/Point.java:41: error: getY() in Point cannot implement getY() in IY
	public int getY()
```

So we're back to where we started.

**Comment by Simn** [comment]
hxcpp is failing creatively as well:

```
TestInterface.hx:66: 2.47032822920623e-323 should be 5
```

**Comment by Simn** [comment]
I have updated again and now only Java fails.

**Comment by Simn** [comment]
I have added these tests with a `#if !java` for now so we don't forget about them again.

**Pull request closed without merging**
