### PR TITLE
[lua] Share metatables with other class instances

### PR DESCRIPTION
**Pull request by Frixuu**
When a constructor is called on the Lua target, at least three tables get created:

1. a table for the object itself,
2. a table for storing existing object fields for reflection purposes,
3. _a metatable for the object._

This PR gets rid of the third table allocation by using one shared metatable per class.

While I'd assume this would not be a breaking change for most projects, for example the unit tests are all still green, it is still an observable behavior in a current version and someone might depend on it. **As such, it is probably best not to backport it to 4.3.x.**

Since the metatable has to be stored _somewhere_, enabling this feature adds about 2-3% to the output file size. The performance benefits are dependent on the scenario, for example (on my machine, WSL2, low-end Zen1):

- [the test suite](https://github.com/HaxeFoundation/haxe/tree/2eb7724a3139f66bcb1b5a132e9b0e9c663d8c96/tests/unit) (typical case?) ran ~3-5% faster (both PUC Lua and LuaJIT)
- [the Mandelbrot benchmark](https://github.com/HaxeBenchmarks/benchmark-runner/blob/925b72dfce557931f1913c79bf02f0e8aaa2a522/cases/mandelbrot/BMMandelbrotCode.hx) (classes, no `reduce_allocs` - corner case) ran ~45% faster (LuaJIT)

### CODE REVIEW

**Comment by Simn** [comment]
Without really knowing anything about lua, this really seems like it should be the default...

**Comment by Frixuu** [comment]
Okay, since we're on 5.0 nightly already now, I guess this doesn't need to be hidden behind a define anymore?

Also, after consideration, I've decided not to make a built-in way to opt out per class - consumers can just do a shallow copy of the metatable in the factory method or whatever

**Comment by Simn** [comment]
Should I merge this or are there any problems here?

**Comment by Frixuu** [comment]
Rebased and everything still passes; if you believe this to be valuable enough, go ahead!

**Comment by Simn** [comment]
Thanks!

**Pull request merged**
