### PR TITLE
Allow structs as generic type params

### LINKED ISSUE #3697: Build failure if @:generic is used with type parameter that is a structure created with typedef
Sample (online sample http://try.haxe.org/#94cbB)

``` Haxe
// Haxe version is 3.1.3

typedef AType = 
{
    a:Int
}
@:generic
class GenericTest<AType>
{
    public function new() {}
}
class Test {
    static function main() {
        var aType:AType = { a:0 };
        var genTest1:GenericTest<AType> = new GenericTest<AType>();
    }
}
```

Error

``` Code
Build failure
Test.hx:13: characters 36-60 : Type parameter must be a class or enum instance (found { a : Int })
```

Without `@:generic` all builds fine. 

Is it a bug or a feature?

### PR DESCRIPTION
**Pull request by bendmorris**
Fixes #3697 

This was surprisingly straightforward, maybe I'm missing something?

### CODE REVIEW

**Comment by andyli** [comment]
The TravisCI `opam update` error seems unrelated to this PR, but somehow it reproduces when I restart the build, but not for the builds of other commits... Anyway, I've added a potential fix in development, would you rebase/merge?

**Comment by Simn** [comment]
I wonder if we should hash the field/type string. These names can get very long very fast...

**Comment by bendmorris** [comment]
They can. Generic functions already have a similar problem, maybe those should be tackled together. Some people are certainly relying on the naming convention though (I know I am, as well as the unit tests...) even if they shouldn't be.

**Comment by Simn** [comment]
I'll merge this now, we can look into the naming details later.

**Pull request merged**
