### PR TITLE
change ipv6 first,ipv4 second.

### PR DESCRIPTION
**Pull request by hpgood**
fix bug: use ipv4  network ,change to ipv6,and the network will cache the ipv4 dns info. test with mac min (net64 wifi).

### CODE REVIEW

**Comment by starburst997** [comment]
I was able to get IPv6 (iOS and native targets) working with this PR, thanks!

**Comment by Simn** [comment]
@hughsando: Could you check this? Looks pretty straightforward.

**Comment by hughsando** [comment]
I don't know if this is the best on all systems.
It seems to be required for some ios tests, but I'm not sure whether it's going to introduce time-out delays on other systems.  Or have the reverse dns caching issues with ipv4?  I don't even really know how to test this.
I guess we could just merge and see if anyone reports any issues.

**Comment by starburst997** [comment]
If you want to test IPv6, you can follow this [guide](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16), requires a Mac computer, they have an hidden option to create a IPv6 local wifi network complete with internet connectivity.

**Comment by hughsando** [comment]
I am happy enough to take your word that this fixes the network in your situation.
But I'm not sure how to test for the reverse case where this change affects all the other possible situations.

**Comment by Simn** [comment]
I'm not sure what to do here because I share @hughsando's concerns.

**Comment by Simn** [comment]
Closing this in favor of the upcoming asys API.

**Pull request closed without merging**
