### PR TITLE
[js] move typed array classes from js.html to js.lib

### PR DESCRIPTION
**Pull request by Gama11**
As mentioned in #7390 and #6586. I expect that this requires an update to the js.html externs generator. For now I've just done a find-and-replace.

This opens the possibility of forbidding access to the `js.html` package when using hxnodejs, which should improve the code completion experience and performance.

### CODE REVIEW

**Comment by haxiomic** [comment]
Awesome, thanks @Gama11! I'll apply this to the externs generator after this merges

**Review by haxiomic — APPROVED** [review]

**Comment by Simn** [comment]
Nice!

**Comment by Simn** [comment]
@nadako: If you approve this I'm fine with merging.

**Comment by nadako** [comment]
Yeah I'm fine with that

**Pull request merged**
