### PR TITLE
[php] Add externs for `SplFileInfo` and `SplFileObject` classes + some SPL iterators

### PR DESCRIPTION
**Pull request by cedx**

### CODE REVIEW

**Comment by cedx** [comment]
Hmmm.... the Linux build fails because `RecursiveDirectoryIterator.hasChildren(allowLinks)` has a different signature from `RecursiveIterator.hasChildren()`.

@RealyUniqueName What is the best way to resolve this issue?

**Comment by cedx** [comment]
I've looked at all core PHP classes that implement `RecursiveIterator`, and `RecursiveDirectoryIterator` is the only one that has an optional parameter in its `hasChildren()` method.

I wonder what is better: remove the `allowLinks: Bool` parameter, or change the signature of `RecursiveIterator.hasChildren()` to `hasChildren(args: Rest<Any>)` and all its implementing classes...

**Comment by RealyUniqueName** [comment]
I think the best solution is to add `@:overload` with an argument to `RecursiveDirectoryIterator`

**Comment by cedx** [comment]
Of course 🤦‍♂️ 
Done @RealyUniqueName

**Pull request merged**
