### PR TITLE
Fix licensing

### PR DESCRIPTION
**Pull request by Maniues**
Split licenses to directory-based licensing to precise what files are under GPL or MIT.

### CODE REVIEW

**Comment by Maniues** [comment]
@ncannasse @Simn

**Comment by Simn** [comment]
I don't know if we want to assert that _all_ other files are part of the Haxe compiler. I don't think you typically declare a tests directory as part of a compiler, and the libs directory is another situation entirely.

But I'm fine with clarifying that the Haxe standard library refers to std in particular.

**Comment by Maniues** [comment]
> I don't know if we want to assert that _all_ other files are part of the Haxe compiler. I don't think you typically declare a tests directory as part of a compiler, and the libs directory is another situation entirely.
> 
> But I'm fine with clarifying that the Haxe standard library refers to std in particular.

It's hard for me to tell later if the files included in the tests are GPL or not. Same for all files in the top directory

**Comment by Maniues** [comment]
And there can be exception for particular directories like `libs`

**Comment by Maniues** [comment]
@Simn like these files:
- extra/
- src-prebuild/
- src/ files without header
- plugins/example (there should be MIT)
- tests/
- config files in .github, .devcontainer, .vscode?
- files in top-level directory:
top-level files

**Comment by Maniues** [comment]
@Simn what do you think about that?

**Comment by Simn** [comment]
To be honest I don't understand what you're saying. You mention that there can be exceptions, but the change in this PR doesn't seem to make exceptions and says "all other files".

**Comment by Maniues** [comment]
I haven't done this yet, I will add it in a few minutes.

I just want to make sure it is okay.

**Comment by Maniues** [comment]
@Simn What about now?

**Comment by Simn** [comment]
I like that "If a file does not have a license header" clause, that seems uncomplicated enough.

So I think this is good now, but let me leave this PR open for a few days in case someone who knows about all this stuff happens to pass by!

**Comment by Maniues** [comment]
Okay, thanks

**Comment by Maniues** [comment]
So I think this is good now, but let me leave this PR open for a few days in case someone who knows about all this stuff happens to pass by!

@Simn any updates here?
I really liked Haxe, but these licensing issues here, in `format` repo and in `api.haxe.org`, so I don't know if I can use it under Open Source licenses.

**Pull request merged**
