### PR TITLE
haxe.macro.Type.hx full stops

### PR DESCRIPTION
**Pull request by markknol**

### CODE REVIEW

**Comment by Simn** [comment]
Technically you're only supposed to put full stop after actual sentences. Things like "The name of the type parameter" is not a sentence because it does not have a verb. I don't know if this is different for API documentation.

Maybe there's some guide in the javadoc-world that we could follow?

**Comment by markknol** [comment]
Not sure if dox follows a standard? (at least, markdown isn't very common for docs?)

BTW I would also like to know how to make links to external pages in our api docs.

**Comment by Simn** [comment]
It's not really about Dox because Dox is just a tool. I'm just thinking we should follow some standard for the standard library.

**Comment by Simn** [comment]
Looking at http://www.oracle.com/technetwork/articles/java/index-137868.html they have "Class constructor." as an example so I suppose having full stops is fine.

**Pull request merged**
