### PR TITLE
Set --run args only when we're actually running

### PR DESCRIPTION
**Pull request by Simn**
This changes the behavior of `Sys.args()` to what @tobil4sk suggests in https://github.com/HaxeFoundation/haxe/issues/11087#issuecomment-1917242911.

Doesn't add a test yet because our sys tests require a PHD.

### CODE REVIEW

**Comment by Simn** [comment]
Also, the fact that this doesn't cause any sys test failures is probably concerning...

Edit: Actually it looks like these tests exclusively check `--run`, so it's expected to not break anything there. In that case all we really need to test is that macros don't have the runtime args on any target.

**Comment by tobil4sk** [comment]
> In that case all we really need to test is that macros don't have the runtime args on any target.

Note, the only possible target where runtime args can be available at macro time is eval, because it is always compiled and run together. For other targets, compilation and execution are completely separate, so there is no way the macro could know what cli arguments the generated code will be run with.

Maybe this would make more sense as an eval-specific test.

**Comment by Simn** [comment]
I was thinking of some crazy case where we would leak `com.args` from `--run` to the macro context, but yeah, that doesn't seem like it would be possible.

**Comment by tobil4sk** [comment]
Maybe worth adding a test for `--interp` as well, so we know the compiler flags don't bleed through into runtime.

**Pull request merged**
