### PR TITLE
Move MapEntry to `js.lib.MapEntry` module.

### PR DESCRIPTION
**Pull request by terurou**
Related #8747 and #8754

### CODE REVIEW

**Comment by terurou** [comment]
Should I rename `MapEntry` to either `KeyValue` or other?

**Comment by RealyUniqueName** [comment]
I agree `MapEntry` doesn't  fit now. Maybe `ArrayKeyValue` is a better name, because `KeyValue` is usually an object with `key` and `value` fields.

**Comment by RealyUniqueName** [comment]
Though it looks like array-based key-value is used everywhere in JS API. So `KeyValue` is good too.

**Comment by haxiomic** [comment]
Thanks @terurou, yeah I vote KeyValue too because it seems like a common thing in ES6

**Comment by terurou** [comment]
Thanks for your comments!
I rename `MapEntry` to `KeyValue`.

**Pull request merged**
