### PR TITLE
this is the file I intended to modify

### PR DESCRIPTION
**Pull request by nanjizal**

### CODE REVIEW

**Comment by nanjizal** [comment]
/usr/local/lib/haxe/std/flash/events/KeyboardEvent.hx:10: characters 173-174 : Int should be flash.ui.KeyLocation
Error: Command failed with error 1

Currently I can't document trilateral3 properly because OpenFL fails on this error, Heaps won't even build now it has ListSort error as per other issue.  NME is just full of dox problems :(

https://github.com/nanjizal/trilateral3/
You will notice that with the keyboard change that I am able to get OpenFL to dox, but not the Heaps and NME ones.

https://nanjizal.github.io/trilateral3/pages/trilateral3/target/openfl/index.html

**Comment by nanjizal** [comment]
Sorry for modifying the wrong one originally I got the code working based on latest install locally and modified it on a fork online, I did not realize two classes that looked very similar.

**Comment by nadako** [comment]
This is not the right fix, enums are there exactly to prevent using random integers. Please provide a reproducible example with the failure instead.

**Comment by nanjizal** [comment]
This alternative also works if it is preferable?
```haxe
package flash.events;

extern class KeyboardEvent extends Event {
	@:flash.property var altKey(get,set) : Bool;
	@:flash.property var charCode(get,set) : UInt;
	@:flash.property var ctrlKey(get,set) : Bool;
	@:flash.property var keyCode(get,set) : UInt;
	@:flash.property var keyLocation(get,set) : flash.ui.KeyLocation;
	@:flash.property var shiftKey(get,set) : Bool;
	function new(type : String, bubbles : Bool = true, cancelable : Bool = false, charCodeValue : UInt = 0, keyCodeValue : UInt = 0, keyLocationValue : flash.ui.KeyLocation = flash.ui.KeyLocation.D_PAD, ctrlKeyValue : Bool = false, altKeyValue : Bool = false, shiftKeyValue : Bool = false) : Void;
	private function get_altKey() : Bool;
	private function get_charCode() : UInt;
	private function get_ctrlKey() : Bool;
	private function get_keyCode() : UInt;
	private function get_keyLocation() : flash.ui.KeyLocation;
	private function get_shiftKey() : Bool;
	private function set_altKey(value : Bool) : Bool;
	private function set_charCode(value : UInt) : UInt;
	private function set_ctrlKey(value : Bool) : Bool;
	private function set_keyCode(value : UInt) : UInt;
	private function set_keyLocation(value : flash.ui.KeyLocation) : flash.ui.KeyLocation;
	private function set_shiftKey(value : Bool) : Bool;
	function updateAfterEvent() : Void;
	static final KEY_DOWN : String;
	static final KEY_UP : String;
}
```

**Comment by nanjizal** [comment]
flash.ui.KeyLocation = flash.ui.KeyLocation.D_PAD

**Comment by nanjizal** [comment]
D_PAD is 0 entry

**Comment by nadako** [comment]
> flash.ui.KeyLocation = flash.ui.KeyLocation.D_PAD

Yeah, I think that's better. But I don't understand why it's failing for you. I mean, the `= 0` in the current externs look like it should fail but it doesn't, so I'm curious in which scenarios it does fail.

**Comment by nanjizal** [comment]
Dox generation ( have to remove heaps and nme folders prior to running scripts ).
https://github.com/nanjizal/trilateral3/blob/master/generate.hxml
https://github.com/nanjizal/trilateral3/blob/master/generateDoc.hxml

( dependances as hxml - https://gist.github.com/nanjizal/d98fcf52c66408a541fa7849df662929 )
I am using them with https://github.com/TrilateralX/TrilateralSamples but wip so mainly html5 stuff works, I may need to update them for recent changes.

**Comment by nanjizal** [comment]
So the error is when dox runs, also there is heaps issue mentioned in another issue related to haxe.ds.ListSort

**Comment by nanjizal** [comment]
oh I am 'allow flash' it's needed because openfl remaps 'flash' packages and nme normally does the same so common to use 'flash' namespace, maybe that's why you don't see it easily?

**Comment by nadako** [comment]
> flash.ui.KeyLocation = flash.ui.KeyLocation.D_PAD

Let's just do this.

**Pull request closed without merging**
