### PR TITLE
Added column to StackItem.FilePos (#662)

### PR DESCRIPTION
**Pull request by RealyUniqueName**
This PR adds column to `haxe.CallStack.StackItem.FilePos`. See #6662.
Opinions?

### CODE REVIEW

**Comment by Simn** [comment]
I think we should be able to distinguish actual column 0 from column "I don't know".

**Comment by RealyUniqueName** [comment]
I'll change it to `Null<Int>`.

**Comment by Simn** [comment]
That should be good.

**Comment by RealyUniqueName** [comment]
Done

**Comment by Simn** [comment]
Hmm yeah, I guess that argument should be optional...

**Comment by ncannasse** [comment]
Yes, please optional and simplify the PR (no extra null)

**Comment by RealyUniqueName** [comment]
Done

**Pull request merged**
