### PR TITLE
[dce] keep constructor if any instance field is kept (fixes #6062)

### LINKED ISSUE #6062: DCE removes parent constructor invocation.
```
class Test {
    static function main() {
        var child = Type.createInstance(Child, []);
      	child.childFn(); //this one works.
        child.parentFn();  //Error: parentFn is not a function
    }
}

class Parent {
    public var parentFn = function() {};
    function new() {}
}

class Child extends Parent {
    public var childFn = function() {};
}
```
http://try.haxe.org/#89Df4
Perhaps constructor should never be DCE'd if class is not DCE'd completely.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Addresses #6062

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
@andyli PHP fail on appveyor doesn't look like it's related to this PR. "permission denied" trying to delete `sys/temp/ok.exe`: 
https://ci.appveyor.com/project/HaxeFoundation/haxe/build/1502/job/0erv4eyalo07o1se#L1725

And i doubt my change affects CPP. @hughsando can you take a quick look at this?
https://travis-ci.org/HaxeFoundation/haxe/jobs/290034157#L2194

@Simn I'd like to merge this fix in next 3.4 release when CI will become green.

**Comment by andyli** [comment]
That file deletion problem happens from time to time but no one knows why. I've just restarted AppVeyor and let's see if it will pass now.

**Comment by RealyUniqueName** [comment]
I can add error handling to that test to make it pass "permission denied" without failing.

**Comment by Simn** [comment]
Are you sure the implementation works like that? I'm worried about this particular case:

1. Have a constructor which is the only one accessing `SomeClass.someField`.
2. Have an instance field which is kept.

Your implementation looks like it would keep the constructor, but not actually explore it further to keep `SomeClass.someField`. That's because during the entry-point check, we might not yet see the kept instance field that is kept. It would accept the constructor in step 3, but at that point it doesn't look its expression.

I think the logic should be inverted: If an instance field is determined to be kept (for whatever reason), check if there's a constructor on the class that should also be kept.

**Comment by RealyUniqueName** [comment]
Simn, do you mean in cases like this constructor and a field should be kept?
```haxe
class Test {
    static function main() {
        var child = Type.createInstance(Child, []);
        trace(child);
    }
}

class Parent {
    public var parentFn = function() return true;
    function new() parentFn();
}

class Child extends Parent {}
```
it's a different case. Because in this case we don't know if constructor will ever be used. But in pr we know for sure that constructor is required, because instance field is kept.

**Comment by Simn** [comment]
I'm talking about this:

```
class Test {
    static function main() {
        var c = Type.createInstance(MyClass, []);
        c.iCauseMyClassNewTobeKept();
    }
}

class MyClass {
    function new() {
        OnlyMyClassNewReferencesMe.field;
    }

    function iCauseMyClassNewToBeKept() { }
}

class OnlyMyClassNewReferencesMe {
    static var field = 1;
}
```

**Comment by RealyUniqueName** [comment]
Done

**Pull request merged**
