### PR TITLE
[matcher] fix handling of forward shadowing

### LINKED ISSUE #9627: [matcher] forward shadowing issue
Example:
```haxe
abstract Foo<T>(T) from T to T {
  public var it(get, never): T;
  private inline function get_it() return this;
}

@:forward
abstract Bar({foo: Array<Int>}) from {foo: Array<Int>} to {foo: Array<Int>} {
  public var foo(get, never): Foo<Array<Int>>;
  private inline function get_foo() return this.foo;
}

class Main {
  public static function main() {
    var bar: Bar = {foo: [0]};
    switch (bar) {
      // case {foo: [0]}: trace(1); // expected error - Foo has no field length
      case {foo: {it: [0]}}: trace(1); // unexpected error - Array has no field it
      case _: trace(0);
    }
  }
}
```

Without `@:forward` it works. Seems like matcher can't decide between forwarded property definition and shadowing one.

### PR DESCRIPTION
**Pull request by vonagam**
Closes #9627.

### CODE REVIEW

**Comment by Simn** [comment]
Hmm, this suggests that there are duplicate fields in `known_fields` already, which is probably where this should be fixed instead.

**Comment by Simn** [comment]
This entire section could probably be cleaned up a bit by using a `StringMap` to deal with the duplicates because I don't think the field order actually matters here. But we can do that later, the changes look good to me.

**Comment by vonagam** [comment]
Ok, moved check up, also pushed more verbose variant that touches more than one line, verbose commit can be dropped.

Initially went to original place because `known_fields` were used only there and it was the fastest variant.

**Comment by Simn** [comment]
Oh, just as I commented everything changed again!

**Comment by vonagam** [comment]
It is more verbose variant (also otherwise abstract fields are checked agains each other for name collision too, not big deal though). And can be dropped.

**Comment by Simn** [comment]
I'm fine with the verbose version, though I generally try to avoid `@`.

In the long run I still think that having a `let fields = ref StringMap.empty in` would simplify some things and avoid all these filter and mem operations on lists (which are O(n)). But as I said, we can clean this up later and it's not like the performance difference would be measurable even for the largest of abstracts.

**Comment by nadako** [comment]
@vonagam I've noticed you're doing a lot of contributions to the compiler code lately. If you're interested, we could also add you to the developer Slack workspace, so communication with the team is faster/easier.

**Comment by vonagam** [comment]
Thanks, you can send an invite to email listed on my profile.

**Comment by vonagam** [comment]
Here is a variant with `let fields = ref StringMap.empty in`.

**Comment by Simn** [comment]
Something is failing now:

```
Changing directory to /Users/runner/runners/2.263.0/work/haxe/haxe/tests/server/
Command: haxe [build.hxml]
src/cases/display/issues/Issue9082.hx:26: characters 29-71 : Cannot field-match against Unknown<0>
```

**Comment by vonagam** [comment]
Seems like in this case order actually matters right now. Problematic example is typing of `args` in `DisplayItem`:
https://github.com/HaxeFoundation/haxe/blob/c6dabfcc924fa025ed4908b1916426fe846945c4/std/haxe/display/Display.hx#L388-L393

If `args` go after `kind` during patterns collection then they seem to infer `T` from type of `kind`, but if `args` matching goes first then it is still monomorph and an error is produced. I guess that some bug that never surfaced before.

**Comment by vonagam** [comment]
Here is a ref list variant that later can be easily converted to ref map.

Hm... actually the problem is that order in which things are typed depends on order of fields definition in a type and not on order of pattern keys. It should be later, then the problematic case and map usage should work.

**Comment by vonagam** [comment]
When i made order based on appearance in a pattern structure another test failed. It seems like after that, during specialisation, every `PatConstructor` is expected to have fields in the same order too, so that's why there is a padding with `PatAny` for unused type fields, maybe if `PatConstructor` had used a map instead of a list for patterns then it would have been possible to use a map here, but not right now.

So tests are passing and there is nothing left to do, if code style is right then it can be merged.

**Pull request merged**
