### PR TITLE
Implement Int128, Int256, and Int512 + their numeral literal suffixes

### PR DESCRIPTION
**Pull request by SomeGuyWhoLovesCoding**
This pull request implements the logic of the 128-bit,  256-bit, and 512-bit integers. They are of course real integers, but right now you can't create those integers with decimal values directly as opposed to initializing 32-bit integer values.

No tests for those integer classes yet cause that causes me more stress.

### CODE REVIEW

**Comment by EyeDaleHim** [comment]
I'm not sure if this is the right place to ask for help, the Issues tab might be more sufficient.

**Comment by Simn** [comment]
Actually I prefer a PR here because it's easier to reason about the code and see the failing tests, so I think this is a good initiative.

**Comment by SomeGuyWhoLovesCoding** [comment]
How come 14 tests failed?

**Comment by EyeDaleHim** [comment]
> How come 14 tests failed?

That's what the details tab are for, perhaps you can click on them :P

**Comment by SomeGuyWhoLovesCoding** [comment]
This is an error from linux build 4.08.1:
```class Int64Helper {
   - |   [...]
 126 | }
Type Int64Helper refined from class Int128Helper```

**Comment by SomeGuyWhoLovesCoding** [comment]
Guess what? I fixed it with no effort just today. It was just that the mask was wrong. The multiply mask for Int64 is 0xFFFF (65535) so The multiply mask for Int128 should be 0xFFFFFFFF (4294967295).

**Comment by TheRealJake12** [comment]
🤓

**Comment by mikaib** [comment]
Just a quick question:

https://github.com/SomeGuyWhoLovesCoding/haxe-int128/blob/5f616d5d557386d2be669b47b8bc846f589a7ea2/std/haxe/Int128.hx#L67C2-L73C3

Could it be that the overflow checks are missing on the `toInt` method?

With kind regards,
mikaib

**Comment by SomeGuyWhoLovesCoding** [comment]
> Just a quick question:
> 
> https://github.com/SomeGuyWhoLovesCoding/haxe-int128/blob/5f616d5d557386d2be669b47b8bc846f589a7ea2/std/haxe/Int128.hx#L67C2-L73C3
> 
> Could it be that the overflow checks are missing on the `toInt` method?
> 
> With kind regards, mikaib

The overflow checks are not missing. I just did `Int64.toInt(x.low)` just to write easier. Then, the low value can do the job instead of repeating the whole task with the int128 value.

**Comment by SomeGuyWhoLovesCoding** [comment]
Successfully finished implementing the Int128 numeral literal suffix for haxe. Now it's done.

**Comment by SomeGuyWhoLovesCoding** [comment]
I see why the issue happened in the first place now

**Comment by SomeGuyWhoLovesCoding** [comment]
Okay so I should've left the increment and decrement functions alone as the tests want
My bad

**Comment by SomeGuyWhoLovesCoding** [comment]
The pain is finally over

**Comment by SomeGuyWhoLovesCoding** [comment]
Now time to wait until the action is fully finished with the checks and this pr gets merged

**Comment by SomeGuyWhoLovesCoding** [comment]
I gotta make an issue about that

**Comment by SomeGuyWhoLovesCoding** [comment]
Now I'm just waiting for this pr to get merged

**Comment by LeonGamerPS1** [comment]
balls

**Comment by SomeGuyWhoLovesCoding** [comment]
> balls

Ok

**Comment by SomeGuyWhoLovesCoding** [comment]
Ignore the commits adter the hrr 717 mention. It was an accident and I didn't mean to do so.

**Comment by SomeGuyWhoLovesCoding** [comment]
100 commits. Oh boy. I wasted the 15 of them lol

**Comment by SomeGuyWhoLovesCoding** [comment]
The toString() function runs very slow, so I'm rewriting it.

**Comment by SomeGuyWhoLovesCoding** [comment]
This pr is now officially closed.

My haxe fork is staying.

**Pull request closed without merging**
