### PR TITLE
add new function type syntax (closes #4799)

### LINKED ISSUE #4799: [suggestion] argument names in function type syntax
I keep remembering about it from time to time and finally decided to open a discussion.

Currently, our function type syntax `TArg1 -> TArg2 -> TReturn` doesn't allow specifying argument names in it, which is a bit unfortunate, because e.g. `String -> String -> Bool -> Void` doesn't describe much about what those arguments actually mean, so additional documentation is required.

One could argue that it's a bad practice to use primitives like that and we could use `typedef` for giving argument more meaning via its type, e.g. `typedef UserId = String`, and then `UserId -> Void`, but this solution has two problems:
1) it's not very handy to create extra types just for describing arguments
2) it won't help when you have several arguments of the same type (e.g. `sender:UserId, receiver:UserId`)

So I'm proposing to support parsing the syntax that we'are already using when printing function types e.g. in completion (`name1 : Type2 -> ?name2 : Type2 -> ReturnType`), so it could be used like this:

```
typedef MessageCallback = sender:UserId -> receiver:UserId -> message:String -> Void
```

Of course, argument names still shouldn't matter when unifying and serve purely for documentation and completion purposes.

---

While writing this proposal, I found out that it would require changing `complex_type.CTFunction` signature, and thus `haxe.macro.Expr.ComplexType.TFunction`, so I'm not sure if this can be implemented in 3.x without breaking macros, which is discouraging. However I'd like to know what are you guys thinking about the idea in general, maybe I'm missing something?

Also, If we talk 4.x, maybe it would be fair to change function type syntax to something that doesn't suggest auto-currying? Something like C# delegates come to mind, but I don't know how to adapt that for haxe, maybe something like `typedef MyCallback = function(a:Int, b:String):Void`?

### PR DESCRIPTION
**Pull request by nadako**
This implements https://github.com/HaxeFoundation/haxe-evolution/pull/23

### CODE REVIEW

**Comment by Simn** [comment]
The grammar part looks good to me.

I don't know about CTNamed though. Shouldn't this be integrated into CTFunction instead? IIRC you wanted to do that for CTOptional as well at some point.

**Comment by nadako** [comment]
Yes that's an [unresolved question](https://github.com/nadako/haxe-evolution/blob/new_function_type_syntax/proposals/0000-new-function-type.md#representation) in the proposal, but since noone commented on that, I went with the least intrusive change. Do we want to rework `CTFunction` instead?

**Comment by Simn** [comment]
We could maybe keep CTOptional because at least it parses on its own and can be used in macros. With CTNamed, it doesn't even parse on its own, so it doesn't make much sense to have a representation for it.

**Comment by nadako** [comment]
So, `CTFunction of (placed_name * bool * type_hint) list * type_hint`?

**Comment by Simn** [comment]
That looks correct.

**Comment by nadako** [comment]
See #6667

**Comment by Simn** [comment]
We can close this one, right?

**Comment by ncannasse** [comment]
Hmm, I would leave `TFunction( args : Array<ComplexType>, ret : ComplexType
)` as-it, and add `TNamedFunction( args : Array<{ name : String, t :
ComplexType, opt : Bool }>, ret : ComplexType );` (or some other
constructor name) for the sake of macro compatibility

**Comment by Simn** [comment]
That would be annoying because you would have to handle both constructors whenever you want to handle a function. It would also still be breaking because it's an additional constructor and causes exhaustiveness errors. Unless you use default cases, in which case you would just silently miss it and your code would break.

**Comment by ncannasse** [comment]
We can always pass TNamedFunction from compiler to macro, but accept both from macro.
But maybe that's not that important given we have reification on complex types, so most of them will be transparent.

**Comment by Simn** [comment]
That sounds awkward... in that case, the CTNamed approach strikes me as better.

**Comment by ncannasse** [comment]
Maybe yes.

**Pull request merged**
