### PR TITLE
Fix for #5429: using ByteBuffer instead of StringBuf in haxe.io.Input…

### PR DESCRIPTION
**Pull request by sebthom**
….readLine() andreadUntil()

### CODE REVIEW

**Comment by ncannasse** [comment]
That's only a partial fix. If the file you're reading is encoded as UTF-16, you might stop when reading the upper byte of a character while it should continue. I prefer to wait until we have proper Unicode support to add explicit encoding for these methods.

**Comment by sebthom** [comment]
Sure it may not fix UTF-16 or other encodings, but it doesn't worsen status quo and at least improves the current situation. The "proper Unicode support" seems to be in discussion for ages already, so I find it a bit unreasonable that you are closing this particular fix which could easily go into the 3.3 release with that argument.

**Comment by ncannasse** [comment]
You're right that it at least fixes UTF8 reading, it's a small step forward so I'll merge.

**Comment by sebthom** [comment]
Thank you!!!

**Pull request merged**
