### PR TITLE
Loop unrolling

### PR DESCRIPTION
**Pull request by Simn**
Supports loop unrolling in `for (x in [1, 2, 3])` and comes with some minor analyzer adjustments.

Technically we're feature-frozen, but I'm willing to make an exception because this feature was requested by a Haxe Foundation partner.

### CODE REVIEW

**Comment by ncannasse** [comment]
Seems good.
BTW we should put a deadline for 3.2

**Comment by Simn** [comment]
Yes, well... you promised a lot of stuff for 3.2 at WWX so we are kind of blocked on #3072 and #3073 at least.

**Comment by delahee** [comment]
We think we can stop procrastrinating for feature releases. If we cannot
produce unicode support, let' get a haxe version out and wait for another
go later. :)

Haxe has a too long release cycle, we should cut anythign that impeach us
having releases at least every 4 month or something...

Good luck pals !

2015-01-22 10:40 GMT+01:00 Simon Krajewski <notifications@github.com>:

> Merged #3786 <https://github.com/HaxeFoundation/haxe/pull/3786>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/haxe/pull/3786#event-222899973>.
>



-- 
David Elahee

**Comment by ncannasse** [comment]
@Simn :) we could release 3.2 without it, and have these in 3.3. But yes I have to look into bytes support soon since it would help me for some side project I've been working on

**Pull request merged**
