### PR TITLE
change Iterator<T> specification regarding calling hasNext before next

### PR DESCRIPTION
**Pull request by nadako**
This is how it should be, right?

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
As said by Nicolas:

> It's only specified to work in the following case : `while( hasNext() ) doSomething(next())`

So I think, something like this should be added to the `Iterator` itself, not the fields.

**Comment by ibilon** [comment]
> It is required to call `hasNext()` **at least once** before calling `next()`

Can you really call hasNext any number of times and not exactly once? Considering the `while( hasNext() ) doSomething(next())` spec I don't think it's defined to work.

**Comment by ncannasse** [comment]
Copy/pasting my slack comment: _it depends how much we allow hasNext() to have side effect. If we don't allow it, then calling next() when we are *sure* there is one could be legit._

**Comment by nadako** [comment]
Alright, let's move the discussion here.

I think the most efficient way to implement `Iterator` based on native iterators like the JS one is to have `hasNext` call initialize the iterator for the first time, and `next` don't do any checking: https://github.com/HaxeFoundation/haxe/blob/e810f2fd3aea9a0baaccf37d65bb651bbf6d22dc/std/js/JsIterator.hx#L14-L32, but that means that calling `hasNext` before `next` must be required by the spec.

Alternatively we could initialize the native iterator in the adapter constructor, but that seems conceptually wrong, because we should only advance when iterator methods are called, not when the iterator is created.

**Comment by ncannasse** [comment]
@nadako why not doing  `s = i.next();` in constructor ?

**Comment by nadako** [comment]
> @nadako why not doing `s = i.next();` in constructor ?

That's what I meant by:

> Alternatively we could initialize the native iterator in the adapter constructor, but that seems conceptually wrong, because we should only advance when iterator methods are called, not when the iterator is created.

In most cases (`for` iteration) it's fine, but if someone has a custom iterator that does some heavy work that they save and somehow iterate by calling `hasNext/next` manually (I imagine this might be the case with coroutines/generators), calling `next` on construction might be unwanted.

**Comment by Simn** [comment]
Branch needs an update.

... and I'll stay out of this one.

**Comment by nadako** [comment]
I'm closing this because I don't like stuff assigned to me hanging around unresolved.

**Pull request closed without merging**
