### PR TITLE
Lua vanilla ci

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
@nadako is this still relevant?

**Comment by nadako** [comment]
Well yeah, we want to test lua-vanilla as well. I don't remember the status here tho.

**Comment by RealyUniqueName** [comment]
If all `-D lua-vanilla` does is disabling unicode support then we now have `-D disable_unicode_strings` for that.

**Comment by nadako** [comment]
cc @jdonaldson

**Comment by nadako** [comment]
Rebased and removed everything but the `lua-vanilla` testing. And yeah maybe we should drop `lua-vanilla` in favor of `disable_unicode_strings`.

**Comment by jdonaldson** [comment]
There's one other usage for integer clamping, but I believe I can autodetect that scenario in the runtime on initialization.

**Comment by jdonaldson** [comment]
I just converted the clamp function to autodetect on startup instead.  It's up on the repo now : https://github.com/HaxeFoundation/haxe/commit/d32f65da888704d0caa2f161de231ae5dd041672

I could also remove/convert the "vanilla" references, but I didn't know if you were already working on that.  Either way, should be super easy.

**Comment by jdonaldson** [comment]
Whoops, broke bitops.  Fix is working its way through the tests.

**Comment by jdonaldson** [comment]
Would it make sense for me to go ahead and remove/convert the references to lua vanilla, and then work on the corresponding (and more general) `disable_unicode_strings` test suite instead?

We could close this pull request and merge any relevant part of @nadako's work on a new PR.

**Comment by Simn** [comment]
@nadako @jdonaldson Please sort this out!

**Comment by jdonaldson** [comment]
I'll use `disable_unicode_strings` and drop `lua_vanilla`.  I don't see anything else that needs to be handled specifically in a "vanilla" setting any more.

**Comment by jdonaldson** [comment]
I have another branch working its way through testing : https://github.com/HaxeFoundation/haxe/tree/lua_drop_vanilla
If that passes I'll merge directly and close this one.

It combines some of @nadako's work here with the rest of the necessary changes.  I also updated CHANGES.txt.  This will probably break some code, but since it's just a single compiler flag that needs to change I think it's tolerable for a minor release.  

If you don't want to break anything, I could also include legacy support for lua_vanilla.

**Comment by jdonaldson** [comment]
Trying to get something resolved : https://github.com/HaxeFoundation/haxe/issues/9196

**Comment by nadako** [comment]
I don't know what is the status of this anymore and I'm unassigning myself. Feel free to close if it's irrelevant nowadays.

**Comment by Simn** [comment]
I suppose we can close this now.

**Pull request closed without merging**
