### PR TITLE
[js] Browser.supported: Check window.document.body

### PR DESCRIPTION
**Pull request by haxiomic**
Continuing on from #9126

---

`js.Browser.supported` tries to verify if the runtime is a browser by checking if `window` is defined

Unfortunately this doesn't work in all scenarios because non-browser contexts might define window for other reasons – see https://github.com/HaxeFoundation/haxe/issues/9118

Implementing @back2dos suggestion https://github.com/HaxeFoundation/haxe/pull/9126#issuecomment-583017706 of checking for window.document.body instead

### CODE REVIEW

**Comment by haxiomic** [comment]
Another problem with this one: when running in a web worker `window` and `document` are undefined (see #9168)

**Comment by RealyUniqueName** [comment]
I guess, while running in a webworker one wouldn't want `Browser.supported` to be `true`.
Otherwise it might be better to have something like `static var js.Lib.runtime:JsRuntimeMode` with
```haxe
enum JsRuntimeMode {
  BrowserMode;
  WorkerMode;
  CliMode;
}
```

**Comment by Simn** [comment]
I've randomly assigned this to @nadako because I don't know who else to ask about whether or not to merge this.

**Comment by nadako** [comment]
I actually recently had an issue when a script was executed while the document was not yet loaded and had no `body`. It sounds to me like `Browser.supported` should still be `true` in this scenario.

**Comment by nadako** [comment]
But also, I might not be the best person for this. I haven't really used `Browser.supported` and I don't do "normal" web dev.

**Comment by Aurel300** [comment]
Generally scripts that need to interact with the loaded DOM attach a listener like `window.onload = ...` or the more fancy `document.addEventListener("DOMContentLoaded", ...)`. This is not necessarily something Haxe should do automatically (you might have a script that doesn't need to wait or is meant for Node.js only …).

**Comment by haxiomic** [comment]
Good point @RealyUniqueName, checking for document.body probably isn't the best way then. Any ideas for how we can better guess if we're executing in a browser? (The original issue was that `window != null` was not enough because React native defines it)

**Comment by RealyUniqueName** [comment]
I think in a mad world of JavaScript there's no reliable way to detect that. There are even libraries for emulating window API in nodejs environment.
Probably the best thing we can do is to provide some default mechanism and an API to alter it.

**Comment by nadako** [comment]
I cannot make a decision about merging this. The check makes sense, and it's generally a good practice to put `<script>` elements at the bottom or listen to `onload` so the `.body` before doing anything. The concern I voiced is still valid IMO, but it can be "solved" by documentation, so I don't mind.

**Comment by back2dos** [comment]
Well, I think we have at least two choices:

1. `'body' in window.document`
2. `!!window.document.head`

Both seem to work on Chrome, Edge, IE and FF. Someone will have to check Safari of course, but I think chances are good ;)

**Comment by haxiomic** [comment]
Maybe checking for the existence of `window.location.protocol` is sufficient to indicate a browser environment (given presumably non-browser spoofs like React Native don't have anything sensible to put in there), whereas browser spoofs might still mimic the document model and have a body and head

Updated PR with this

**Comment by nadako** [comment]
It's a bit concerning that it's a property that actually now does multiple checks including type checking on every access, but I guess it's not a big problem, given that it's (hopefully) rarely called 1000 times every frame :)

**Comment by nadako** [comment]
Also maybe it shouldn't be `inline` anymore.

**Comment by haxiomic** [comment]
Removed inline
It's pretty ugly but thankfully I think typeof is weirdly fast these days. I can't get it to breach 1µs on my laptop, testing with:
```javascript
var n = 1000000; 
var array = new Array(n);
var t_0 = window.performance.now();
for (let i = 0; i < n; i++) {array[i] = typeof window !== 'undefined' && typeof window.location !== 'undefined' && typeof window.location.protocol === 'string';}

var dt_ms = window.performance.now() - t_0;
console.log(dt_ms / n + ' ms', array.length)
```
Including writing and reading from array to try to prevent optimisations

**Comment by haxiomic** [comment]
I think this one is good to go now :), will merge later today if all good with everyone else

**Comment by nadako** [comment]
Boop

**Pull request merged**
