### PR TITLE
Java Reflection

### PR DESCRIPTION
**Pull request by imcasper**
Field may be type "java.lang.Integer", "java.lang.Object", or raw "int" (for integer for sample). Methot "set" correctly processes any cases.

### CODE REVIEW

**Comment by Simn** [comment]
@waneck: Could you check this? I don't think that we should accept this PR because commenting out code can't be the answer, but maybe the code can simply be removed.

**Comment by imcasper** [comment]
Of course, the code in the comments should be deleted. The new version is more stable than the old one.

**Comment by RealyUniqueName** [comment]
Commented out code handles assignment of `null` to `Int` and `Float` fields. Method `set` just throws `java.lang.IllegalArgumentException` exception in this case.
We cannot accept this change.

**Comment by RealyUniqueName** [comment]
I'm wrong, commented code also throws that exception on `null`

**Comment by RealyUniqueName** [comment]
But with this PR accepted java fails unit tests.

**Pull request closed without merging**
