### PR TITLE
I'm getting errors related to mainThread not being set.

### PR DESCRIPTION
**Pull request by 0b1kn00b**
There's probably a better way to do this, but it'll show the problem in any case.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
This approach is wrong. If `EntryPoint.mainThread` is accessed for the first time from a secondary thread, then it would point to that thread instead of real main thread.
Please, open an issue and describe your problem there.

**Comment by 0b1kn00b** [comment]
Yikes, sorry.

**Comment by 0b1kn00b** [comment]
Who calls `EntryPoint.init`? I can't find a reference, sorry.

It's in the compiler, but is it called before or after `main` because `MainEvent.add` needs it and I often haven't got it, and annotating `init` with a trace isn't helping.

I think it's `finalization.ml` line 80 but it's not being called in eval, maybe?

**Comment by RealyUniqueName** [comment]
Yes, the call is generated by the compiler in finalization.ml.

I think if it's not the case for eval, then our CI would not pass for eval target.

**Comment by RealyUniqueName** [comment]
Can you assemble a sample for me to reproduce the issue?

**Comment by 0b1kn00b** [comment]
Not to be an arse, but:
```haxe
import haxe.EntryPoint;

class Main {
	static function main() {
		var a = @:privateAccess EntryPoint.mainThread;
		trace(a);//null
	}
}
```

built with `--interp`,`--cpp`,`python` or `hl` thus far.
Lubuntu 20.04, haxe: https://github.com/HaxeFoundation/haxe/commit/a16c00f6af58082d0a6565bc7da2ab6da018328a
Building haxe using `ocaml-system.4.08.1`

**Comment by RealyUniqueName** [comment]
@0b1kn00b I've pushed a fix into development branch.

**Pull request closed without merging**
