### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by RealyUniqueName**

### CODE REVIEW

**Comment by Aurel300** [comment]
The file is auto-generated, I think you should fix the source …

**Comment by RealyUniqueName** [comment]
Do you know where is the source?

**Comment by Aurel300** [comment]
It is in `extra/github-actions`, specifically this line maybe:

https://github.com/HaxeFoundation/haxe/blob/b7d4a1d0ba2ddbd9e1610093585f3a5cfe2bd35a/extra/github-actions/build-mac.yml#L5

The whitespace  changes are also not very useful given the auto-generation.

**Comment by RealyUniqueName** [comment]
I can't figure out what's wrong with windows builds.
I diff'ed the last successful build log with the current log and the only suspicious thing I found is `-I/usr/local/include` added to opam building of conf-mbedtls (and probably other opam packages and something else). That suggests environment was changed. 
Also azure pipelines agent version is now 2.175.2. The last successful build used 2.174.1. But I didn't find anything suspicious in the changes: https://github.com/microsoft/azure-pipelines-agent/releases
@andyli could you please take a look?

**Comment by andyli** [comment]
Looks like something has changed in cygwin or fdopen's ocaml distribution. I think one should reproduce it locally and report the issue to somewhere. I don't have time to do it this week though.

**Comment by RealyUniqueName** [comment]
I tried to reproduce it locally. But without success. I'll try again tomorrow.

**Comment by RealyUniqueName** [comment]
This is indeed 100% reproducible with the latest version of cygwin.
I've found this in the [cygwin changelog](https://cygwin.com/cygwin-ug-net/ov-new.html):
> Built-in implementation of _FORTIFY_SOURCE guards for functions in <stdio.h>, <stdlib.h>, <string.h>, <strings.h>, <unistd.h>, <wchar.h>, <sys/poll.h>, and <sys/socket.h>. New APIs: __chk_fail, __gets_chk, __memcpy_chk, __memmove_chk, __mempcpy_chk, __memset_chk, __snprintf_chk, __sprintf_chk, __stpcpy_chk, __stpncpy_chk, __strcat_chk, __strcpy_chk, __strncat_chk, __strncpy_chk, __vsnprintf_chk, __vsprintf_chk.

Unfortunately, I don't know if this is the reason and how to fix it.

**Pull request closed without merging**
