### PR TITLE
Add addHeader function for neko and php

### PR DESCRIPTION
**Pull request by lublak**
Must be merged before:

https://github.com/HaxeFoundation/neko/pull/205
https://github.com/HaxeFoundation/tora/pull/17

### CODE REVIEW

**Comment by Simn** [comment]
Please update the branch, CI is freaking out.

Looks like `Web` survived my std purge... I'm inclined to move this to hx3compat and just let it sit there because I don't want to have this in the standard library. Still, if this small change makes your life any better I'm fine with merging this PR.

**Comment by RealyUniqueName** [comment]
>  I'm inclined to move this to hx3compat and just let it sit there because I don't want to have this in the standard library.

#9153

**Comment by lublak** [comment]
"Web" is not important to me. Only the add_header for neko and tora, since I have my own "web" implementation.
This pull request is just for those, who need it in the standard library.
I'm fine to skip this pull request.

**Comment by Simn** [comment]
Alright then, thanks for the effort.

**Pull request closed without merging**
