### PR TITLE
Fix constraint checking for abstracts

### LINKED ISSUE #8984: Map is unifiable with Iterable as a cosntraint
```haxe
class Main {
	static function main() {
		var m = [1 => 'hello'];
		iter(m);
	}

	static function iter<T:Iterable<String>>(m:T) {}
}
```
```
$ haxe -main Main
Main.hx:4: characters 3-7 : Constraint check failure for iter.T
Main.hx:4: characters 3-7 : haxe.ds.Map<Int, String> should be Iterable<String>
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #8984 

@Simn how about this? It's quite an isolated and simple fix for now.

### CODE REVIEW

**Comment by Simn** [comment]
Check the code paths that go through `check_constraints` instead of `add_constraint_checks`. For instance, `enum_field_type` does that.

I would really prefer to not touch this and clean it up first. Constraint implementation is just a big mess in general.

**Comment by RealyUniqueName** [comment]
I doubt we will get to constraints refactoring in a foreseeable future.
So I suggest to merge this as it seems isolated and fixes weird situation when something works as a "direct" type hint, but does not work as a type constraint.

**Comment by Simn** [comment]
No, this is bad. You're creating an expression, run `cast_or_unify` on it and then `ignore` the result. This means that the cast-call never makes it into the output. Please test this with a cast that does something other than `return this` so you can test if the code actually executes at run-time.

**Comment by RealyUniqueName** [comment]
Yeah, that call doesn't happen. This approach is wrong.

**Pull request closed without merging**
