### PR TITLE
add @:bypassAccessor (closes #5039)

### LINKED ISSUE #5039: Bypass accessors and access field directly without resorting to reflection
Well, the title says it all, I guess. Is there a way to do this? Maybe `@:privateAccess` or something like `@:privateAccess(true)` or whatever might be hijacked to that end?

Probably a bad moment to ask, but this comes up every now and then and I tend to bump into it every now and then myself, so I would appreciate if it could be taken under consideration for 3.4.

### PR DESCRIPTION
**Pull request by nadako**
~Works just like the `@:privateAccess`/`@:noPrivateAccess` pair~. See #5039 for reasoning.

### CODE REVIEW

**Comment by Simn** [comment]
I understand bypassAccessor, but why do we need noBypassAccessor?

**Comment by nadako** [comment]
> I understand bypassAccessor, but why do we need noBypassAccessor?

The situation is exactly like with `@:privateAccess`: we might want to bypass the accessors for the toplevel expression, but not for sub-expressions. E.g. `obj.field = calc(otherObj.otherField)` and we only want to bypass the accessor for `obj.field`, but not for `otherObj.otherField`.

**Comment by Simn** [comment]
Hmm, I'd expect that to be the default behavior though. I think `@:bypassAccessor` should work like `@:inline` with regards to scoping. Unfortunately, that's much more annoying to implement...

**Comment by nadako** [comment]
Yeah, you're right...

**Comment by nadako** [comment]
> Unfortunately, that's much more annoying to implement...

What if we set a `ctx.bypass_accessor` flag to `true` and just reset it back to `false` on the first `field_access`?

**Comment by Simn** [comment]
Doesn't it see the innermost field access first?

**Comment by nadako** [comment]
> Doesn't it see the innermost field access first?

I don't think so, it's always typed left-to-right?

Maybe just a flag would not be enough and we need to have a counter instead, because `@:bypassAccessor (@:bypassAccessor obj.prop).otherProp` might be desired...

**Comment by nadako** [comment]
how about now? :)

**Comment by Simn** [comment]
Meh that's hacky. If someone accidentally uses this on an expression that doesn't end up being a field access you leave the counter increased and then it affects some random other property field access...

**Comment by nadako** [comment]
yes I also just thought about that, but I think we can get away with checking if the counter is back to the old value after `e()` and error?

**Comment by lublak** [comment]
@nadako if you add something like this. Should bypassAccessor also bypass "AccCtor"?
Sometimes it could be also usefull to access a final variable.

**Comment by nadako** [comment]
> yes I also just thought about that, but I think we can get away with checking if the counter is back to the old value after `e()` and error?

Added that, seems to work. Of course it's still quite hacky, but at least the behaviour is what we want now? (and we do the annoying refactoring later?)

**Comment by nadako** [comment]
> @nadako if you add something like this. Should bypassAccessor also bypass "AccCtor"?
> Sometimes it could be also usefull to access a final variable.

If you mean writing into a final variable, I think we should not do that because that'll limit us from generating target-native final and this have nothing to do with get/set accessors anyway...

**Comment by lublak** [comment]
@nadako okay you are right 👍

**Review by Simn — APPROVED** [review]
I don't particularly like this and it still feels pretty hacky, but I acknowledge that we need a solution for this and I don't have a better idea at the moment. So I'm fine with merging this for now.

**Pull request merged**
