### PR TITLE
Vector defaultValue argument

### LINKED ISSUE #8040: [js][java] Performance lost
I created two identical files  - Haxe and java source -  and after that compile Haxe to Java target and run via JVM . There is significant difference between Haxe generated java classes and those write on Java . At example : 
  1)  Haxe - Java takes  1.01  seconds
  2) Pure  Java takes  0.40 seconds

Here is all sources and test vectors:
  1) Haxe source :  https://gist.github.com/flashultra/8b33d48aca7c48a9a4d4e7d36b0a3d66 
  2) Java source : https://gist.github.com/flashultra/498963ec508e9fb099e3e7110fee7f69

### PR DESCRIPTION
**Pull request by RblSb**
Should fix #8040 and unblock #8495

### CODE REVIEW

**Comment by Simn** [comment]
I'm worried about code generation on static targets because the argument is optional. In particular, we have to make sure that `this[i] = defaultValue` does not unwrap `Null<T>` on each iteration as that would cause a big performance hit.

**Comment by RblSb** [comment]
Some way to unwrap it before iteration, like `final value:T = cast value`?
In other case Vector probably can be generated as `{array: [], length: 123}` on js (only 10% slower for array access, but requires more work for other methods). Or filled with nulls (50% slower, still fine).

**Comment by back2dos** [comment]
Adding optional arguments is technically a breaking change. Also I'm having trouble imagining that `new Vector(1000000)` has the same performance characteristics on JS with this change. I wonder if having a `fill` method that returns the vector itself won't do the trick while avoiding all sorts of issues.

**Comment by RblSb** [comment]
In what cases this is breaking change?
Not against `Vector.fill`, but i think access performance should be fixed for `new Vector` too, and initilization performance mean less for storage of fixed size (static targets fill the vector anyway). Some opinions about my ideas above?

**Comment by RealyUniqueName** [comment]
It's a breaking change because of a signature change. But that's not important because `Vector.new` is probably never used as a closure.
But having a loop for 100000 iterations inside of `new Vector(100000)` _is_ important.

**Comment by back2dos** [comment]
Sorry, forgot to respond.

> It's a breaking change because of a signature change. But that's not important because `Vector.new` is probably never used as a closure.

I was thinking of allocation pools, which doesn't seem *that* far fetched. But yeah, it's probably not going to affect anyone.

---

I would propose this:

```haxe
abstract Vector<T> {
  public function new(size:Int):Void;
  public function fill(value:T):Void;// exercise for the writer
  static public function prefilled<T>(size:Int, value:T):Vector<T> {
    #if xyz
      /* fancy xyz-specific magic here */
    #else // default implementation
      var ret = new Vector(size);
      ret.fill(value);
      return ret;
    #end
  }
}
```

**Comment by Simn** [comment]
I'm closing this because I don't think having the Vector constructor loop over its length is acceptable. I'd be fine with adding a separate `fill` method as suggested, that might be useful in various situations anyway.

**Pull request closed without merging**
