### PR TITLE
add test for field access on null

### PR DESCRIPTION
**Pull request by nadako**
This PR is not for merging (yet), but for running the CI to see where we're at and also for discussing whether we want to specify this or not.

### CODE REVIEW

**Comment by nadako** [comment]
Looks like it's only a problem on genjvm (no exception, returns `null` instead), and C++ (segfaults, but not on win64???)

**Comment by Simn** [comment]
Please use a static var for the `null` value. I'm worried about constant propagation, though I'm not sure if we do that for `null` still.

**Comment by nadako** [comment]
Updated and rebased.

**Comment by RealyUniqueName** [comment]
I think this should always throw.

**Comment by Simn** [comment]
This fails on Java and C++.

@hughsando Is it possible for hxcpp to raise a catchable exception on `null` field access?

Also @nadako please update the branch again.

**Comment by hughsando** [comment]
There is  -D HXCPP_CHECK_POINTER, or -debug to do this.
On windows you can trap the  OS exception with  -D HXCPP_SEH_THROW for "free" checks - I would like to extend this to the other targets.
The checks are not normally done for performance reasons, but I could look at making it on by default, and reverse the check to be an opt-out.

**Comment by Simn** [comment]
@hughsando I think it would be good to flip the check so we can go for a consistent behavior. I doubt that this could have an observable impact in any code that isn't a micro-benchmark. Could you make this change for 4.1?

Also, anyone interested in looking into the problem on Java? Maybe @RblSb?

**Comment by RblSb** [comment]
I cannot see this PR build log, but it works on java and returns `null` on jvm in second check.
This is because of `obj == null` part here:
https://github.com/HaxeFoundation/haxe/blob/development/std/jvm/Jvm.hx#L316
Pass without. @nadako can remove this check and see CI results here.

**Comment by RealyUniqueName** [comment]
@Simn java failure comes from JVM:
```haxe
trace((null:{s:String}).s); // Prints "null" instead of emitting an exception
```

**Comment by Simn** [comment]
Fixed on development.

I don't like that access through `Reflect.field` has different semantics, but I guess it is what it is.

**Comment by RealyUniqueName** [comment]
Huh, I've never thought of this aspect of `Reflect.field`. 
I think it would've been better if it was throwing on null.

**Comment by Simn** [comment]
Me too, but we can't really change that at this point.

**Comment by Simn** [comment]
Could you update the branch so we can see what the CI says?

**Comment by nadako** [comment]
rebased

**Comment by nadako** [comment]
fails on cppia

**Comment by nadako** [comment]
java seems fine? was it JVM-only issue?

**Comment by Simn** [comment]
Yes

**Comment by RealyUniqueName** [comment]
cppia still fails the test

**Comment by nadako** [comment]
I guess I'll look into CPPIA, unless @hughsando wants to :)

**Comment by nadako** [comment]
Hm, I'm getting `"NPE"` locally huh.

**Comment by nadako** [comment]
The example works with `haxelib run hxcpp`, so it's something about how we compile our host executable.

**Comment by nadako** [comment]
So this fails for me:

build.hxml
```hxml
-cp src
-main Main
-cppia main.cppia
```

Main.hx
```haxe
class Main {
	var s:String;

	static var nf1:Main;

	static function main() {
		trace("START");
		trace(try nf1.s catch (e:Any) "NPE");
		trace("END");
	}
}
```

build-host.hxml
```hxml
-main cpp.cppia.Host
-D scriptable
-cpp bin/cppia
```

`bin\cppia\Host.exe main.cppia` crashes.
`haxelib run hxcpp main.cppia` works.

**Comment by RealyUniqueName** [comment]
@nadako same results for me.

**Comment by RealyUniqueName** [comment]
I also tried with `-debug`, `-D HXCPP_CATCH_SEGV` and `-D HXCPP_CHECK_POINTER`. Still segfaults with any of these.

**Comment by hughsando** [comment]
Yes, I forgot the cppia host was built differently on the test system.  I'm hoping to get `-D HXCPP_CATCH_SEGV` to work on all systems, and put it on by default, so this is the flag to test. (Note: this define goes on the cppia c++ host compile, not the cppia bytecode compile)
If you try a cppia binary from `http://nmehost.com/hxcpp/?latest=1` and it still fails, any debug info would be helpful.  The implementation is quite different on windows/non-windows so the system might be a factor.

**Comment by nadako** [comment]
I extracted Cppia.exe from that and tried to run, but it gives me another error:

```
Unknown static call to Std::isOfType (0)
 in haxe.Exception::00000061D1AFF400
   CallStatic at :0 caught
Error : Bad link
```

which looks like a haxe version mismatch or something

**Comment by hughsando** [comment]
Yes, this is due the the fact that the hxcpp cppia host is built against the release version of haxe (4.0.x) which does not have isOfType in it, so not great for cutting edge testing I guess.  If the little test code works when compiled with haxe 4.0, then at least I know that the solution is to get this flag in by default.

**Comment by nadako** [comment]
This still fails on CPPIA. I'm closing this PR because I can't do anything about CPPIA and I don't want unactionable things hanging in my github.

**Pull request merged**
