### PR TITLE
[tests] Restore flash tests

### PR DESCRIPTION
**Pull request by tobil4sk**
Restores flash tests.

Changes to flash tests required to get them running:
- e2ad176 - Disabled flash http windows test (this was disabled on Mac and Linux already)
- 511ff61 - Updated test for issue [#8218](https://github.com/HaxeFoundation/haxe/issues/8218) in line with changes in [#10521](https://github.com/HaxeFoundation/haxe/issues/10521)

### CODE REVIEW

**Comment by tobil4sk** [comment]
I think reverting to http for one of the links and hard coding a mirror for the apache download should have fixed the certificate error for now.

**Comment by tobil4sk** [comment]
I looked into it and the 32 bit tests on Windows print `Warning: valueOf is not a function` after the .swf file is run and then hang. Perhaps it's fine to just leave those disabled?

**Comment by Simn** [comment]
I'm fine with disabling them. I vaguely remember this being an issue long ago already.

**Comment by tobil4sk** [comment]
Could be an issue with flash player not being able to access the configuration for the debug log, which might be the cause for the missing output (and thus the seemingly hanging test). I don't know why it would only happen on 32 bit and it's hard to test because I don't have a 32 bit windows environment lying around, and at this point it's probably not worth it. So I'll just leave them disabled. Looking back it seems it's a miracle that the 64 bit tests even run.

Also, I did some testing on another branch when I tried to run a simple hello world program and that didn't trace anything either, even on 64 bit windows. I think it's best to just leave it with just 64 bit while that even still works.

**Comment by tobil4sk** [comment]
Bumping because the last failure should have been a one off.

**Pull request merged**
