### PR TITLE
Fix some Reflect issues with PHP

### PR DESCRIPTION
**Pull request by mockey**
getProperty was broken, see #4915, I tried to fix it in the way that seems most logical to me, using the method from field, same for setProperty
fix isObject and isEnumValue (both were failing in Reflect.unit)
enable Reflect.unit for PHP, also uncomment some disabled tests

### CODE REVIEW

**Comment by mockey** [comment]
Reflectiion is quite a mess.
There is a magic `__setfield__` function:
https://github.com/HaxeFoundation/haxe/blob/development/genphp.ml#L561
There is a global `_hx_field`PHP function, that also handles string functions:
https://github.com/HaxeFoundation/haxe/blob/development/std/php/Boot.hx#L363

**Comment by Simn** [comment]
The C2.func writing has to go, we cannot set methods on classes like that. Please remove that test (instead of commenting it out) so nobody gets the idea to comment it back in later.

**Comment by mockey** [comment]
What about the two lines above that (c.v2)? Remove these as well?

**Comment by Simn** [comment]
Yes, that tries to set a non-existing property.

**Comment by mockey** [comment]
mmmmh, java

**Comment by mockey** [comment]
I close this one, because it was from the wrong branch.

**Pull request closed without merging**
