### PR TITLE
[cpp] Allow multiple include meta entries

### PR DESCRIPTION
**Pull request by Aidan63**
https://github.com/HaxeFoundation/hxcpp/issues/885

I also found myself wishing I could add multiple include metas on a extern type so I decided to try and have a go at adding it. With these changes you can add multiple `include`, `depend`, `cppInclude`, and `headerInclude` meta tags, you can also add multiple strings to a single one of these metas and it will process them all.

```haxe
@:headerInclude("header1.h")
@:headerInclude("header2.h", "header3.h")
@:cppInclude("header4.h", "header5.h")
class Main
{
    static function main()
    {
        SomeLib.someFunc();
    }
}

@:include("other_header1.h", "other_header2.h")
@:include("other_header3.h")
@:depend("Class1.h", "Class2.h")
@:depend("Class3.h")
extern class SomeLib
{
    @:native("someFunc") static function someFunc() : Void;
}
```

I'm still very new to ocaml so sorry if I've done something horrifically wrong!

### CODE REVIEW

**Comment by haxiomic** [comment]
To keep things simpler what do you think about just allowing multiple instances of the meta rather than multiple arguments? So there's only one way of doing things rather than two

For example, I have a macro that tries to extract which headers a class is using, and just looping over `var includeMetas = meta.extract(':include')` is simpler than both looping over the metas and then looping over their args

**Comment by Aidan63** [comment]
Yeah, I think that makes sense and would be my preference (adding an extra include meta was what I tried before realising it didn't work). I added both after seeing the multiple in one meta suggestion in the issue to see what peoples preference was.

**Comment by RealyUniqueName** [comment]
@hughsando, are you ok with this?

**Comment by posxposy** [comment]
Sorry for the ping, but any news on this? It's a really useful feature! 
I'm always fighting with the current limitations of `@:include` which allows to include only one file. This PR finally solves the problem. 
Thanks for your time!

**Comment by hughsando** [comment]
It's been a little while since I've looked into gencpp, but this looks good/useful.

**Pull request merged**
