### PR TITLE
Add AES , Blowfish and 3DES encryption, crypto modes ( ECB, CBC, CTR ... ) and paddings 

### PR DESCRIPTION
**Pull request by flashultra**
Crypto modes and padding can be used for symmetric-key algorithms ( such as AES, 3DES, BlowFish, TwoFish , RC4 ). At the moment Haxe have  crypto package  which have limited functionality.  The only available lib for haxe is haxe-crypto based on Hurlant  AS3 crypto library with about 45K downloads.
 I could not say is it need to have separate library only for crypto ( including current implementation on SHA1, HMAC , etc)  or this should be part of haxe.crypto package.
 My pull request is based on the current state of Haxe. If you have any questions , I will  give it  my best to answer ,

### CODE REVIEW

**Comment by kevinresol** [comment]
IMO, the whole `haxe.crypto` package should actually be moved out of the standard library to a haxelib.

**Comment by Simn** [comment]
Could someone check if we depend on it, e.g. haxelib?

**Comment by sebthom** [comment]
I agree with @kevinresol this should be a separate haxelib. esp. in case of security issues a new haxelib release is considerably faster published than a new haxe release.

**Comment by ibilon** [comment]
> Could someone check if we depend on it, e.g. haxelib?

Haxelib needs crypto for md5/crc32, but like we said in #6586 that shouldn't be a blocking reason, there are ways around it.

**Comment by jdonaldson** [comment]
I guess this boils down to what's meant by "batteries included", and how important/complex the feature is.  I don't think folks outside the compiler team could've coordinated and accomplished all of the work needed for Utf8/crypto.  I think it's good we make a push towards it together and stabilize it.  Then, yes, in this case I think crypto should be split off into a haxelib, while basic hashing functions (md5, crc, sha) can stay in core.

**Comment by kevinresol** [comment]
Another opinion is that variable and function name should use camelCase instead of PascalCase, even they are private.

**Comment by ncannasse** [comment]
@flashultra would you agree to maintain a repository for crypto functions hosted on github.com/haxefoundation/crypto that would include your contributions as well as Sha224 / Sha256 / Hmac that would be moved out of haxe std library?

Would requires some unit tests wrt Unicode support as we do here https://github.com/HaxeFoundation/haxe/blob/c7d386d09558ce89ed4ce28353e10c0378d96c38/tests/unit/src/unitstd/Unicode.unit.hx#L109

**Comment by flashultra** [comment]
I can try to maintain crypto repository, but what is the main idea here ? Are all crypto functions will be moved ( includign MD5 , SHA1 as they are used by HMAC ) ? And what about Crc32, Basecode, Base64 ? 
Regarding AES, Blowfish, 3DES they will used bytes as input and output , so  will depends only from Bytes.ofString  for Unicode. I will need to do some cleaning and add more unit tests.

**Comment by ncannasse** [comment]
@flashultra we want to keep the most common one in haxe.crypto : Md5, Sha1 , Base64 (and BaseCode, which is generic) . Crc32 and Adler32 are necessary for haxelib (zip support I think). We can remove the others.

**Comment by ncannasse** [comment]
@flashultra I have created https://github.com/HaxeFoundation/crypto and sent you an invite

**Comment by Simn** [comment]
I suppose that means we can close here!

**Comment by flashultra** [comment]
@ncannasse  Thank you for invitation !  About test, I created new repository https://github.com/flashultra/crypto-test . Not sure how these tests will be invoke in crypto/ . I have not experinece with Travis

**Comment by ncannasse** [comment]
@flashultra better have the tests in the same repo. Ask @andyli about help with Travis setup ;)

**Comment by flashultra** [comment]
I created some tests ( same unit test used in haxe repository with small changes  ) , but I think not have access to settings for Travis and Appveyor:  https://github.com/HaxeFoundation/crypto/settings/installations ( this give me 404 error)  .
 Could  @andyli  check my settings on https://github.com/HaxeFoundation/crypto/ ? Thank you.

**Comment by andyli** [comment]
I've enabled TravisCI and AppVeyor. There are some problems with the tests which I will leave to you :)

**Pull request closed without merging**
