### PR TITLE
[php] fixes for Ereg.replace and Web.getParams

### PR DESCRIPTION
**Pull request by mockey**
fix for #4629
fix for Ereg.replace problem #4657 #4430 (capture groups with 1 character)

### CODE REVIEW

**Comment by Simn** [comment]
Awesome! Could you also add relevant test cases here? https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/EReg.unit.hx#L97

**Comment by mockey** [comment]
How does that work in unitstd? You simply add a line with `==`?

**Comment by Simn** [comment]
Yes, it's transformed by some macro.

**Comment by mockey** [comment]
OK, will add it.
BTW: How do I find a failing unit test, when all I get is:
```
Test.hx:221: DONE [6314 tests]
Test.hx:222: SUCCESS: false
```

**Pull request merged**
