### PR TITLE
merge genswf9 into genswf as we don't need two modules for that anymore

### PR DESCRIPTION
**Pull request by nadako**
we don't have swf8 support nowadays and we won't need modularity here since it's unlikely that there'll ever be any developments in swf format

### CODE REVIEW

**Comment by ncannasse** [comment]
I think we have already too big files for the compiler, I would prefer if we take actions to split them instead of merging them :) genswf9 handles the AVM bytecode part and genswf the SWF file format, maybe we can find a better naming and still keep them separate?

**Comment by nadako** [comment]
I see, that makes sense.

BTW, splitting source files is an interesting (and important) topic to discuss. I would also love to see smaller files (hello gencommon!), but what's the best approach? OCaml doesn't support packages, right? :)

**Comment by Simn** [comment]
I want to reorganize this and do some cleanup for Haxe 4. I'm already trying to group things into their own `module` so we don't have to much stuff lying around at file-module-level.

I'm also thinking about adding some directories:

```
generators
    codegen.ml
    genjs.ml etc.
macro
    interp.ml (this will likely be split up a bit)
optimization
    analyzer.ml
    dce.ml
    filters.ml
syntax
    ast.ml
    lexer.mll
    parser.ml
typing
    common.ml
    matcher.ml
    type.ml
    typecore.ml
    typeload.ml
    typer.ml
main.ml
```

**Comment by ncannasse** [comment]
Agree, but let's put all of these in a `src` package then
And yes, ocaml is not easy to refactor, the main problem being that mutually referencing modules are not possible, leading to use ref functions pointers (or context fields) to allow such recursions

**Pull request closed without merging**
