### PR TITLE
close #4825

### LINKED ISSUE #4825: macros and type building issue
I can't compile my work project codebase after commit eca310eac210fc3379ef560ab3fd22c20fc6344b, it says that it can't find a field which is a macro method. I'll try to reduce it to a reproducible example, but it won't be easy because the code involved is complex.

### PR DESCRIPTION
**Pull request by ncannasse**
close #4825

### CODE REVIEW

**Comment by Simn** [comment]
```
<PSvils> Simn: just got the type not found error, same as when I changed the 'if' statement to empty.
<Simn> Ok, I think that's actually good.
```

I expect that error to happen because from what I can tell luxe relies on undefined type-building order, i.e. a `@:genericBuild` as a typedef target being built early.

**Comment by ncannasse** [comment]
BTW, it is NOT OK to merge, I'm getting some other errors using this branch in my Evo2 codebase

**Comment by ncannasse** [comment]
... and I think I'm doing things correctly there

**Comment by Simn** [comment]
I don't know, this change looks very sane to me. Following typedefs like that is just wrong.

**Comment by ncannasse** [comment]
Yes, but I would like to investigate first why it cause a regression in Evo2, there might be something bad going on

**Comment by Simn** [comment]
Can we sort this out soon? Your typing order adventures are a bit scary so I would like to make sure things are working.

**Comment by ncannasse** [comment]
Will look at it next week, it's in my inbox and I'm going skying tomorrow :)

**Pull request closed without merging**
