### PR TITLE
Add copy() to DynamicAccess

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by Simn** [comment]
What's the point of that? Seems strange from an API point of view, especially if it only calls Reflect.copy.

**Comment by kevinresol** [comment]
> What's the point of that? Seems strange from an API point of view, especially if it only calls Reflect.copy.

Does that point holds for all functions in this abstract?

**Comment by Simn** [comment]
Yes, but the rest is at least part of the general map interface. I don't particularly mind adding this, but I wonder why copy is so special here.

Assigning to @nadako for decisions/opinions.

**Comment by kevinresol** [comment]
In fact, I have plans to add some more functions like `merge` which behaves like `Object.assign` in js.

**Comment by back2dos** [comment]
I guess `copy` really should be part of the `Map` interface too, because as an implementor you are almost certainly able to provide a more efficient implementation than looping the original and inserting into a new map.

OTOH adding a method to an interface is a breaking change, so we can't add it to `IMap` (although we could add it to all implementations already to use in performance critical situations).

**Comment by RealyUniqueName** [comment]
We can consider it for Haxe 4 :)

**Comment by Simn** [comment]
I'm open to suggestions regarding the Map interface. Until then I don't think we should add this.

**Comment by kevinresol** [comment]
While #6331 is merged, shall we reopen and merge this one?

**Comment by ncannasse** [comment]
You might want to add an optional "recursive = false" flag to it.

**Pull request merged**
