### PR TITLE
[js] Shared state for multiple haxe-generated  js modules

### LINKED ISSUE #7936: [js] $fid value sharing
I hit into some weird and very hard to debug error that was related to `$bind` function counter `$fid` being reset, this occured while loading some scripts dynamically. As the result, two methods on same object had the same __id__, leading to $bind returning the wrong closure.

I fixed it in js-classic here: 91dac26cb95dfb891c9bc46fff81d6927e402cc9

However I think the error can still reproduce without -D js-classic. The problem being that when you have several modules, while they cannot call each other directly they can exchange instances (through interfaces or other mechanisms), and thus having for each module its own `$fid` can make things go wrong. I think this is a particular case that would require to put $fid in "exports" so all modules $bind implementations references the same variable.

Ping @nadako @elsassph

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #7936

This PR modifies `$bind` and adds `$global.$haxe` code to the generated js:
```js
function $bind(o, m) {
	if (m == null) return null;
	if (m.__id__ == null) m.__id__ = $global.$haxe.nextId('fid'); //this was $fid++
	var f;
	if (o.hx__closures__ == null) o.hx__closures__ = {};
	else f = o.hx__closures__[m.__id__];
	if (f == null) {
		f = m.bind(o);
		o.hx__closures__[m.__id__] = f;
	}
	return f;
}
$global.$haxe = $global.$haxe || (function () {
	var ids = {};
	return {
		nextId: function (name) {
			if (ids[name] == null) ids[name] = 0;
			return ids[name]++;
		}
	}
})();
```
There is a probloem now that at the moment when generator should decide whether `$global` identifier needs to be generated, it does not know if  `$global.$haxe` will be required. And to avoid heavy refactoring I've made it to always generate the `$global` identifier.
So the minimal "Hello world" js looks like this now:
```js
// Generated by Haxe 4.0.0-rc.2
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("src/Main.hx:3:","Haxe is great!");
};
Main.main();
})({});
```

The new `js.Lib.getGlobalHaxe()` can be used to access `$haxe.$global` on the Haxe-side. And it is used in `haxe.ds.ObjectMap.assignId()` (see the diff)

### CODE REVIEW

**Comment by ncannasse** [comment]
Ping @elsassph and @back2dos for feedback

**Comment by ncannasse** [comment]
@nadako as well

**Comment by ncannasse** [comment]
Personally, I think that's a bit overkill. Having a single $haxeUID : Int counter - even if shared amount several kind of different uids - seems enough for me, as we don't really care about having contiguous ids for both objects and closures

**Comment by elsassph** [comment]
I agree a single counter would be enough. Aside from that I like the idea of the nextId function.

**Comment by nadako** [comment]
I'm also in favor of single id, or hardcoded multiple ids, as i don't like the mapping lookup for nextId

**Comment by RealyUniqueName** [comment]
Changed the code to `$global.$haxeUID`.
Now the generated js is:
```js
function $bind(o, m) {
	if (m == null) return null;
	if (m.__id__ == null) m.__id__ = $global.$haxeUID++; //this was $fid++
	var f;
	if (o.hx__closures__ == null) o.hx__closures__ = {};
	else f = o.hx__closures__[m.__id__];
	if (f == null) {
		f = m.bind(o);
		o.hx__closures__[m.__id__] = f;
	}
	return f;
}
if(typeof $global.$haxeUID == "undefined") $global.$haxeUID = 0;
```
And `js.Lib` got the method `getNextHaxeUID()`, which is used in `ObjectMap`.

**Comment by nadako** [comment]
> ```js
> $global.$haxeUID; //this was $fid++
> ```

Looks like this is missing a `++`?

**Comment by RealyUniqueName** [comment]
Fixed :)

**Pull request merged**
