### PR TITLE
[php] fixed EReg.split when called with malformed utf8 input

### PR DESCRIPTION
**Pull request by AlexHaxe**
had a weird error after migrating an old PHP application to Haxe 4... turns out some database entries had malformed utf8 data

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
I think `Bytes.toString()` is not specified for malformed strings. It's probably better to change the test to `Bytes.getString()` with `RawNative` encoding.

**Comment by RealyUniqueName** [comment]
Also, please, merge latest CI fixes from development branch.

**Comment by AlexHaxe** [comment]
seems like lua is not happy...
 don't know about hl or macro, they run fine on my system but that's Linux

**Comment by RealyUniqueName** [comment]
AFAIR Haxe does not guarantee handling of malformed utf8 strings.
I'd merge the PR but, the test bothers me. I doubt it's a good thing to specify it via a test for a single case on a single target.

**Comment by AlexHaxe** [comment]
I can remove the testcase if that helps, my last commit restricted it to PHP because that's the target that had a problem.

**Pull request merged**
