### PR TITLE
`enum abstract` syntax

### PR DESCRIPTION
**Pull request by Simn**
Allows `enum abstract` instead of `@:enum abstract` and deprecates the latter. We still use `@:enum` internally for now, so most of the changes here are in .hx files.

I'll follow my usual policy of "merge if nobody complains".

### CODE REVIEW

**Comment by Justinfront** [comment]
```
if p <> null_pos then ctx.com.warning "`@:enum abstract` is deprecated in favor of `enum abstract`" p;
```
would this require #if haxe3 code in libraries or will both be supported for awhile?

**Comment by Simn** [comment]
It's a warning, so it's gonna work either way. I think we have a way to disable warnings now as well. @RealyUniqueName should know more.

**Comment by ncannasse** [comment]
Regarding deprecation warnings: we have several of them for Haxe 4.0 , I wonder how we should handle them. For instance compile with -D haxe3-syntax would disable all these warnings. Whereas compiling with -D haxe4-syntax would turn them into errors.

**Comment by ncannasse** [comment]
Question:  `enum abstract` or `abstract enum` ?

**Comment by Simn** [comment]
Conceptually, it's still an abstract and comes with all abstract features. So `enum abstract` is correct.

**Comment by Gama11** [comment]
I agree that a define to disable Haxe 4 specific warnings would be helpful, all the warnings can get annoying, especially if you can't fix them because they're in third-party libs.

I think `enum abstract` makes sense because `enum` in this case is like a modifier for `abstract`.

**Comment by back2dos** [comment]
@R32 In theory it's not a bad idea. In practice there are multiple differences to consider:

1. abstracts have more features (implicit casts, operator overloading, methods)
2. abstracts don't exist at compile time: `Type.typeof(Bar.A)` is `TEnum(Bar)` and `Type.typeof(Foo.A)` is `TInt`. Corollary: enums unify with `EnumValue`, abstracts don't.

**Comment by Simn** [comment]
I'll go ahead and merge this, then disable the deprecation warning for now. We can re-enable it once we know how to deal with the Haxe 4 transition in general.

**Comment by Simn** [comment]
It just occurred to me that we can check for the presence of the `hx3compat` define. This way we can keep some behavior if `-lib hx3compat` is in place.

**Pull request merged**
