### PR TITLE
Remove old PHP target

### PR DESCRIPTION
**Pull request by RealyUniqueName**
I can't push to @simn's repo so i created a new PR instead of #6604

### CODE REVIEW

**Comment by Simn** [comment]
Should we take this opportunity to get rid of these --php-front etc. command line arguments?

**Comment by Simn** [comment]
Also we already have a conflict, sorry about that...

**Comment by RealyUniqueName** [comment]
> Should we take this opportunity to get rid of these --php-front etc. command line arguments?

We can remove `--php-fron` and `--php-lib`. 

`--php-prefix` is really useful. But there is also `--no-root` for C# which solves similar problem. Maybe we should think about common directive for such things.

**Comment by Simn** [comment]
I think all of these should become `-D` flags instead.

But we can merge this first so it's out of the way.

**Comment by Simn** [comment]
F

**Comment by RealyUniqueName** [comment]
`--php-front`, `--php-lib`, `--php-prefix` changed to `-D` flags in 67e4c6336531b4b494218ec2061f3f3f5e0a0fce

**Pull request merged**
