### PR TITLE
TIdent

### PR DESCRIPTION
**Pull request by Simn**
This adds a new node `TIdent` to the typed AST and gets rid of the concept of unbound variables.

I'm sure this will break something because it's a big change and very easy to miss the pattern in some places. We'll have to deal with this step by step.

@hughsando: The way I handle this in gencpp is quite bad because I just re-introduce unbound variables and use CppVar. I thought we could always use CppGlobal, but I had some problem with `__trace` there. You may want to check that.

### CODE REVIEW

**Comment by ncannasse** [comment]
While I like the idea, I think TIdent is wrongly named since we already have EConst (CIdent) in untyped AST. Maybe TGlobal or TUnbound would be more appropriate ? (and yes I know it's not fun changing it again, but better doing it now than keeping it this way for the next ten years or so)

**Comment by Simn** [comment]
I don't really care how we call it, it's a simple string replace to change that now. Can't say I really understand your reasoning about EConst (CIdent), but I actually like TUnbound more anyway.

**Comment by hughsando** [comment]
TUnbound makes sense to me too.  Do I need to fix or check something?

**Comment by Simn** [comment]
> Do I need to fix or check something?

Yes, see my comment above.

**Comment by hughsando** [comment]
I took the opportunity to allow externs that are not in the global namespace, so should be good now.  The @:native specification pretty much makes the `__global__` and untyped directives redundant but I've kept the legacy option.

**Pull request merged**
