### PR TITLE
Upload nightly builds through Travis/AppVeyor

### LINKED ISSUE #6149: Nightly builds are broken again
The latest builds for all platforms (but most importantly linux64, which powers Travis) were on March 23rd:

http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/

Presumably 501b7a64887fdbe1eae55cf275cd49029d7aa1a9 broke the builds. Ping @waneck.

### PR DESCRIPTION
**Pull request by waneck**
This is the initial implementation to use both Travis and AppVeyor to submit the builds to the nightly builds s3 repo. We still need to build windows-installer and mac-installer (and Linux 32-bit will be discontinued), but I think this initial implementation can already be merged (as a flattened commit ;) )

Closes #6149

### CODE REVIEW

**Comment by andyli** [comment]
That's great! Looks good to me!
We still have to add an option to static link the libraries and enable it in CI.
I am going to merge it and let's improve from here :D

**Comment by Simn** [comment]
\o/

**Comment by Gama11** [comment]
...aand Flixel's Travis is broken:

>haxe: symbol lookup error: haxe: undefined symbol: pcre_free_study

https://travis-ci.org/HaxeFlixel/flixel/jobs/230831096#L354

**Comment by Simn** [comment]
> undefined symbol: pcre_free_study

<strike>That's because Bernie didn't win</strike> I have no idea where that would come from... did you try rebooting your computer?

**Comment by andyli** [comment]
That's why we need static linking ;)

```
$ readelf -d haxe

Dynamic section at offset 0x510d88 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpcre.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
...
```

So, until we static link them, you have to
```
sudo apt-get install zlib1g libpcre3 -y
```

**Comment by Simn** [comment]
I thought we already had dynamic linking supported, but I guess that was only on Windows.

**Comment by andyli** [comment]
Yeah, currently things are dynamically linked. So for Windows, it's just a matter of bundling the dll files and place them next to haxe.exe and Windows can handle that perfectly. On Unix, its a bit complicated, the shared libs (*.so) have to be placed in special locations (e.g. /usr/lib), or one have to set some special env var, or modify the executable in some way. Static linking would be the most user-friendly option for Unix.

**Comment by Gama11** [comment]
Hmm, somehow that didn't work - same error still.. https://travis-ci.org/HaxeFlixel/flixel/jobs/231064880#L166

**Comment by ibilon** [comment]
Haxe travis has `dist: trusty` while HaxeFlixel's doesn't, so the error might be from the different version of the libs.

> Static linking would be the most user-friendly option for Unix.

The most user friendly option is a package rpm+deb that tell the package manager to find the libraries and put them where they should go.

**Comment by andyli** [comment]
> Haxe travis has dist: trusty while HaxeFlixel's doesn't, so the error might be from the different version of the libs.

Exactly! https://github.com/HaxeFlixel/flixel/pull/2065

> The most user friendly option is a package rpm+deb that tell the package manager to find the libraries and put them where they should go.

I kind of agree. And we have ppa:haxe/snapshots for Ubuntu, although I stopped Travis to upload there since I haven't sort out the opam dependencies.

**Comment by ibilon** [comment]
We can upload the rpm and deb to s3 until/if we create a haxe-nigtlly repositories, but they are still useful on their own. And a lot easier to install for someone unfamiliar with linux.

**Comment by andyli** [comment]
It's not that simple. Both rpm and deb binary packages are arch-dependent, that means we will have to build both amd64 and i686. I'm not sure how to build the i686 one on Travis...
Also, different Debian releasees and different rpm-based distros have their own separated repos, containing different versions of libs. so it would be nearly impossible to declare package dependency properly. We can bundle the *.so files instead, but that goes to the same problem of not using rpm/deb.

Snap and flatpak can be the ultimate solution, but they are only supported in recent versions of Linux distros....

**Comment by waneck** [comment]
I remember we were statically linking on the old build servers. I'll see what I can do for mac and linux

**Comment by andyli** [comment]
I *think* I've got the static linking right as of now. @ibilon @Gama11 can you try the nightlies with your projects?

A note:
The Mac binaries require OS X 10.10+, and the Linux binaries *probably* require Ubuntu Trusty+ (*probably* because I'm never sure about libc).
They also requires a working Neko install, such that haxelib can load libneko.

**Comment by Gama11** [comment]
Flixel has been running Haxe dev again for a few days now. ;) https://github.com/HaxeFlixel/flixel/commit/3c68ef4f67a817cd4719e16a2b99bb27c17f65c4 No Trusty required it seems.

**Comment by ibilon** [comment]
Works now, even when using the default osx version.

**Pull request merged**
