### PR TITLE
hxSerialize performance improvement for references

### PR DESCRIPTION
**Pull request by thomasuster**

### CODE REVIEW

**Comment by ncannasse** [comment]
Maybe using a single get + null check instead of exits+get would be even more efficient
@Simn any restrictions for ObjectMap that should apply here ?

**Comment by thomasuster** [comment]
@hughsando An

**Comment by thomasuster** [comment]
@hughsando Any concerns for GC?

**Comment by thomasuster** [comment]
@ncannasse An invalid get would return 0, which is a valid index, so I think it has to use .exists unless I change the map value type to Null<Int> maybe. Right?

**Comment by Simn** [comment]
Does it return 0 or null? The get method has a `Null<T>` return type but I always forget what that entails.

**Comment by ncannasse** [comment]
It will return null

**Comment by thomasuster** [comment]
Sorry for not replying earlier. I also tested this, it returns null. The files changes in PR has the get & null check.

**Comment by Simn** [comment]
Let's see how it goes!

**Pull request merged**
