### PR TITLE
[php] modified generated comparison function

### PR DESCRIPTION
**Pull request by mockey**
The original function generates a comparison between objects `$a` and `$b` in the form of:
`if((is_object($_t = $a) && !($_t instanceof Enum) ? $_t === $b : $_t == $b))`
So all objects except Enums are compared with `===`, the rest (including Enums) with `==`.
I would prefer:
`if((is_object($_t = $a) && ($_t instanceof Enum) ? $_t == $b : $_t === $b))`
So only Enums are compared with `==` and all the rest (not only objects) is compared with `===`.
This has the advantage, that e.g. PHP native arrays are compared with `===`.
Hope I got the OCaml right.

### CODE REVIEW

**Comment by andyli** [comment]
Thanks a lot for looking into this. But would you run the unit test on your side before submitting a PR? It is easy: https://github.com/HaxeFoundation/haxe/tree/development/tests
You can run it locally or config TravisCI for your forked repo : )

**Comment by mockey** [comment]
So a unit test failed? Is it possible to see which one? When running locally, I only see:
```
Test.hx:221: DONE [6314 tests]
Test.hx:222: SUCCESS: false
```

**Comment by Simn** [comment]
That's odd... here's how I usually run the tests:

```
cd github\haxe\tests\unit
compile-php.hxml
php bin/php/index.php
```

You see the failures on our CI too: https://travis-ci.org/HaxeFoundation/haxe/jobs/94408529#L467

**Comment by mockey** [comment]
Ah, these are the failures?
`TestOps.hx:35: 5 should be 5`

**Comment by Simn** [comment]
Yes

**Comment by mockey** [comment]
Hm, interesting. I learn things about PHP here, I never wanted to know :-)

**Comment by mockey** [comment]
OK, the thing is: Int unifies with Float in Haxe and it doesn't in PHP (of course). There is a special function `hx_equal` in Boot that deals with this (and also `null`) normally, but in a function like `eq<T>`, the code from above comes into play and then `===` is not good for comparing Float and Int of course. But the other way is not correct as well, that should lead to errors comparing `""` and `null` with `==` e.g. The correct way would be adding `hx_equal` to the code above, I think.

**Comment by mockey** [comment]
Actually `20/2/2 === 5` is true in PHP, but `5. === 5` (what gets replaced by the compiler) is not.

But anyway, as I said, `eq("", null)` and `eq(false, null)` are both `true` with the old function, that's probably not tested in unit tests.

So I integrated `_hx_equal` in the function above and after one more fix to `Sys.getEnv` (returns `false` not `null`) unit tests are working. I try another pull request then.

**Comment by Simn** [comment]
Can we get a test for what was previously failing?

**Comment by mockey** [comment]
As a separate issue test?
I guess `eq("", null)` and `eq(false, null)` being  `true` are issues? These are probably checked in sys tests in some other way. The thing is that the php generator produces different code for `false == null` and `eq(false, null)`.
The other thing would be comparison of native arrays with `===` instead of `==`.
BTW: I think it is not so good that this code is in genphp.ml. Maybe a general function in Boot.hx would be better?

**Comment by Simn** [comment]
My thinking is that if this fixes something, there should be a test we can add that would fail without this change.

**Comment by mockey** [comment]
Sure. I'm just asking: You want the the test as Issue4695.hx then?
And are `eq("", null)` and `eq(false, null)` being  `true` bugs or not?

**Comment by Simn** [comment]
Making an issue test is fine.

And yes these are bugs.

**Comment by mockey** [comment]
So if it's just for PHP, do you put the Test class in `#if php` or the test functions?

**Comment by Simn** [comment]
These assumptions should hold on all targets.

**Comment by mockey** [comment]
Yes, but the native array test is php specific (with `untyped __php__`), so put this in `#if php`?

**Comment by Simn** [comment]
Yes

**Comment by mockey** [comment]
Uhm, actually there isn't an issue for this. Shall I create one? Or can I use the PR id #4695 for the test?

**Comment by Simn** [comment]
Sure, they use the same numbering.

**Comment by mockey** [comment]
OK, the added test should fail with the old version and work with the new one. Hope it's OK like this.
BTW: Is it normal, that OCaml recompiles all the ml-files with `make haxe` when I just changed the genphp..ml or is there a way to speed this up (like in C that only the changed stuff gets compiled)?

**Comment by Simn** [comment]
Hmm, that doesn't happen for me. I couldn't work on the compiler if it did.

Not sure why that would happen. What OS are you on?

**Comment by mockey** [comment]
Argh. You can't compare `false` and `null` on static platforms of course. So I put this into `#if !(cpp || flash9 || as3 || java || cs)`? There isn't a general `static-platform` flag or so, is there?

**Comment by mockey** [comment]
> Hmm, that doesn't happen for me. I couldn't work on the compiler if it did.
Not sure why that would happen. What OS are you on?

Linux. Maybe that's because I switched git branches. Or something is setup wrong.

**Comment by Simn** [comment]
Thanks, I've merged this locally!

**Pull request closed without merging**
