### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Aurel300**
I guess we need a HashLink 1.11 release @ncannasse ?

### CODE REVIEW

**Comment by kLabz** [comment]
Should we really keep the 4.0.0 previews and rcs in there? If it's only to have the exact version of haxe for each and every HL version, maybe that should be documented there instead?

**Comment by Aurel300** [comment]
I agree it seems unnecessarily long now.

**Comment by Simn** [comment]
Yes we can axe all those.

**Comment by ncannasse** [comment]
4.0 is compatible with HL 1.10, can use HL 1.11 date functions with -D hl-ver=1.11.0 (if I remember correctly)

**Comment by Gama11** [comment]
>4.0 is compatible with HL 1.10

The readme says 1.11 now though - is that intentional?

**Pull request merged**
