### PR TITLE
Set default value of Process.exitCode as true for backward compatibility

### PR DESCRIPTION
**Pull request by ibilon**
Fix 4bdbc88b0afaa6607d20276702edb25df4518f2e
`?block : Bool` doesn't defaults to false but null, and the backward compatibility requires true as default since it was blocking before.

Added the argument to the php7 std for consistency and made it blocking only,
but maybe it could be made non blocking, cc @RealyUniqueName

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Yes, it could be non-blocking for php. I'll do it later today.

**Comment by RealyUniqueName** [comment]
@ncannasse Can this PR be merged?

**Comment by ncannasse** [comment]
@ibilon why did you change the signature on every platform ?

**Comment by ibilon** [comment]
It's better to have it default to true instead of null, and no point in making the argument optional.

**Pull request merged**
