### PR TITLE
String.index of

### PR DESCRIPTION
**Pull request by Simn**
see #5271

* [x] C++
* [x] JVM
* [x] Flash
* [ ] Lua

### CODE REVIEW

**Comment by Simn** [comment]
Pushing this back because it's a corner case that involves too many targets and people.

**Comment by Simn** [comment]
Updated the branch, both JVM and Flash fail with this:

```
line: 45, expected 0 but it is -1
line: 51 expected 0 but it is -1
line: 60, expected 0 but it is -1
```

C++ fails on those plus these:

```
line: 15, expected 0 but it is -1
line: 21, expected 0 but it is -1
line: 30, expected 0 but it is -1
```

And lua... uhm, I don't know what that's about:

```
rc/hxluasimdjson.cpp: In function ‘int ParsedObject_at(lua_State*)’:
src/hxluasimdjson.cpp:218:23: warning: ‘simdjson::simdjson_result<simdjson::dom::element> simdjson::dom::element::at(std::string_view) const’ is deprecated: For standard compliance, use at_pointer instead, and prefix your pointers with a slash '/', see RFC6901  [-Wdeprecated-declarations]
  218 |     element.at(pointer).tie(returned_element, error);
      |                       ^
In file included from src/hxluasimdjson.cpp:4:
src/simdjson.h:5979:33: note: declared here
 5979 | inline simdjson_result<element> element::at(std::string_view json_pointer) const noexcept {
      |                                 ^~~~~~~
Error: Process completed with exit code 1.
```

**Comment by Simn** [comment]
I have fixed JVM and C++, and ignored Flash.

The lua issue I have no idea.

**Comment by tobil4sk** [comment]
> And lua... uhm, I don't know what that's about:

That's just the hxluasimdjson compilation output (just warnings, not errors), which for some reason comes after the test output:

```
results: SOME TESTS FAILURES (success: false)
unit.issues.Issue5271
  test: FAILURE ................F.............................
    line: 30, expected 0 but it is 2
```
https://github.com/HaxeFoundation/haxe/actions/runs/7830066531/job/21363364263?pr=7402#step:11:300

**Comment by Simn** [comment]
Oh damn, you're right! I really suck at reading CI logs it seems.

**Comment by Simn** [comment]
I'm dodging the lua test for now because I don't have a local lua installation, which makes fixing lua things a nuisance. Will open an issue to track this and then finally merge this PR.

**Comment by kLabz** [comment]
Probably need to update docs too? For example (not sure there's more actually..) that part doesn't seem to apply anymore:
> If `startIndex` is negative, the result is unspecifed

**Comment by Simn** [comment]
Ideally we would solve this as part of #8905, but we can add this before as well.

**Pull request merged**
