### PR TITLE
[hxb] Implement shared string pools

### PR DESCRIPTION
**Pull request by Simn**
This implements what I'm talking about in #11510. When using `--hxb`, a top-level `StringPool.hxb` is generated, which is then read once and passed to all hxb readers. For now, this is always activated. Once #11507 is merged we can make this configurable. I think the default should probably be off because it's unclear if this actually yields better performance characteristics for completion and such.

The cache-aspect of this is not implemented yet. @kLabz Could you handle this? It should be very straightforward because all hxb readers have access to a  `cc` instance anyway, so if that carries a string pool we should be good to go. The only part I'm worried about is `--hxb` using the data from the cache, but perhaps that is also just a matter of writing the pool from cc to StringPool.hxb.

Edit: Note that the cache version should not call `StringPool.finalize` because we never want finalize the persisted pool.

### CODE REVIEW

**Comment by kLabz** [comment]
I still need to (at least) tackle the "`--hxb` using the data from the cache" part, for which I'm not sure yet what strategy to apply since macro and non macro context use different `cc` instances, and thus different string pools. Maybe we should write `StringPool.hxb` and `StringPool.macro.hxb`? (but that would remove quite a bit of optimization from the generated file.. which may not be an issue?)

**Comment by Simn** [comment]
Yes I think that's what the "TODO: macro vs non macro" was about.

**Comment by kLabz** [comment]
Yeah that was me adding that when merging dev with the config changes x)

**Comment by kLabz** [comment]
Adding to 5.0 preview 1 because I don't remember what the status is here (thought this was merged already..) so I should at least check what's up.

**Comment by Simn** [comment]
Huh, I also thought we merged this already...

**Comment by kLabz** [comment]
So, this lgtm.

Rudy CI (well, the parts that I updated) complains a bit about changing IDs but that applies to `development` too and probably isn't relevant anyway.

I see around 33% time reduction on display requests, which is pretty nice (though I'm still barely under 200ms).

**Comment by Simn** [comment]
The configuration is still missing, but I'd be fine with adding that "later".

**Comment by kLabz** [comment]
Opened #11648 for this, I need that small perf boost to work on further improvements :)

**Pull request merged**
