### PR TITLE
Omit internal defines from --help-defines

### PR DESCRIPTION
**Pull request by Gama11**
`define_parameter ` can eventually also be used for platforms etc similar to `meta_para
`.

### CODE REVIEW

**Comment by Simn** [comment]
I don't know about this, it's a lot of changes for 4 internal defines. I think we should instead remove these defines altogether and replace their checks with `raw_defined`.

**Comment by Gama11** [comment]
You don't think the ability to add other params to defines is useful? Marking defines as platform-specific, similar to how it's done with metas, etc.

**Comment by Simn** [comment]
I'm not a big fan of the metadata documentation either. It's annoying to keep it in sync with the website version and there's not enough space to document anything meaningful anyway.

**Comment by Gama11** [comment]
What's the alternative, not having any docs available for them on the command-line at all?

**Comment by Gama11** [comment]
One option would be to move these to `.json` or some other format that is then loaded by common.ml - from that, it shouldn't be too hard to also generate the docs on the website.

**Comment by Simn** [comment]
I'll have to think about how to do this. It might indeed not be necessary to have the documentation in the OCaml sources.

**Pull request closed without merging**
