### PR TITLE
std/cs/Flags.hx documentation fix

### PR DESCRIPTION
**Pull request by markknol**
https://github.com/dpeek/dox/issues/128#issuecomment-104256370

### CODE REVIEW

**Comment by Simn** [comment]
Thanks!

**Comment by waneck** [comment]
As nadako pointed out, this change is actually wrong. We need to revert it

**Comment by Simn** [comment]
Eh... it looked really natural. Thanks for noticing that.

**Comment by markknol** [comment]
Oh, I'm sorry.

**Pull request merged**
