### PR TITLE
[macro] apply @:native for extern enum

### LINKED ISSUE #11598: [dev] Field index for SSL_IS_SERVER not found on prototype mbedtls._SslEndpoint.SslEndpoint_Impl_
When building my project for the JDK target with the `development` version of Haxe, I get the following error:

```
Field index for SSL_IS_SERVER not found on prototype mbedtls._SslEndpoint.SslEndpoint_Impl_
```

This is the full output of the compilation when using `haxe ./generated/build.hxml`. There are no line numbers or additional diagnostic information, even when using `--verbose`, thus I haven't been able to figure out what feature is causing the issue or create a minimal reproduction.

**Platform:** Windows 10 x64
**Haxe Version:** `5.0.0-alpha.1+9aae69c`
**Project Link**: https://github.com/EliteMasterEric/PickHaxe-Samples/tree/master/madeinhaxe

### LINKED ISSUE #11631: Bug during haxe --macro Field index for SSL_IS_SERVER not found
Run the following code with `haxe --macro Config.main()` result in error `Field index for SSL_IS_SERVER not found on prototype mbedtls._SslEndpoint.SslEndpoint_Impl_`
Since https://github.com/HaxeFoundation/haxe/commit/944d4fdba9cce40d0e00c3a2495d0180e6e1f3c5 ( https://github.com/HaxeFoundation/haxe/issues/11481 )

It works fine with `haxe --run Config`.

```haxe
class Config {
	public static function main() {
		Sys.println("Config...");
	}

	public static function updateHaxeLinux() {
		new haxe.Http("https://build.haxe.org/builds/haxe/linux64/");
	}
}
```

### PR DESCRIPTION
**Pull request by kLabz**
Closes #11631 

See also 944d4fdba9cce40d0e00c3a2495d0180e6e1f3c5 / #11481

### CODE REVIEW

**Comment by Simn** [comment]
Making this conditional seems strange if the real filters don't do the same. What's the rationale here?

**Comment by kLabz** [comment]
I'm actually having doubts too.

Rationale is that `eval` target does apply `@:native`, which is used for mbedtls extern enums.

I want the same to happen with macro context, but it's a bit more involved than I first thought because macro context does have both externs for current targets and eval externs...

Edit:
Given that such externs would only work for std anyway (or maybe plugins? not sure that's still used tbh), we could use some trick there to identify "eval externs", but would be nice to do so in a not too hacky way

**Comment by kLabz** [comment]
Well.. technically "target externs" should not be loaded in macro context, but I can still see some problematic edge cases.

I don't see any with only doing this for `extern enum`, though.

**Comment by Simn** [comment]
So what exactly breaks if we just apply this to everything?

**Comment by kLabz** [comment]
#11481 does

**Comment by Simn** [comment]
Ah, I completely forgot about that. In that case I think this change is fine, though it makes me wonder if a variant of #11481 with enum abstracts could exist.

**Comment by kLabz** [comment]
Turning into a draft while adding a test because it's not working properly for some reason atm :thinking: 

Edit: right, it's enum abstract, not enum...

**Pull request merged**
