### PR TITLE
New js.html externs generated from WebIDL

### PR DESCRIPTION
**Pull request by aduros**
The old externs were getting crusty, and had numerous issues. This improved version fixes many of them:

- *Much* more accurate and complete overall. Lots of new modern web APIs, and fixes to the existing ones.
- Constructor params are typed instead of Dynamic.
- Abstract enums in places instead of strings.
- A lot easier to maintain and keep up to date. Mozilla maintains both the WebIDLs and parser in one place. With the old WebKit IDLs, updating would usually break everything. Also, the tools used to generate the externs are now in the Haxe repo instead of out in my Browser.hx repo.

There are breaking API changes here! Mainly classes automatically being renamed to match their true name in JS, and WebKit-only or experimental APIs being dropped. I've tried to document them in the README at https://github.com/HaxeFoundation/haxe/tree/webidl-externs/extra/js_externs.

I also made all HTML elements extend HTMLElement instead of Element directly, as suggested by #3644. Same with Document and HTMLDocument.

The externs don't contain documentation pulled from MDN anymore. I don't think that's worth re-adding, especially since the old docs were often poorly formatted and many times completely incorrect.

### CODE REVIEW

**Comment by Simn** [comment]
Can we add @:deprecated` typedefs for at least Document and Element?

**Comment by aduros** [comment]
Unfortunately no, those classes still actually exist. Before the inheritance chain was eg: Node -> Element -> CanvasElement, now it's Node -> Element -> HTMLElement -> CanvasElement. However, since the fields on HTMLElement are rarely used, I don't think this will have too much impact. There may be rare cases where you need to explicitly cast to HTMLElement now though.

All the third party libs we test against still build, so that's encouraging. Flambe only required one change (setting XMLHttpRequest.responseType to an enum value instead of a raw string).

**Comment by Simn** [comment]
Okay, I'm fine with the breaking changes then.

Only thing I'm not sure about is having `extra/js_externs` in the Haxe repository. It might be better to have that in a separate repository I would think.

**Comment by aduros** [comment]
I'd be ok with that.

**Comment by aduros** [comment]
I would like to get feedback from more projects about that. From what I can tell the impact is very small. Most projects seamlessly migrate without any code changes.

**Comment by aduros** [comment]
No feedback, anybody mind if I merge this later today? (with Simn's suggestion of keeping the generator on another repo)

**Comment by aduros** [comment]
Generator is at https://github.com/HaxeFoundation/html-externs. Please add issues and fixes there.

**Pull request closed without merging**
