### PR TITLE
Improve `make_static_call`

### PR DESCRIPTION
**Pull request by Simn**
Opening a PR so that I have a single place to put my conclusions.

The problem with `make_static_call` is that it currently spawns a bunch of monomorphs that are never unified with anything. We have a mechanism now to unify typed call arguments and we should use it here.

However, we're running into problems with some tests related to `@:multiType`, in particular situations where we have `Map<NotString, X>` with `NotString` NOT being assignable to `String` but still supposed to end up as `StringMap`. This means a proper unification fails.

If we want to keep this behavior (related issues: #4777, #9712, #10098) we have to add a special case for it "somewhere". I'm having a hard time understanding why it should be justifiable to have a type that is not assignable to another type except when used as a key to `Map`. However, multiple people whose opinions I usually value highly are somehow totally fine with that idea, so maybe I just have to find the right mindset...

### CODE REVIEW

**Comment by Simn** [comment]
@kLabz Could you check how badly this messes up Shiro things? #4777 mentions CastleDB so I expect apocalypse.

**Comment by kLabz** [comment]
Yeah there are some failures:
```
src/Console.hx:1117: characters 18-27 : error: RegionKind should be String
src/Console.hx:1117: characters 18-27 : ... have: haxe.IMap<RegionKind, ...>
src/Console.hx:1117: characters 18-27 : ... want: haxe.IMap<String, ...>
```

**Comment by kLabz** [comment]
Hide breaks too. Need https://github.com/HeapsIO/hide/pull/230 for module resolution, and then we get

```
hrt/prefab/l3d/HeightMap.hx:805: characters 47-56 : error: hrt.prefab.l3d.HeightMaPTexturePathKind should be String
hrt/prefab/l3d/HeightMap.hx:805: characters 47-56 : ... have: haxe.IMap<hrt.prefab.l3d.HeightMaPTexturePathKind, ...>
hrt/prefab/l3d/HeightMap.hx:805: characters 47-56 : ... want: haxe.IMap<String, ...>
```

**Comment by Simn** [comment]
Alright, thanks... so we need more hacks.

**Comment by Simn** [comment]
@yuxiaomao Could you check if Shiro survives this?

**Comment by yuxiaomao** [comment]
All projects survived with this PR.

**Pull request merged**
