### PR TITLE
Deprecate Std.instance; Add Std.downcast

### LINKED ISSUE #5946: [js] Std.instance does not work with instance implements interface
Std.instance(value, c) will fail when the value implements the interface c.

maybe modify as below:
```haxe
	public static inline function instance<T:{},S:T>( value : T, c : Class<S> ) : S {
		return Std.is(value, c) ? cast value : null;
	}
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #5946 

* Deprecates `Std.instance()`
* Adds `Std.downcast()`, which also works for interfaces on all targets

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Cpp failure is unrelated.

**Comment by ncannasse** [comment]
Maybe trying to downcast to unrelated interface should be tested as well?

**Comment by RealyUniqueName** [comment]
It fails at compile time with constraints failure.

**Comment by RealyUniqueName** [comment]
Added a test for unrelated classes/interfaces to `tests/misc/projects`

**Pull request merged**
