### PR TITLE
Fix for issue #8983

### PR DESCRIPTION
**Pull request by codeservice**
Test for issue #8983

### CODE REVIEW

**Comment by Aurel300** [comment]
Why did you close your two PRs and open a third one? x) You could have just pushed the test to the original PR …

**Comment by codeservice** [comment]
I didn’t know how I can push test to original PR on web interface.I am
using only web interface for haxe.

**Comment by Gama11** [comment]
By editing files on that branch on your fork.

**Comment by codeservice** [comment]
Yes, that is exactly what I did with new proposal when I find out how can I
make it in web interface.

**Comment by Simn** [comment]
Let us please make an effort to not commit any more `untyped` to the standard library.

**Comment by Simn** [comment]
There hasn't been any action here for a while and I don't think this solution is quite right in the first place, so I'll close this PR.

**Pull request closed without merging**
