### PR TITLE
[lua] Fix haxe.Utf8.iter, charCodeAt and validate

### PR DESCRIPTION
**Pull request by mandel59**
This fix is based on decode_code_point of [unifill/Utf8.hx](https://github.com/mandel59/unifill/blob/master/unifill/Utf8.hx)

### CODE REVIEW

**Comment by Simn** [comment]
Could you add a test case here? https://github.com/HaxeFoundation/haxe/tree/development/tests/unit/src/unit/issues

**Comment by jdonaldson** [comment]
Looks good to me, thanks for this @mandel59.

**Comment by Simn** [comment]
The test seems to fail on several other targets, so don't merge this yet.

**Comment by Simn** [comment]
Too late! Check travis to see what targets are failing and #if them out for now please.

**Comment by jdonaldson** [comment]
Hah, yeah I'll send you a note on which ones failed.

**Comment by jdonaldson** [comment]
looks like neko, macro, and cpp might have problems.  Hugh's cpp is failing for another reason, so I took it out just to get rid of noise while he works.

https://github.com/HaxeFoundation/haxe/commit/a091ec4e4086103a5818210befc989c252b07e24

**Pull request merged**
