### PR TITLE
[js] generate `value instanceof MyClass` instead of `Std.is(value, MyClass)`

### PR DESCRIPTION
**Pull request by RealyUniqueName**

### CODE REVIEW

**Comment by nadako** [comment]
There are these weird "native" thingies that are checked by `js.Boot.__instanceof`, we gotta make sure this doesn't break it.

**Comment by Simn** [comment]
Man, I really wish this could be handled in the type system...

**Comment by RealyUniqueName** [comment]
> There are these weird "native" thingies that are checked by js.Boot.__instanceof, we gotta make sure this doesn't break it.

Looks like all of them are handled few lines above my addition.

Also this change only affect cases where `MyClass` is explicitly written and typed as `Class<T>` and is not an interface.

**Comment by RealyUniqueName** [comment]
CI is ok, so maybe merge this?
I guess cases nadako mentioned should be covered by specification tests.

**Comment by nadako** [comment]
Let's first enable saucelabs tests, because these spec tests only run on browser.

**Comment by ncannasse** [comment]
I think this won't work with interfaces.

**Comment by nadako** [comment]
> I think this won't work with interfaces.

Well, this is not triggered on interfaces (`TTypeExpr (TClassDecl cls) when not cls.cl_interface`).

**Comment by RealyUniqueName** [comment]
Looks like i've ruined this PR with merge commit )
I'll open another one.

**Pull request closed without merging**
