### PR TITLE
Generalize state restoration of module types

### LINKED ISSUE #10986: [jvm] Overload+any change on haxe.ds.Vector breaks compilation server
Other targets seems fine, but if you change anything (even comments) in this project `Vector` file after first compilation and rebuild, there will be errors like:
```
haxe/ds/IntMap.hx:350: lines 350-352 : Field iterator has different type than in core type
haxe/ds/IntMap.hx:350: lines 350-352 : error: Iterator<haxe.ds.IntMap.T> should be haxe.root.Iterator<haxe.ds.IntMap.T>
haxe/ds/IntMap.hx:350: lines 350-352 : ... have: (...) -> Iterator<...>
haxe/ds/IntMap.hx:350: lines 350-352 : ... want: (...) -> haxe.root.Iterator<...>
```
If you change something like `std.StringTools`, it also breaks cache.
[bug_vector_jvm_server.zip](https://github.com/HaxeFoundation/haxe/files/10853506/bug_vector_jvm_server.zip)

Found on https://github.com/HaxeFoundation/haxe/pull/10687

### PR DESCRIPTION
**Pull request by Simn**
This adds a `_restore` function to all module type kinds, which should be useful for various situations. I'm using it to fix #10986 where the server didn't restore the paths of typedefs due to a lack of state saving.

### CODE REVIEW

**Comment by Simn** [comment]
@kLabz Do we have some straightforward way to add a test for #10986 now?

**Comment by kLabz** [comment]
Not yet. I can write classic server test for this if you want.

**Comment by Simn** [comment]
That would be appreciated!

**Comment by kLabz** [comment]
@Simn I added a test (that was failing without your commits). Could have reduced the source a bit but I guess it's fine?
Edit: right, ubuntu 18.04 won't run today...

**Pull request merged**
