### PR TITLE
Add native meta for java

### PR DESCRIPTION
**Pull request by RblSb**
Not sure if same name field will work.
About this meta version: https://github.com/HaxeFoundation/haxe/issues/2288

### CODE REVIEW

**Comment by back2dos** [comment]
There's an overlap here, we should avoid: `@:native("some") function other()` makes the method `other` be generated as `some` in Java code (and in fact all targets I've checked).

**Comment by RealyUniqueName** [comment]
What's the purpose of this meta? Why no code handling it?

**Comment by RblSb** [comment]
I mean "Add description about `@:native` meta (without args)" for Java target. This meta adds `native` keyword to generated java functions and has no real overlap with `@:native("newName")` meta.

**Comment by back2dos** [comment]
My bad. This already works the way it's described ... this PR merely adds documentation. I would kinda prefer that this meta were `@:java.native` but now seems a very bad time to change it.

**Comment by RealyUniqueName** [comment]
I don't like that we will have the same meta twice. Maybe merge both descriptions?

**Comment by RealyUniqueName** [comment]
Actually, we can just introduce new meta `@:java.native` which will do the job, leave `@:native` without arguments intact for now and deprecate it in future.

**Comment by RblSb** [comment]
I think this should be done for every platform-dependent meta, for example `@:flash.sound`, `@:flash.debug`, like we do for `--/-` compiler args (hiding current versions from manual now and deprecate someday).

**Comment by Simn** [comment]
The fact that `@:native` has semantics for Java is pretty bad, so I don't want to document this. We should change it to use `@:java.native` instead.

**Comment by RblSb** [comment]
Example:
```haxe
class Main {
	static function main() {
		@:keep foo();
	}
	// @:native static function foo():Void {};
	@:java.native static function foo():Void;
}
```
```hxml
-main Main
-java bin
-D no-compilation
```

**Comment by Simn** [comment]
Thanks!

Do you know what this actually does in `javac` and if I should change something in genjvm too?

**Comment by onehundredfeet** [comment]
Any chance that the haxe documentation could get updated to include this flag?

**Comment by onehundredfeet** [comment]
@Simn I plan on using the JVM target, I hope that this works.

**Pull request merged**
