### PR TITLE
[std] add StringTools.remove()

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Simn** [comment]
Hmm, I'd expect a `remove` function to remove a specified range of characters (kinda like a reverse `substr`). But I'm probably just weird.

**Comment by Simn** [comment]
Actually I don't expect to find something called `remove` on an immutable data type at all...

**Comment by Gama11** [comment]
>Hmm, I'd expect a remove function to remove a specified range of characters

Hm... You may have a point actually, that seems to be C#'s definition..

https://docs.microsoft.com/en-us/dotnet/api/system.string.remove?view=netframework-4.7.2

C++ seems to call that `erase()` though. But either way, I can't find a lot of "remove substring" methods in the std libs of popular languages, so maybe this isn't such a great idea after all.

>Actually I don't expect to find something called remove on an immutable data type at all...

Well, with that argument, we shouldn't have `replace()` either. :)

**Comment by Gama11** [comment]
Yeah, considering how rare this seems to be in other languages, I think I've convinced myself that this is probably a step too far in the direction of minor convenience methods. `contains()` is great, but this may be too much.

**Pull request closed without merging**
