### PR TITLE
[4.3.5] Backport Json RPC diagnostics

### PR DESCRIPTION
**Pull request by kLabz**
* [x] Backport https://github.com/HaxeFoundation/haxe/pull/11412
* [x] Backport test changes from https://github.com/HaxeFoundation/haxe/pull/11412 ([running CI](https://github.com/HaxeFoundation/haxe/actions/runs/9772499931) on legacy diagnostics first :heavy_check_mark:)
* [x] Track and add other diagnostics related tests from `development`
  * [x] #7282
  * [x] #7931
  * [x] ~~#9705~~
  * [x] #11177
  * [x] #11184
  * [x] #11203
  * [x] ~~#11516~~ doesn't apply to `4.3_bugfix` (tests pass just fine but are useless there)
  * [x] #11695
* [x] Backport other diagnostics related fixes
  * [x] #11220
  * [x] Kinda related: https://github.com/HaxeFoundation/haxe/commit/19cc8a50d3f90d1afa0452e7cf5ae0867106fc37
  * [x] https://github.com/HaxeFoundation/haxe/commit/160a49095d5e54fe65345c896c7d02d18369b9ce for #7282 
  * [x] ddef63886e69bb78e7623820a20b5b06fc49ba50, e4ca1c81f00082a22caa3fcde4663bd822caf2fb, 19cc8a50d3f90d1afa0452e7cf5ae0867106fc37
  * [x] Remove `populateCacheFromDisplay` https://github.com/HaxeFoundation/haxe/pull/11696/commits/0f40f12d46ab33b19eedd070084e4f80f7fae1b2
  * [x] #11709
* [x] Add doc to `DisplayMethods.Diagnostics`... (same in `development`)

### CODE REVIEW

**Comment by kLabz** [comment]
This might be a bit much for a patch release but I think it's worth it, especially with [Json RPC diagnostics `vshaxe/haxe-language-server#124`](https://github.com/vshaxe/haxe-language-server/pull/124).

I kept the commit history clean for easier review.
Also CI is having a stroke again :shrug: (ignore windows and mac, it's failing on 4.3 branch atm; but linux is having some random ppa issues too today)

**Comment by RblSb** [comment]
Tested with latest vshaxe commit, got `Failed - Exception while handling Haxe completion response: Unexpected end of JSON input` from `organizeImportGroup > formatText > loadConfig > determineConfig` stacktrace (https://github.com/HaxeFoundation/haxe/issues/11709?)

**Comment by kLabz** [comment]
Sounds like #11709 indeed

**Comment by Simn** [comment]
The changes here look good to me. As I've said on Slack, it's quite a lot for a patch release, but it's a very nice cleanup, so I'm fine with merging this.

**Pull request merged**
