### PR TITLE
update extlib version (closes #7796)

### LINKED ISSUE #7796: [flash] Failing on glsl2agal.swc
With the latest Haxe:
```haxe
class Main {
  static public function main() {}
}
```
```
$ haxe -main Main -swf-lib glsl2agal.swc -swf test.swf -swf-lib glsl2agal.swc 
Error: The input swf glsl2agal.swc is corrupted
```
This is official Adobe's library: https://github.com/adobe/glsl2agal/blob/master/bin/glsl2agal.swc
Works fine with Haxe 3.4.

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by Simn** [comment]
I'm still seeing
```
Your request can't be satisfied:
  - No package matches extlib>=1.7.6.
```

**Comment by nadako** [comment]
Well, FML :) @andyli please halp!

**Comment by nadako** [comment]
At least MacOS installed the good version.

**Comment by andyli** [comment]
That's because extlib 1.7.6 was published after opam 2 so it is only available from the opam 2 repo. I have to look into using opam 2 in Trusty...

**Comment by nadako** [comment]
Ooh, I see now. And osx uses the latest opam already? Makes sense, thanks Andy!

**Comment by Simn** [comment]
Could you rebase?

**Comment by andyli** [comment]
I still have to upgrade opam for AppVeyor builds. Will try to do it tonight.

**Pull request merged**
