### PR TITLE
implement non-blocking connect for cpp

### PR DESCRIPTION
**Pull request by yanhick**

### CODE REVIEW

**Comment by ncannasse** [comment]
I'm not sure about the peer()/host() changes, and also could you replicate the Blocking support in neko ?

**Comment by bjitivo** [comment]
What do you mean "not sure about the peer()/host()" changes?

The haxe sys.net.Socket API has a setBlocking call which allows the socket to be set nonblocking.  The API does not say that this function cannot be called before connect().  If the socket is set nonblocking before connect(), then the changes in this commit are necessary to allow the connect to succeed.  This is a bug fix for the C++ implementation of sys.net.Socket, to fix the failure to connect when a socket is set to nonblocking before connecting.

Specifically, this code:

* Throws haxe.io.Eof when an EOF is encountered on the underlying socket instead of throwing a Custom error (not sure why this was necessary, the reasoning is lost in the history of time for us, but it certainly seems more correct in any case)

* Doesn't throw an exception if the underlying socket reported "Blocking" on a connect attempt, since this is expected behavior for a nonblocking connect.

* Doesn't crash in calls to peer() and host() for an unconnected Socket, instead returning sensible values

**Comment by bjitivo** [comment]
We can make the corresponding changes in the neko target too.

**Comment by ncannasse** [comment]
@bjitivo the fact that peer()/host() returns dummy values for an unconnected socket does not seem like a good idea for me, what's wrong with returning null in that case ?

**Comment by bjitivo** [comment]
That would be fine too.

**Comment by ncannasse** [comment]
@yanhick could you update the PR accordingly ?

**Comment by bjitivo** [comment]
The change has been updated according to ncannasse's comments.  Is there anything else you need before pulling this?

**Comment by ncannasse** [comment]
Could the changes be replicated in neko version of sys.net.Socket as well ? (and tested if possible). I would like to keep the same behavior between the two platforms.

**Comment by bjitivo** [comment]
Oh yeah I forgot about that request.  I'll get on it.

**Comment by bjitivo** [comment]
Pull request updated, I believe all issues have been addressed.  Thanks.

**Comment by bjitivo** [comment]
The corresponding hxcpp changes have been pulled in commit 396b65490be119d6cb4c02b01a748513ccf17dc5.

**Comment by Simn** [comment]
@ncannasse: Is this okay to merge? I would like to merge this locally because the commits look a bit messed up, so don't hit that button.

**Comment by ncannasse** [comment]
Ok for me

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/commit/9a17cb67d84047249727018e7c9a2374acdfe3b0

**Pull request closed without merging**
