### PR TITLE
Small typo in BaseCode class description

### PR DESCRIPTION
**Pull request by markknol**

### CODE REVIEW

**Comment by Simn** [comment]
Thanks! The irony of misspelling dictionary...

**Comment by markknol** [comment]
Hehe, I'm lucky my egnlish is better than that.

**Comment by Gama11** [comment]
Not the only location it looks like: https://github.com/HaxeFoundation/haxe/blob/d3ea417a74c0a989b534a47b86aaf90b48cbf156/genxml.ml#L505

**Comment by markknol** [comment]
What does that line of code do?

**Comment by Simn** [comment]
It's probably some ancient hack for --gen-hx-classes.

**Comment by markknol** [comment]
https://github.com/HaxeFoundation/haxe/pull/4822

**Pull request merged**
