### PR TITLE
Add support for toString metadata.

### LINKED ISSUE #6841: Array.join() and -dce full issue
https://try.haxe.org/#0Dc93

```haxe
class Foo {
    public function new() {        
    }
    
    public function toString()
    	return Std.string(Std.random(100) + 100);
}

class Test {
    static function main() {
        // trace(Std.string(new Foo()));        
        var foos: Array<Foo> = [new Foo(), new Foo(), new Foo()];
        trace(foos.join('/'));        
    }
}
```

Results in
```
[object Object]/[object Object]/[object Object]
```

If i uncomment the first trace `trace(Std.string(new Foo()));` i get the expected output (of some random numbers).

```
170
182/170/178
```

Is this expected behavior with DCE, I certainly was surprised by it?

### PR DESCRIPTION
**Pull request by abeaumont**
toString metadata existed but was not used, now it can be used to
annotate methods to provide DCE information about which types
will be converted to string and thus, its `toString` method should be
preserved.

This metadata mechanism replaces the previous way of adding this
information directly into the DCE code.

Fixes #6841

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
I'm not sure it's a consistent solution. 
What about inheritance? What if a type is passed to `@:toString` annotated method through a change of type parameters?
Perhaps type parameters need a flag, which will indicate that any type passed as those type parameters should keep `toString` method.

**Comment by abeaumont** [comment]
@RealyUniqueName The types I have to keep the `toString` method are checked in the call to the method, so it should work (maybe there's some case where it doesn't, such an example would be helpful). I added some test cases that show how it handles inheritance correctly.

Note also that, as commented in https://github.com/HaxeFoundation/haxe/issues/6841#issuecomment-371237157, it's not a perfect solution and has some rough edges, but (afaik) it already should work better than the previous (hardcoded) solution.

**Comment by RealyUniqueName** [comment]
I mean something like this:
```haxe
class Test<T> {
  var array:Array<T>;
  //<...>
  public function print() {
    trace(array);
  }
}

class A {
  public function toString() return 'a'; 
}

var t = new Test<A>();
//<...>
t.print();
```
or this
```haxe
class Parent<T> {
  var value:T;
  public function print() {
    trace(value);
  }
}

class Child<T> extends Parent<T> {}


```

**Comment by abeaumont** [comment]
@RealyUniqueName those examples actually work. Not sure if I'm missing something, so I just completed them to build:

```haxe
class Test<T> {
	var array:Array<T>;
	public function new() {
		array = new Array<T>();
	}
	public function add(a: T) {
		array.push(a);
	}
	@:toString(T) public function print() {
		trace(array);
	}
}

class A {
	public function new() {}
	public function toString() return 'a'; 
}

class Main {
	public static function main() {
		var t = new Test<A>();
		t.add(new A());
		t.print();
	}
}
```

Resulting in:

```
> haxe -dce full -x Main.hx
Main.hx:11: [a]

```

and

```haxe
class Parent<T> {
	var value:T;
	public function new() {}
	public function set(v: T) value = v;
	@:toString(T) public function print() {
		trace(value);
	}
}

class Child<T> extends Parent<T> {}

class A {
	public function new() {}
	public function toString() return 'a';
}

class Main {
	public static function main() {
		var c = new Child<A>();
		c.set(new A());
		c.print();
	}
}
```

resulting in:

```
> haxe -dce full -x Main.hx
Main.hx:7: a

```

In both cases the result is the expected, isn't it? Ideally, metadata here shouldn't be necessary, but as I said, metadata has no transitive property at the moment, yet it should work if you add the metadata explicitely. Is it this what you are referring to?

**Comment by RealyUniqueName** [comment]
> is it this what you are referring to?

Yes. User should not be required to add `@:toString` to `Test`, because that meta is already added to `Array`. But as I mentioned above it's probably not possible now. 
While this solution is better than no solution at all, it still has that downside that user will have to spread `@:toString` all around a project. Especially for generic-heavy code.

**Comment by abeaumont** [comment]
Ok, I understand now. I agree that it makes sense to wait till this is solved to merge the branch, any feedback about current approach is welcome though. I think the support can be made transitional by making metadata checking recursive, I will take a look at it.

**Comment by Simn** [comment]
I don't like this very much, but I'm not sure if it can be avoided given all the run-time magic going on with `toString`.

I do wonder if we have to be this accurate when it comes to `toString`. Wouldn't it be sufficient to have a define `dce-keep="toString,whatever"` which simply keeps all these methods by name?

**Comment by abeaumont** [comment]
That approach would certainly be simpler. I'm not so sure that dependencies are easy to handle, so this could end up being way too messy to be worth it.

**Comment by ncannasse** [comment]
I think the way @abeaumont solved the issue works great. However I agree it could be slightly automated, for instance by automatically adding - if it's not already present -  `@:toString(parameters)` to `toString` methods having typed arguments (Array, Map) which would already remove a lot of changes in the PR.

**Comment by ncannasse** [comment]
And if we inherit @:toString from @:coreType definition as we do with the documentation then there's only very little classes that require @:toString actually. Most of the instances comes from per-platform implementation.

**Comment by Simn** [comment]
This PR is very outdated and I don't expect an update to this, so I'll go ahead and close it.  We still have #6841 open to look for a different (or maybe somewhat similar) solution.

**Pull request closed without merging**
