### PR TITLE
Set haxelib_src to 4.1.x branch

### LINKED ISSUE #11035: haxelib_src submodule
Shouldn't the haxelib_src submodule be updated to the latest haxelib version?

### PR DESCRIPTION
**Pull request by tobil4sk**
Closes #11035

This branch includes a backport of the defines/metadata documentation feature required for #10858.

### CODE REVIEW

**Comment by kLabz** [comment]
CI isn't green there atm, is that an issue?
https://github.com/HaxeFoundation/haxelib/commits/d8a1366b2c4e5db9d9fad75bc7f4c847d64d7667

**Comment by tobil4sk** [comment]
> CI isn't green there atm, is that an issue?

Well, same thing happened when we released 4.0.3. It's based on an old version, and there were some CI issues back then which is why it's failing. There have been a lot of CI changes since then so it will take a while to get it green. I've run the unit tests for the define/metadata changes locally and it seems good. Just need to make sure the relevant tests pass here as well.

**Comment by tobil4sk** [comment]
```
Command: haxelib [git,hxnodejs,https://github.com/HaxeFoundation/hxnodejs]
Installing hxnodejs from https://github.com/HaxeFoundation/hxnodejs
Library hxnodejs current version is now git
Command exited with 139 in 2s: haxelib [git,hxnodejs,https://github.com/HaxeFoundation/hxnodejs]
Segmentation fault (core dumped)
```
uh oh...

**Comment by tobil4sk** [comment]
I'm not too sure why there was a random segmentation fault in the previous run... hopefully just a random one-off failure.

**Comment by Simn** [comment]
Oh well...

**Pull request merged**
