### PR TITLE
[server] implement --wait-connect (see vshaxe/vshaxe#217)

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by nadako** [comment]
Not sure about the argument name, maybe it should be `--connect-wait` or something completely different?

**Comment by Simn** [comment]
How about:

* `--server-wait` for `--wait`
* `--server-connect` for `--wait-connect`
* `--client` for `--connect`

Keeping `--wait` and `--connect` for compatibility of course.

**Comment by Simn** [comment]
Meh, `--connect 6000` sounds better than `--client 6000`... never mind.

**Comment by RealyUniqueName** [comment]
I think for tcp servers `listen` is kind of established term.

**Comment by Simn** [comment]
So `--listen-wait` and `--listen-connect`?

**Comment by Aurel300** [comment]
`--listen-connect` sounds really strange. Just `--listen`?

**Comment by Simn** [comment]
But it connects.

**Comment by nadako** [comment]
`--server-listen`, `--server-connect`, `--connect`?

**Pull request merged**
