### PR TITLE
Setup tests for source maps

### PR DESCRIPTION
**Pull request by RealyUniqueName**
I'd like to find a good approach to testing source maps.
After setting up such tests we will be able to improve source maps generation and add it to other targets.

So this is my "proposal" for testing source maps generation.
Here is how it looks in ci: https://travis-ci.org/RealyUniqueName/haxe/jobs/355092123#L1758

### CODE REVIEW

**Comment by ncannasse** [comment]
Just to be clear : you're writing down an expression, then the corresponding generated code and checking that the generated code mapping is the same as the original source source right?

One problem with sourcemaps might be with inner expressions, such as the `else` part of a `if`. Would your approach allows such test and then how?

**Comment by ncannasse** [comment]
PS: I entirely agree with the goal of having robust sourcemap and unit tests requirements for them btw :)

**Comment by RealyUniqueName** [comment]
> Just to be clear : you're writing down an expression, then the corresponding generated code and checking that the generated code mapping is the same as the original source source right?

Yes.

It allows to check any valid Haxe expression:
```haxe
if(expect(condition, [Js => 'condition'])) ifAction();
if(condition) expect(ifAction(), [Js => 'ifAction()']);
if(condition) ifAction() else expect(elseAction(), [Js => 'elseAction()']);
```
It can't `expect(else elseAction(), ...)` because `else elseAction()` is not a valid Haxe expression. But that's probably not that important, because keywords are not of such interest as other expressions. E.g. debuggers won't stop on `else`, but will stop on `elseAction()`.

**Comment by RealyUniqueName** [comment]
@ncannasse Is it ok to merge?

**Comment by ncannasse** [comment]
Sure

**Pull request merged**
