### PR TITLE
[cppia] Generate scriptable functions for overriden functions

### LINKED ISSUE #1150: [cppia] Cant seem to get host to call extern super functions
So Ive reduced my problem scope to the following:

In the cppia host:
```haxe
class FakeButton extends FakeInteractiveComponent {
    public override function someFunction() {
        super.someFunction();
        trace(">>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeButton");
    }
}

class FakeInteractiveComponent extends FakeComponent {
    public override function someFunction() {
        super.someFunction();
        trace(">>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeInteractiveComponent");
    }
}

class FakeComponent extends FakeComponentBase {
    public override function someFunction() {
        super.someFunction();
        trace(">>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeComponent");
    }
}

class FakeComponentBase {
    public function new() {
    }

    public function someFunction() {
        trace(">>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeComponentBase");
    }
}
```
As expected if you create an instance of this in the host (`new FakeButton()`) and call the `someFunction()` then things trace as you would imagine:
```
src/fake/FakeComponentBase.hx:8: >>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeComponentBase
src/fake/FakeComponent.hx:6: >>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeComponent
src/fake/FakeInteractiveComponent.hx:6: >>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeInteractiveComponent
src/fake/FakeButton.hx:6: >>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeButton
```

All fine, however, in the script file, i have a set of externs for these classes, as well as a class that extends one of these externs:
```haxe
@:expose("MyFakeButton")
class MyFakeButton extends FakeButton {
    public override function someFunction() {
        super.someFunction();
        trace(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> MyFakeButton.someFunction");
    }
}

extern class FakeButton extends FakeInteractiveComponent {
    public function someFunction():Void;
}

extern class FakeInteractiveComponent extends FakeComponent {
    public function someFunction():Void;
}

extern class FakeComponent extends FakeComponentBase {
    public function someFunction():Void;
}

extern class FakeComponentBase {
    public function someFunction():Void;
}
```
When i load this script into the host, create an instance of the `FakeButton` (via `cpp.cppia.Module.resolveClass`) and call `someFunction` i, weirdly, get the following:
```
src/fake/FakeComponentBase.hx:8: >>>>>>>>>>>>>>>>>>>>>>>>> SOME FUNCTION: FakeComponentBase
src/MyFakeButton.hx:9: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> MyFakeButton.someFunction
```
Its like its skipped the rest of the class hierarchy or something, ive tried various things but can never seem to get it to call, for example, `FakeComponent.someFunction` 

Any thoughts, is there something ive doing incredibly wrong here? 

Note1: i tried adding `override` to the extern functions, same thing

Note2: a similar thing is perfectly fine with js (obviously not using cppia), but dynamically loading a .js file and creating class instances

Note3: i _thought_ it might be somewhat related to: https://github.com/HaxeFoundation/hxcpp/issues/423 - albiet not using externs, etc - but my understanding is that issue was fixed anyway

### PR DESCRIPTION
**Pull request by Aidan63**
Fixes https://github.com/HaxeFoundation/hxcpp/issues/1150

Test has been added in this hxcpp merge https://github.com/HaxeFoundation/hxcpp/pull/1154

That hxcpp merge is failing due to the new test, once this is merged the CI on that hxcpp merge should be re-ran and it will then pass.

### CODE REVIEW

**Comment by Simn** [comment]
Does this interact with overloads somehow given that we're comparing methods by name?

**Comment by Aidan63** [comment]
I don't think so. Overloads only really work on extern classes iirc, and that code is only ran on haxe classes and interfaces.

**Comment by rainyt** [comment]
This fix doesn't seem to have released a new haxe yet. Can I get a new haxe executable file from the nightly build? Which one is stable? (Mac user)

**Comment by rainyt** [comment]
4.3 bug fix did not update this modification. Can it be fixed in 4.3?

**Comment by rainyt** [comment]
```haxe
src/haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.cpp 
Error: ./src/haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.cpp:141:13: error: invalid covariant return type for 'virtual Dynamic haxe::ds::_GenericStack::GenericStackIterator_hscript_Token_obj__scriptable::next()'
   ::Dynamic next(  ) {
             ^
./src/haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.cpp:48:19: error:   overriding 'virtual hscript::Token haxe::ds::_GenericStack::GenericStackIterator_hscript_Token_obj::next()'
  ::hscript::Token GenericStackIterator_hscript_Token_obj::next(){
                   ^
./src/haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.cpp:152:55: warning: 'fastcall' attribute directive ignored [-Wattributes]
 static void CPPIA_CALL __s_hasNext(::hx::CppiaCtx *ctx) {
                                                       ^
./src/haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.cpp:157:52: warning: 'fastcall' attribute directive ignored [-Wattributes]
 static void CPPIA_CALL __s_next(::hx::CppiaCtx *ctx) {
                                                    ^
./src/haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.cpp:171:67: warning: 'fastcall' attribute directive ignored [-Wattributes]
 static void CPPIA_CALL __script_construct_func(::hx::CppiaCtx *ctx) {
```
I have tried this fix, but compilation errors occur.

**Comment by rainyt** [comment]
https://github.com/HaxeFoundation/hxcpp/issues/1175

Even with this PR, the test cases cannot pass. This is my issues.

**Pull request merged**
