### PR TITLE
The function equality situation

### PR DESCRIPTION
**Pull request by Simn**
From #6705

My main question here is what we want to fix and what we want to warn about...

* [x] **hl**: `unit/issues/Issue6705.hx:71: Check failure at fun@2635 @5 - Register 1((f64):void) should be (i32):void and not (f64):void`
* [x] **java & cs**: fail `==` for static and member functions
* [x] **neko**: fails `==` for member functions

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
I think Haxe should generate `Reflect.compareMethods()` or other generator-specific comparison function.
Why force developers to write it manually and use conditional compilation if it could be generated automatically? Let's make Haxe code cleaner :)

**Comment by Simn** [comment]
That would also be my preferred solution. I don't understand why we would essentially tell people to write `#if java Reflect.compareMethods(a, b) #else a == b #end` instead of just generating the right thing for them.

Ideally, we wouldn't need `compareMethods` (which by the way is a bad name) at all, but I guess that's not feasible even if we ignore neko.

**Comment by Simn** [comment]
The other thing I wonder about is if the fact that `!=` doesn't hold in some of these cases suggests that there are potential performance problems, like allocating a new closure on each access.

**Comment by nadako** [comment]
I feel like auto-generating code for `==` will lead to confusion. E.g. consider `Array.indexOf` that is supposed to check "standard equality", which is `==`, right? But then we'll have `fun1 == fun2` magically working while `[fun1].indexOf(fun2)` not, meh.

**Comment by Simn** [comment]
Using that argument, you'd get a warning for `fun1 == fun2`, but not for the `indexOf` case. That's just as confusing.

**Comment by nadako** [comment]
> Using that argument, you'd get a warning for `fun1 == fun2`, but not for the `indexOf` case. That's just as confusing.

Yes, in my opinion we should leave things as they are for now :)

**Comment by Simn** [comment]
You wouldn't happen to know why static equality fails on C#? I understand why member functions might cause issues, but static ones should just be `==` no matter what...

**Comment by nadako** [comment]
> You wouldn't happen to know why static equality fails on C#? I understand why member functions might cause issues, but static ones should just be `==` no matter what...

It actually seems to be supposed to work for both static and member functions, but the `Closure` implementation only provides `Equals` function and not `==` operator overload and I'm not sure if there's a reason for that (cc @waneck).

**Comment by Simn** [comment]
Let me ask it differently: Why create a new `Closure` instance every time for static functions? If that was a singleton or something it should be way more efficient _and_ support `==` automatically.

I'm thinking that for member functions it could also be cached on the instance, but that's a bit more involved.

Still, I think we should just fix this...

**Comment by nadako** [comment]
Yes, method closures in C#/Java is something that needs to be reworked. I think there are several issues about that already (e.g. #4393). Both static and non-static functions can be cached somewhat similarly to what we do for JS.

**Comment by Simn** [comment]
Oh dear... thanks for the link.

This makes me think we should just fix this even more...

**Comment by Simn** [comment]
Quick & dirty: https://github.com/Simn/haxe/commit/f3636117a9daa42236807930dc8262f0a2251f05

This obviously should distinguish static and non-static to avoid leaks (no WeakMap on C#), but it's already enough to fix the tests here.

Can we do something like this properly for Haxe 4?

**Comment by ncannasse** [comment]
Can't == be overloaded for C# Closure ?

**Comment by Simn** [comment]
I'm sure it could be, but my point is that instantiating new closure objects every time is not good for performance anyway, and addressing that would fix equality checks as a subset.

**Comment by nadako** [comment]
> Can't == be overloaded for C# Closure ?

It could, that's why I pinged @waneck: to know if it wasn't overloaded for a reason? But that's a quick solution. In general, as said, we should cache closure objects.

**Comment by ncannasse** [comment]
@nadako I don't think that should be a requirement. In HL I don't cache closures and it doesn't cause big problems. Also, such cache requires a per-object storage as a global cache would surely leak and I think it's better to have no cache than a cache that leaks.

**Comment by Simn** [comment]
You only need a global cache for static functions and I don't think anything leaks there.

For non-statics, you can cache the closures on the object itself. That way nothing leaks there either.

P.S.: You might want to support WeakMap regardless.

**Comment by nadako** [comment]
It shouldn't really be global. Static closures are cached in some collection inside a static var of a class, non-static closures are cached inside instances. For C#/Java there was ideas to have some support data stored inside the class anyway, to make reflection faster, so I don't see any problem with storing closures there as well.

That said, still someone (and I think it's either me or Caue) have to find time to implement that. So the solution for time being would be to try overloading `==` and see if that fixes the issue at hand.

**Comment by Simn** [comment]
We can do that for C#, but it wouldn't help us with Java.

**Comment by RealyUniqueName** [comment]
Is it possible to add fields at runtime to extern classes in C#/Java?

**Comment by nadako** [comment]
No, for those we would have to either go the slow way and allocate stuff or using caching via a WeakMap. Good point actually

**Comment by ncannasse** [comment]
Having a per object cache requires an extra field per object for all instances, and uses extra memory for closures in general even when they are accessed only once. I'm not sure it's worth it unless we're able to pinpoint which are the short living closures (vs one time creation / long living)

**Comment by Simn** [comment]
Can we at least do something for static closures?

**Comment by ncannasse** [comment]
@Simn there's maybe no such thing as a static closure, at it's a closure over nothing ;)

I think we should postpone changes here as I'm even sure what we want here, and that's a quite specific change if it were to happen post 4.0 that shouldn't have wide consequences.

**Comment by Simn** [comment]
> @Simn there's maybe no such thing as a static closure, at it's a closure over nothing ;)

Yes that's exactly why I think their inequality suggests that the run-time is doing something weird.

**Comment by ncannasse** [comment]
I suggest we move this to 4.1

**Comment by Simn** [comment]
It's a bit sad because this is a huge problem for the Java target. But yes, there's plenty other things to worry about.

**Comment by jeremyfa** [comment]
I have been hitting this issue recently with C# target.

I don't mind so much having to use `Reflect.compareMethods()` instead of `==`.

What bugs me though is that, on C# target, plain equality test on member method fails, as mentioned in this issue, but if I put the same member method inside an `Array<Dynamic>`, `indexOf(method)` works as expected and returns the correct index if the method is referenced inside the array. What does Array.indexOf() use internally that makes it work?

A small code to illustrate this:

```haxe
    function someMethod():Void {
    }

    function testMethodEquals() {

        var methodRef1 = someMethod;
        var methodRef2 = someMethod;

        var array:Array<Dynamic> = [];
        array[0] = methodRef1;

        trace(array.indexOf(methodRef1)); // -> prints 0 (found it)
        trace(array.indexOf(methodRef2)); // -> prints 0 (found it)
        trace(array.indexOf(someMethod)); // -> prints 0 (found it)
        
        trace(methodRef1 == methodRef2); // -> prints false
        trace(methodRef1 == someMethod); // -> prints false

    }
```

**Comment by RealyUniqueName** [comment]
Now for platforms with `pf_supports_function_equality = false` this PR generates `Reflect.compareMethods(fn1, fn2)` in place of `fn1 == fn2` if at least one of the values has function type.
And if it's unknown whether compared values are functions (e.g. inside of generic functions) then `Reflect.isFunction` is used as well. 
However comparing dynamic values is not covered by this PR. Should it also generate `Reflect.compareMethods(dynamic1, dynamic2)`?

**Comment by RealyUniqueName** [comment]
CI failure is not related.

**Comment by Simn** [comment]
> Now for platforms with pf_supports_function_equality = false this PR generates Reflect.compareMethods(fn1, fn2) in place of fn1 == fn2 if at least one of the values has function type.

I don't think we agreed on actually doing that though...

**Comment by RealyUniqueName** [comment]
IIUC the concern was methods like `Array.indexOf`. I've implemented that and added a test.
This PR affects only three and a half targets: cs, java, jvm and neko. And once function equality is handled in the target generators, we can disable this behavior by switching `pf_supports_function_equality`

**Comment by Simn** [comment]
I have removed the expression-level rewrite here because I don't want to do this. To make up for it, I have fixed the checks on the JVM target because that wasn't working through both the good and the dynamic path. The only targets having issues now are neko (which we won't fix) and HL due to #10031.

I'll add some more tests for the dynamic case, and also with reversed order because those are different cases for stack-based targets like genjvm.

**Pull request merged**
