### PR TITLE
[std/hl] move some hl.Format into lib format/heaps

### PR DESCRIPTION
**Pull request by yuxiaomao**
This PR address the problem that some `hl.Format` function should not exist in std.
The idea is to split `hl.Format` functions into 3 types:
- `digest`: needed by some std crypto function (`hl/_std/haxe/crypto`), we can keep it
  - It can also be moved into `hl.Api` if we'd like to remove this file
- png, jpg, dxt, scale: basic image function, will be moved to `format.hl.Native`
  - https://github.com/HaxeFoundation/format/pull/112
- Mikktspace, and other heaps-specific functionalities such as MeshOptimizer: will be moved/added to `hxd.MeshTools` (in heaps)
  - https://github.com/HeapsIO/heaps/pull/1250

I don't know if it's ok to remove totally these functions so I just declared them deprecated.

### CODE REVIEW

**Comment by Simn** [comment]
I would prefer removing this, there's a roughly 100% chance that you guys were the only ones using it anyway.

**Comment by kLabz** [comment]
> I would prefer removing this, there's a roughly 100% chance that you guys were the only ones using it anyway.

Well, heaps uses some of these so I'm not sure about this :thinking: 
(it's probably fine either way, especially if heaps is updated quickly)

**Comment by yuxiaomao** [comment]
If the changes is validated, I'll make sure to merge some heaps PR at the same time.

**Comment by Simn** [comment]
Consider them validated.

**Pull request merged**
