### PR TITLE
Don't ignore default values of arguments of inlined functions

### LINKED ISSUE #7032: optional argument default value lost when inlining a function call
```haxe
class Test {
    static function main() {
        f(null);
    }
    
    static function f(p) {
        trace(f2(p));
    }
    
    static inline function f2(p = 10) {
        return p;
    }
}
```

generates:

```js
Test.f = function(p) {
	console.log("root/program/Test.hx:7:",p);
};
```

although it should insert the null-check for the `p` argument at the call site.

so this snipped traces `null` instead of `10` as it would if we remove the `inline` modifier

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #7032

### CODE REVIEW

**Comment by Simn** [comment]
This doesn't seem quite right because we now handle default values in two places. This PR would introduce unwanted branching in cases where we have all the static information, e.g. if we're calling your `def2` directly.

Please make sure to check the output without `-D analyzer-optimize` to make sure this doesn't happen. The branching should only occur if we're calling the function with a statically unknown value.

**Comment by RealyUniqueName** [comment]
Actually, we don't handle default values like that anywhere in the compiler. Generators have to do that manually. And this branching is only inserted on the call site. Original function body is not changed.

> Please make sure to check the output without -D analyzer-optimize to make sure this doesn't happen. The branching should only occur if we're calling the function with a statically unknown value.

Here is the generated js:
```js
// Generated by Haxe 4.0.0-rc.3
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("src/Main.hx:3:",10);  // This is for `trace(def2(null))` or `trace(def2())`
	console.log("src/Main.hx:4:",Main.def(null));
};
Main.def = function(p) {
	var p1 = p;
	if(p == null) {
		p1 = 10;
	}
	return p1;
};
Main.main();
})({});
```

**Comment by Simn** [comment]
```haxe
class Main {
	static function main() {
		trace(f());
	}

	static inline function f(p = 10) {
		return p;
	}
}
```

Compiled to JS without `-D analyzer-optimize`:

```js
Main.main = function() {
	var p = 10;
	if(p == null) {
		p = 10;
	}
	console.log("source/Main.hx:3:",p);
};
```

**Comment by RealyUniqueName** [comment]
Sorry, I run it _with_ analyzer-optimize

**Comment by RealyUniqueName** [comment]
What would be the correct fix then?
Because if I have a code like this:
```haxe
var p = null;
trace(f(p));
```
does it count for `p` being statucally known? Or do we need an analyzer pass prior to inlining to be able to fix the issue?

**Comment by Simn** [comment]
In that case we have to accept the branching, nothing we can do about it. The analyzer will clean this up where possible and it's fair to require its usage in these situations.

**Pull request closed without merging**
