### PR TITLE
Change String.iterator() to @:using

### LINKED ISSUE #8329: Make String non-Iterable again!
From slack:

> question: do we really want `String` to be `Iterable`?
> wouldn't it be better to add `@:using(StringTools.StringIteration)` (or wherever the code should go)?
> I still think `String` should become an abstract in some distant future and the less types we let if unify with, the less painful this transition will be

Alex likes it:

> I like the idea.
> The need to deal with String as a class instance in dynamics and structure unification requires > a lot of hacks in generators and at run time.

And Simn didn't hesitate to express his unrestrained love for this proposal:

> Yes that doesn't sound like the worst idea you've ever had...

So, how about it?

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #8329 

@SImn I'm not sure  if genjvm needs some code to be removed on ocaml side.

I added `@:using(StringTools)` to `String` instead of creating another helper class. That feels right, but maybe will cause some terrible consequences, which I can't think of.

### CODE REVIEW

**Comment by ncannasse** [comment]
Personally I would like not to have to do StringTools.startWidth etc. anymore, but I'm a bit worried about having using on a basic class such as String.

There can be several problems with it from a newcomer perspective:
- String has an iterator() function - it shows in completion - but is not an Iterable
- also, suddenly half he functions are not working anymore in Dynamic/Reflect situations, whereas they work perfectly fine in "normal" Haxe code.

More generally, this requires developers using String to actually understand the @:using feature and its consequences on both compiletime and runtime. And I think it's a bit hardcore for such a basic class.

**Comment by Gama11** [comment]
>also, suddenly half he functions are not working anymore in Dynamic/Reflect situations, whereas they work perfectly fine in "normal" Haxe code.

I can understand the argument, but you don't seem to apply it consistently. This is _already_ the case with methods of `Array` (which is just as core as `String`) on platforms like JS (https://github.com/HaxeFoundation/haxe/issues/3330). To quote you:

>Dynamic at your own risk

**Comment by Simn** [comment]
I usually don't like drawing comparisons like this, but I have to agree that in the case of "field access through Dynamic" we don't have a consistent guideline. My understanding after the Array discussion was that we're slowly moving away from this and maybe even disallow field access through Dynamic entirely at some point. It would be good to sort out our agenda in this regard.

**Comment by RealyUniqueName** [comment]
There is an issue with C# target: `class String implements ArrayAccess<cs.Char16> {` so the compiler picks length + ArrayAccess first, which makes `iterator` via using impossible for `String`.
I guess it's ok to change the precedance of "using" iterator over "length + ArrayAccess" one, because ArrayAccess interface is not something used widely.

**Comment by back2dos** [comment]
Hmm. I think the root of all evil here is that it's considered a good idea to recommend `Dynamic` to newcomers. We should stop doing that.

Short of that, we could go with my original proposal of having a different class just with the iteration extensions, since can't iterate on `Dynamic` anyway.

**Comment by RealyUniqueName** [comment]
> we could go with my original proposal of having a different class just with the iteration extensions

It will not work for C# target unless we change `using IteratorExt` to be higher priority than `implements ArrayAccess`.

**Comment by nadako** [comment]
> `using IteratorExt` to be higher priority than `implements ArrayAccess`.

This makes sense to me. Surely _any_ actual iterator implementation is more specific than array access. In general, I think, iterating over length+array access should be deprecated, since there'a ton of ways to add a fully inlined iterator nowadays. And then again, maybe we could provide a standard iterator over length+array-access that one can add as a static extension.

**Comment by back2dos** [comment]
Yeah, sorry, I was unclear in my prior comment, which was directed solely at the concerns raised by Nicolas. As far as priority is concerned, an explicit iterator should definitely outrank length + array access.

**Comment by RealyUniqueName** [comment]
@ncannasse  What's the decision here?
Should we keep `String` iterable or add `@:using(StringTools)` or add `@:using(StringIterators)`?

**Comment by ncannasse** [comment]
For now lets move iterator to StringTools. So it will have the exact same usage as other String extensions. I don't want to create another third case. And I don't think we should have @:using on String right now.

**Pull request merged**
