### PR TITLE
[php7] fix "ErrorException: Undefined property: unit\Name::$null" in Template

### PR DESCRIPTION
**Pull request by AlexHaxe**
added a few unit tests for Template class

### CODE REVIEW

**Comment by ncannasse** [comment]
That seems the wrong fix to me

**Comment by RealyUniqueName** [comment]
At the first glance this PR needs more work. On php `"null"` is a valid field name. 
I'll try to find a time for review in nearest future.

**Comment by AlexHaxe** [comment]
My first attempt at fixing was adding 
```
if( v == "null" )
    return null;
```
to resolve in Template.hx. The problem is: that affects all platforms. But the bug only occurs on php7 (as far as I know, I didn't test every platform), so I tried to limit my fix to php7.

I'm open to suggestions for a better fix.

**Comment by RealyUniqueName** [comment]
You can use conditional compilation:
```
#if php7
if( v == "null" )
    return null;
#end
```

**Comment by RealyUniqueName** [comment]
This was indeed caused by a bug in `Reflect.getProperty()` described in #6559.
Since bug is fixed and unit test submitted, i'm closing this PR. Feel free to reopen if needed.

**Comment by AlexHaxe** [comment]
thanks for fixing the issue

Would it make sense to use my unittests for Template class to increase coverage?

**Comment by RealyUniqueName** [comment]
There is [Template.unit.hx](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/haxe/Template.unit.hx) for testing templates.
I think, if you want to improve coverage, you need to move your cases to that file.

**Comment by AlexHaxe** [comment]
Some of them are already in there. 

I had to create TestTemplate.hx as an additional test case file because I couldn't add new types in Template.unit.hx, because the bug only occured when using class instances. It worked fine with anonymous objects.

**Pull request closed without merging**
