### PR TITLE
More unicode tests and fixes

### PR DESCRIPTION
**Pull request by Simn**
Fixes some eval string handling.

@hughsando: These tests are failing on hxcpp:

```
var s = "ä😂";
s.toUpperCase() == "Ä😂";
s.toLowerCase() == s;

var s = "Ä😂";
s.toUpperCase() == s;
s.toLowerCase() == "ä😂";

var s = "a😂";
s.toUpperCase() == "A😂";
s.toLowerCase() == s;

var s = "A😂";
s.toUpperCase() == s;
s.toLowerCase() == "a😂";
```

### CODE REVIEW

**Comment by hughsando** [comment]
I did some initial work in hxcpp, but the native 'toupper' function does not convert the 228 character.
I think it might be local dependent?  I am not sure exactly what to do.

**Comment by RblSb** [comment]
If I understand correctly, eval will only support ISO-8859-1? Because this is specified for the Char module in ocaml.
Is it possible to make support for all characters? For example, here is a class with a complete list of lower/upper-case maps in utf8 with some optimization:
https://github.com/restorer/zame-haxe-stringutils/blob/master/org/zamedev/lib/internal/Utf8ExtInternal.hx

**Comment by Simn** [comment]
[Way ahead of you](https://github.com/Simn/haxe/commit/e7078082a03ad5fdf6e7442e557a1be9311392ef).

@hughsando: I guess you also need a port of HL's casing functions: https://github.com/HaxeFoundation/hashlink/blob/master/src/std/string.c#L159

The data for that is here: https://github.com/HaxeFoundation/hashlink/blob/master/src/std/unicase.h

**Comment by Simn** [comment]
Note: I've merged this locally because the branch has important changes for eval. The failing hxcpp tests are `#if`ed out. Keeping this open as an issue until it's resolved.

**Comment by RblSb** [comment]
After these fixes we no longer need `haxe/Ucs2.hx` and `haxe/Utf8.hx`?

**Comment by Simn** [comment]
@ncannasse Can we move these to hx3compat?

**Comment by ncannasse** [comment]
We can move these out. 

We might still want a way to correctly iterate on all unicode chars the way haxe.Utf8.iter does (without having to worry about surrogate pairs) but that's another story.

**Comment by Simn** [comment]
This is the last failing hxcpp unicode test I'm aware of.

**Pull request closed without merging**
