### PR TITLE
Reduce the temp variables generated by "flash.Memory"

### PR DESCRIPTION
**Pull request by R32**
for #6727, 
```haxe
abstract Ptr(Int) to Int {
    public inline function new(i: Int) this = i;
    @:arrayAccess inline function get(i: Int):Int return flash.Memory.getByte(this + i);
    @:arrayAccess inline function set(i: Int, v:Int):Void flash.Memory.setByte(this + i, v);
}

class App {
    static function main() {
        var ba = new flash.utils.ByteArray();
        ba.endian = flash.utils.Endian.LITTLE_ENDIAN;
        ba.length = 1024;
        flash.Memory.select(ba);
        var ptr = new Ptr(0);
        var i = rand();
        var start = i;
        ptr[i++] = start;
        ptr[i++] = rand();
        ptr[i++] = ptr[start] + rand();
        trace(ptr[start] == start);
    }
    static inline function rand() {
        return Std.int(Math.random() * 100);
    }
}
```
App.dump: Origin
```
class App {

    static function main() {
        var ba = new flash.utils.ByteArray();
        ba.endian = flash.utils.Endian.LITTLE_ENDIAN;
        ba.length = 1024;
        flash.system.ApplicationDomain.currentDomain.domainMemory = ba;
        var this1 = 0;
        var ptr = cast this1;
        var i = App.rand();
        var start = i;
        {
            var i1 = i ++;
            __vmem_set__(0, cast ptr + i1, start);
        };
        {
            var i2 = i ++;
            var v = App.rand();
            __vmem_set__(0, cast ptr + i2, v);
        };
        {
            var i3 = i ++;
            var v1 = __vmem_get__(0, cast ptr + start) + App.rand();
            __vmem_set__(0, cast ptr + i3, v1);
        };
        haxe.Log.trace(__vmem_get__(0, cast ptr + start) == start, {fileName : "App.hx", lineNumber : 21, className : "App", methodName : "main"});
    }

    static function rand() {
        return Std.int(Math.random() * 100);
    }
}
```
App.dump: After this PR
```
class App {
    static function main() {
        var ba = new flash.utils.ByteArray();
        ba.endian = flash.utils.Endian.LITTLE_ENDIAN;
        ba.length = 1024;
        flash.system.ApplicationDomain.currentDomain.domainMemory = ba;
        var ptr = cast 0;
        var i = App.rand();
        var start = i;
        flash.Memory.setByte(cast ptr + i ++, start);
        flash.Memory.setByte(cast ptr + i ++, App.rand());
        flash.Memory.setByte(cast ptr + i ++, flash.Memory.getByte(cast ptr + start) + App.rand());
        haxe.Log.trace(flash.Memory.getByte(cast ptr + start) == start, {fileName : "App.hx", lineNumber : 21, className : "App", methodName : "main"});
    }
    static function rand() {
        return Std.int(Math.random() * 100);
    }
}
```

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
What is the motivation to reduce amount of temp vars for flash? What benefits does it bring?

**Comment by R32** [comment]
maybe it can reduce the size of the swf file.

**Comment by nadako** [comment]
I think it would be better to haxe vmem_get/set as extern methods handled in the compiler and then use them within inline methods like it's done right now.

**Comment by R32** [comment]
so which class should I put "vmem_get/set" inside? flash.Lib? or still in flash.Memory?

**Comment by nadako** [comment]
I would put it in `flash.Memory`.

**Comment by R32** [comment]
I have tried to add the following, but I feel it doesn't looks good.
```hx
    @:extern static function vmem_set_int( mod : Int, addr: Int, v: Int ) : Void;
    @:extern static function vmem_set_float( mod : Int, addr: Int, v: Float ) : Void;

    @:extern static function vmem_get_int( mod : Int, addr: Int) : Int;
    @:extern static function vmem_get_float( mod : Int, addr: Int) : Float;

    @:extern static function vmem_sign( mod : Int, v: Int ) : Int;
```

**Comment by ncannasse** [comment]
Please look at the SWF output using a disassembler, there are big chances that these temp variables will be eliminated by our code generator, so it's not an actual real issue.

**Comment by R32** [comment]
I feel that the optimizer does not optimize untyped-related code. and i'm trying to find another way to solve it.

I compiled the swf file with `-dce full -D analyzer-optimize`,  and the following code dumped by [jpexs-decompiler](https://github.com/jindrapetrik/jpexs-decompiler)

Before:
```as
     var _loc2_:int = 0;
         var _loc3_:int = _loc2_;
         var _loc4_:int = int(Math.random() * 100);
         var _loc5_:int = _loc4_;
         _loc4_++;
         var _loc6_:int = _loc4_;
         si8(_loc5_,_loc3_ + _loc6_);
         _loc4_++;
         _loc6_ = _loc4_;
         var _loc7_:int = int(Math.random() * 100);
         si8(_loc7_,_loc3_ + _loc6_);
         _loc4_++;
         _loc6_ = _loc4_;
         _loc7_ = li8(_loc3_ + _loc5_) + int(Math.random() * 100);
         si8(_loc7_,_loc3_ + _loc6_);
```

After:

```as
         var _loc2_:int = 0;
         var _loc3_:int = int(Math.random() * 100);
         var _loc4_:int = _loc3_;
         _loc3_++;
         si8(_loc4_,_loc2_ + _loc3_);
         _loc3_++;
         si8(int(Math.random() * 100),_loc2_ + _loc3_);
         _loc3_++;
         si8(li8(_loc2_ + _loc4_) + int(Math.random() * 100),_loc2_ + _loc3_);
```

**Pull request closed without merging**
