### PR TITLE
Change Path.unique_file_path to an explicit key type

### LINKED ISSUE #8868: Casing of file in debug infos
I'm not sure if that's a change in VSCode or Haxe, but I now get some weird behavior regarding file casing. For instance in HL I put a breakpoint in `CityView.hx`  and when I break vscode opens a second tab with `cityview.hx`, at the good line, but not showing my breakpoints because they are on "another file".

Actually, I just restarted VSCode and now it works well, so I suppose it's somewhat related to compiler cache ? :-/

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #8868

@ncannasse please, try this branch. It doesn't pass all the tests yet, but I want to know if it's worth going forward with this approach first.

### CODE REVIEW

**Comment by nadako** [comment]
@ncannasse since it "should be fixed urgently", please review ^^

**Comment by ncannasse** [comment]
Seems good to me in terms of overall logic, I couldn't check all the small details, maybe @Simn wants also to review before merge.

**Comment by RealyUniqueName** [comment]
@ncannasse I meant to ask you to build the branch and try it in your workflow to see if it fixes the issue.

**Comment by Simn** [comment]
Changes look good to me. The only thing is that I would like to have the option to cache these keys per-compilation. But it should be easy to add that later by having a `Hashtbl` in the `UniqueKey` module which the compilation server resets.

**Comment by Simn** [comment]
Let's merge this.

**Pull request merged**
