### PR TITLE
[java] support --java-lib <directory>

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Gama11** [comment]
It only just now occurred to me that this might break the "load a directory of class files" feature:

```
--java-lib <file>                     add an external JAR or class directory library
```

Should add some tests...

**Comment by Simn** [comment]
Does this work well with the compilation server?

**Comment by Gama11** [comment]
Um... not sure how it would impact the server, it's just "CLI syntax sugar"?

**Comment by Simn** [comment]
The server tries to avoid some I/O so that we don't have to read things on every request. I'll have to check how to make that work with a directory-based approach.

**Comment by Gama11** [comment]
Ah, but it does check the mtime of the jar files I hope? :)

**Comment by Gama11** [comment]
Regarding the "load a directory of class files" feature, I'll just adjust the CLI help since that doesn't even seem to work without this PR right now...

**Pull request merged**
