### PR TITLE
Handle `1 - - 2` in santize_expr

### LINKED ISSUE #6942: Generated code are wrong
```haxe
class Test {
    static function main() {
        trace(-First);
    }
}

@:enum private abstract ColorRectangleQuadrant(UInt) from UInt to UInt {
 var First = -1;
}
```
results:
```javascript
// Generated by Haxe 3.4.4
(function () { "use strict";
var Test = function() { };
Test.main = function() {
 console.log(--1);
};
Test.main();
})();
```
```javascript
// Generated by Haxe 4.0.0 (git build master @ 2344f23)
(function () { "use strict";
var Test = function() { };
Test.main = function() {
	console.log("Test.hx:4:",--1);
};
Test.main();
})();
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #6942

### CODE REVIEW

**Comment by ncannasse** [comment]
I'm worried that we optimize binops on TInt while they are TCast to Float

**Comment by RealyUniqueName** [comment]
I'd say that's a different issue.
This PR doesn't change existing behavior. It only allows constructors of `enum abstract` to be handled the same way as ordinary `inline var` on binop/unop optimizations.

**Comment by RblSb** [comment]
`(UInt) from UInt to UInt` test is not requred?

**Comment by RealyUniqueName** [comment]
I don't think so. It's about constants, not types. `-1` is always represented as `TConst (TInt -1)` regardless the type.

**Comment by Simn** [comment]
I'm worried about this too and it's not an appropriate fix for #6942 because it's an optimization. Let's please do this later.

**Comment by RealyUniqueName** [comment]
But that's the place, which handles ordinary `inline var`s.
If I disable `optimize_unop` function then this code:
```haxe
class Main {
	static inline var SECOND = -2;

	static function main() {
		trace(-SECOND);
	}
}
```
gets compiled to this js:
```js
console.log("src/Main.hx:5:",--2);
```
So, either we handle it in optimizer, or introduce an intermediate step between typing and optimizer. And that seems to be an overkill.

**Comment by RealyUniqueName** [comment]
Oh, sorry. Missed the messages about sanitize_expr.

**Comment by RealyUniqueName** [comment]
Btw `optimize_unop` and `optimize_binop` are executed even with `--no-opt`

**Comment by RealyUniqueName** [comment]
Fixed in `sanitize_expr`
But still left cast unwrapping in `optimize_unop` and `optimize_binop` because this generated js looks silly:
```js
console.log("src/Main.hx:6:",-(-1));
console.log("src/Main.hx:7:",1 - (-1));
```

**Comment by RealyUniqueName** [comment]
I reverted cast unwrapping

**Comment by Simn** [comment]
Looks like the CI failures are actually related for once.

**Comment by RealyUniqueName** [comment]
CI is green. Is it ok to merge?

**Pull request merged**
