### PR TITLE
[php] refactor bytesdata

### PR DESCRIPTION
**Pull request by frabbit**

### CODE REVIEW

**Comment by Simn** [comment]
Oh god...

**Comment by ncannasse** [comment]
Just after a RC, that's exactly what we need :)

**Comment by Simn** [comment]
To be fair I've been thinking the same thing about everything you do to Bytes. :P

**Comment by frabbit** [comment]
yeah, i wouldn't do it when the current implementation of BytesData in PHP wouldn't be so flawed (BytesData = php.NativeString => call-by-value).

**Comment by Simn** [comment]
So, uh, I have to meditate about this one.

**Comment by Simn** [comment]
Alright then... let's do it!

**Pull request merged**
