### PR TITLE
[cpp] overload resolution for TNew

### PR DESCRIPTION
**Pull request by vonagam**
Adds overloading support for `new` in cpp.

### CODE REVIEW

**Comment by vonagam** [comment]
Rebased on #9516 and added a test.

**Comment by Simn** [comment]
On a related note, I think we should try adding a `tclass_field` to `TNew` so the generators don't have to play this resolution game.

However, my bigger concern is `super()` calls because that would require a different AST node altogether.

**Comment by vonagam** [comment]
Oh, right forgot about `super`. Thanks.

**Comment by vonagam** [comment]
Ah, misinterpreted what you said in `super` concern as about untested effect of this PR on `super` resolution in cpp.
Checked if it wasn't working - it works. Added inheritance with super calls to the test just in case.

Yeah, i find it strange that haxe resolves overloads and then a generator has to do it again.

**Comment by vonagam** [comment]
Simply rebased (now that #9516 was merged), nothing new.

@hughsando can this be given the green light?

**Comment by hughsando** [comment]
thanks - looks good

**Pull request merged**
