### PR TITLE
[php] right shift : return left operand if right operand is 0 in PHP

### PR DESCRIPTION
**Pull request by clemos**
This seems to fix these issues in PHP:
https://gist.github.com/clemos/fc48d8076d936531a386#file-test-hx-L14-L18
Please review carefully, as I'm not at all an expert in bit manipulation :p

### CODE REVIEW

**Comment by ncannasse** [comment]
Could you add the (previously failing) unit test to your PR ?

**Comment by clemos** [comment]
Here it is.
Please notice the test won't pass in JS, though it passes in Neko, CPP and now PHP.

**Comment by ncannasse** [comment]
We can't merge it if it doesn't pass on some platform. Maybe using `>>` still allows you to unit test without having the JS error ?

**Comment by clemos** [comment]
Unfortunately, changing `>>>` to `>>` makes the test irrelevant, as it currently passes in PHP:
The issue only happens with `a >>> 0` where `a < 0` on PHP and JS.
Then unfortunately I have no idea how to fix it in JS.
Maybe we could disable the test while keeping it there for reference, and create another issue based on this test to fix the JS output ?

**Comment by ncannasse** [comment]
Well, let's drop the test then, I agree there was an issue with  _hx_shift_right(0) in the first place.

**Comment by clemos** [comment]
Ok, do you want me to rename the test to `.hx.disabled` then ?

**Comment by ncannasse** [comment]
Remove it from the PR, sry

**Comment by clemos** [comment]
Done

**Comment by ncannasse** [comment]
TY

**Comment by azrafe7** [comment]
I was reading the discussion and found http://stackoverflow.com/questions/1822350/what-is-the-javascript-operator-and-how-do-you-use-it
so maybe it's not worhty to fix js (in the sense that patching it could confuse users)?

**Pull request merged**
