### PR TITLE
[lua] fix signed bitwise ops

### LINKED ISSUE #8849: [lua] invalid bitwise and, or, shift right with negative right hand operand
```haxe
class Main {
    public static function main() {
        var a = -1;
        trace(a & -1);
        trace(a | -1);
        trace(a >> -1);
    }
}
```
lua:
```
$ lua bin/test.lua
src/Main.hx:4: 4294967295
src/Main.hx:5: 4294967295
src/Main.hx:6: 4294967294
```
every other target:
```
src/Main.hx:4: -1
src/Main.hx:5: -1
src/Main.hx:6: -1
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #8849

### CODE REVIEW

**Review by jdonaldson — COMMENTED** [review]
I don't see any issues at first glance.  If CI passes across all the versions we test for it LGTM.
Thanks!

**Comment by jdonaldson** [comment]
Everything looks green, thanks again.

**Comment by RealyUniqueName** [comment]
We could optimize for `-D lua_ver=5.3` by generating `a & b` instead of `_hx_bit.band(a, b)`. Same for other bitwise ops.

**Comment by jdonaldson** [comment]
That's true.  Let me make a feature issue and link this.

**Pull request merged**
