### PR TITLE
Rework internal frontend part 2

### PR DESCRIPTION
**Pull request by Simn**
In part 2 we're mostly dealing with how the compiler manages diagnostics runs. Diagnostics is no longer considered any form of "display mode", but is now what I've called a "report mode". Compilation in diagnostics mode works like normal compilation, but errors are handled differently and at the end we emit the diagnostics report.

Since the goal here is to use diagnostics to fill the cache, proper error state tracking is very important. The function `is_diagnostics_run` was used to branch in various places and usually avoid explicit errors. I have renamed it to `error_in_diagnostics_run`, which now sets `com.has_error <- true`. This is also true for `add_diagnostics_message` if the severity is `Error`. This _should_ cover all cases.

The architecture to re-cache in diagnostics mode is in place as well, but it's not executed yet because for now I just want everything to still work.

Other than that:

* `CompilationServer` is now named `CompilationCache` and is a child of `ServerCompilationContext`. There's no longer any global instance, which in theory allows us to completely replace the cache on a running server. It is also available on `com.cs` for convenience.

* `dms_display` has been removed. It was used in various places to avoid some work in display mode, but it wasn't really consistently used. In cases where we want to avoid showing errors, we now check for `dms_error_policy = EPIgnore`. In other places, we check against `dms_full_typing`, which is pretty much the same thing anyway.

* I noticed that the very entry point of the compiler had `MacroContext.setup()`. This would setup a complete macro context even in cases where we pretty much immediately `--connect` out. I have moved the call to the point right after we're done parsing arguments, which should be the earliest we ever need a macro context.

Once this is merged, we can try activating the diagnostics caching again and maybe it will finally work now...

### CODE REVIEW

**Comment by Simn** [comment]
I don't know what's up with `windows-test (macro) (pull_request)` failing. `windows-test (macro) (push)` passed, and so did `windows64-test (macro) (pull_request)`. I'll assume that this is in the "random nonsense" category and merge regardless.

**Comment by RblSb** [comment]
Can you please restore this branch, so i can checkout it and test per-commit?

**Comment by Simn** [comment]
done

**Comment by RblSb** [comment]
Completion doesn't fail if i revert these two lines on this commit:
https://github.com/HaxeFoundation/haxe/pull/10631/commits/cd873c3a0ec1f801b39f681f15899db95e8d45ac#diff-3da2cb86f720d73378e4c6ff1ffd34c8f7ac5d8c19a2bbf70a79ef36b977d858L701-L702
(dont know how to test such match case on current development after refactoring)
There is minimal patch i can get, applied to commit before broken one in this PR ([rename is_diagnostics_run to error_in_diagnostics_run](https://github.com/HaxeFoundation/haxe/pull/10631/commits/9f8a865a5340bf2934e65731c3383dd203e6b5d1)):
[0001-Fix.patch.zip](https://github.com/HaxeFoundation/haxe/files/8395917/0001-Fix.patch.zip)

Also, there is no difference in vshaxe output log with broken completion server, only this error data from here https://github.com/vshaxe/haxe-language-server/blob/c53778accdd55c4082f585d0addaf6a37eed82df/src/haxeLanguageServer/server/HaxeServer.hx#L160
```json
{
   "jsonrpc":"2.0",
   "id":0,
   "result":{
      "result":{
         "methods":[
            "display/definition",
            "server/contexts",
            "server/moduleCreated",
            "server/invalidate",
            "server/module",
            "server/files",
            "initialize",
            "display/completion",
            "typer/compiledTypes",
            "display/references",
            "server/modules",
            "server/memory/context",
            "display/completionItem/resolve",
            "display/typeDefinition",
            "server/memory",
            "display/implementation",
            "display/hover",
            "display/package",
            "display/signatureHelp",
            "server/memory/module",
            "server/readClassPaths",
            "server/configure"
         ],
         "haxeVersion":{
            "major":4,
            "minor":3,
            "patch":0,
            "pre":"rc.1",
            "build":"793d63d97"
         },
         "protocolVersion":{
            "major":0,
            "minor":5,
            "patch":0
         }
      },
      "timestamp":1648771043.357264
   }
}
```

**Pull request merged**
