### PR TITLE
Allow nullable bool if

### PR DESCRIPTION
**Pull request by RblSb**
```haxe
final map = [1 => true];
if (map[1]) {}
```

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
This is by design. The intention was to help to detect if you forget to initialize your boolens.
Though I'm not sure if that's convenient in practice.

**Comment by RblSb** [comment]
I feel like this restriction will mostly force people to write `if (arr[i] == true)`, same for any other array access structure with bools, and it looks meh... And with this change `bool = nullableBool` still will be error, so it's just a sugar for such cases.

**Comment by Gama11** [comment]
For what it's worth, Kotlin took the same approach, so Haxe is not alone here:

```kotlin
val b:Boolean? = false
// Type mismatch.
// Required: Boolean
// Found: Boolean?
if (b) {

}
```

**Comment by RealyUniqueName** [comment]
Kotlin has operator for that. In Haxe we only have static extensions.

**Comment by RblSb** [comment]
Not sure other operators are related.
Also Kotlin code:
```kotlin
var arr = booleanArrayOf(true, true)
if (arr[1]) println("Hi")
arr[2] = true; // error
if (arr[2]) println("Hi") // error
```
Not for Kotlin's Map tho, so i guess writing `if (keys[Backspace]) {}` is not safe enough anymore, will be missing it.
About not-null arrays, there is safety lib for that, i hope this will be in std top-level and with compiler flag sooner than later.

**Pull request closed without merging**
