### PR TITLE
remove @:fakeEnum

### PR DESCRIPTION
**Pull request by nadako**

### CODE REVIEW

**Comment by nadako** [comment]
Should we add an error on `@:fakeEnum` hinting that one needs to migrate to `enum abstract`?

**Comment by RealyUniqueName** [comment]
It's better to add it.

**Comment by nadako** [comment]
https://github.com/HaxeFoundation/hxnodejs uses some `@:fakeEnum`s but that can be easily changed I think

**Comment by nadako** [comment]
> It's better to add it.

Done :)

**Comment by Simn** [comment]
I don't really understand this `"enumAbstract:"` stuff, but you probably do.

**Review by Simn — APPROVED** [review]

**Comment by nadako** [comment]
> I don't really understand this `"enumAbstract:"` stuff, but you probably do.

That is for this "type patching" thing, it's a marker that enables transforming a class with static constants into an enum. it was @:fakeEnum before, now it's enum abstract :-)

**Pull request merged**
