### PR TITLE
possible fix for PHP reflection problem

### PR DESCRIPTION
**Pull request by mockey**
fix for reflection problem that occurred in #3030
use $r->name instead of $r for array that gets passed to call_user_func
enabled Issue3030

### CODE REVIEW

**Comment by Simn** [comment]
@tml: Does that make sense to you?

**Comment by tml** [comment]
:+1:

**Comment by Simn** [comment]
I'll go ahead and merge this because it fixes the current issue. We can look into optimizing it for the call-case at some point, but I'm not sure I'll be able to do that for 3.2.

Did I mention that we need a maintainer for genphp? :)

**Comment by mockey** [comment]
Well, I have a couple of websites running with haxe-php, so naturally I'm interested in being able to generate them with a current haxe version. Which means: you can call me whenever there's a problem :-)
I reckon there's not much interest in updating genphp to use some current PHP features (namespaces, closures,...), though.

**Comment by Simn** [comment]
Could you test your applications with current Haxe some time? There haven't been too many changes to the PHP generator but we should still double-check that there are no silly regressions.

**Comment by mockey** [comment]
Sure. I always use a quite current Haxe dev version, compiled from git every one or two weeks. It's mostly stable and usable BTW (for my usage at least) and small regressions are always fixed quickly (great praise for that!).
And of course I report issues whenever I find them (see e.g. #3897). That's the least I can do.

**Comment by tml** [comment]
It might be nice to get some of that code into tests, so that we can start to make some real changes to genphp with a bit more confidence. :)

**Pull request merged**
