### PR TITLE
Remove hx4compat stuff (part 1)

### PR DESCRIPTION
**Pull request by Simn**
Removes `sys.db`, `neko.Web` and `php.Web`. These have been moved to https://github.com/HaxeFoundation/hx4compat.

Neko and PHP need an update to utest before this can be merged: https://github.com/haxe-utest/utest/pull/125

### CODE REVIEW

**Comment by Simn** [comment]
I'm testing this with my utest branch to make sure it works, but I'd still like to only merge this once it has been fixed in real utest.

**Comment by Simn** [comment]
Thanks for helping!

The remaining JS failures all come from failing to assign `Something<Dynamic>` to `Something<Specific>`. Order matters here, and the usual 1. expected 2. actual assertions won't work like that because we usually expect something specific and have something generic.

I'll just swap these for now...

**Comment by Simn** [comment]
utest2 has been merged, so now I actually have to merge this PR or else our tests won't work anymore!

**Comment by kLabz** [comment]
Ohh so that's why :sweat_smile:
I always have the best timing for updating branches full of conflicts, I thought I messed up something horribly :laughing:

**Pull request merged**
