### PR TITLE
Save big files using Http

### PR DESCRIPTION
**Pull request by nescribal**
Adds the posibility to set an haxe.io.Output to save the response into a file for example. So if you want to download a big file, you don't have much memory consumption.
Also adds the posibility to cancel the ouput reading from socket, allowing to cancel the request (if run it in a thread for example).

### CODE REVIEW

**Comment by nescribal** [comment]
Use:

```
var r: Http = new Http("http://www.mydomain.com/large-video.mp4");
r.customOutput = haxe.io.File.write("./output.mp4");
r.onData = function(d: String){trace("File downloaded at: ./output.mp4" );}
r.onError = function(e: Dynamic){trace("ERROR downloading ./output.mp4" + e );}
r.request();
```

**Comment by ncannasse** [comment]
You can already do that by calling customRequest instead of request

**Comment by nescribal** [comment]
Nicolas,

Would you consider add the cancel part if I create a new pull request?

Thanks!

**Comment by ncannasse** [comment]
The cancel would not work very nicely since the socket is blocking. Properly canceling a download would require multithreading and a proper event loop with async sockets, which is not the goal of haxe.Http for now

**Pull request closed without merging**
