### PR TITLE
Http class returns code 0 (not a real Http code) when accessing a file f...

### PR DESCRIPTION
**Pull request by yanhick**
...rom the local filesystem

### CODE REVIEW

**Comment by ncannasse** [comment]
There was recently a merge related to this, could you confirm it fixes your issue ?

**Comment by bjitivo** [comment]
Looking at change 018ad84 (Merge pull request #3353 from SmilyOrg/development), it would appear that this would fix the bug and that this pull request  #3993 is unnecessary for fixing our particular issue.

However, I would like to point out that the version pulled in with change @3353 looks to be alot less efficient (doing string math, creating a regexp, matching a regexp against a string) than just accepting a status code of 0 as is in this pull request, which is just an integer comparison.

Furthermore, change 018ad84 uses a set of arbitrary seeming strings to match against for file protocol.  I don't know what guarantee there is that the list is complete and will continue to be complete going forward.

**Comment by bjitivo** [comment]
Furthermore, I think that change 018ad84 will fail for

**Comment by bjitivo** [comment]
Whoops hit comment accidentally.

Furthermore, I think that change 018ad84 will fail for empty files, which is a valid (albeit unusual) use case.

**Comment by derRaab** [comment]
Since @ncannasse commented here https://github.com/HaxeFoundation/haxe/pull/3353#issuecomment-87781444 I'd like to give you my (2) point(s) of view on this:

1. I think it's a good idea to accept http status 0 ONLY for local protocols (which is usually, but not only, meant as a fallback for development purposes). If we would always accept http status 0 it would be very difficult to realize server side misconfigurations for example. So I'm definitely for checking the protocol (which only happens if http status is 0. But I would love to see a Browser.isLocal property which evaluates the protocol just once.

2. I furthermore think it's a good idea to check if actual data is available. There is (to my knowledge) no other way to detect if a file is actually loaded or not. Even if it's not possible to load empty files (which is a rare case).

So in the end I would love to see the currently merged solution in Haxe 3.2. We use it since even before we created the pull request. Consider since as of today nobody can load local static files using haxe 3.1.3.

**Comment by derRaab** [comment]
But we could improve on this for 3.2.1!

**Comment by ncannasse** [comment]
It seems that the approach in 018ad840bbdc01c2845005e05c3c42822f51b640 was following the one that is made by JQuery. I tend to think that what is good for JQuery is good for us as well, should we close @bjitivo ?

**Comment by bjitivo** [comment]
Yes, you can close this.

**Pull request closed without merging**
