### PR TITLE
Fix String API for Lua with --no-inline

### PR DESCRIPTION
**Pull request by piotrklibert**
This (probably) solves: https://github.com/HaxeFoundation/haxe/issues/9530

### CODE REVIEW

**Comment by Simn** [comment]
@jdonaldson Please check!

@piotrklibert A test would be good. Since this depends on compilation argument, the best place to add the test is in tests/misc. Try copying https://github.com/HaxeFoundation/haxe/tree/development/tests/misc/projects/Issue4265 and adjust the files there accordingly.

**Comment by piotrklibert** [comment]
Thanks, I'll try doing that.

**Comment by jdonaldson** [comment]
Thanks for this!  I'm checking it out, I think it'll cover the problem.  I'm also going to remove some of the inlines from the string methods.  I can't tell that they improve anything at all.

**Comment by Simn** [comment]
I'm tentatively setting this to 4.3 because it looks quite useful, but we'd need a lua person to add a test.

**Comment by Simn** [comment]
Closing in favor of #11057.

**Pull request closed without merging**
