### PR TITLE
[ci] add deploy job to GH actions (will publish into a separate folder for now)

### PR DESCRIPTION
**Pull request by nadako**
not sure if i'm missing anything, but this seems to work: https://build.haxe.org/builds/gh-actions/haxe/

### CODE REVIEW

**Comment by nadako** [comment]
I guess I'll just merge this and let CI run for some time to see if there are issues. If all is good, we can remove deploying from azure and make GH actions deploy to the main folder.

**Comment by Simn** [comment]
The linux64 binaries gained some weight:

```
Azure    : 2020-07-26 07:39:10      6986095        haxe_2020-07-26_development_646f1c2.tar.gz
ghactions: 2020-07-26 07:27:52      8739585        haxe_2020-07-26_development_646f1c2.tar.gz
```

Other builds are fine.

**Comment by Simn** [comment]
By the way, I'm noticing that the NSIS terror doesn't seem to affect the gh-actions builds. Not sure if that's just luck or "by-design".

**Comment by nadako** [comment]
> The linux64 binaries gained some weight:
> 
> ```
> Azure    : 2020-07-26 07:39:10      6986095        haxe_2020-07-26_development_646f1c2.tar.gz
> ghactions: 2020-07-26 07:27:52      8739585        haxe_2020-07-26_development_646f1c2.tar.gz
> ```
> 
> Other builds are fine.

That's weird, probably has something to do with the building process or compiler versions, because the deployment is exactly the same as before - unzip artifacts and upload with s3...

**Comment by nadako** [comment]
> By the way, I'm noticing that the NSIS terror doesn't seem to affect the gh-actions builds. Not sure if that's just luck or "by-design".

[Yeah...](https://github.com/HaxeFoundation/haxe/commit/f3788ca5a6cb4f49efa83e86a61c28732b86f45a)

**Pull request merged**
