### PR TITLE
Fast version of startsWith/endsWith

### PR DESCRIPTION
**Pull request by robinrodricks**
This PR improves the implementation of `String.startsWith` and `String.endsWith` to improve performance and memory usage in the JS and AS3 targets.

- Hidden object allocation removed (in the present implementation a new string is created and then compared with the prefix/postfix)
- High speed platform methods (`indexOf` and `lastIndexOf`) are used in a novel way to provide "begins with" and "ends with" functionality
- **startsWith** : we run `lastIndexOf` with the prefix, starting at character 0. This means it performs a single check starting at character 0, instead of searching through the whole string.
- **endsWith** : we run `indexOf` with the postfix, starting at `mainStr.length - end.length`. This means it performs a single check starting at character `mainLen - endLen`, instead of searching through the whole string.

### CODE REVIEW

**Comment by ncannasse** [comment]
I'm not sure if that's an actual optimization... on big strings, indexOf will do a full lookup on the whole string.

**Comment by jonasmalacofilho** [comment]
> on big strings, indexOf will do a full lookup on the whole string

Won't `indexOf` simply bail out when the first check (at `slen - elen`) fails?  At any later position there won't be enough room for `end` anyway.

**Comment by Simn** [comment]
Sounds like a benchmark case for https://github.com/HaxeFoundation/haxe/blob/development/tests/benchs/src/cases/StringScan.hx

**Comment by robinrodricks** [comment]
> I'm not sure if that's an actual optimization... on big strings, indexOf will do a full lookup on the whole string.

@ncannasse No. That's the whole point of this "novel" usage. To check if a string begins with a prefix, we run `lastIndexOf` instead of `indexOf`. And we run it in such a way that it bails out after exactly one check, ie. after comparing the prefix at character 0 of the main string. For "ends with" we do the opposite. 

Here's a quick speedtest in JS: ([gist](https://gist.github.com/robinrodricks/a71b4b38ce8b7a2c3c52e76493a2700c))

- startsWith using Substring : 16.0649999997986 ms
- startsWith using LastIndexOf : 13.644999999996799 ms
- endsWith using Substring : 9.340000000520376 ms
- endsWith using IndexOf : 5.839999999807333 ms

And here's a quick speedtest using AS3 AIR: ([gist](https://gist.github.com/robinrodricks/ecaf53e95e9584225ab039e93b45746d))

- startsWith using Substring : 391 ms
- startsWith using LastIndexOf : 348 ms
- endsWith using Substring : 403 ms
- endsWith using IndexOf : 370 ms

Even if its the same speed, it eliminates the allocation of new strings every time you want to check startsWith and endsWith.

**Comment by ncannasse** [comment]
Yes, my bad, I didn't see you were using the start position of indexOf/lastIndexOf.

**Comment by Simn** [comment]
You might want to check this on HL due to #7746.

**Comment by ncannasse** [comment]
We already have some `#if hl` that directly compares the bytes without any allocation ;)

**Pull request merged**
