### PR TITLE
[eval] Migrate to pcre2

### LINKED ISSUE #10491: migrate pcre
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000117

### PR DESCRIPTION
**Pull request by tobil4sk**
Closes #10491

I rewrote the existing ocaml pcre bindings for pcre2. I also uploaded them here: https://github.com/tobil4sk/pcre2-ocaml, but the version in this PR is slightly modified for compatibility with the OCaml version used by Haxe.

This addresses the null byte in regex bug as well: #10592

### CODE REVIEW

**Comment by Simn** [comment]
Oh shit, CI is actually green...! I'll quickly merge this before it changes its mind.

Thank you so much, this has certainly been on my personal "Oh God not that problem"-backlog.

**Comment by Uzume** [comment]
@tobil4sk Great work! Are you going to look at hxcpp next?

Maybe I will try to take [tobil4sk/pcre2-ocaml](https://github.com/tobil4sk/pcre2-ocaml) and work it into a PR at [mmottl/pcre-ocaml](https://github.com/mmottl/pcre-ocaml) or something and try to get it introduced into opam. There are many dependencies on [opam - pcre](https://opam.ocaml.org/packages/pcre/) that would do well to be ported to pcre2. I know many distributions (like Debian and Ubuntu, etc.) that want to drop pcre1 packages (like the confusingly named [pcre3](https://tracker.debian.org/pkg/pcre3)) but there is still too much software that depends on them and this might go a long ways towards helping that situation.

**Comment by tobil4sk** [comment]
> Are you going to look at hxcpp next?

@Uzume Yes, I'll make a PR soon. I've ported our code, but there are still some building issues that have to be resolved.

> Maybe I will try to take [tobil4sk/pcre2-ocaml](https://github.com/tobil4sk/pcre2-ocaml) and work it into a PR at [mmottl/pcre-ocaml](https://github.com/mmottl/pcre-ocaml)

The author of pcre-ocaml has said he thinks pcre2-ocaml should be kept separate, but we can upload prce2 as a new opam package. There are still a few things that are missing (namely jit compilation) which we didn't need for Haxe but which would have to be implemented before the library is ready more generally. If you like, feel free to open an issue in pcre2-ocaml and we can discuss further over there.

**Comment by Uzume** [comment]
> The author of pcre-ocaml has said he thinks pcre2-ocaml should be kept separate, but we can upload prce2 as a new opam package. There are still a few things that are missing (namely jit compilation) which we didn't need for Haxe but which would have to be implemented before the library is ready more generally. If you like, feel free to open an issue in pcre2-ocaml and we can discuss further over there.

@tobil4sk: Yes, I am aware of that. I was just thinking to create a branch in the original repo for pcre-ocaml and move the default master branch over to pcre2-ocaml (or something similar). It makes little sense to consider maintenance for these in entirely different repos when a separate branch should suffice.

**Comment by RblSb** [comment]
I don't think that `brew install pcre2` from `BUILDING.md` is enough for macos setup, there is `pcre2.h not found` error anyway.
I fixed this for myself with manual pcre2 installation from [this archive](https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.42/pcre2-10.42.tar.gz), and then doing `configure/make` from haxe CI instructions and `chmod`ing everything in `usr/local` to make it install at any permission price (don't care much).

**Comment by tobil4sk** [comment]
Hm, could be related to https://github.com/HaxeFoundation/haxe/issues/11012

**Pull request merged**
