### PR TITLE
[macro] Expose `followWithAbstracts`

### PR DESCRIPTION
**Pull request by waneck**
I wasn't sure where to add that test, but I guess `TestType` doesn't sound too bad ;)

### CODE REVIEW

**Comment by Simn** [comment]
What's the deal with that `once` argument anyway?

**Comment by back2dos** [comment]
@Simn It has to do with the fact that sometimes you want to know all the typedefs along the way. Example `typedef Foo = Null<Int>`. If say RecordMacros encounters a field of type `Foo` it must have a way to find out it's nullable and that is accomplished by following only once (recursively).

**Comment by fzzr-** [comment]
:+1: I think `followWithAbstracts` will be a great addition to macro-tools.

**Comment by waneck** [comment]
I'm telling appveyor to rerun the tests, since the failure had nothing to do with the change

**Comment by waneck** [comment]
@andyli , any idea why AppVeyor is failing?

**Comment by andyli** [comment]
Looks like an issue of AppVeyor itself.
I cannot request AppVeyor to rebuild this PR since there is merge conflict.

**Pull request merged**
