### PR TITLE
[std] modernize some @:optional/@:extern/@:final/@:enum syntax

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Simn** [comment]
Note that `final` on field-level is a replacement for `var`, not a modifier.

**Comment by Gama11** [comment]
Good point...

I knew CI would find something, there's also a failure on Lua. Does `@:extern` on class level have a different behavior than `extern`? Or does `@:extern` simply not exist on class level and is just dead code? 🙃

**Comment by Simn** [comment]
That might be dead code.

**Comment by Gama11** [comment]
Looks like there's also no completion for this stuff, with or without `@:`: https://github.com/HaxeFoundation/haxe/issues/7761

**Pull request merged**
