### PR TITLE
[neko] Make haxe.Int64 use the new int64 primitive in Neko if possible

### PR DESCRIPTION
**Pull request by waneck**
This PR only makes sense when coupled with https://github.com/HaxeFoundation/neko/pull/55 . All tests pass with the new int64 primitive; I've made it so the implementation would gracefully fall back to the default implementation if the primitive wasn't found.

### CODE REVIEW

**Comment by ncannasse** [comment]
Did you try actual benchmarks to compare the new version vs the old one ? My guess is that unless we properly support int64 into the JIT this might be slower than using two int32 fields. Also, if it becomes a primitive, maybe we really don't want to make it mutable...

**Comment by waneck** [comment]
I didn't try them. I can do it - but my main purpose on adding them was not entirely speed (although I'm quite convinced that it will be faster than the interpreted version), it was in order to be able to use int64 on the neko side in a better way. This way it will be easier to support APIs using it on the C side - for example, I can imagine extending the I/O API to support file seeks using a 64-bit Int.

**Comment by waneck** [comment]
Also I agree that it's better to make it immutable.

**Comment by Simn** [comment]
This PR no longer merges. Sorry for not looking into it earlier, but at this point the best we can do is close it.

**Pull request closed without merging**
