### PR TITLE
Xml rewrite

### PR DESCRIPTION
**Pull request by Simn**
This pull request unifies XML handling into a single representation for all targets. My plan is to get this stable, then look into optimizing performance again. These are the current results of parsing and traversing a 2.7 MB XML file:

target | new parse | old parse | new access | old access | %
--- | --- | --- | --- | --- | ---
flash | 0.63 | 0.27 | 1.6 | 7.36 | 29%
neko | 4.45 | 1.07 | 3.81 | 3.82 | 169%
php | 8.63 | 5.11 | 11.25 | 10.3 | 129%
cpp | 0.92 | 4.33 | 0.27 | 0.45 | 25%
interp | 7.28 | 2.91 | 5.03 | 5.55 | 146%

The Flash results are with #3743 merged. 

For neko I've already worked on a native parser implementation to speed up parsing again: https://github.com/HaxeFoundation/neko/compare/xml_parser_backport

I've also tried using the native PHP parser again but ran into too many issues for now.

@ncannasse: Any objections?

### CODE REVIEW

**Comment by delahee** [comment]
I find it encouraging and am eager for Neko improvement :)
Le 13 janv. 2015 18:24, "Simon Krajewski" <notifications@github.com> a
écrit :

**Comment by Simn** [comment]
It looks like I was testing with debug neko. This is what I'm getting in release mode with https://github.com/HaxeFoundation/neko/pull/48 being merged:

target | new parse | old parse | new access | old access | %
--- | --- | --- | --- | --- | ---
neko | 0.88 | 0.91 | 0.94 | 0.8 | 106%

So accessing is a little bit slower now because the Xml data structure is less tailor-made for neko. That's easy to optimize though.

**Comment by ncannasse** [comment]
Only one thing I wish before we merge that : keep the old NativeXml implementations in platform specific package ( php.NativeXml etc. ) so people that want to keep old broken behavior can use them instead.

**Comment by ncannasse** [comment]
PS : any reason why the results in C++ are slower than Flash and Neko ?

**Comment by Simn** [comment]
No idea, but we can reintegrate the native cpp parser too once we fixed things.

**Comment by Simn** [comment]
I'll merge this first and add the NativeXml classes a bit later because I have to make sure that all the untyped stuff uses the correct classes. I also have to add the special checks for flash/as3 again and deal with matches on the old XmlType again... argh.

**Comment by jdonaldson** [comment]
Thanks for putting this together @Simn!

**Pull request merged**
