### PR TITLE
Disallow macro-in-macro

### PR DESCRIPTION
**Pull request by Simn**
This PR disallows _calling_ a macro while in macro context. We do this by replacing macro calls with `throw "macro-in-macro"`. This means that you get a proper eval exception with stacktraces and can also debug it.

Macro-in-macro has been a long standing problem for various reasons. Combined with the fact that I think nobody actually _wants_ to use this as a feature and only does so accidentally, I propose that we remove it entirely for Haxe 4.

As for the benefits of this change, it

* removes the last reason why inlining could still be canceled,
* eliminates a cryptic cause of the compiler cache not working for certain modules and
* probably addresses a leak due to the captured `ctx` that was used for typing the macro at macro run-time.

Please note that it doesn't complain about a macro-in-macro being _typed_. The error only triggers if it ends up actually being _called_. This is an important distinction because it means we don't need additional `#if macro` fencing.

### CODE REVIEW

**Comment by ncannasse** [comment]
Good for me, although I think we should be able to properly support macro-in-macro by creating a second macro context (which would use same interp because of cache), the only problem being infinite loops for which we should limit the depth and then fallback to your solution of a runtime error.

**Comment by Simn** [comment]
I experimented with this and I don't think it's a good idea. Properly supporting macro-in-macro would mean that we expand macros while _typing_ the macro context. That would mean a huge shift in semantics because suddenly all your macros get called twice if you have the macro in the same class as the call.

**Comment by ncannasse** [comment]
Well, they actually do get calls N times where N is the depth level we
allow (macro-in-macro-in-macro-in-...). Another possibility would be to
forbid calling macros in the module you're currently macro'ing - the way
your current patch does it.

**Comment by Simn** [comment]
> Well, they actually do get calls N times where N is the depth level we allow

That would only be true if we keep creating macro contexts, which doesn't sound like a good idea in the first place.

But what I really ask myself in all this is: Why? Does this bother you only on a technical level or do you see legitimate use-cases for macro-in-macro? I just don't think the complexity is worth it.

**Comment by ncannasse** [comment]
There are two kind of macros : API macros that helps with building specific
content (CastleDB, Heaps resources, SQL macros, etc.) and more "generic"
programming macros that can help to better express some high level
concepts. While the "specific" macros are only used from the main context I
can see the "generic" macros being themselves used in macros. But I agree
it's not a big show stopper for me or my team atm.

**Comment by Simn** [comment]
I'll merge this for now. If we decide to support macro-in-macro in the future we can discuss this further.

**Pull request merged**
