### PR TITLE
add string_kind to String constants

### PR DESCRIPTION
**Pull request by nadako**
This adds "kind" information to string constants, preserving whether the string is single or double quoted. 

It's a first step towards proper handling of string interpolation, so the idea is that the third `Format` kind will be added for format strings containing information about interpolations that will be processed by typer (instead of current re-parsing) and also available to users through macro API.

This is a breaking change regarding macros in two ways:
 * the `CString` constructor now accepts a new `kind:StringKind` argument, so construction and pattern-matching will have to be adapted
 * the `macro "some"` is now different from `macro 'some'` due to different kind argument value, which can affect macros that use reification together with pattern matching (e.g. `case macro "some"` won't match `'some'` now because of different quoting).

As a hardcore macro user, @back2dos might want to comment on this breaking.

### CODE REVIEW

**Comment by Simn** [comment]
We could make the second argument to CString optional and default to double quotes. But I'd also prefer to do it properly, if it doesn't break too much code.

**Comment by Simn** [comment]
Actually, we should consider the Haxe 3 vs. 4 problem again. It should be possible to define things in a way that works on both of them. So maybe making it optional is indeed a good idea...

**Comment by back2dos** [comment]
I'm not particularly concerned about pattern matching `CString`, because most of the time I use [tink_macro's `getString`](https://github.com/haxetink/tink_macro/blob/master/src/tink/macro/Exprs.hx#L340) which can abstract away the differences.

The reification thing strikes me as way more problematic (because it's a great source of weird errors) and I think it's avoidable. What surprises me is that we wind up with three kinds. Wouldn't it make more sense to do this:

```haxe
enum StringKind {
  Plain;
  Format(e:Expr);//or use some more specific data structure here
}
```

Examples:

```haxe
macro "some" => EConst(CString("some", Plain))
macro 'some' => EConst(CString("some", Plain))
macro "some$thing" => EConst(CString("some$thing", Plain))
macro 'some$thing' => EConst(CString("some$thing", Format(...)))
```

---- 

> We could make the second argument to CString optional and default to double quotes. But I'd also prefer to do it properly, if it doesn't break too much code.

I don't think that creating constant string expressions by hand is a thing, so on that end it doesn't matter.

**Comment by Simn** [comment]
How does having 2 or 3 kinds make a difference? The reification problem is not going to go away if there are only 2 options.

The new behavior is technically correct and more accurate: There's no reason why `macro "foo"` should match `'foo'` because both are different syntax. On the other hand, it seems reasonable to assume that someone matching that might only care about the string value, not how the string is quoted. So I'm not sure...

> I don't think that creating constant string expressions by hand is a thing, so on that end it doesn't matter.

Maybe not, but matching CString certainly is a thing.

**Comment by back2dos** [comment]
> How does having 2 or 3 kinds make a difference? The reification problem is not going to go away if there are only 2 options.

To me it seems like it is going away.

Right now, these `case macro "foo"` and `case macro 'foo'` are equivalent, while `case macro "$foo"` and `case macro '$foo'` are not. With the representation I am proposing, this will remain the case.

> The new behavior is technically correct and more accurate: There's no reason why `macro "foo"` should match `'foo'` because both are different syntax. On the other hand, it seems reasonable to assume that someone matching that might only care about the string value, not how the string is quoted. So I'm not sure...

Here's the thing `"foo"` and `'foo'` are exactly the same thing. Under all circumstances `"foo" == 'foo'` holds (unlike `"$foo" == '$foo'`). They are the same constant, always. Practically speaking, it's borderline insane to write a macro that treats the differently and I don't remember anyone ever asking for the possibility to do that. It is surely is "technically correct and more accurate". Accuracy comes at a price and in this case I would say it's not worth paying. The pragmatic sweet spot lies not in discerning single vs. double quoted strings, but plain vs. interpolated. That distinction still is "technically correct". It abstracts away a concrete detail, but last I checked, that what the A in AST stands for ;)

**Comment by Simn** [comment]
> Here's the thing "foo" and 'foo' are exactly the same thing.

Their values are, their syntax isn't. For example, you wouldn't want a code formatter to replace all your double quotes with single quotes. That makes it necessary to distinguish them _at some level_.

**Comment by back2dos** [comment]
> That makes it necessary to distinguish them *at some level*.

Your emphasis is spot on. A code formatter transforms *concerte* syntax, not *abstract* syntax. You wouldn't want it to throw out comments or conditional compilation branches that are skipped. These are two separate problems, that need to be tackled on two different levels. Any unifying solution will fall short on both.

**Comment by nadako** [comment]
What @back2dos says makes sense to me. Our AST isn't full-fidelity, so for practical reasons it might not make sense to distinguish string quotes at that level indeed...

**Comment by nadako** [comment]
closed for rework (once again)

**Comment by back2dos** [comment]
Sorry ^^

**Comment by nadako** [comment]
It's fine, really :) What you said about concrete vs abstract syntax gave me an idea on could concrete parse trees work with our ast in haxe (for better ide support) :)

**Pull request closed without merging**
