### PR TITLE
fixed split/indexOf between chars

### PR DESCRIPTION
**Pull request by ncannasse**

### CODE REVIEW

**Comment by ncannasse** [comment]
PHP issue seems unrelevant

**Comment by ncannasse** [comment]
Uhm, weird travis was giving green but now eval fails, that's work for you @Simn

**Comment by Simn** [comment]
I've already reopened #7247.

**Comment by Simn** [comment]
Note that your `lastIndexOf` implementation has linear cost in a contrived worst-case:

```haxe
import haxe.Timer;

class Main {
	static public function main() {
		var s = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";
		for (i in 0...10) {
			s += s;
		}
		var t = Timer.stamp();
		trace(s.length, s.lastIndexOf("e"));
		trace(Timer.stamp() - t);
	}
}
```

That takes 3.5 seconds through the HL interpreter for me.

**Pull request merged**
