### PR TITLE
Map toString brackets

### LINKED ISSUE #8030: [std] use map literal syntax in Map's toString()
In the context of modern Haxe with its map literal syntax, `Map`'s string representation feels a bit unnatural, as it uses `{}` instead of `[]`:

```haxe
class Main {
	static function main() {
		trace([1 => "one"]); // {1 => one}
	}
}
```

I'm assuming that this is from a time before Haxe had map literals?

Changing it might be considered a minor breaking change.

### PR DESCRIPTION
**Pull request by RblSb**
Closes #8030
Also requires change in hxcpp and fixes. Check if current test in `TestBasetypes` is fine.
Upd: oh, i thought there would be CI unit test results.

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
> oh, i thought there would be CI unit test results.

There should be. Maybe a temporary lag. Let's wait.

**Comment by Simn** [comment]
Might have to force-push to get it to trigger again.

**Comment by RblSb** [comment]
After some investigation i can only say that this PR is CURSED.
Can try to recreate, but not sure after hxcpp repo ignores me too.
I'm also tried to setup azure for fork, but `Build.Repository.Uri` and `Build.SourceBranchName` vars is not enough? Instructions in `tests/README` would be nice.
My error is `An error occurred while loading the YAML build pipeline. Variable group  was not found or is not authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

**Comment by RealyUniqueName** [comment]
I remember having the same issue in my fork, but I don't remember how I fixed it. Maybe @andyli can help?

**Comment by RblSb** [comment]
See #9260

**Pull request closed without merging**
