### PR TITLE
Bitwise operators overflow on 32 bits even on 64bit systems

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Check targets which don't agree. See #8095

### CODE REVIEW

**Comment by Simn** [comment]
Note that our CI mostly runs on 64bit systems.

**Comment by ncannasse** [comment]
PHP + Python + Lua, I think that should be easily fixable for 4.0 final.

**Comment by Simn** [comment]
Branch needs an update.

**Comment by RealyUniqueName** [comment]
This was just to find out failing targets.

**Pull request closed without merging**
