### PR TITLE
[WiP] Adding keyValueIterator to Array

### PR DESCRIPTION
**Pull request by elnabo**
See #7395 

# Array
- [x] unit test
- [x] cpp
- [x] cs
- [x] eval
- [x] flash
- [x] hl
- [x] java
- [x] js
- [x] lua
- [x] neko
- [x] php
- [x] python

Edit: Limit to Array

### CODE REVIEW

**Comment by elnabo** [comment]
@nadako didn't see your comment on #7395 before doing this commit. Hope didn't redo what you already did.

Some changes might be needed to the Array.keyValueIterator function according to what have been said there.

**Comment by Simn** [comment]
Oooh, I like where this is going!

I was thinking that we should open `haxe.iterator` to store some common code. That way we don't have to duplicate these iteration classes so much.

**Comment by elnabo** [comment]
That would be nice, especially since many target have different naming/style convention.

Btw, I assume that Array handling in cpp is done in hxcpp. But what about the hl and flash target ?

**Comment by Simn** [comment]
Check the Boot.hx class for flash.

And yes, both hxcpp and hl are going to need updates to their native code.

**Comment by ncannasse** [comment]
Just wanted to make sure : can we accurately make sure that the code `for( idx => key in array )` will not result in any temp object being allocated in the form `{ key : index, value : v }` ?

**Comment by RealyUniqueName** [comment]
@elnabo I can't make a PR to your fork, so here is the commit wich, I guess, illustrates what @Simn means with `haxe.iterators`: https://github.com/RealyUniqueName/haxe/commit/3303ce374916090844675210273e3e83302ab6b1
This way no temp objects/allocations will be generated by the compiler.

**Comment by elnabo** [comment]
@RealyUniqueName Thanks for the commit. Dunno why it's not possible to PR the fork.

However for the `hl` target, I don't think it is possible to access the `Array` and thus to return something equivalent to an `haxe.iterators.ArrayKeyValueIterator`.

**Comment by elnabo** [comment]
I'm also unsure how the `eval` would use this class.

**Comment by RealyUniqueName** [comment]
We can have this in `std/Array.hx`:
```haxe
@:pure @:runtime inline function keyValueIterator() : ArrayKeyValueIterator<T> {
	return new ArrayKeyValueIterator(this);
}
```
I just checked, and it works for cpp, which also does not have `_std/Array.hx` implementation.
The same approach is used for `String` on some targets: https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/String.hx#L35
Or maybe @nicolas could advise about hl.

**Comment by Simn** [comment]
> Just wanted to make sure : can we accurately make sure that the code for( idx => key in array ) will not result in any temp object being allocated in the form { key : index, value : v } ?

That depends on how well we dodge #7379, which is why I would like to specify ArrayKeyValueIterator instead of KeyValueIterator (the typedef) like in @RealyUniqueName's commit.

**Comment by elnabo** [comment]
Yeah, I just tested and it seems to works flawlessly on all targets. As there seems to be no target specific key/value iterator. It might be best to simply put it in Array. Unless there is a good reason not to, I'm going to change to that.

Maps are going to be different however.

**Comment by Simn** [comment]
Yes, maps worry me a bit because they are surely gonna hit #7379...

**Comment by Simn** [comment]
I think we should focus on Array in this PR and then merge it. Otherwise it's gonna be delayed by the other types.

**Comment by elnabo** [comment]
Using the provided commit, the `k=>v` operator is supported on all target (for `Array`) and doesn't generate a `{key,value}` temporary object.

**Comment by RealyUniqueName** [comment]
Still, need to implement it in the generators of eval, cpp, hl, and flash. Otherwise it won't be accessible through the structure or dynamic field access.

**Comment by RealyUniqueName** [comment]
E.g.
```haxe
static var dyn:Dynamic = [1, 2, 3, 4];
static var struct:{function keyValueIterator():KeyValueIterator<Int,Int>} = [1, 2, 3, 4];

static function test() {
  trace(dyn.keyValueIterator()); //exception
  for(key => value in struct) { //exception
  }  
}
```

**Comment by elnabo** [comment]
I'm unsure I have the understanding to adapt all generators for this.

**Comment by RealyUniqueName** [comment]
Let's wait for @ncannasse @Simn @hughsando

**Comment by Simn** [comment]
You can add the keyValueIterator field like you did before, but then just make it construct an instance of ArrayKeyValueIterator. Check out the createInstance implementation for a reference.

Or I can look into it tomorrow.

**Comment by Simn** [comment]
I don't have time to test it right now, but something like this should work for eval:

```ocaml
	let keyValueIterator = vifun0 (fun vthis ->
		let ctx = get_ctx() in
		let path = key_haxe_iterators_array_key_value_iterator in
		let vit = encode_instance path in
		let fnew = get_instance_constructor ctx path null_pos in
		ignore(call_value_on vit (Lazy.force fnew) [vthis]);
		vit
	)
```

**Comment by elnabo** [comment]
Tried to implement it with 

`key_haxe_iterators_array_key_value_iterator = hash_s "haxe.iterators.ArrayKeyValueIterator"`

But I get `Instance prototype not found` when I try to use `keyValueIterator().hasNext()`. The struct example is still not compiling eitherway.

**Comment by elnabo** [comment]
@Simn I tried the same as you, but my example was different. Got the same errors with your commit.

```haxe
var a:Dynamic = ["a", "b", "c", "d","e"];
trace(a.keyValueIterator); // #closure
var kvi = a.keyValueIterator();
trace(kvi.hasNext()); // [0] Instance prototype not found: haxe.iterators.ArrayKeyValueIterator
trace(a.keyValueIterator().hasNext()); // [0] Instance prototype not found: haxe.iterators.ArrayKeyValueIterator
```

If I specify the type of `kvi:haxe.iterators.ArrayKeyValueIterator<String>` it works as expected.

**Comment by Simn** [comment]
Right, that was actually a DCE problem. I have added an `@:ifFeature` to ArrayKeyValueIterator so we keep the class if there's an unknown field access on `keyValueIterator`.

However, this still breaks apart if the field is only ever accessed through `Reflect.field`. I'm not sure what guarantees we make here for other cases like this.

**Comment by RealyUniqueName** [comment]
I have @:keep on `Array.iterator` to workaround the same problem for normal iterators. Maybe @:keep should be used in `std/Array.hx` too.

**Comment by Simn** [comment]
Could you update the overview post so it reflects which targets support the dynamic version of this?

I recommend the following to avoid DCE issues: Have the properly typed test, then have the dynamic one. That way everything should be available.

**Comment by Simn** [comment]
I would like to see this completed. Anything I can help you with?

**Comment by elnabo** [comment]
I don't have much time at the moment to finish it.

I have for aim to test which target works with the Dynamic array this week-end since it didn't work as is for eval. But I don't think, I'll be able to adapt the generator if required.

Feel free to hijack, if you want to complete it faster.

**Comment by Simn** [comment]
I have worked on this today and just updated the initial post. The failing targets are HL, hxcpp and lua.

## HL

Fails with `Can't cast #hl.types.BytesKeyValueIterator_Int to #haxe.iterators.ArrayKeyValueIterator`. The problem here is that we specify the return type on `Array` to be `ArrayKeyValueIterator`, not the `KeyValueIterator` typedef. So the types are obviously not compatible. I'm not sure how to approach this.

## Lua

CI fails with `bin/unit.lua:10685: attempt to index field 'arr' (a nil value) in unit.TestSpecification.testArray_unit_hx`. I don't have a local environment for running lua so I can't investigate this further.

## C++

Requires a patch to hxcpp to support keyValueIterator on Array. Not sure if anything else needs fixing here.

**Comment by Simn** [comment]
Sadly, I'm moving this to 4.1 because there are still some problems to sort out. The HL issue in particular worries me quite a bit.

**Comment by RealyUniqueName** [comment]
I've disabled test of anon/dynamic access to `Array.keyValueIterator()` for cpp target unitl https://github.com/HaxeFoundation/hxcpp/issues/871 is resolved.
HL implementation is fixed, but not inlinable at all currently. Maybe @ncannasse can come up with a better solution.
Everything else seems fine.

**Comment by Simn** [comment]
@elnabo If you're still around, please update the branch.

@Aurel300 Any chance you could look into https://github.com/HaxeFoundation/hxcpp/issues/871? I think that's the last part that's missing here.

**Comment by elnabo** [comment]
It should be up to date now.

**Pull request merged**
