### PR TITLE
Fix  #4445

### LINKED ISSUE #4445: [php] Type.getClassFields() + Rtti meta = error
Using Rtti combined with run-time metas leads to inoperative code generated by Haxe for php target.

`Type.getClassFields()` generates following code: https://github.com/RealyUniqueName/type-getClassFields/blob/master/php/lib/Type.class.php#L5
Which collects a list of all properties and methods into single array `$r`. 
If objective class has `@:rtti` and run-time meta, then that `$r`  array will contain values `['__meta__', '__meta__', '__rtti']` becuase generated class looks like this: https://github.com/RealyUniqueName/type-getClassFields/blob/master/php/lib/Bugged.class.php
Now when `Type.getClassFields()` is about to finish its work it uses php function `array_unique` to remove duplicates from `$r` array and pass the result to `_hx_array`: https://github.com/RealyUniqueName/type-getClassFields/blob/master/php/lib/Type.class.php#L27
But `array_unique` preserves keys in processed array while `_hx_array` expects items in array to be indexed starting from zero without gaps, so when `Rtti` tries to iterate though that `_hx_array` it fails here: https://github.com/RealyUniqueName/type-getClassFields/blob/master/php/lib/php/Boot.class.php#L212 because `$this->a` is `[0 => __meta__, 2 => __rtti]` while `$i` is `1`. So `Undefined offset` error is thrown:
```
uncaught exception: Undefined offset: 1 (errno: 8) in /home/alex/temp/type-getClassFields/php/lib/php/Boot.class.php at line #212Undefined offset: 1

in file: /home/alex/temp/type-getClassFields/php/lib/php/Boot.class.php line 212
#0 /home/alex/temp/type-getClassFields/php/lib/php/Boot.class.php(212): _hx_error_handler(8, 'Undefined offse...', '/home/alex/temp...', 212, Array)
#1 /home/alex/temp/type-getClassFields/php/lib/Lambda.class.php(10): _hx_array_iterator->next()
#2 /home/alex/temp/type-getClassFields/php/lib/haxe/rtti/Rtti.class.php(6): Lambda::has(Object(_hx_array), '__rtti')
#3 /home/alex/temp/type-getClassFields/php/lib/PhpBug.class.php(6): haxe_rtti_Rtti::hasRtti(Object(_hx_class))
#4 /home/alex/temp/type-getClassFields/php/index.php(9): PhpBug::main()
```

To fix that bug cover `array_unique` with `array_values` to reindex items in array:
This line https://github.com/RealyUniqueName/type-getClassFields/blob/master/php/lib/Type.class.php#L27
```
return new _hx_array(array_unique($r));
```
Should be changed to 
```
return new _hx_array(array_values(array_unique($r)));
```

### PR DESCRIPTION
**Pull request by RealyUniqueName**
PHP: surround array_unique with array_values in Type.getClassFields()

### CODE REVIEW

**Comment by andyli** [comment]
Would you add a test in "tests/unit/src/unit/issues", please? : )

**Comment by RealyUniqueName** [comment]
Done!

**Comment by RealyUniqueName** [comment]
Any chances this PR will be merged?
I have another fix for another bug in php target, but i can't create new pull request because new commits in my repo will be added to this PR.
Or maybe there is a way to make another PR without affecting this one?

**Comment by nadako** [comment]
I'll just merge this as it seems trivial and has tests.

**Comment by nadako** [comment]
cc @mockey, @tml maybe you guys could review that?

**Pull request merged**
