### PR TITLE
SSL for neko and cpp platforms

### PR DESCRIPTION
**Pull request by pperidont**
Haxe wrapper for a new SSL lib for hxcpp and neko :

neko PR : https://github.com/HaxeFoundation/neko/pull/114
hxcpp PR : https://github.com/HaxeFoundation/hxcpp/pull/393

It's based on hxssl, but I switch from OpenSSL to mbedTLS to enable better compatibility on all hxcpp platforms.

Main features :
 - SSL sockets for client and server :
  - standard certificate and commonName verification
  - use certificate / key
  - Server Name Indication
 - Load Certificate from file or directory
 - Load Private / Public Key
 - Digest signature and verification using public / private key

### CODE REVIEW

**Comment by Simn** [comment]
Nice!

Could you squash the commits?

**Comment by nadako** [comment]
Is this going to be merged for 3.3? I kind of want to experiment with enabling HTTPS for haxelib.

**Comment by ncannasse** [comment]
I think it would be nice as well.

**Comment by Simn** [comment]
I can't even merge it so we'll need a new PR.

**Comment by Simn** [comment]
@pperidont: Could you open another PR so we can merge this?

**Pull request closed without merging**
