### PR TITLE
Unicode regex

### PR DESCRIPTION
**Pull request by Simn**
Look guys, I'm sorry...

* [x] PHP
* [x] Lua
* [ ] C++

I don't test map, split and matchSub yet, so there might be more to come.

### CODE REVIEW

**Comment by Simn** [comment]
Note: I have merged this locally because we need the eval changes for our documentation generation. Keeping this PR open as an issue.

**Comment by RealyUniqueName** [comment]
Idk what does "locally" mean, but this is already in development: https://github.com/HaxeFoundation/haxe/commit/8a2517e2aeb79729bf2cc4afe105de7ab118acfa

**Comment by Simn** [comment]
Yes that's what I mean. I merged it locally and pushed it. :P

**Comment by RealyUniqueName** [comment]
So what's the purpose of this PR? )

**Comment by Simn** [comment]
Just pretend it's an issue.

**Comment by Simn** [comment]
@RealyUniqueName: The `/i` test fails on PHP.

**Comment by RealyUniqueName** [comment]
Done

**Comment by jdonaldson** [comment]
The workaround is a little wonky for Lua.  Lrexlib has its own group character (%), which has the same escape behavior (double % is a plain %).  I also have to escape double $ that occurs in the "by" argument.

**Comment by Simn** [comment]
#3430 is still failing on Java and I think there's still something wrong on hxcpp too (#7408), but I'll merge this for now because I want to have the branch out of the way.

**Pull request merged**
