### PR TITLE
Safe navigation operator

### PR DESCRIPTION
**Pull request by Simn**
Just making a PR so I don't forget about this branch...

### CODE REVIEW

**Comment by Simn** [comment]
If nobody complains about anything I'll go ahead and merge this tomorrow to avoid conflicts. Test coverage sucks but we can look into that later. I'm terrible at writing tests for my own implementations anyway, so if anyone wants to try and break things, you're very welcome to do so!

**Comment by RblSb** [comment]
I can handle some tests after merge. Found first thing:
```haxe
function hi() return "hi";
@:nullSafety(StrictThreaded)
function test() {
	eq(hi()?.length, 2); // ok
	// requres nullSafety meta and fails in runtime on js/jvm for me
	@:nullSafety(Off) eq(hi()?.charAt(0), "h");
	// TypeError: Cannot create property 'hx__closures__' on string 'hi'
}
```

**Comment by Simn** [comment]
Ah yeah, I didn't look into null-safety stuff at all. We can tackle that as a next step, too!

**Comment by RblSb** [comment]
Yea, but null-safety filter does nothing here, this code crashes because `hi()?.charAt(0)` generates `(tmp != null ? $bind(tmp,tmp.charAt) : null)(0)`, or `(@:mergeBlock if ((tmp != null)) cast tmp.charAt else null)(0)` in dump. Maybe that function call can be moved in block, or this is generator problem?

**Comment by onehundredfeet** [comment]
Thanks so much for adding this!

**Pull request merged**
