### PR TITLE
Reconstruct do-loops

### PR DESCRIPTION
**Pull request by Simn**
Currently, the analyzer does not reconstruct `do`-loops so the generators never really see them. This PR changes this and surfaced some problems:

* [x] C++

This somehow generates a label after closing the loop, which throws off native compilation: `while((cur_match < 10))              _hx_goto_1:;`

* [x] Lua

Fails with `/home/travis/build/Simn/haxe/std/lua/_std/EReg.hx:142: characters 5-10 : This expression cannot be compiled to Lua`

* [ ] HL

Just hangs.

---

I'm assigning the related target maintainers. I don't want to merge this for 4.0 anyway, but we should look into supporting this properly again.

### CODE REVIEW

**Comment by hughsando** [comment]
Are  you thinking about reconstructing for loops?  IIRC, I had  a few optimizations in there, which may have got a bit rusty.

**Comment by hughsando** [comment]
I put a fix in for hxcpp: 
https://github.com/HaxeFoundation/haxe/commit/c025565a8c280370224fa138caeaefca6be14820
There is also a fix in the hxcpp repo for cppia jit case.

**Comment by Simn** [comment]
I have added support for do-while loops to the JVM target. It's not perfect but good enough for now.

@jdonaldson Lua still fails: `std/lua/_std/EReg.hx:156: characters 5-10 : This expression cannot be compiled to Lua`

@ncannasse HL still hangs

**Comment by jdonaldson** [comment]
I'll check into this, sorry for the delay.

**Comment by Simn** [comment]
Updated the branch and added a checkbox for Justin. :)

**Comment by jdonaldson** [comment]
image

**Comment by jdonaldson** [comment]
/// CHECKBOX CLICKING INTENSIFIES ///

**Comment by Simn** [comment]
I want to check this for 4.3 and see where we're at. Maybe I'm even brave enough to fix HL.

**Comment by Simn** [comment]
Shockingly, the HL debugger worked and pointed me to `EReg.map`. The problem can be reproduced with that:

```haxe
function main() {
	var a = ~/a+/g.map("aaabacx", function(r) return "[" + r.matched(0).substr(1) + "]");
	trace(a);
}
```

According to the debugger, `offset` is 0 on every iteration, which means there's never any break.

**Comment by Simn** [comment]
```haxe
final global = true;

function main() {
	var offset = 0;
	do {
		trace(offset);
		if (offset >= 3)
			break;
		offset = 3;
	} while (global);
}
```

This infinitely prints `0`. Dump looks fine, so I think it's the codegen.

**Comment by Simn** [comment]
Version without trace:

```haxe
final global = true;

@:pure(false)
function dontTrace(d:Int) {}

function getOffset() {
	return 0;
}

function main() {
	var offset = getOffset();
	do {
		dontTrace(offset);
		if (offset >= 3)
			break;
		offset = 3;
	} while (global);
}
```

This is some problem with hlopt. Diff with/without `-D hl_no_opt`:

Merge_S9p39Xwddc

The original compares via registers 11 -> 1 -> 8, the optimized version stores in register 4 but never does anything with it. At the very least this would require a `mov 0,4` before jumping back.

This might be a bit above my paygrade because it likely goes into the register liveness analysis. I'll probably just disable do-reconstruction for HL, but at some point this should definitely be looked into.

**Pull request merged**
