### PR TITLE
Added a test for sys.db.Sqlite

### PR DESCRIPTION
**Pull request by RealyUniqueName**
What's our spec for Sqlite?

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
@andyli what should i do to add sqlite support to sys tests for java and c#?

**Comment by andyli** [comment]
I remember @waneck mentioned the targets need some native libs for db support, see:
 * https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/compile-cs-travis.hxml#L5
 * https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/compile-java.hxml#L11

And yes, there are some db tests in `tests/unit/`, and they probably should be moved to `tests/sys/`...

**Comment by Simn** [comment]
@andyli @RealyUniqueName: What exactly has to happen here?

**Comment by RealyUniqueName** [comment]
Proper setup of SQLite for testing java and cs. And find out the reason of the error on Neko and CPP.

**Pull request closed without merging**
