### PR TITLE
use sedlex for utf-8 aware lexing (closes #5163)

### LINKED ISSUE #5163: Lexer positions vs multi-byte file encodings
We discussed it before with @Simn and decided that it's probably a Haxe 4 material, still, I'm creating this issue so we don't forget about this.

Because our lexer isn't encoding-aware it reports byte positions within lines instead of character positions, which creates all kind of issues for the IDEs when code contains non-ascii strings and comments.

``` haxe
class Main {
static function main() {
/* Privet */ var someVar1; // main.hx:3: characters 17-25
/* Привет */ var someVar2; // main.hx:4: characters 23-31
}
}
```

Sometimes, this can be corrected by the IDE, by reading file again, splitting it in lines, getting the specific line and encoding-decoding it, like it's done for example in [haxe-languageserver](https://github.com/nadako/haxe-languageserver/blob/875c1aaa174566c93de1d98be91fc58eb5bb1f89/src/HaxePosition.hx#L35), which is ugly and inefficient enough already.

However, often editors don't even provide a way to execute that kind of code. For example, both Sublime Text and VS Code provide a way to reckognize and extract compilation errors from the output, using regex group that capture line and character number. Then it uses that info to goto/underline the problem place. And if we have multi-byte strings/comments on that line, we'll end up with a complete off position.

I think, in 2016 it's safe and fair to require source files to be in UTF-8 encoding and report correct positions for that.

---

PS While we're at it, we also should think about making reported character offsets 1-based instead of 0-based, to be consistent with our line numbers. This is also an issue with both ST and VSCode - they currently underline positions shifted to the left by 1 char.

### PR DESCRIPTION
**Pull request by nadako**
As we discussed on Slack, I updated my sedlex branch from https://github.com/HaxeFoundation/haxe/issues/5163#issuecomment-240806895. The only thing changed in the lexer since then is the ["cache friendly debug line calculus"](https://github.com/HaxeFoundation/haxe/commit/a7b39dd6abd2be60fbb3196361662f98ac81ccb8) and the following fix by @ncannasse which were straightforward to add here as well.

### CODE REVIEW

**Comment by nadako** [comment]
@andyli Hey, it looks like our ocaml setup on Travis/Linux is not opam-aware, so I have no idea how to install sedlex there? Could we have opam there?

**Comment by andyli** [comment]
It's a bit complicated.
Ubuntu Trusty do not have ocaml 4.02, so I've backported one and put it in ppa:haxe/ocaml such that we can install it without compiling from source.
opam, similar to other ocaml lib/bytecode program, only works with the exact ocaml version. That means we cannot use the opam Ubuntu Trusty package. I looked into backporting one just like how I did for ocaml 4.02, but opam itself has a lot of dependencies that need backporting too...

I will see what I can do.

**Comment by andyli** [comment]
Turn out we can still install the opam binary and let it use the system ocaml by adding the `system` param at the end as follows:
```
wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin system
```

And then all we need to do is to
```
opam install sedlex
opam config exec -- make
```

Tested it locally and it worked well.

**Comment by nadako** [comment]
Thanks, I'll try adding that!

**Comment by Simn** [comment]
I'm fine with merging this as soon as the #6143 people are in a good place.

**Comment by nadako** [comment]
Rebased the branch and force-pushed to trigger Travis/Appveyor.

**Comment by nadako** [comment]
> I'm fine with merging this as soon as the #6143 people are in a good place.

It's not clear to me what to do to move this forward...

**Comment by Simn** [comment]
Basically ask @hughsando if he can run `opam install sedlex`.

**Comment by Simn** [comment]
Your .merlin change conflicts.

**Comment by nadako** [comment]
Fixed.

**Comment by Simn** [comment]
I'll go ahead and merge this now. Let me know if there are any problems.

**Pull request merged**
