### PR TITLE
Add @:nullSafety(Off) to the first argument of Std.isOfType(v, t)

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #7953 

Waiting for CI

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
@Simn do you think this is an acceptable change?

**Comment by Simn** [comment]
I don't know man, it's pretty ugly... It looks like a hack/workaround, but I don't really have a better solution at the moment either.

**Comment by Gama11** [comment]
We really need some general solution for the whole inlining vs null safety issue (https://github.com/HaxeFoundation/haxe/issues/7897). If inlining can break it, it's rather pointless to be able to specify it per package / type at all...

**Comment by RealyUniqueName** [comment]
I'll try to find a general solution for inlining issue till 4.1. 
Leaving this PR open as a reminder and as a plan B.

**Comment by RealyUniqueName** [comment]
I don't have a better solution, but also I don't like this one and I don't want to merge it.

**Pull request closed without merging**
